### ISSUE TITLE
Moonscript compiler

### ISSUE THREAD

**Issue by its-suun** [thegrb93/StarfallEx#1]
Hey, what about adding the [moonscript](http://moonscript.org/) compiler? It's compiled to lua and so it would be possible to implement it.

**Comment by thegrb93** [comment]
It definately looks possible. I'm thinking that I'll just add a --@moonscript preprocessor which will tell starfall to compile your file as a moonscript file. Simple enough.

**Comment by thegrb93** [comment]
I'll have to study moonscript a bit though just to be sure there aren't any tricks that can be used to bypass the sandbox environment of starfall.

**Comment by thegrb93** [comment]
Another problem is the library uses "require" in a way that garrysmod doesn't support so it might take a while to adapt it.

**Comment by thegrb93** [comment]
It also requires the lpeg library which is an external .dll for regex matching.

**Comment by thegrb93** [comment]
I could use this though. https://github.com/wyozi/gmod-moonscript

**Comment by suunrider** [comment]
There is lua implementation of lpeg (https://github.com/pygy/LuLPeg), so it doesn't need any .dll.  There shouldn't be any tricks because it gets compiled to lua and could be run like starfall.

**Comment by thegrb93** [comment]
Cool thanks. I'll try it out.

**Comment by thegrb93** [comment]
I'll do this in a week after my exams.

**Comment by thegrb93** [comment]
I'm getting an error the the lulpeg library. I'll see if the authors know what the deal is.

**Comment by suunrider** [comment]
I tested https://github.com/wyozi/gmod-moonscript out and it works fine. Tested it through
```
] lua_run_cl print(moonscript.to_lua("abc=->"))
local abc
abc = function() end 	table: 0x2b7d3e98
```
But it looks pretty outdated

**Comment by thegrb93** [comment]
Another problem is comments '--' aren't getting ignored for some reason.

**Comment by thegrb93** [comment]
I've put my progress up on the moonscript branch. You can try it if you want.

**Comment by suunrider** [comment]
Thanks for spending your time in this!

**Comment by thegrb93** [comment]
The author of moonscript still hasn't looked at the issue so I might just use the older version. It'll have to wait until Dec 10 once I finish exams.

**Comment by suunrider** [comment]
When i try to execute some moonscript code, i get this error:
```

[ERROR] addons/starfallex-moonscript/lua/entities/starfall_processor/init.lua:105: attempt to call field 'MoonscriptToLua' (a nil value)
  1. Compile - addons/starfallex-moonscript/lua/entities/starfall_processor/init.lua:105
   2. callback - addons/starfallex-moonscript/lua/weapons/gmod_tool/stools/starfall_processor.lua:92
    3. func - addons/starfallex-moonscript/lua/starfall/sflib.lua:532
     4. unknown - lua/includes/extensions/net.lua:32

```

**Comment by thegrb93** [comment]
There must have been an error loading the moonscript library.

**Comment by suunrider** [comment]
```
Couldn't include file 'moonscript\moonscript\base.lua' (File not found) (@addons/starfallex-moonscript/lua/starfall/moonscript.lua (line 23))

[ERROR] addons/starfallex-moonscript/lua/starfall/moonscript.lua:37: attempt to index field 'moonscript.base' (a nil value)
  1. unknown - addons/starfallex-moonscript/lua/starfall/moonscript.lua:37
   2. include - [C]:-1
    3. unknown - addons/starfallex-moonscript/lua/starfall/sflib.lua:57
     4. include - [C]:-1
      5. unknown - addons/starfallex-moonscript/lua/weapons/gmod_tool/stools/starfall_component.lua:9
       6. include - [C]:-1
        7. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/stool.lua:142
         8. include - [C]:-1
          9. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:363
           10. include - [C]:-1
            11. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/init.lua:9
```

**Comment by thegrb93** [comment]
I guess the git submodule didn't download automatically. This explains how to clone with submodules http://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules maybe I shouldn't use submodules.

**Comment by suunrider** [comment]
Now it works

**Comment by thegrb93** [comment]
I finally talked with the guy making moonscript and found that the reason it isn't working is because gmod lua doesn't support __len metamethod on tables. There's a quick fix I can do to work around that and I'll see if it works.

**Comment by thegrb93** [comment]
After my final exam tomorrow

**Comment by thegrb93** [comment]
I've tried and fixed that. Now waiting for the author to reply about why comments aren't being ignored.

**Comment by thegrb93** [comment]
Moonscript is now working. Make sure to update the submodule. The only problem I know of now is the runtime error will not be representative of the original moonscript code since it is converted to lua and ran, but the compile errors are printed to the console. I'll look into a fix for that.

**Comment by thegrb93** [comment]
I don't think moonscript is practical since it relies on being translated into lua at runtime and will make runtime errors impossible to track since they will appear on the translated code instead of the moonscript code.

**Comment by thegrb93** [comment]
No to mention the dependencies on 3rd party libraries/modules.

**Comment by thegrb93** [comment]
Maybe a 3rd Party starfall extension can be done for this, but I'm not going any further with it.
