### ISSUE TITLE
Callback from net.readEntity executes with nil entities

### ISSUE THREAD

**Issue by adamnejm** [thegrb93/StarfallEx#1000]
Gets called with `nil` param multiple times about 5 seconds after all entities have been fully received. Will look into it later

**Comment by thegrb93** [comment]
That means `ent = instance.WrapObject(ent)` returned nil so ent was some unknown type.

**Comment by thegrb93** [comment]
The bug would have to be somewhere here. https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/sflib.lua#L745-L773

**Comment by thegrb93** [comment]
Need to add IsWorld check on https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/sflib.lua#L751 so that world works with this function.

**Comment by thegrb93** [comment]
I should also note I've never seen this bug so it seems server/addon dependent.

**Comment by adamnejm** [comment]
```lua
net.receive("", function()
  local count = net.readUInt(8)
    for i = 1, 8 do
      net.readEntity(...)
    end
end)
```
I don't think I need to explain what happened here :D

**Comment by thegrb93** [comment]
So it read some wrong entities that it couldn't wrap and returned nil. I'll still add that IsWorld check.
