### ISSUE TITLE
--@include should also look in subdirectories of the script

### ISSUE THREAD

**Issue by its-suun** [thegrb93/StarfallEx#101]
Let's say you have a script splitted in 2 files:
`main.lua` and `second.lua`
The first user has these both files in the main starfall folder. Now he decides to share it with someone else, but the second user would like to put it in `apps/` so its more organized for him.
`--@include` will only search in the root folder and not in script's folder. So the second user has to add `apps/` to the `--@include` and `require()` statement so it works for him.

**Comment by thegrb93** [comment]
This isn't natural lua behavior though, plus how would conflicts be resolved? e.g. two folders containing a file with the same name.

**Comment by its-suun** [comment]
The natural behaviour of `require` is that it checks first the modules which are local to it and then checks global paths (`/usr/local/`) (see https://www.lua.org/pil/8.1.html). Also Starfall doesn't really implement the normal require function, which takes its path divided by dots and no file extension; so i guess you can't really speak of natural behaviour anyways.

**Comment by thegrb93** [comment]
Still doesn't solve the conflict problem and I don't think it's good behavior anyway.

**Comment by its-suun** [comment]
> Still doesn't solve the conflict problem  

There is no conflict problem since you first check locally to the script and then you check main starfall folder.
For example script `apps/snake.txt` has `--@include lib/class.txt`: First starfall looks for `apps/snake/lib/class.txt` and then at `lib/class.txt`.

Anyways I think having `require` in general is just confusing and not similiar to normal lua. `require` is there to load modules and outside of gmod you specify a module path, not a file path. Also it's not really optimal in my opinion to first *include* something in preprocessor and then *require* that file. It would be better to rename `require` to `include`, so it's more similiar to GLua and the name fits to the preprocessor.

> and I don't think it's good behavior anyway.  

Current implementation of the preprocessor and requiring isn't good behaviour. It doesn't really promote scripters to make use of multiple files to make their code organized, when they have to tell always the other player where you should save what and in what directory name. Scripts should work, no matter in which directory they are.

**Comment by thegrb93** [comment]
Oh I see what you mean. The include isn't relative to the mainfile. Yeah that can be fixed.

**Comment by thegrb93** [comment]
Okay, I tested and it seems to work.
