### ISSUE TITLE
Entity:linkComponent(nil) will attempt to network nil entity indexes

### ISSUE THREAD

**Issue by itisluiz** [thegrb93/StarfallEx#1014]
This issue takes place when starfall components attempt to broadcast their linking information [here](https://github.com/thegrb93/StarfallEx/blob/87a7f39d2b4a5ae93349ac3937cf05e3ae0fbcf2/lua/entities/starfall_hud/shared.lua#L35) and [here](https://github.com/thegrb93/StarfallEx/blob/87a7f39d2b4a5ae93349ac3937cf05e3ae0fbcf2/lua/entities/starfall_hud/shared.lua#L35), with the following error: `addons/starfallex-master/lua/entities/starfall_screen/shared.lua:35: attempt to index local 'ent' (a nil value)`

**Comment by thegrb93** [comment]
Yeah, looks like unlinking needs to be fixed. Using 0 for index and checking IsWorld in the client should fix it.
