### ISSUE TITLE
can't open starfall editor

### ISSUE THREAD

**Issue by spankyyy** [thegrb93/StarfallEx#1015]
[starfallex-3.3] addons/starfallex-3.3/lua/starfall/editor/editor.lua:87: bad argument #1 to 'CRC' (string expected, got nil)
  1. CRC - [C]:-1
   2. init - addons/starfallex-3.3/lua/starfall/editor/editor.lua:87
    3. open - addons/starfallex-3.3/lua/starfall/editor/editor.lua:107
     4. func - addons/starfallex-3.3/lua/weapons/gmod_tool/stools/starfall_processor.lua:67
      5. unknown - lua/includes/extensions/net.lua:32

**Comment by thegrb93** [comment]
SF.DocsData can't be nil there so you got an addon that broke your glua file lib or something.
