### ISSUE TITLE
Expand permission system to modify convar limits for a specific chip.

### ISSUE THREAD

**Issue by DivideAndRule** [thegrb93/StarfallEx#1020]
In cases when you are showcasing something that exceeds the default starfall limits its annoying and sometimes difficult to get people to input console commands that change the default starfall limits, Additionally those convar changes are global to every chip and stay changed even after you restart your client. Some sort of way to check and request to modify sf_ convars like sf_timebuffersoftlock_cl and sf_mesh_triangles_max_cl would make life easier in these cases.

**Comment by thegrb93** [comment]
Will require looooots of changes. Better solution is request default limit be changed or ask player to do it manually.
