### ISSUE TITLE
Using custom RT breaks stereoscopy

### ISSUE THREAD

**Issue by DivideAndRule** [thegrb93/StarfallEx#1023]
Simply spawn the chip with my example code or any other code that renders to custom RT(s) and enable stereoscopy in the post processing tab. Pressing E on my example code will flip between using custom RT.

```Lua
--@client

render.createRenderTarget("RT_test")
local rtEnabled = false

hook.add("render","",function()

if rtEnabled then
	render.selectRenderTarget("RT_test")
		render.drawText(200,200,"new RT here!")
	render.selectRenderTarget()
end
    render.drawText(200,200,"Hello world!")
end)

hook.add("starfallUsed","",function() 
	rtEnabled = not rtEnabled
end)
```

![RToffRTon](https://user-images.githubusercontent.com/75858900/102015243-029f8f00-3d63-11eb-8057-2e064203598e.png)

**Comment by thegrb93** [comment]
![image](https://user-images.githubusercontent.com/6713261/102023954-eef12a00-3d5c-11eb-9237-79f13f81bedf.png)

Try updating your graphics driver.
