### ISSUE TITLE
Relax builtin getmetatable (allow strings)

### ISSUE THREAD

**Issue by Cheatoid** [thegrb93/StarfallEx#1032]
I am not sure why is [`getmetatable`](https://github.com/thegrb93/StarfallEx/blob/b00f24cd43d4a37924ac1d0708f77550bc506620/lua/starfall/libs_sh/builtins.lua#L152) being so strict there letting tables only... 😕
Please consider relaxing it by allowing strings (and possibly numbers too).
Some quick test code:
```lua
--@server

local STRING = getmetatable("")
rawset(STRING, "sub", function() return "should_never_see_this" end)

print(string.sub("abcdef", 3))
print(("ABCDEF"):sub(1, 3))
```
After relaxed, the above should output:
> cdef
> ABC

**Comment by thegrb93** [comment]
debug.getmetatable is needed to edit the metatable of a lua type. This affects the whole lua environment so it's not going to happen.

**Comment by Cheatoid** [comment]
@thegrb93 The string metatable, I thought it was only editable using debug lib... welp.
Ok so the safe way of handling this would be to have a `__metatable` field and make it immutable damn :/
