### ISSUE TITLE
URL Whitelist

### ISSUE THREAD

**Issue by Superlamaface** [thegrb93/StarfallEx#1037]
I request for the following URL to be added to the whitelist as it doesn't contain anything grabby its just a download link to the radio station _Noise FM_ **pls file**. I have found nothing wrong or harmful with this link and use it almost every day, so for everyone to be able to hear it would be welcoming.

http://yp.shoutcast.com/sbin/tunein-station.pls?id=567807

**Comment by thegrb93** [comment]
Seems fine
