### ISSUE TITLE
Custom fonts supporting for render.createFont

### ISSUE THREAD

**Issue by Opti1337** [thegrb93/StarfallEx#1043]
I wanna use Segoe MDL2 Assets icons font which  shipped with Windows 10, but getting error "invalid font".  Why do you use list of valid fonts? Is this for some kind of security or what? Could you add the ability to add custom fonts?

**Comment by thegrb93** [comment]
Not sure, the font code is 7 years old. Will look

**Comment by thegrb93** [comment]
@Opti1337 can you try adding the font to this list and see if it works? https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/libs_cl/render.lua#L59

I think the list is mainly just to help users avoid attempting to use fonts that don't work.

**Comment by thegrb93** [comment]
As far as I know, trying to use system fonts won't work.

**Comment by Opti1337** [comment]
I added font to the valid list fonts
![3aDpHYO 1](https://user-images.githubusercontent.com/13350049/104673323-b8b41b00-570b-11eb-81fd-77958efb8f2b.png)

Then i create font with render.createFont
![js1PThm 1](https://user-images.githubusercontent.com/13350049/104673440-f6b13f00-570b-11eb-9d06-161771d62d20.png)

And use this font along with string.utf8char
![3DQx6Io 1](https://user-images.githubusercontent.com/13350049/104673510-12b4e080-570c-11eb-8219-653727a59588.png)

Result
![2ZsSuG7 1](https://user-images.githubusercontent.com/13350049/104673530-1ea0a280-570c-11eb-9ba5-0e1147097efe.png)

**Comment by thegrb93** [comment]
Looks like some defined fonts missing too. https://wiki.facepunch.com/gmod/Default_Fonts

I think we can unrestrict the fonts. However I also need to add a limit to the number of fonts a player can create.

**Comment by thegrb93** [comment]
Going to link this here since it would be good to throw an error if the font is missing. https://github.com/Facepunch/garrysmod-requests/issues/1781
