### ISSUE TITLE
Adding a function to send the permission request screen to clients with HUD enabled

### ISSUE THREAD

**Issue by SubArrest** [thegrb93/StarfallEx#1044]
Would it be possible to create a function that sends the permission request screen to clients when they have the HUD enabled, since it would would make it less hassle to setup everything (especially when the chip is invisible etc) rather than having to first +use the hud to enable it and then +use the chip to grant permissions.
An example would be smth like:
```lua
local first = true
hook.add("drawhud", "", function()
    if first then
        first = false
        sendPermissionRequest(player(),perms,desc)
    end
    --someRenderStuff
end)
```

**Comment by thegrb93** [comment]
Can start after https://github.com/thegrb93/StarfallEx/pull/1025 is merged
