### ISSUE TITLE
Make convar lib default allowed

### ISSUE THREAD

**Issue by LightRobin** [thegrb93/StarfallEx#1046]
would it be possible to add a whitelist for some convars that dont contain confidential information, would be useful in my case to check a players max render targets (sf_render_maxrendertargets) and prompt them to increase it if its too low to work with my chip (theyre connected to a hud), thanks

**Comment by adamnejm** [comment]
I think functions to check stuff like that should be added instead.

**Comment by adamnejm** [comment]
And I don't think you can really implemented this sort of thing, because even if convar is expected to only store, let's say a material path, user can usually set it to whatever he wants and it might happen to be that it's something he doesn't want to share.

**Comment by thegrb93** [comment]
I think a blacklist against confidential convars would be better, but what convar are we talking about? afaik, there aren't any confidential ones you can get the value of.

**Comment by LightRobin** [comment]
idk any specifics, i was just assuming that's the reason for convar lib to require client permission to use in the first place

**Comment by adamnejm** [comment]
I still agree that we need functions to grab Starfall's convars though, mb reopen and rename?

**Comment by thegrb93** [comment]
what do you mean?

**Comment by thegrb93** [comment]
Oh, the library is clientside only.

**Comment by adamnejm** [comment]
Functions like `render.getRenderTargetLimit`

**Comment by thegrb93** [comment]
convar.getInt("sf_render_maxrendertargets")

**Comment by adamnejm** [comment]
Well yeah, but that will only for work yourself with the default permissions. You won't be able to check what other users set the convar to.

Unless I'm wrong about the 1 [here](https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/libs_cl/convar.lua#L4) meaning "Only You"

**Comment by LightRobin** [comment]
it only works for the owner of the chip which is why i opened this request, there should be a way to check it for other players, i dont see what's harmful about knowing how many render targets the user can have

**Comment by thegrb93** [comment]
I think we can make the permissions allowed. I think that should've been the title of the issue.
