### ISSUE TITLE
Multi-word name / path detection issue strikes back

### ISSUE THREAD

**Issue by ElHyperion** [thegrb93/StarfallEx#106]
Same as my previously reported  [issue **#88**](https://github.com/thegrb93/StarfallEx/issues/88)
(both --@name and --@include will take only the first word of a multi-word path)

**Comment by thegrb93** [comment]
That's weird, it works for me. Can you give an example?

**Comment by ElHyperion** [comment]
My bad, I haven't noticed I've left a wrong GitHub branch selected in the desktop app.

The difference now is only within requiring, where my includes will work only if I put in the file name, not the full path, but that's an enhancement I guess. However, dofile() still requires the full path, and for --@include it works both ways. Tested when the main file was within the same folder as the files being included.

**Comment by thegrb93** [comment]
I'll look at require and dofile later.

**Comment by Damianu** [comment]
require should also look in global path, as now old scripts are broken..
Example:
--@include lib/class.txt
require("lib/class.txt") and it says that lib/lib/class.txt wasnt found..

**Comment by thegrb93** [comment]
Ya i know. Sorry I forgot about that case. Should be good now.
