### ISSUE TITLE
Add ability to check CPPI friendship status

### ISSUE THREAD

**Issue by adamnejm** [thegrb93/StarfallEx#1062]
```lua
getCPPIFriends()
Player.getCPPIFriendStatus()
```
Both shared, limited to instance owner.

**Comment by thegrb93** [comment]
I remember neatro requested this. Just use hasPermission with entities.canTool?

**Comment by adamnejm** [comment]
This would require the other player to have at least one entity spawned that we can pass into the function, will it not?

**Comment by adamnejm** [comment]
I don't think prop protection often allow to toolgun other players, even if you're friends with them.

**Comment by thegrb93** [comment]
What would you need the check then if they have no entities?

**Comment by adamnejm** [comment]
If they're our friends, that means they can touch our stuff, so I think there are real uses.

**Comment by thegrb93** [comment]
I still don't see what this could be used for

**Comment by adamnejm** [comment]
Welp... I still think this should be added.
Be the one to close this issue if you think otherwise.

**Comment by thegrb93** [comment]
I'm just really against naming it after CPPI. It's not user friendly at all and it adds the dependency of a prop protection system.

**Comment by thegrb93** [comment]
The only use I can see of it is making a menu that shows player's prop friends and that isn't really worth adding this feature for.

**Comment by Cheatoid** [comment]
Starfall is apparently strangely missing this; `CPPIGetFriends`...
Let's not argue, ok. This is crucial functionality which should be exposed.

Question is: How do you tell if a player *X* trusts player *Y*?

`hasPermission` + `canTool` is not adequate solution at all. (See Discord for more context.)
Why? Because it doesn't solve the above question.

E2 has such functionality, it is called [`entity:trusts(entity)`](https://github.com/wiremod/wire/search?q=entity+trusts+filename%3Aplayer.lua&type=Code).
And yeah, it should be in shared realm.

**Comment by thegrb93** [comment]
What's trusts used for?

**Comment by thegrb93** [comment]
I see this as more of a invasion of privacy that coders can see who trusts who

**Comment by adamnejm** [comment]
>  see this as more of a invasion of privacy that coders can see who trusts who

I stated in the original description of the issue that it should only be available for instance owner.
Actually more should be allowed, since I missed the functionality of getting somebody's friendship status towards you, that could potentially be just done by returning 2 values from `Player.getCPPIFriendStatus(ply)`, whether you trust the player and whether they trusts you.
So only things you'd see is people you trust and who trusts you.

I don't see where privacy is being invaded here, also I want to point out my concerns about privacy on: https://github.com/thegrb93/StarfallEx/issues/1046 which in my opinion are way more infringing than this is, even if you could check status of other players towards other players.
