### ISSUE TITLE
Bad realm API

### ISSUE THREAD

**Issue by Cheatoid** [thegrb93/StarfallEx#1063]
It is weird, but I have noticed some of the Starfall API/functions are exposed as shared, even though they are **not** actually shared;
Some are clientside-only. Some are serverside-only. Others should have been made shared.

# List
There are multiple, I don't have the full list right now, to be filled later.

| Patched | Link to Function | Docs | Correct Realm |
| :-: | :-: | :-: | :-: |
| ❌ | [`Player.getFriendStatus`](https://github.com/thegrb93/StarfallEx/search?q=player_methods+getFriendStatus+filename%3Aplayers.lua) | [Starfall](https://thegrb93.github.io/StarfallEx/#Types.Player.getFriendStatus) / [GMod](https://wiki.facepunch.com/gmod/Player:GetFriendStatus) | [![][CLIENT]](#List)
| TBD | TBD | TBD |

Feel free to report via comment if you find more of those bad realm API, and I will add them in the list above.

## Proposed Patch
A list of the APIs which require extra care.

### `Player.getFriendStatus`
Instead of just making it clientside-only (the ***lazy fix***).
I would suggest to make this cached upon player connect (similar to how it is implemented in [Wiremod/E2](https://github.com/wiremod/wire/search?q=entity+isSteamFriend+filename%3Aplayer.lua)). Why make it cached? AFAIK, friend-status between players is only fetched once a player is connected and therefore is not going to update in real-time while playing the game. (Blame Garry.)

[CLIENT]: https://img.shields.io/badge/-CLIENT-dea909?style=flat-square "Clientside"

**Comment by Cheatoid** [comment]
@thegrb93 Guess I will make my own fork since that commit is not patched the way I have suggested for it.
Also why closed this?

**Comment by thegrb93** [comment]
Serverside doesn't make sense. E2 only does it out of necessity.

**Comment by adamnejm** [comment]
Honestly here I agree with Sparky.
Those function is available only on clientside in GLua and the only thing wrong was documentation.
We shouldn't just do stuff "because E2 did it".

**Comment by Cheatoid** [comment]
> Serverside doesn't make sense.

*You* don't make sense... if i have a **serverside-only** SF chip, which lets players "do something" using chat commands (PlayerSay hook).
And guess what, certain commands I'd only allow to allow to Steam friends.

Question is: How do you expect me to handle the "permission check" (or command logic depending on what the command does) in this case?
Remember I don't have clientside context at all, only serverside. And then there's the issue with blocking SF chip, which means if I were to implement networking within SF chip to send the FriendStatus from client to the server, and if the player has blocked my SF chip, that would be bad as I still want commands to work (but if blocked, then their clientside won't send the net message), which means they won't appear as a Steam friend even though he/she is indeed a Steam friend of whoever is the invoker of the chat command.

Still why closed this. Ah screw it, I will make and maintain my own fork, waste of time here.

**Comment by thegrb93** [comment]
You would network it from your local client. You can either make your script shared or include a shared script that does this.

**Comment by Cheatoid** [comment]
> You would network it from your local client. You can either make your script shared or include a shared script that does this.

I explained why this won't work. Read more carefully.

**Comment by thegrb93** [comment]
You don't get it from their client, you get it from your own. Did you read my comment?

**Comment by Cheatoid** [comment]
I need to test it from command *invoker's* client, **not** mine client. fool.

**Comment by thegrb93** [comment]
No possible anymore anyway unless they enable the new permission

**Comment by thegrb93** [comment]
https://github.com/thegrb93/StarfallEx/commit/41f0d2e62dfd954cfd799c82642a70d5a4ca729d

**Comment by adamnejm** [comment]
`sf_timebuffer_cl 0`

**Comment by thegrb93** [comment]
Also if you're doing the check on their client then your blocking argument is moot anyway because they won't have a clientside.

**Comment by Cheatoid** [comment]
We're done here. My own fork, it is.

**Comment by thegrb93** [comment]
Learn some modesty while you're at it
