### ISSUE TITLE
sf serverside chat hook breaks very easily

### ISSUE THREAD

**Issue by Fasteroid** [thegrb93/StarfallEx#1069]
From what I understand here, passing true for the last arg makes whatever starfall hook being added run last:
https://github.com/thegrb93/StarfallEx/blob/c90bfd7667f0acec3e837c356c2dddc8c89caa91/lua/starfall/sflib.lua#L528-L529

That means here when Starfall sets up its PlayerSay hook, it gets set to be one of the last things if not THE last thing to run on Gmod's PlayerSay hook:
https://github.com/thegrb93/StarfallEx/blob/9f83585a0618f6d278eae37eeee7414856ec66ba/lua/starfall/libs_sh/hook.lua#L33

Due to running last, however, any addon that decides to return something from the PlayerSay hook however **will completely stop Starfall's PlayerSay from running**.  ULX for example has a hook that manages mutes and gimps that causes exactly this problem with affected players:
```lua
if SERVER then
	local function gimpCheck( ply, strText )
		if ply.gimp == ID_MUTE then return "" end
		if ply.gimp == ID_GIMP then
			if #gimpSays < 1 then return nil end
			return gimpSays[ math.random( #gimpSays ) ]
		end
	end
	hook.Add( "PlayerSay", "ULXGimpCheck", gimpCheck, HOOK_LOW )
end
```
When this returns from the PlayerSay hook, Starfall no longer gets to call its own PlayerSay hook.  Starfall's PlayerSay call should be medium priority instead of guaranteed last.

**Comment by thegrb93** [comment]
This was done exactly for this reason. It keeps muted players or players running hidden commands from chat from having their messages picked up by starfall.

**Comment by thegrb93** [comment]
Also this is gmod's issue since they never added PlayerCanSay which is what those addons should use instead.
