### ISSUE TITLE
"fastlz" is not the FastLZ! it is LZMA.

### ISSUE THREAD

**Issue by Cheatoid** [thegrb93/StarfallEx#1071]
https://github.com/thegrb93/StarfallEx/blob/ade77c50e25d91f9b2258ebb5d7f243b15544aff/lua/starfall/libs_sh/fastlz.lua#L3

Rename this whole library. Note: breaking change.

**Comment by thegrb93** [comment]
I don't think anyone minds, but I would prefer this function in the bit lib but it's not worth breaking things.

**Comment by thegrb93** [comment]
Blame 0faf0747fd6088e931051c74f7fb523c51c41071

**Comment by thegrb93** [comment]
I guess an undocumented alias would be fine.
