### ISSUE TITLE
A nul char ("\0") issue... is still living.

### ISSUE THREAD

**Issue by Cheatoid** [thegrb93/StarfallEx#1073]
Unsurprisingly, the editor is broken:
![image](https://user-images.githubusercontent.com/13347909/106973441-2ecc0080-6753-11eb-8970-449afe1c3168.png)

But also if you just try to spawn the code, it will fail due `unfinished string near '<eof>'`.
[Download the sample file](https://github.com/thegrb93/StarfallEx/files/5929322/null.txt) and try spawning it.
It has the nul char at the offset 9 (which is inside the string):
![image](https://user-images.githubusercontent.com/13347909/106973542-54f1a080-6753-11eb-828b-d395667e3fe4.png)

**Comment by thegrb93** [comment]
That's expected behavior and loadstring will generate that error. Use \0 if you want a null char in your string.
