### ISSUE TITLE
Lua error when scaling holograms

### ISSUE THREAD

**Issue by LightRobin** [thegrb93/StarfallEx#1075]
[starfallex] addons/starfallex/lua/entities/starfall_hologram/cl_init.lua:28: bad argument #1 to 'Scale' (Vector expected, got nil)
  1. Scale - [C]:-1
   2. v - addons/starfallex/lua/entities/starfall_hologram/cl_init.lua:28
    3. CallProxies - lua/includes/extensions/entity.lua:265
     4. CallDTVarProxies - lua/includes/extensions/entity.lua:273
      5. unknown - lua/includes/extensions/entity.lua:171 (x96)
    
doesnt happen 100% of the time when scaling holograms but when it does happen the hologram doesnt actually change scale, I tried reproducing it in sp but wasnt able oto so idk what exact scenario causes it

**Comment by thegrb93** [comment]
I think the next gmod update will fix it. https://github.com/Facepunch/garrysmod-requests/issues/1743

**Comment by thegrb93** [comment]
Might be able to just add a nil check meanwhile.

**Comment by thegrb93** [comment]
> Let me know if it still happens on Monday or something, and make sure your server is up to date if it is on any beta branches.
> 
> Should give everyone enough time to get their clients updated on the Beta branches.

**Comment by thegrb93** [comment]
This should be fixed now. Let the gmod devs know if its still happening
