### ISSUE TITLE
repeat-until 'continue' checks breaks way too easily

### ISSUE THREAD

**Issue by LightRobin** [thegrb93/StarfallEx#1084]
```lua
function doshit()
  repeat
    print(gay)
  until not gay
end 

function moreshit()
  while true do 
    if x = y then
      continue
    end
  end
end

function breakit()
  repeat
    print(gay)
  until not gay
end

```

`Due to a glua bug. Use of the string 'continue' in repeat-until loops has been banned`

it sees the continue in the middle function and errors, regardless of whenther the continue is inside the repeat-until

**Comment by thegrb93** [comment]
That's because it's too much effort to make it 100% unbreakable otherwise.

**Comment by thegrb93** [comment]
pr if you have a better solution
