### ISSUE TITLE
See if rshift is faster than floor+divide

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#1089]

**Comment by thegrb93** [comment]
yes it is

**Comment by artemking4** [comment]
obviously it is lol
shift is just a bit operation that cpus support as just a single instruction

**Comment by thegrb93** [comment]
> obviously it is lol
> shift is just a bit operation that cpus support as just a single instruction

There's overhead from it being a C function as well as converting double to int and back so it's not  completely obvious. Luckily it is still faster.

**Comment by artemking4** [comment]
yet all math functions are c functions.... Also, converting double to int and back is not too much of an issue because iirc you can do this in a single instruction too

**Comment by thegrb93** [comment]
float -> int, rshift, int -> float

vs

divide, floor


It's not obvious and that's why I tested it.
