### ISSUE TITLE
Hologram clips broken for some reason

### ISSUE THREAD

**Issue by Fasteroid** [thegrb93/StarfallEx#1091]
Getting errors related to hologram clips where I didn't before without making any changes to my chip.
```
[starfallex] addons/starfallex/lua/entities/starfall_hologram/cl_init.lua:98: attempt to get length of field 'buffer' (a nil value)
  1. callback - addons/starfallex/lua/entities/starfall_hologram/cl_init.lua:98
   2. callback - addons/starfallex/lua/starfall/sflib.lua:809
    3. WaitForConditions - addons/starfallex/lua/starfall/sflib.lua:782
     4. WaitForEntity - addons/starfallex/lua/starfall/sflib.lua:806
      5. func - addons/starfallex/lua/entities/starfall_hologram/cl_init.lua:114
       6. unknown - lua/includes/extensions/net.lua:32
```

I did a little digging myself and I think something in #1085 broke clips—the 'buffer' field isn't getting networked anymore.
```lua
net.Receive("starfall_hologram_clips", function()
	local index = net.ReadUInt(16)
	local clipdata = SF.StringStream(net.ReadData(net.ReadUInt(32)))
```
Calling `PrintTable(clipdata)` [here](https://github.com/TheGrb93/StarfallEx/blob/872a8627c33e5c325dc360c7f02504ae1d6ea549/lua/entities/starfall_hologram/cl_init.lua#L96) yields a disappointingly empty-looking table:
```
1	=	
index	=	1
subindex	=	1
```

**Comment by thegrb93** [comment]
It'd more likely be https://github.com/thegrb93/StarfallEx/commit/387d764327d8163c77c60c91ec4cc4e339e762cf that broke it. Will need to debug tomorrow.

**Comment by thegrb93** [comment]
>Calling PrintTable(clipdata) here yields a disappointingly empty-looking table:

That means the net.ReadData returned an empty string

**Comment by thegrb93** [comment]
Found this bug though https://github.com/thegrb93/StarfallEx/blob/master/lua/entities/starfall_hologram/cl_init.lua#L101

Should be clipdata:size().

**Comment by Fasteroid** [comment]
Confirmed fixed.  Thanks!
