### ISSUE TITLE
Editor bugs

### ISSUE THREAD

**Issue by LightRobin** [thegrb93/StarfallEx#1099]
1. Syntax highlighting when you select a {'then', 'else', 'end', 'function'} block doesnt not highlight the correct end point for that block
e.g 
![image](https://user-images.githubusercontent.com/55828615/108824525-b9b55380-75b9-11eb-94e5-c2a6b370d12c.png)

2. Sometimes the bottom line gets fully, or partially, covered by the validation bar, will update with an example next time i see it happen, but i mean here:
![image](https://user-images.githubusercontent.com/55828615/108824784-0862ed80-75ba-11eb-9c38-1526fcb0fd5a.png)

Ill add any more editor bugs I run into here, these are just the main ones that come to mind

**Comment by thegrb93** [comment]
Will focus on 1. and close once that's done. You can open another issue with 2. if you figure out how to reproduce it.

**Comment by thegrb93** [comment]
Just need to debug this
https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/editor/tabhandlers/tab_wire.lua#L2755

**Comment by thegrb93** [comment]
I see a bug sticking out already, 'else' is counted twice due to that 'goto'.

**Comment by thegrb93** [comment]
If it's not there, then its here https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/editor/syntaxmodes/starfall.lua#L214

**Comment by thegrb93** [comment]
Still issues

**Comment by thegrb93** [comment]
Had an idea for getting 'else' to work
