### ISSUE TITLE
Ply:keyDown(...) checks for wrong key

### ISSUE THREAD

**Issue by suunrider** [thegrb93/StarfallEx#11]
```
if CLIENT then return end

hook.add("think","",function()
    print(entities.owner():keyDown(KEY.E))
end)
```
returns false if I press E, but true if I press W

**Comment by suunrider** [comment]
Oh noticed that i need to use `IN_KEY` enum, but IN_KEY.E doesn't exist

**Comment by thegrb93** [comment]
Yeah, its IN_KEY.USE. I should add all of those globals to the keyDown info.
