### ISSUE TITLE
perms window gets spammed when pressing use on a parented chip that was duped in advdupe2

### ISSUE THREAD

**Issue by daftpotato** [thegrb93/StarfallEx#1118]

**Comment by thegrb93** [comment]
Need a bit more info. Can't reproduce this

**Comment by thegrb93** [comment]
Was it singleplayer/multiplayer? beta/non-beta? Is server sf and advdupe2 up to date? what code was used?

**Comment by daftpotato** [comment]
it was multiplayer i was on the 64 bit beta and i probly should of specified that if i parented it to a prop and duped  the sf then tryed to do the permissions window it got spammed. i will attach the code that it happens on but mind the mes
[car_radio_golf.txt](https://github.com/thegrb93/StarfallEx/files/6255356/car_radio_golf.txt)

**Comment by thegrb93** [comment]
I still can't get it to happen. I can probably add a safeguard anyway to prevent it.
