### ISSUE TITLE
Add support for various draw modifier functions in the render library

### ISSUE THREAD

**Issue by PolySteam** [thegrb93/StarfallEx#1122]
The following functions are part of gmod's normal lua render system, they are often used in 2d and 3d cam and are entirely missing in starfall.

DrawBloom 
DrawColorModify 
DrawMaterialOverlay 
DrawMotionBlur 
DrawSharpen 
DrawSobel 
DrawSunbeams 
DrawTexturize 
DrawToyTown

**Comment by thegrb93** [comment]
I'm fairly certain some one these can crash/lag the game if used incorrectly.

**Comment by thegrb93** [comment]
Will have to see if they are safe to add.

**Comment by PolySteam** [comment]
Should most likely give them their own special Render.draw permission that's off by default then

**Comment by thegrb93** [comment]
If any of them are problematic then they could be made owner only, yeah.

**Comment by thegrb93** [comment]
Looks like we have setMaterialEffectColorModify already. The others can be based off of that.
