### ISSUE TITLE
Hook 'KeyPress' and 'KeyRelease' produces double or even triple ticks when added in multiplayer game

### ISSUE THREAD

**Issue by maksimp04** [thegrb93/StarfallEx#1142]
tried out testing in singleplayer and it works just fine, but when tested in multiplayer game it sometimes produces double clicks. The significance of the problem is that 'KeyPress' bugged ticks are not synced with 'KeyRelease' bugged ticks, causing to having two or more ticks of 'KeyPress' and only one 'KeyRelease' tick
![image](https://user-images.githubusercontent.com/19390500/115955736-46c54c00-a51a-11eb-807d-5afa9e605842.png)

**Comment by x4fx77x4f** [comment]
I recall having the same problem a while ago, and I can reproduce it on fb27b7a. It was such a problem 2 months ago that [I wrote a debouncer library to alleviate the problem](https://gist.github.com/x4fx77x4f/00b423e7b6ec4eacb612fe89f82a1e4f) so that I could use it in an ATM that responded to `+use`. `inputPressed` and `inputReleased` do not have the same problem.
```lua
--@client
hook.add('keypress', '', function(_, key)
    print('keypress', key)
end)
hook.add('keyrelease', '', function(_, key)
    print('keyrelease', key)
end)
```
```
keypress	2
keypress	2
keypress	2
keyrelease	2
keypress	2
keyrelease	2
keypress	2
keyrelease	2
keypress	2
keyrelease	2
keypress	2
keyrelease	2
keyrelease	2
```

**Comment by CornerPin** [comment]
`KeyPress` and `KeyRelease` are predicted hooks, which means in multiplayer, they may be called multiple times on the client-side. You can use [isFirstTimePredicted](http://thegrb93.github.io/StarfallEx/#Libraries.builtins.isFirstTimePredicted) to determine if the hook was predicted for the first time.

```lua
--@client

hook.add("keypress", "", function(_, key)
    if not isFirstTimePredicted() then return end
    print("keypress", key)
end)

hook.add("keyrelease", "", function(_, key)
    if not isFirstTimePredicted() then return end
    print("keyrelease", key)
end)
```
