### ISSUE TITLE
Add support for GThread

### ISSUE THREAD

**Issue by storm37000** [thegrb93/StarfallEx#1147]
Would be cool to have a clientside and serverside API to work with that DLL if installed.  A fallback that simulates how it works but maybe uses coroutines instead would be cool too so that the same code could work everywhere.

https://github.com/Thomasims/GThread

**Comment by thegrb93** [comment]
The spawned threads won't have access to any of the garrysmod environment. They're solely for math, data processing and stuff. What would you use it for?

**Comment by storm37000** [comment]
For that stuff exactly.  I have been looking into finding math heavy parts of addons i use and see if i could offload them from the main thread.  Simfphys and GDisasters are examples where extreme math actually does slow things down.

**Comment by thegrb93** [comment]
I think it would be fine to make a library for this. Help would be appreciated. It would need to be admin only or heavily sandboxed.

**Comment by thegrb93** [comment]
Found the reference https://github.com/Thomasims/GThread/wiki/Reference

**Comment by storm37000** [comment]
I would say having a permission to set it to admin only would be good.

**Comment by thegrb93** [comment]
Not really sure if I'll merge the code into the main branch, at least not until its sandboxed properly. Will leave the branch open though.
