### ISSUE TITLE
Allow enableHud( ) to draw on players who have given perms that are NOT in a vehicle or owner of chip.

### ISSUE THREAD

**Issue by EagleChan99** [thegrb93/StarfallEx#1149]

**Comment by thegrb93** [comment]
This would be a very strong permission to have. Infinite control over enabling hud on someone; probably need to think about this.

**Comment by EagleChan99** [comment]
Though it will only be able to be done on people who have given perms, an example being people who have manually pressed e on the chip and given permission.

**Comment by thegrb93** [comment]
Normally you can disconnect the hud if you ever need to using a console command; but with this you could keep them permanently in a hud. Will need to make the console command also revoke the permission.

**Comment by EagleChan99** [comment]
That could work

**Comment by SeahDokki** [comment]
Is it possible to set specific server permission to specific rank ?
So, admins get allow some users to enableHud on "Anyone/Friends Only/Seated"

**Comment by thegrb93** [comment]
The provider to be added in
https://github.com/thegrb93/StarfallEx/tree/master/lua/starfall/permissions/providers_sh
