### ISSUE TITLE
Add debugTraceback

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#1150]

**Comment by Vurv78** [comment]
I think there should be a full on ``debug`` library at this point to not clutter builtins, I was talking to @x4fx77x4f about this in game some time ago iirc

**Comment by x4fx77x4f** [comment]
Can confirm. I've been meaning to do something about the debug functions.

**Comment by thegrb93** [comment]
I guess it would also be good to be closer to native lua.
