### ISSUE TITLE
add wireframe shader to material shaders whitelist

### ISSUE THREAD

**Issue by Neatro** [thegrb93/StarfallEx#1155]
https://developer.valvesoftware.com/wiki/Wireframe

allows the use of the wireframe shader, similar to material models/wireframe

**Comment by thegrb93** [comment]
I guess editing some of those options on it such as nocull and color would be useful.

**Comment by Neatro** [comment]
it's indeed for $nocull and coloring, as the "default" don't render the color properly, as far as i know, it also should support $vertexcolor/$vertexalpha
