### ISSUE TITLE
Not all contributors are displayed

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#1157]
For some reason this link doesn't show all contributors. https://github.com/thegrb93/StarfallEx/blob/dochtml/src/Components/Cards/ContributorsCard.js#L8

**Comment by Vurv78** [comment]
Iirc it's just a default api limit to like 30 you can change in the link

**Comment by thegrb93** [comment]
per_page parameter yeah
https://docs.github.com/en/rest/reference/repos#list-repository-contributors

**Comment by thegrb93** [comment]
I think I'll leave it alone since they are ordered by contribution count and I don't want to get into adding pages. Will just leave it as a top 30.

**Comment by thegrb93** [comment]
Nvm, top 50 would be better
