### ISSUE TITLE
After the recent update inputPressed is even more broken

### ISSUE THREAD

**Issue by AdamName** [thegrb93/StarfallEx#116]
Previously I couldn't use inputPressed hook while on singleplayer, not a big problem and I just hosted local. Now it seems that the whole thing went to shit.

`hook.add("inputPressed", "FixPlz", function(btn) print(btn) end)`

Local / P2P:
> [ERROR] addons/starfallex/lua/starfall/libs_sh/input.lua:107: attempt to index field 'instance' (a nil value)
>   1. customargfunc - addons/starfallex/lua/starfall/libs_sh/input.lua:107
>    2. v - addons/starfallex/lua/starfall/libs_sh/hook.lua:59
>     3. unknown - lua/includes/modules/hook.lua:84

Singleplayer:
> [ERROR] addons/starfallex/lua/starfall/libs_sh/input.lua:107: attempt to index field 'instance' (a nil value)
>   1. customargfunc - addons/starfallex/lua/starfall/libs_sh/input.lua:107
>    2. v - addons/starfallex/lua/starfall/libs_sh/hook.lua:59
>     3. Run - lua/includes/modules/hook.lua:84
>      4. func - addons/starfallex/lua/starfall/libs_sh/input.lua:27
>       5. unknown - lua/includes/extensions/net.lua:32

**Comment by thegrb93** [comment]
Ya looks like a typo from the permissions update. SF.instance.player should be instance.player

**Comment by thegrb93** [comment]
I've patched that, and I'll test it further when I get home to see if its still not working in singleplayer.

**Comment by thegrb93** [comment]
Seems to work.
