### ISSUE TITLE
clientside holos still detatch on full updates

### ISSUE THREAD

**Issue by shadowscion** [thegrb93/StarfallEx#1162]
They seem to reparent themselves but the positions and angles are never correct

'full update' may be wrong, but it happens when going underground in gm_flatgrass_classic etc

**Comment by thegrb93** [comment]
This is the code. Will probably have to store their relative position and re-apply that as well as the parenting.

https://github.com/thegrb93/StarfallEx/blob/68527049b110af75ee08020255318099ddda58d5/lua/starfall/libs_sh/holograms.lua#L32-L48

**Comment by thegrb93** [comment]
@shadowscion let me know if its still not fixed
