### ISSUE TITLE
Specific Prop Permissions System Suggestion

### ISSUE THREAD

**Issue by SubArrest** [thegrb93/StarfallEx#1163]
Would it be possible to beable to apply permissions to an sf prop (upon spawning or after) that allows other players to toolgun/physgun/interact etc with it? I was thinking of uses could be something like the indicators used in mobenix that you weld to your vehicle during the racetrack to detect when you cross checkpoints or the finish line.

**Comment by thegrb93** [comment]
Prop protection does permission on a per player basis, not per prop. Not sure if this is possible.

**Comment by thegrb93** [comment]
Probably not do-able.
