### ISSUE TITLE
owner() does not update to the new entity when rejoining the server with the chip still spawned

### ISSUE THREAD

**Issue by JaCoB123456798** [thegrb93/StarfallEx#1166]
If you rejoin a server with a chip still spawned, you are no longer the owner according to the chip both client-side and server-side.

**Comment by thegrb93** [comment]
Duplicate of https://github.com/thegrb93/StarfallEx/issues/1113 . I started working on it here https://github.com/thegrb93/StarfallEx/pull/1146 but have been busy
