### ISSUE TITLE
Drawing rendertargets to screens can cause a thin strip

### ISSUE THREAD

**Issue by JaCoB123456798** [thegrb93/StarfallEx#1168]
When drawing a rendertarget to a screen, sometimes there will be a thin strip at the edge which seems most likely to come from texturing the rect with uvs and using % 1 where when u or v is 1, the coordinate wraps back to 0 as opposed to 1023, creating the thin line.

**Comment by JaCoB123456798** [comment]
Also I do mean with `render.setRenderTargetTexture()` and `render.drawTexturedRect()`
![image](https://user-images.githubusercontent.com/46092227/121827980-be466a80-cc83-11eb-9b34-e301232b55f9.png)
This rt with a grid on it has this corner in the bottom left and then a vertical grid bar on the left side. You can see the strip at the right edge of the rt.

**Comment by thegrb93** [comment]
Do you have reproducible code? That'd make it easier to look at

**Comment by JaCoB123456798** [comment]
```lua
render.createRenderTarget("")

hook.add("renderoffscreen", "", function()
    render.selectRenderTarget("")
    render.setRGBA(255, 0, 0, 255)
    render.drawRect(0, 0, 512, 1024)
    hook.remove("renderoffscreen", "")
end)

hook.add("render", "", function()
    render.setRenderTargetTexture("")
    render.drawTexturedRect(128, 0, 256, 512)
end)
```

**Comment by thegrb93** [comment]
That's due to the "uv wrapping" property of the rendertarget. I don't know if we can create them without wrapping. Your best bet is to avoid the border of the RT, or draw them with UV coordinates 0.5/1024, 0.5/1024, 1023.5/1024, 1023.5/1024

**Comment by JaCoB123456798** [comment]
Is there a way to change how it renders with uvs? I know you can wrap them while still allowing 1.

**Comment by CornerPin** [comment]
Can't be properly fixed until https://github.com/Facepunch/garrysmod-requests/issues/1695 is added.
