### ISSUE TITLE
docs: improve `function` generator

### ISSUE THREAD

**Issue by Cheatoid** [thegrb93/StarfallEx#1169]
It would be a great help to be able to know argument/return types for `function`...
Here's what I mean, let's take `bass.loadURL` as an example, the 3rd argument is a `function`, [from JSON point of view](https://github.com/thegrb93/StarfallEx/blob/gh-pages/sf_doc.json) we can see it as:
```json
{
  "type": "function",
  "value": "function callback Function which is called when the sound channel is loaded. It'll get 3 arguments: `Bass` object, error number and name.",
  "name": "callback",
  "description": "Function which is called when the sound channel is loaded. It'll get 3 arguments: `Bass` object, error number and name."
}
```

This is pretty bad time since there is no way to simply determine what arguments does a `function` itself take (or must return).
This applies to all params/returns that have `"type": "function"` or `"type": "function?"` (in JSON). (There are about ~50 of those.)

So I am suggesting to add an additional node which would describe type/signature information. For example, let it be called `signature`:
```json
{
  "type": "function",
  "value": "function callback Function which is called when the sound channel is loaded. It'll get 3 arguments: `Bass` object, error number and name.",
  "name": "callback",
  "description": "Function which is called when the sound channel is loaded. It'll get 3 arguments: `Bass` object, error number and name.",
  "signature":
  {
    "returns": [],
    "params": [
      {
        "type": "Bass",
        "name": "channel"
      },
      {
        "type": "number",
        "name": "errorCode"
      },
      {
        "type": "string",
        "name": "errorName"
      }
    ]
  }
}
```

Nice. (Having this information will result in more type-safe C# API which is cool.)

**Comment by thegrb93** [comment]
This can go on with infinite depth. I think one level describing the callback function is sufficient enough.
