### ISSUE TITLE
Many files in sf_filedata causes chips to crash from global ram usage

### ISSUE THREAD

**Issue by Jacbo1** [thegrb93/StarfallEx#1180]
Starfall indexes every file in sf_filedata which causes it to use a lot of ram which then causes chips to crash. The command to set the ram limit, sf_ram_max_cl, also does not work. It seems to crash around 2gb regardless of what this is set to.

It would be good if sf_filedata wasn't viewable in the browser in-game or at least not until selecting it.

**Comment by thegrb93** [comment]
Wdym? It doesn't read all the data in them. Are you saying it's using up all the ram just from the file names?

**Comment by Jacbo1** [comment]
Basically yeah, probably from starfall allowing you to expand folder trees and view the almost 2,000 files I have in there. Also this has been discussed in the starfall discord before and confirmed by at least one or two other people.

**Comment by Jacbo1** [comment]
Link to the discussion in discord https://discord.com/channels/268423739123826688/268423739123826688/807487926400843797

**Comment by Jacbo1** [comment]
Also it crashes more and more consistently the more files are in there.

**Comment by Jacbo1** [comment]
Confirmed in discord here https://discord.com/channels/268423739123826688/268423739123826688/804045578413146132

**Comment by thegrb93** [comment]
I'll have to try it out and see. Very strange if so

**Comment by Jacbo1** [comment]
By the way, real issues started for me before when I had 21,000 files in there. The 2,000 this time might just be a one off.

**Comment by thegrb93** [comment]
I couldn't reproduce the issue. Tried with that many files.

**Comment by thegrb93** [comment]
I'm just going to remove it though because I imagine that would make searches pretty annoying and the data files being in the editor isn't really necessary.
