### ISSUE TITLE
Textures scaled weirdly for 3D render functions

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#119]

**Comment by thegrb93** [comment]
Will look at this later today. Seems to be a problem with mixing 3d render functions and surface functions.

**Comment by thegrb93** [comment]
Material type might be able to fix this.

**Comment by thegrb93** [comment]
I went ahead and removed the hack. It seems that using the "surface" library with textures, it expects a boundary on the texture. IMesh however, works without this boundary.

**Comment by Damianu** [comment]
https://github.com/thegrb93/StarfallEx/commit/ed03bf416e8d291c2f12246995f2afb3cf1c848e

**Comment by thegrb93** [comment]
I guess this can be closed. Need to do that material implementation though. I probably won't have time until May after finals.
