### ISSUE TITLE
Instance:checkCpu error

### ISSUE THREAD

**Issue by LiddulBOFH** [thegrb93/StarfallEx#1190]
`Hook 'net' errored with: addons/starfallex/lua/starfall/instance.lua:461: attempt to perform arithmetic on field 'start_time' (a nil value)
stack traceback:
    addons/starfallex/lua/starfall/instance.lua:461: in function 'checkCpu'
    addons/starfallex/lua/starfall/libs_sh/net.lua:131: in function 'send'`

Sooo I get this error while working on a script that relies on net functions, doing so in singleplayer, local servers, and P2P sessions, and works absolutely fine otherwise on normal servers.
My guess after looking at where its referencing https://github.com/thegrb93/StarfallEx/blob/192f51a7e7a852a2613d34f26d441d4e49ca95ee/lua/starfall/instance.lua#L461
is that start_time just simply isn't getting set before being able to run this, but I'm not exactly sure how singleplayer/local/P2P would affect this
Happens regardless of the lifetime of the chip itself as well, can reliably reproduce whether its the first possible moment I can send a net message to several minutes later, and on both client/server realms

**Comment by thegrb93** [comment]
Should be fixed now. thanks
