### ISSUE TITLE
Suggestion: add Game Events

### ISSUE THREAD

**Issue by wrefgtzweve** [thegrb93/StarfallEx#1191]
https://wiki.facepunch.com/gmod/Game_Events
Adding a way to use game events in sf would be incredibly helpful and allow for the use of more complex and efficient ways of making scripts. 
A great example for this would be hitmarkers, without game events everything has to be networked from server to client. With a game event the client realm can just use the hook player_hurt.

**Comment by Cheatoid** [comment]
Keep in mind not to expose player's IP address (in case of `player_connect`)... xD

**Comment by banoargeek** [comment]
Yeah, it'd be nice to not have to loop through the players table whenever you want to do stuff.
