### ISSUE TITLE
Hologram counter does not reset immediately

### ISSUE THREAD

**Issue by Jacbo1** [thegrb93/StarfallEx#1198]
When you restart a chip client side, the hologram counter doesn't immediately reset which can lead to the chip erroring from hologram limit being exceeded, even though it was fine before the restart.

**Comment by thegrb93** [comment]
I believe this is to prevent them from being removed during a render hook if the chip errors in a render hook which crashes the game if that happens.

**Comment by thegrb93** [comment]
Maybe could check if instance.data.render.isRendering and only do the timer if that is true
