### ISSUE TITLE
Suggestion: Add some form of SF.EntIsReady(Entity)

### ISSUE THREAD

**Issue by Jacbo1** [thegrb93/StarfallEx#1199]
What I mean is I'd like to be able to use [this](https://github.com/thegrb93/StarfallEx/blob/192f51a7e7a852a2613d34f26d441d4e49ca95ee/lua/starfall/sflib.lua#L762) from within starfall.

**Comment by thegrb93** [comment]
The callback to net.ReadEntity uses this already. I'd rather users not have to worry about this bug and would rather it be handled internally. What use case do you think this needs to be added for?

**Comment by Jacbo1** [comment]
I need it for my networking library which writes everything to stringstreams and networks that.

**Comment by thegrb93** [comment]
What about adding stringstream read/write entity?

**Comment by Jacbo1** [comment]
Yeah that'd be good I think
