### ISSUE TITLE
Stuff to add

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#12]
- [x] Npc functions.
- [x] Team functions.
- [x] Hologram setAngles
- [x] Attachment pos/ang
- [x] MaterialFromScreen
- [x] Url texture load callback
- [x] getScreenInfo
- [x] link functions
- [x] net.WriteData
- [x] multiple links
- [x] Select component model
- [x] Client/Server only preproc
- [x] Fix runRemote
- [x] getFFT
- [x] Clipboard errors
- [x] isTyping
- [x] getScreenResolution
- [x] color __mul
- [x] vector __mul improvements
- [x] bass deinitialization
- [x] hologram setColor setMaterial
- [x] Show examples in docs and helper
- [x] Trails
- [x] Von fixes
- [x] Increase screen resolution
- [x] Check compile status before sending to client.
- [x] Color __add and __sub
- [x] enumerate files.
- [x] add getWiredTo
- [x] add getWiredToName

**Comment by suunrider** [comment]
- [ ] NPC functions
- [ ] Bone functions
- [ ] Team functions
- [ ] Hologram setAngles instead of setAng
- [ ] Attachment pos/ang

much cooler list

**Comment by Orzlar** [comment]
and I trust Team Functions include teamColor() :+1:

**Comment by thegrb93** [comment]
Team is done. Tested it a little, but not fully so let me know if there are any mistakes.

**Comment by thegrb93** [comment]
Finished attachment stuff

**Comment by thegrb93** [comment]
The Bone one will take a very long time and I might need some help since it has so many functions. Idk I might do it, but I'm getting pretty tired for today. I'll finish npc tho.

**Comment by thegrb93** [comment]
Finished npc.

**Comment by suunrider** [comment]
Something like e2's `egpMaterialFromScreen` would be also useful. Also some callback if you load a texture from an URL would be good.

**Comment by thegrb93** [comment]
Let me look up what egpMaterialFromScreen actually does and I'll add a texture load callback for urls. You can catch errors with the try() function, but the quota error is specifically designed to be uncatchable. I'm not sure if allowing quota error to be caught but running the catch function after a delay is good design. I think it would be better design to put cpu monitors on the heavy loops to prevent it from going over quota.

**Comment by suunrider** [comment]
If you want to sandbox some lua, you can't control it's quota

**Comment by thegrb93** [comment]
I guess it can call the catch function next frame so that the quota has time to go down a bit. I will experiment with it.

**Comment by suunrider** [comment]
`render.getScreenInfo()` always returns nil if you connect the chip to a HUD.

**Comment by suunrider** [comment]
Some way to connect a chip to a screen with a function like `entities.self():linkTo( screen )`

**Comment by suunrider** [comment]
You can't select the model of the component with the UI

**Comment by suunrider** [comment]
A preprocessor to let a chip only run serverside or clientside

**Comment by thegrb93** [comment]
I'm going to be studying for my physics ph.d qualifier exams which are next tuesday and wednesday so I have to postpone this until afterwards. Once that's finished I'll be able to add these suggestions.

**Comment by suunrider** [comment]
`hook.runRemote` doesn't work; already fixed in inpstarfall

**Comment by suunrider** [comment]
Errors get set into everyone's clipboard

**Comment by suunrider** [comment]
`getFFT` for bass

**Comment by suunrider** [comment]
something like `Player:isTyping()`

**Comment by thegrb93** [comment]
Returns true if the player has their chat window open?

**Comment by suunrider** [comment]
yes

**Comment by thegrb93** [comment]
I think you can use the renderTarget functions for egpMaterialFromScreen. I'm not sure what you want from that, but let me know.

**Comment by thegrb93** [comment]
render.getScreenInfo() returns information about the screen prop itself, such as offsets or the projector and stuff. I'll update the doc for that.

**Comment by thegrb93** [comment]
I'll add a way to get the screen resolution

**Comment by suunrider** [comment]
Multiply metamethod for colors

**Comment by suunrider** [comment]
Stop the bass sounds automatically when the starfall errors

**Comment by thegrb93** [comment]
Also need to make vector maths invariant to the side the scalar is on.

**Comment by thegrb93** [comment]
I don't think I like errors getting put into my clipboard. How about I make the starfall tool copy the chip's error to clipboard when pressing r while aiming at the chip?

**Comment by suunrider** [comment]
That's how its supposed to work (except you need to press e)

**Comment by thegrb93** [comment]
Okay, I'll fix that. I'm almost done modifying the helper so examples show in it.

**Comment by suunrider** [comment]
Let constraint library have more check types.

**Comment by thegrb93** [comment]
The checktype system is stupid. I'm thinking about just making starfall functions protected call so that they can correctly report garrysmod's own typechecking errors.

**Comment by suunrider** [comment]
It's not stupid. It shows the error fast and displays the line. Some starfall users dont even know glua and dont know what to do with gmod typechecking errors.

**Comment by thegrb93** [comment]
I can map the glua error to a user readable sf error

**Comment by thegrb93** [comment]
Egh I don't know, I need to think about it more. The redundant type checking is really unhealthy for performance. I'll get around to adding more of it to the constraint library.

**Comment by suunrider** [comment]
Change the function to get the chip from self to something like chip, processor. `self` is commonly used and dont think it's good to have it globally

**Comment by thegrb93** [comment]
Yeah I completely forgot about that. Thanks.

**Comment by suunrider** [comment]
Trails

**Comment by suunrider** [comment]
You can use the file library on every client and on the server. You can abuse it by making many many files with much data.

**Comment by suunrider** [comment]
```
addons/starfallex/lua/starfall/libs_cl/render.lua:743: attempt to compare number with nil
stack traceback:
	addons/starfallex/lua/starfall/libs_cl/render.lua:743: in function 'createRenderTarget'
	SF:DrawImage.txt:14: in function 'func'
	addons/starfallex/lua/starfall/instance.lua:38: in function <addons/starfallex/lua/starfall/instance.lua:37>
	[C]: in function 'xpcall'
	addons/starfallex/lua/starfall/instance.lua:71: in function 'runWithOps'
	addons/starfallex/lua/starfall/instance.lua:133: in function 'initialize'
	addons/starfallex/lua/entities/starfall_processor/cl_init.lua:54: in function 'CodeSent'
	addons/starfallex/lua/entities/starfall_processor/cl_init.lua:74: in function 'func'
	lua/includes/extensions/net.lua:32: in function <lua/includes/extensions/net.lua:17>
```
when trying to create a rendertarget with `render.createRenderTarget`

**Comment by suunrider** [comment]
Add to von library starfall types.

**Comment by Orzlar** [comment]
entity:setVar, entity:getVar,  maybe limit these per chip, and have entity:getGVar for global sharing.

I understand this can be created as a library using starfall already, but as its native in glua, could be handy to have it built in.

**Comment by suunrider** [comment]
You can just use rawset and rawget on entities.

**Comment by thegrb93** [comment]
Don't know why they thought unlimited filesaving to the server was a good idea. I fixed the permission that was allowing it on other clients. Fixed rendertarget. I'll see how von is implemented and fix that.

**Comment by suunrider** [comment]
1024x1024 screens

**Comment by McDunkinY** [comment]
Honestly, I've used 3D2D cameras a lot and I haven't noticed a drop in performance if the resolution of the camera is increased. The only issue is with fonts because they can only get so big. By allowing for bigger resolution / scale, fonts and everything else become sharper. I use 0.1 scale on the screens and multiply the size of everything by that scale, including font sizes.

So yes, even if it's not fixed to 1024, at least a scale multiplier set in code as a pre-processor or just completely change 512 as the default

**Comment by thegrb93** [comment]
I can try that. I'll also make scrW and scrH return the resolution of the screen if a screen is being used.

**Comment by thegrb93** [comment]
All of the drawing is done on a rendertarget which is handled by wirelib and all the resolutions are locked at 512x512. I'll need to pr a function that can change the resolution of the rendertarget. I'll make scrW() and scrH() return the resolution of screen theyre attached to.

**Comment by suunrider** [comment]
Can't move the starfall editor out of the garrys mod window (into invisible area). Annoying if you play in window mode and with low resolution.

**Comment by thegrb93** [comment]
I think I remember that reported in garrysmod-issues.

**Comment by suunrider** [comment]
Do a syntax check of the program before sending it to the client.
2 Errors of the same syntax error is useless.

**Comment by suunrider** [comment]
Color add and sub metamethods

**Comment by suunrider** [comment]
A function in the file library to list all the files in a directory

**Comment by suunrider** [comment]
Using clipboard (paste or copy) in starfall editor freezes gmod. I use linux and if i untick "Fix keys not working on linux" the clipboard works fine

**Comment by thegrb93** [comment]
I'll work on these once I get home. Also need to remember to look into why the editor's colors sometimes stop working.

**Comment by thegrb93** [comment]
Got a lot of stuff that needs to be tested then I'll push them.

**Comment by suunrider** [comment]
A way to get information of special entities, e.g. e2 (`getOps`, `getName`).

**Comment by suunrider** [comment]
Something like a global table, but which is for one chip only and the table should be saved if you copy it with advdupe2.

**Comment by thegrb93** [comment]
So multiple links are working, but not nicely with the wire gpu library. I'm just going to write my own render function for the screen since the gpu library is bloated and unnecessary for this application.

**Comment by thegrb93** [comment]
Almost done, just need to fix an issue with the depth buffer.

**Comment by thegrb93** [comment]
Fixed, just need to test. The main difference between this and the previous implementation is that you no longer clear the screen because clearing is automatic now, and if you want to render to a surface that doesn't automatically clear then you need to use a rendertarget.

**Comment by thegrb93** [comment]
The coordinate system will remain the same 0-512 for compatibility (might change this), but resolution is now the same as in-game resolution.

**Comment by thegrb93** [comment]
Need to fix render-targets

**Comment by thegrb93** [comment]
Done. Fixing bug with UV offset and the halo effect causing everything to turn white.

**Comment by suunrider** [comment]
![](http://i.imgur.com/vKD5SsK.jpg)
Color applies to the whole screen if you look at the starfall screen. Dunno if the server applied the latest update (it should).

**Comment by thegrb93** [comment]
I decided not to prevent sending code if the chip errors. That way a friend can view the code and help even if the code errors.

**Comment by suunrider** [comment]
A way to get the entity to which an input is wired too. There's only wirelink_methods:isWired(), but something isWiredTo() would be good

**Comment by thegrb93** [comment]
I believe you would just do. 

local myentity = mywirelink["InputName"]

If you want to get the entity of the wirelink then you would use

local myentity = mywirelink:entity()

**Comment by suunrider** [comment]
mywirelink["InputName"] returns nil

**Comment by thegrb93** [comment]
Ya I think you were talking about entity inputs at first. I pushed the update, getWiredTo will return what the input is wired to.

**Comment by suunrider** [comment]
hm, also some way to get to which output the input is wired to

**Comment by thegrb93** [comment]
Done also added client/server preproc, file.find, and fixed von

**Comment by suunrider** [comment]
* Clamp the colors when subtracting or adding
* Load clientside code for players who joined

**Comment by thegrb93** [comment]
That's weird. Client-side code should be sending when someone joins. I'll check that.

**Comment by suunrider** [comment]
`render.cursorPos` isn't very precise. If you aim on the right side of the screen, the position is a little left to the cursor

**Comment by suunrider** [comment]
implement `Entity:setModelScale`

**Comment by suunrider** [comment]
Remove prop limit

**Comment by suunrider** [comment]
setTrails isnt working

**Comment by thegrb93** [comment]
setTrail worked when I tried it, can you put the code you used?

**Comment by suunrider** [comment]
`e:setTrails(32, 0, 2, "Laser", Color(255, 0, 0), 0, false)`

**Comment by thegrb93** [comment]
I'll try it tomorrow

**Comment by suunrider** [comment]
`holograms.canSpawn()` isn't working.
Error:
```
addons/starfallex/lua/starfall/libs_sv/holograms.lua:303: attempt to call global 'personal_max_reached' (a nil value)
stack traceback:
	addons/starfallex/lua/starfall/libs_sv/holograms.lua:303: in function 'canSpawn'
	SF:Football.txt:8: in function 'func'
	addons/starfallex/lua/starfall/instance.lua:38: in function <addons/starfallex/lua/starfall/instance.lua:37>
	[C]: in function 'xpcall'
	addons/starfallex/lua/starfall/instance.lua:71: in function 'runWithOps'
	addons/starfallex/lua/starfall/instance.lua:251: in function 'runFunction'
	addons/starfallex/lua/starfall/libs_sh/timer.lua:77: in function <addons/starfallex/lua/starfall/libs_sh/timer.lua:68>
```

**Comment by thegrb93** [comment]
Woops. I'll fix that. It's only used to check if your at your limit though so you should be fine without it.

**Comment by suunrider** [comment]
`NPC:attackMelee()` always attacks in one direction

**Comment by suunrider** [comment]
Add `timer.canCreate()`

**Comment by suunrider** [comment]
Add `Ent:getSkin()`

**Comment by thegrb93** [comment]
Can't reproduce the trail not working. Works fine when I tried. Opened a new issue since this one is big.
