### ISSUE TITLE
Bodygroups

### ISSUE THREAD

**Issue by AdamName** [thegrb93/StarfallEx#120]
Seems like `setBodygroup` is throwing an error and there is no `getBodygroups` or similar function at all.

Trying to remove GMan's briefcase:
```chip():isWeldedTo():setBodygroup(1,1)```

> addons/shitfallsapartex/lua/starfall/libs_sv/entities.lua:558: attempt to call method 'SetBodyGroup' (a nil value)
> addons/shitfallsapartex/lua/starfall/libs_sv/entities.lua:558: attempt to call method 'SetBodyGroup' (a nil value)
> stack traceback:
> 	addons/shitfallsapartex/lua/starfall/libs_sv/entities.lua:558: in function 'setBodygroup'
> 	SF:main:5: in main chunk
> 	[C]: in function 'xpcall'
> 	addons/shitfallsapartex/lua/starfall/instance.lua:128: in function 'runWithOps'
> 	addons/shitfallsapartex/lua/starfall/instance.lua:188: in function 'initialize'
> 	addons/shitfallsapartex/lua/entities/starfall_processor/init.lua:112: in function 'Compile'
> 	addons/shitfallsapartex/lua/weapons/gmod_tool/stools/starfall_processor.lua:104: in function 'callback'
> 	addons/shitfallsapartex/lua/starfall/sflib.lua:528: in function <addons/shitfallsapartex/lua/starfall/sflib.lua:519>
> 	[C]: in function 'pcall'
> 	addons/shitfallsapartex/lua/starfall/netstream.lua:60: in function 'Remove'
> 	addons/shitfallsapartex/lua/starfall/netstream.lua:50: in function 'Read'
> 	addons/shitfallsapartex/lua/starfall/netstream.lua:202: in function 'func'
> 	lua/includes/extensions/net.lua:32: in function <lua/includes/extensions/net.lua:17>

Also, when given third argument it's throwing just a bit different thing:
```chip():isWeldedTo():setBodygroup(1,1,owner())```
> lua/includes/util.lua:181: attempt to index local 'object' (a number value)
> lua/includes/util.lua:181: attempt to index local 'object' (a number value)
> stack traceback:
> 	lua/includes/util.lua:181: in function 'IsValid'
> 	lua/includes/extensions/net.lua:52: in function 'WriteEntity'
> 	addons/shitfallsapartex/lua/starfall/libs_sv/entities.lua:440: in function 'sendRenderPropertyToClient'
> 	addons/shitfallsapartex/lua/starfall/libs_sv/entities.lua:556: in function 'setBodygroup'
> 	SF:main:5: in main chunk
> 	[C]: in function 'xpcall'
> 	addons/shitfallsapartex/lua/starfall/instance.lua:128: in function 'runWithOps'
> 	addons/shitfallsapartex/lua/starfall/instance.lua:188: in function 'initialize'
> 	addons/shitfallsapartex/lua/entities/starfall_processor/init.lua:112: in function 'Compile'
> 	addons/shitfallsapartex/lua/weapons/gmod_tool/stools/starfall_processor.lua:104: in function 'callback'
> 	addons/shitfallsapartex/lua/starfall/sflib.lua:528: in function <addons/shitfallsapartex/lua/starfall/sflib.lua:519>
> 	[C]: in function 'pcall'
> 	addons/shitfallsapartex/lua/starfall/netstream.lua:60: in function 'Remove'
> 	addons/shitfallsapartex/lua/starfall/netstream.lua:50: in function 'Read'
> 	addons/shitfallsapartex/lua/starfall/netstream.lua:202: in function 'func'
> 	lua/includes/extensions/net.lua:32: in function <lua/includes/extensions/net.lua:17>

**Comment by thegrb93** [comment]
Okay, I think its all fixed
