### ISSUE TITLE
ents_methods:isValid() uses ent:IsValid() instead of IsValid(ent)

### ISSUE THREAD

**Issue by legokidlogan** [thegrb93/StarfallEx#1207]
Both the master branch and newest release (4.4), `ents_methods:isValid()` assumes the entity has an `IsValid` function if it's not falsy, which is not always the case. Replacing `ent:IsValid()` with `IsValid(ent)` would fix this, as the global `IsValid` function safely checks if the value has an `IsValid` function on it before running. Normally, entities always have it, but rare circumstances can cause the function to become nil or not be assigned in time, erroring the chip.

https://github.com/thegrb93/StarfallEx/blob/34df4c549d0fbc6cd7c5215773be5b4246cb789a/lua/starfall/libs_sh/entities.lua#L674-L681

https://github.com/thegrb93/StarfallEx/blob/2cd527442e440ec9c8810f8f791b96fd6e4c3a3b/lua/starfall/libs_sh/entities.lua#L616-L623

**Comment by thegrb93** [comment]
What would cause an entity to not have an isValid function?

**Comment by thegrb93** [comment]
I think you can use starfall's global isValid() for those weird cases you're talking about. Makes more sense.

**Comment by legokidlogan** [comment]
When you run Starfall's global `isValid(ent)`, it just points to `ents_methods:isValid() `, which tries to use `:IsValid()` instead of the global `IsValid()`, right now the only way for Starfall users to avoid this error is with a pcall.

I'm not entirely certain what scenarios allow for Starfall to think it's an entity while the entity doesn't have `:IsValid()` anymore, but I have had it happen many times while working on a recent project. The error crops up on occasion when looking through ents obtained from `:getAllConstrained()` some time prior, and it often happens while the contraption is getting blown up. So, maybe an entity in that list was in the process of getting removed and lost its `:IsValid()` function, but Starfall hadn't yet recognized the object as not being an entity, thus leading to the error.

Regardless of whether or not that's what led to the error, I know that it does sometimes crop up, and starfall users can't avoid it without using pcall. Switching to `IsValid(ent)` or directly checking if `ent.IsValid` is not nil would fix the issue.

**Comment by legokidlogan** [comment]
> What would cause an entity to not have an isValid function?

@thegrb93 Variables without an `IsValid()` function happens quite commonly in GMod, this case was just a bit weirder since it had to go through Starfall's system first. While writing addons, I almost *always* use `IsValid(ent)` over `ent:IsValid()` because it's pretty easy for a non-entity variable to somehow slip in, or the variable becomes nil instead of a NULL entity.

**Comment by adamnejm** [comment]
> it's pretty easy for a non-entity variable to somehow slip in, or the variable becomes nil

Starfall already performs necessary checks *(before unwrapping)* if the variable isn't guaranteed to be an entity. Those are mostly used in places where function behaves differently depending on the result of that check, but if you are unsure of the data you're handling in your code, you should implement such checks yourself.  
___  
Another thing I noticed is that Starfall uses [`constraint.GetTable`](https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/includes/modules/constraint.lua#L1528-L1566) function which actually doesn't use the global `IsValid`, but uses `IsWorld` and `IsValid` methods.  
Could it be possible that the error you're getting is actually a result of that function not checking for `nil`?
If that's the case we could rewrite it in Starfall instead of using GMod's one. Haven't tested it though, just a thought.

**Comment by legokidlogan** [comment]
> If however a non-nil, non-entity value creeps up [here](https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/includes/modules/constraint.lua#L1545) then we could just rewrite that function in Starfall with proper checks.

`:getAllConstrained()` Never yielded erroneous vars, they became erroneous *later on* (likely while in the process of getting removed), so changing that function won't do anything. The issue is `ents_methods:isValid()`. I could test to see if checking the var's type yields something other than Entity, but the fact that Starfall is using `ents_methods` implies that it believes the var is an ent, which means checking first with the chip won't do any good, not to mention the loss of efficiency that'd come with.

**Comment by thegrb93** [comment]
All right, I pushed a hopefully suitable fix then. Let me know if it works or not
