### ISSUE TITLE
Add doc annotation for deprecated methods (`--@deprecated`)

### ISSUE THREAD

**Issue by Cheatoid** [thegrb93/StarfallEx#1208]
As the title says. This annotation could then be used elsewhere, say for example to display a red warning on those functions in SF helper.  
According to "DEPRECATED" (from function docs) there are 13 of such functions which are deprecated at the moment (and there may be more, just being undocumented).

**Comment by thegrb93** [comment]
I think i'd rather just either remove the deprecated warning or remove whats deprecated

**Comment by Cheatoid** [comment]
Better do the latter then...
