### ISSUE TITLE
Add `input.LookupKeyBinding`

### ISSUE THREAD

**Issue by Cheatoid** [thegrb93/StarfallEx#1211]
[GMod wiki](https://wiki.facepunch.com/gmod/input.LookupKeyBinding)

This function is basically the inverse of [`input.LookupBinding`](https://wiki.facepunch.com/gmod/input.LookupBinding).

**Comment by x4fx77x4f** [comment]
I think that if added, it should be made owner only as it allows for a great deal of information collection, and I can't really think of a legitimate use for it. I don't think just *any* chip should be able to see every single one of my binds.

**Comment by thegrb93** [comment]
I agree
