### ISSUE TITLE
SF not working on archlinux

### ISSUE THREAD

**Issue by VigilanteHobo** [thegrb93/StarfallEx#1223]
Either this bug is an oversight on my part or insanely evil. Posting since I couldn't figure it out on my own.

On Archlinux, StarfallEX (fully lowercase name) everything is missing and no lua errors are thrown unless ACF is also mounted (I haven't installed a patched version that works with SF

**Comment by thegrb93** [comment]
Sounds like addon mounting problem if so

**Comment by adamnejm** [comment]
I'm running Arch and Starfall always has worked for me fine, multiple PCs, multiple installs.
Works when SF is the only addon installed and along with Wiremod, ACF, and basic stuff from workshop.
Also works fine on both the default and the x64 branch.

Must be something on your end.
Also, [ACF-3](https://github.com/Stooberton/ACF-3) is actively maintained and comes with SF library.
