### ISSUE TITLE
Allow file.write() and file.read() to access a starfall/sfshared dir

### ISSUE THREAD

**Issue by Extra-Mental** [thegrb93/StarfallEx#1225]
Allowing the file library to access "data/starfall/sfshared" folder would come in handy for a script I'm making to load specific SF scripts and allowing data to be stored along side those scripts and let it be accessed by the SF editor.

I think it should only be able to access "data/starfall/sfshared" to prevent a rogue SF chip overwriting all of someone's scripts in "data/starfall"

Maybe even a "data/starfall/sfprivate" that ONLY the owner can access

**Comment by thegrb93** [comment]
Imo this is too niche to add. A good workaround is creating a windows 'junction' in your data/starfall folder to data/sf_filedata. Or a symlink if you use linux.
