### ISSUE TITLE
Let --@includdir include all dirs and files contained within be included

### ISSUE THREAD

**Issue by Extra-Mental** [thegrb93/StarfallEx#1228]
Say you had `starfall/dir/subdir/script.txt`
and your main script is `starfall/main.txt`
Would it be possible to use `--@includdir  dir` or `--@includdir  dir/*` to include all dirs and files contained with in it?

**Comment by thegrb93** [comment]
requiredir will need this too I think

**Comment by thegrb93** [comment]
Probably would break some people's things. Adding a recursive option would be safer.

**Comment by Manonox** [comment]
@thegrb93, if it is really complete, how do I actually use it? Can't find any way to make it recursive right now

**Comment by thegrb93** [comment]
Wrong option I guess
