### ISSUE TITLE
CheckType missing

### ISSUE THREAD

**Issue by Damianu** [thegrb93/StarfallEx#124]
https://github.com/thegrb93/StarfallEx/commit/c0709d5484360061399fe870c82d3a5c8603e9d1
As I said in comment, "depth" has no checktype.

**Comment by edgarasf123** [comment]
Since the parameter is boolean type, I don't think you need to check type. If you're not passing `false` or `nil`, the function will treat it as `true`.

**Comment by thegrb93** [comment]
That or error.

**Comment by edgarasf123** [comment]
I checked it, when I pass for instance Vector() for depth, it doesn't give any error.

**Comment by thegrb93** [comment]
Okay it'll be fine then.
