### ISSUE TITLE
Adding 'istype' functions

### ISSUE THREAD

**Issue by ESSYREV** [thegrb93/StarfallEx#1244]
I suggest adding the following functions:

1) isnumber ( https://wiki.facepunch.com/gmod/Global.isnumber )
2) isstring ( https://wiki.facepunch.com/gmod/Global.isstring )
3) istable ( https://wiki.facepunch.com/gmod/Global.istable )
4) ismatrix ( https://wiki.facepunch.com/gmod/Global.ismatrix )
5) isvector ( https://wiki.facepunch.com/gmod/Global.isvector )
6) isangle ( https://wiki.facepunch.com/gmod/Global.isangle )
7) isbool ( https://wiki.facepunch.com/gmod/Global.isbool )
8) IsColor ( https://wiki.facepunch.com/gmod/Global.IsColor )
7) IsEntity ( https://wiki.facepunch.com/gmod/Global.IsEntity )
8) ispanel - Subject to the addition of the ability to create a menu

I think it will be quite useful, because this code [ if tonumber(var) ~= nil then ] does not look very good, and [ if isnumber(var) then ] would be a very good option

**Comment by Vurv78** [comment]
> I think it will be quite useful, because this code [ if tonumber(var) ~= nil then ] does not look very good, and [ if isnumber(var) then ] would be a very good option

You're meant to use the ``type`` function: ``if type(var) == "number"``

Although this would be an optimization (for primitives at least) so maybe these can be added, just not really necessary

**Comment by thegrb93** [comment]
I'll see real quick which is actually faster.

**Comment by thegrb93** [comment]
I do know for a fact that the is\* functions are much slower in x64

**Comment by thegrb93** [comment]
In-fact it might be worth migrating starfall away from TypeID due to this.

**Comment by thegrb93** [comment]
Nvm it doesn't matter. Jit in beta gmod is fucked up for all type related functions.

**Comment by Vurv78** [comment]
Yeah I just meant since primitives wouldn't need the metatable check like type() has

**Comment by thegrb93** [comment]
I added the functions for basic types, but the other types should still use "type" because of wrapping/unwrapping there'd be no performance benefit.
