### ISSUE TITLE
Cannot return false from EntityTakeDamage

### ISSUE THREAD

**Issue by Jacbo1** [thegrb93/StarfallEx#1245]
The glua version of the EntityTakeDamage hook allows you to return false to block damage to the entity but in starfall you cannot.

**Comment by thegrb93** [comment]
That's intended. There is setUnbreakable as an alternative which also blocks damage I think.

**Comment by wrefgtzweve** [comment]
can confirm that setUnbreakable blocks damage on entities

**Comment by thegrb93** [comment]
^

**Comment by Jacbo1** [comment]
> can confirm that setUnbreakable blocks damage on entities

This would block all damage though. If you only wanted to block damage from specific sources, I'm not sure you could currently.

**Comment by thegrb93** [comment]
@adamnejm you should use 'hasPermission' to check if they're allowed to return true. 'check' will error and that's bad inside of this context.

**Comment by thegrb93** [comment]
Here's an example https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/libs_cl/render.lua#L287

**Comment by adamnejm** [comment]
Oh I see, thanks! The function itself works pretty nicely, well besides that error. You can add it yourself, if not, tomorrow I'm gonna fix the perms issue, test it a bit more and then open a PR.
