### ISSUE TITLE
External Lib Example

### ISSUE THREAD

**Issue by ajloveslily14** [thegrb93/StarfallEx#1254]
It would be nice to see an example custom library for starfall. It seems there's a few different ways of doing it, but it would be nice to know the "correct" way

**Comment by adamnejm** [comment]
I don't think there's any difference between external and built-in libraries.  
You get access to the SF table so you can import various functions, tables / types, etc.  
Then you return one function that will be executed for the passed instance.  
  
If you want a concise example: https://github.com/Sevii77/proper_clipping/blob/master/lua/starfall/libs_sv/proper_clipping.lua

**Comment by thegrb93** [comment]
Yeah, 3rd party libs are no different from first party ones. Feel free to ask the discord if you need help

**Comment by thegrb93** [comment]
That's true

**Comment by alexanderjwallen** [comment]
That's fine but it'd still be nice to have at least some direction when creating libraries instead of relying solely on somewhat ambiguous stack traces when starfall initializes.

**Comment by thegrb93** [comment]
There's tons of libraries to learn off of. If you have questions or run into issues, the discord is there to help

**Comment by ajloveslily14** [comment]
Well, me and others *would* join the discord for help, but we're all banned for calling you out for being weird around kids so that's not an option
