### ISSUE TITLE
bass ignoring "noblock" argument

### ISSUE THREAD

**Issue by evilbuddy** [thegrb93/StarfallEx#1255]
I have wrote a little code with a music that should be looping.
I put "noblock" in the bass.loadURL second argument but it ignores it, and errors me that I need to parse the noblock argument to be able to loop the song.

Here is the player part of the code:
```lua
--@client

local music = nil

bass.loadURL(DL .. ID, "mono noblock", function(s)
    if isValid(s) then
        music = s
        s:setLooping(true)
        s:play()
    end
end)
```

**Comment by thegrb93** [comment]
I've never had this issue but I'm guessing some combination of your sound file and 'mono' is causing the error. Seems like a gmod bug.

**Comment by thegrb93** [comment]
It could also be that the web-server the url is from doesn't allow the noblock parameter.

**Comment by thegrb93** [comment]
From the bass API:

```
BASS_STREAM_BLOCK

Download and play the  file in smaller chunks, instead of downloading the entire file to  memory. Uses a lot less memory than otherwise, but it is not possible to  seek or loop the stream; once it has ended, the file must be opened  again to play it again. This flag will automatically be applied when the  file length is unknown, for example with Shout/Icecast streams. This  flag also has the effect of restricting the download rate.
```

**Comment by thegrb93** [comment]
So the problem is the web-server is causing the 'Block' flag to be applied anyway because it's not providing the file length.

**Comment by thegrb93** [comment]
It's not fixed but I provided the info about why it won't work in the doc
