### ISSUE TITLE
enableHud() doesn't use permission system

### ISSUE THREAD

**Issue by chair65** [thegrb93/StarfallEx#1257]
I'd like to see HUD drawing use the permission system. Right now, enableHud() checks if the player is in a vehicle you own, and disconnects them if they leave it. This is unideal as players on foot cannot access your HUD. I'd greatly appreciate it if someone could change this up if it wasn't intentional.

**Comment by thegrb93** [comment]
I think this is a duplicate of https://github.com/thegrb93/StarfallEx/issues/1149

**Comment by chair65** [comment]
> I think this is a duplicate of #1149

My bad 😬.
