### ISSUE TITLE
Allow SetParent functions to use either strings or numbers for attachments

### ISSUE THREAD

**Issue by adamnejm** [thegrb93/StarfallEx#1282]
Right now `Entity.SetParent` can only take a `string` name of the attachment, but clientside's `Hologram.SetParent` can only take a `number` attachment ID. Both should be able to take either type.  
Name from ID for `SetParentAttachmentMaintainOffset` can be easily looked up using [`Entity.GetAttachments`](https://wiki.facepunch.com/gmod/Entity:GetAttachments) in which entries seem to correspond to IDs, so not a big problem.

**Comment by adamnejm** [comment]
You can assign me, will take care of this after #1281

**Comment by thegrb93** [comment]
This was merged
