### ISSUE TITLE
[BUG] Bass objects use X:IsValid() instead of IsValid( X )

### ISSUE THREAD

**Issue by wrefgtzweve** [thegrb93/StarfallEx#1288]
The starfall bass IsValid check uses the metatable IsValid instead of the function, this causes the chip to error whenever the bass object  becomes invalid or nil.

Older issue that had the same issue in entities: https://github.com/thegrb93/StarfallEx/issues/1207

### Error:
```
Hook 'think' errored with: addons/starfallex-master/lua/starfall/libs_cl/bass.lua:234: attempt to call method 'IsValid' (a nil value)
stack traceback:
    addons/starfallex-master/lua/starfall/libs_cl/bass.lua:234: in function 'isValid'
    SF:Music_Player.txt:33: in function <SF:Music_Player.txt:32>
```

### Code used:
![image](https://user-images.githubusercontent.com/69946827/158631532-5190c68b-ed58-4a79-a65c-f673b9e31bee.png)

### "Bug" code:
https://github.com/thegrb93/StarfallEx/blob/95ffa7ef13e150d1a46c808ac7a2270be479fa5a/lua/starfall/libs_cl/bass.lua#L234

**Comment by adamnejm** [comment]
Fixed in https://github.com/thegrb93/StarfallEx/commit/0ec1069de40524b3b9f2c3fd4e4e74752638a2f3
