### ISSUE TITLE
hooks KeyPress and KeyRelease Ignore Keypress

### ISSUE THREAD

**Issue by Orzlar** [thegrb93/StarfallEx#13]
``` hook.add("KeyPress", "TestKey", function(ply,key) print(key) end) ```

key does not print on arrow keys, or numpad.

**Comment by suunrider** [comment]
Use "inputPressed" hook

**Comment by thegrb93** [comment]
Yeah, keypress and player.keydown are for the actual game controls (such as running, jumping, crouching). Don't ask me why garry named them that way. The input library is for all keyboard buttons, and I think that is client-side only (so you'll have to use net library if you want to control stuff on the server with them).
