### ISSUE TITLE
Model viewer button seems to be useless

### ISSUE THREAD

**Issue by Divran** [thegrb93/StarfallEx#1300]
This commit https://github.com/thegrb93/StarfallEx/commit/a92fdd931b598b610ccb0b8d8909d4a6239354d5 deleted the old model viewer and instead changed the button so that it only opens the Q menu. But the way it opens the Q menu makes it get stuck on your screen so that the only way to close it again is to type `+menu` and then `-menu` into console. The aforementioned commit even mentions "it will be removed soon". It may be time to remove this button, but I'll leave that choice up to you thegrb93

**Comment by thegrb93** [comment]
I think a gmod update broke this. I recall it working before.

**Comment by Divran** [comment]
> I think a gmod update broke this. I recall it working before.

Broke which part? The q menu opening? Because sf has been opening that for ages, whereas previously sf had its own model viewer which was deleted for some reason (see the commit I linked earlier). Not sure why that was removed since it probably wouldn't be difficult to make a better search box than the q menu

**Comment by thegrb93** [comment]
Idk, we can revert to the previous code for it tho

**Comment by Divran** [comment]
Probably was something wrong with it, why else was it removed? Should try to find out what that was. Maybe the search algorithm wasn't well optimized and caused lag with tons of content add-ons installed? Or maybe it wasn't able to search through all add-ons correctly?

**Comment by thegrb93** [comment]
Found the commit https://github.com/thegrb93/StarfallEx/commit/e4c5f5d83e724155c9ef5c9859443d6d03e99d97
