### ISSUE TITLE
[BUG] Starfall editor not working at all and erroring.

### ISSUE THREAD

**Issue by wrefgtzweve** [thegrb93/StarfallEx#1302]
Serverside errors:
Second caused by the first.
```
addons/starfallex4.5/lua/starfall/editor/editor.lua:509: bad argument #1 to 'WriteStream' (string expected, got table)
   0.  unkown - [C]:-1
    1.  error - [C]:-1
     2.  WriteStream - addons/advdupe2/lua/autorun/netstream.lua:154
      3.  unkown - addons/starfallex4.5/lua/starfall/editor/editor.lua:509
```
```
Warning! A net message (starfall_docs) is already started! Discarding in favor of the new message! (starfall_openeditor)
   0.  Start - [C]:-1
    1.  OpenEditor - addons/starfallex4.5/lua/weapons/gmod_tool/stools/starfall_processor.lua:189
     2.  Think - addons/starfallex4.5/lua/weapons/gmod_tool/stools/starfall_processor.lua:232
      3.  unkown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:161
```

**Comment by wrefgtzweve** [comment]
https://github.com/thegrb93/StarfallEx/blob/68527049b110af75ee08020255318099ddda58d5/lua/autorun/netstream.lua#L154
https://github.com/thegrb93/StarfallEx/blob/68527049b110af75ee08020255318099ddda58d5/lua/autorun/netstream.lua#L151-L155
https://github.com/thegrb93/StarfallEx/blob/207ac9569015e51dfa8cb722776e18b8f8e57ecf/lua/starfall/editor/docs.lua#L1-L2

Seems like this is the source, yet none of these files have been updated recently?

**Comment by thegrb93** [comment]
SF.Docs is turned into a string here https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/sflib.lua#L1690

If an error happens before that, then it'll remain as a table, so there's an error during initialization causing those errors.

**Comment by wrefgtzweve** [comment]
```
addons/starfallex4.5/lua/starfall/sflib.lua:863: attempt to call field 'StringStream' (a nil value)
   0.  StringStream - [C]:-1
    1.  TableToString - addons/starfallex4.5/lua/starfall/sflib.lua:863
     2.  unkown - addons/starfallex4.5/lua/starfall/sflib.lua:1570
      3.  include - [C]:-1
       4.  unkown - addons/starfallex4.5/lua/autorun/server/sf_init.lua:34
```

Seems to be after the server restarted, yet the line number doesn't seem to match up. 
Yeah we're using an outdated version, I'll open it again if this happens in the latest version too.

**Comment by wrefgtzweve** [comment]
Turns out we're using the latest tagged version from january 5th

**Comment by thegrb93** [comment]
> ```
> addons/starfallex4.5/lua/starfall/sflib.lua:863: attempt to call field 'StringStream' (a nil value)
>    0.  StringStream - [C]:-1
>     1.  TableToString - addons/starfallex4.5/lua/starfall/sflib.lua:863
>      2.  unkown - addons/starfallex4.5/lua/starfall/sflib.lua:1570
>       3.  include - [C]:-1
>        4.  unkown - addons/starfallex4.5/lua/autorun/server/sf_init.lua:34
> ```
> 
> Seems to be after the server restarted, yet the line number doesn't seem to match up. Yeah we're using an outdated version, I'll open it again if this happens in the latest version too.

The bit module failed to load if StringStream is nil

**Comment by wrefgtzweve** [comment]
I'll look into it

**Comment by wrefgtzweve** [comment]
Looking back it seems like another addon might've caused it, sorry again.

**Comment by thegrb93** [comment]
No problem
