### ISSUE TITLE
Make editor not wait on doc download

### ISSUE THREAD

**Issue by Divran** [thegrb93/StarfallEx#1303]
Almost every time you open the starfall editor, you have to wait for it to download the documentation. Two questions here:
* Why do you have to wait for it? Why not open the editor first and *then* download the documentation? Just prevent the user from viewing this documentation until the download is finished. Which brings is to question number 2:
* Why download this at all since there seems to be no way to even look at this downloaded documentation ingame? Pressing the SFHelper button just opens a website.

The code seems to imply that the SFHelper button is meant to work only in non-standard branches, since it checks for the `BRANCH` variable (which afaik is `unknown` in the normal branch). Unless I'm mistaken, this means it'll currently only work in the chromium, x64, dev, or prerelease branches for now but once any of those get merged it'll stop working even for those.

**Comment by Divran** [comment]
All the code here
https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/editor/editor.lua#L76-L100
could be moved into this else statement
https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/editor/sfframe.lua#L1703-L1712

**Comment by adamnejm** [comment]
The documentation is downloaded from the server and it contains all the custom stuff added via extensions. The Starfall's website [[https://thegrb93.github.io/StarfallEx/]](https://thegrb93.github.io/StarfallEx/) has only the built-in stuff.  
Also IIRC the docs won't be downloaded unless the version differs from your local copy, in any case it for sure doesn't happen **every time**.

**Comment by Derpius** [comment]
> once any of those get merged  

:trollface:

**Comment by Divran** [comment]
Pretty sure it happens every time you join a different server. There's still no reason to block the editor from opening though.

**Comment by Vurv78** [comment]
Pretty sure the syntax highlighting also depends on the docs. Might need to check again

**Comment by Divran** [comment]
> Pretty sure the syntax highlighting also depends on the docs. Might need to check again

Took a quick glance and it does look like that is the case. Could still open the editor immediately, then load the docs, then just redraw the visible area when the docs have finished loading, though.

**Comment by Derpius** [comment]
Has anyone looked into just optimising the docgen

**Comment by thegrb93** [comment]
@Divran its basically the same as the E2 'downloading extension info'. The editor uses it for coloring. Sure we could open the editor anyway and have all the colors messed up and redraw when its done, but I think this is the less jank option.

**Comment by Divran** [comment]
Yeah I found that earlier and it does answer one of my two questions.

Not sure why you think loading the highlighter first is less jank. Pretty much every single editor on the planet does it the other way around - you won't find an editor that forces you to wait for the syntax highlighter to load before opening the file.

E2 already does it the less janky way - open the editor first and load info after, then redraw. If I open E2 and take a screenshot immediately, everything's red 

![image](https://user-images.githubusercontent.com/1485728/162071698-7ff69447-11f4-4528-b324-599d5ba9f4cb.png)

and then this updates less than a second later. 

Some things to keep in mind
* E2s synced data seems to take around half the time to send compared to starfall (not sure why that is, less data to send?)
* On my listen server it takes several seconds to load, on some public servers it takes even longer
* SFs cache does barely anything at all if you frequently play on two or more different servers.
* Fixing this will probably be super easy. Actually I'm not even sure why I'm writing here any more since I probably could've already fixed it and posted a PR lul

**Comment by thegrb93** [comment]
Sure I guess not having the colors for a while is ok. The reason it takes SF longer is likely because its also sending all the documentation with the function names.

**Comment by Divran** [comment]
> The reason it takes SF longer is likely because its also sending all the documentation with the function names.

pretty sure e2 does that too though

**Comment by thegrb93** [comment]
Maybe it's starfall's netstream lib sending it less aggressively.

**Comment by Divran** [comment]
alright I'm done, but I am big dumb dumb and made the font editor in the master branch so I'm gonna have to wait until that's merged before I make a PR for this lmao
