### ISSUE TITLE
Starfall chips error when using a non-empty wire Array output

### ISSUE THREAD

**Issue by legokidlogan** [thegrb93/StarfallEx#1312]
```lua
SF:main:16: Invalid type in array at index: 1
```

On branch `4.7`, starfalls error when a non-empty table is passed to a wire `Array` output, regardless of the content types. It doesn't error when the output is instead marked as a wire `Table`, but various wire/e2 components and functions solely require `Array`s, making them needed at times.

For example,

(error)
```lua
wire.adjustOutputs( { "Test" }, { "Array" } )

wire.ports.Test = {
    1,
    2,
    3,
}
```

(error)
```lua
wire.adjustOutputs( { "Test" }, { "Array" } )

wire.ports.Test = {
    chip(),
}
```

(no error)
```lua
wire.adjustOutputs( { "Test" }, { "Array" } )

wire.ports.Test = {}
```

(no error)
```lua
wire.adjustOutputs( { "Test" }, { "Table" } )

wire.ports.Test = {
    1,
    2,
    3,
}
```

**Comment by thegrb93** [comment]
Fixed
