### ISSUE TITLE
Using setParent to deparent only works on props parented by starfall

### ISSUE THREAD

**Issue by diemarthaha** [thegrb93/StarfallEx#1313]
^

**Comment by wrefgtzweve** [comment]
Me and a few other people have the same issue, traced it back to https://github.com/thegrb93/StarfallEx/commit/c3f31b490ff7cf77471bbc63cb3c4f23a3c45a67 and https://github.com/thegrb93/StarfallEx/blob/8ba5292ad07d4e17f81c0cbcc88d80c3834ec6f7/lua/starfall/libs_sh/entities.lua#L340-L341
