### ISSUE TITLE
:unparent() being removed breaks backwards compatibility

### ISSUE THREAD

**Issue by legokidlogan** [thegrb93/StarfallEx#1314]
`:deparent()` has been completely replaced by `:setParent( nil )`, which breaks starfall chips that use the old function, requiring people to update it in every single starfall script and AdvDupe with them. A real pain.

**Comment by Vurv78** [comment]
Did that function ever exist?

I don't see it in github commit/code logs, nor INPStarfall / original sf?
Also it isn't a glua function so I don't see why it'd exist.

Can only find it as an e2 function

**Comment by legokidlogan** [comment]
Sorry, meant to put `:unparent()`, which was removed in [`c3f31b4`](https://github.com/thegrb93/StarfallEx/commit/c3f31b490ff7cf77471bbc63cb3c4f23a3c45a67)

[lua/starfall/libs_sv/entities.lua lines 119-124](https://github.com/thegrb93/StarfallEx/commit/c3f31b490ff7cf77471bbc63cb3c4f23a3c45a67#diff-81ced901439124d5a7950ece022afdea692e56c623ebe7b0e219e2381577ed81L119-L124)
