### ISSUE TITLE
Suggestion: Add EntityEmitSound hook.

### ISSUE THREAD

**Issue by QualityOverQuantity** [thegrb93/StarfallEx#1316]
Title.

**Comment by ANormalTwig** [comment]
Would this only apply to entities that the player can toolgun?

**Comment by QualityOverQuantity** [comment]
Yah, I would assume so.

**Comment by QualityOverQuantity** [comment]
`-- Register privileges
registerprivilege("entities.canTool", "CanTool", "Whether or not the user can use the toolgun on the entity", { entities = {} })

--- Called whenever a sound has been played. This will not be called clientside if the server played the sound without the client also calling Entity:EmitSound.
-- @name EntityEmitSound
-- @class hook
-- @shared
-- @param table data Information about the played sound. Changes done to this table can be applied by returning true from this hook. See https://wiki.facepunch.com/gmod/Structures/EmitSoundInfo.
-- @return boolean? Return true to apply all changes done to the data table. Return false to prevent the sound from playing. Return nil or nothing to play the sound without altering it.
add("EntityEmitSound", nil, function(instance, data)
	return true, {SF.StructWrapper(instance, data, "Sound")}
end, function(instance, data)
	if (instance.player == SF.Superuser or haspermission(instance, data.Entity, "entities.canTool")) then
		return true
	end
end)`

Don't know what else needs to be added to get this to work. Hook registers properly and detects sound emission. However, for some reason making adjustments the sound data table and passing true does not result in any changes to the sound itself. Also not sure if I did the can tool check properly, but figured I might as well give it a try.

**Comment by thegrb93** [comment]
Try pull requesting that

**Comment by StyledStrike** [comment]
If returning `true`, that canTool check isn't quite working right now, it makes the permission system throw this error:

```
lua/starfall/permissions/core.lua:86: attempt to call a nil value
  1. haspermission - addons/starfall/lua/starfall/permissions/core.lua:86
   2. customretfunc - addons/starfall/lua/starfall/libs_sh/hook.lua:449
    3. v - addons/starfall/lua/starfall/sflib.lua:658
     4. unknown - lua/includes/modules/hook.lua:96
```

If returning `false`, it does not prevent the sound from playing (differently from what it should be).
Also, I'm guessing that modifying the sound data table does nothing because the StructWrapper creates a copy instead.

**Comment by thegrb93** [comment]
Yeah returning true does nothing. Returning false worked in my tests.
