### ISSUE TITLE
Chips created on newer versions of Starfall will not load code on older versions

### ISSUE THREAD

**Issue by QualityOverQuantity** [thegrb93/StarfallEx#1318]
Starfall Chips don't seem to be backwards compatible, resulting in dupes breaking on older versions of Starfall, even if it's only by a couple of versions.

**Comment by thegrb93** [comment]
They are backwards compatible, they aren't forwards compatible.

**Comment by thegrb93** [comment]
Also the dupe format changed years ago, so they should've updated by now

**Comment by QualityOverQuantity** [comment]
> They are backwards compatible, they aren't forwards compatible.

Do you perhaps mean the opposite. I have no issues with older chips working fine whenever Starfall is updated. However, when I attempt to load chips duped on an newer version of Starfall on a server with a previous version, the code does not load at all, and the chips themselves are empty.

**Comment by thegrb93** [comment]
> I have no issues with older chips working fine whenever Starfall is updated

That's backwards compatibility

**Comment by QualityOverQuantity** [comment]
I see. I guess is it possible to add forwards compatibility. E2 seems to have it. I would appreciate at least being able to spawn newer dupes on older versions without manually reuploading all the code.

**Comment by thegrb93** [comment]
Like I said, they are at least 4 years behind. Putting the code into it manually might not even work.
