### ISSUE TITLE
Add render.drawFilledCircle

### ISSUE THREAD

**Issue by xbyte3** [thegrb93/StarfallEx#1319]
It would be very useful, since drawing only the outline of a circle is almost useless.

**Comment by ANormalTwig** [comment]
There's no default function for drawing a filled circle. You can make a polygon for a circle and use render.drawPoly()

**Comment by thegrb93** [comment]
We can use the rounded rect and a mesh to do a circle. drawPoly is super slow

**Comment by thegrb93** [comment]
Here's the code they use for rounded rects. We can use these textures based on the circle size https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/includes/modules/draw.lua#L199-L203

**Comment by thegrb93** [comment]
And something close to this for the mesh.

```lua
local circleMesh = {
	-- Top Left Quad
	{pos = Vector(-0.5, -0.5, 0), u = 1, v = 1},
	{pos = Vector(0, -0.5, 0), u = 0, v = 1},
	{pos = Vector(0, 0, 0), u = 0, v = 0},
	{pos = Vector(-0.5, -0.5, 0), u = 1, v = 1},
	{pos = Vector(0, 0, 0), u = 0, v = 0},
	{pos = Vector(-0.5, 0, 0), u = 1, v = 0},
	-- Top Right Quad
	{pos = Vector(0, -0.5, 0), u = 0, v = 1},
	{pos = Vector(0.5, -0.5, 0), u = 1, v = 1},
	{pos = Vector(0.5, 0, 0), u = 1, v = 0},
	{pos = Vector(0, -0.5, 0), u = 0, v = 1},
	{pos = Vector(0.5, 0, 0), u = 1, v = 0},
	{pos = Vector(0, 0, 0), u = 0, v = 0},
	-- Bottom Left Quad
	{pos = Vector(-0.5, 0, 0), u = 1, v = 0},
	{pos = Vector(0, 0, 0), u = 0, v = 0},
	{pos = Vector(0, 0.5, 0), u = 0, v = 1},
	{pos = Vector(-0.5, 0, 0), u = 1, v = 0},
	{pos = Vector(0, 0.5, 0), u = 0, v = 0},
	{pos = Vector(-0.5, 0.5, 0), u = 1, v = 1},
	-- Bottom Right Quad
	{pos = Vector(0, 0, 0), u = 0, v = 0},
	{pos = Vector(0.5, 0, 0), u = 1, v = 0},
	{pos = Vector(0.5, 0.5, 0), u = 1, v = 1},
	{pos = Vector(0, 0, 0), u = 0, v = 0},
	{pos = Vector(0.5, 0.5, 0), u = 1, v = 1},
	{pos = Vector(0, 0.5, 0), u = 0, v = 1},
}
```

**Comment by CornerPin** [comment]
@thegrb93 I feel like using a pre-generated circle mesh would be better than using a rounded rect texture.

Pros:
- The circle can be scaled to any size without blurring the circle edges.
- Can be textured.
- Works well with the stencil buffer. A rounded rect texture will write to the stencil buffer regardless of the transparency of the texture pixels.

The only con I see is that it will require a few more triangles to draw.

**Comment by thegrb93** [comment]
2 cons,
Won't be perfectly round unless you use 50 triangles maybe and the edges will be hard instead of soft. I'd be ok with it that way though. I'm not writing it.

**Comment by CornerPin** [comment]
It seems like it can't be done with a pre-generated mesh because it turns out you can't dynamically change its color. Even `render.SetColorModulation` does nothing to it.

**Comment by Vurv78** [comment]
Yeah you need to set the $color and $alpha flags on the mesh material

**Comment by thegrb93** [comment]
Code looks clean, nice. Only problem is you can't use your own material on it I think.

**Comment by thegrb93** [comment]
Maybe only use the circle material if there's no material set?

**Comment by CornerPin** [comment]
It needs to store the last set material in a variable just like `render.setColor` does, then it should be possible.

**Comment by thegrb93** [comment]
Probably not necessary. If someone really wanted it, they use the circle as a stencil and draw their material as a quad with the stencil.
