### ISSUE TITLE
WebSocket can be used to run Javascript

### ISSUE THREAD

**Issue by ANormalTwig** [thegrb93/StarfallEx#1321]
![image](https://user-images.githubusercontent.com/78218557/171481386-37e4a63c-aad5-4750-81a4-c115440666b6.png)
![image](https://user-images.githubusercontent.com/78218557/171481441-6e55a27d-9577-42fa-b219-126886c7dac2.png)
Yeah, I know my console font looks terrible.

**Comment by ANormalTwig** [comment]
https://github.com/thegrb93/StarfallEx/blob/fb546610c36f8e0e77ec6a297b44116c47a44027/lua/starfall/libs_cl/websocket.lua#L11-L23
Could probably replace this with RunJavascript or something that doesn't Involve html

**Comment by thegrb93** [comment]
Not a huge issue since only owners can run it on them self. Also @Vurv78 this 'p' looks like a typo https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/libs_cl/websocket.lua#L44
