### ISSUE TITLE
Can't pcall(require, ...)

### ISSUE THREAD

**Issue by Manonox** [thegrb93/StarfallEx#1324]
```lua
require("lib/vectormath.txt")
print(vector) -- Does work
```

```lua
local success, v = pcall(require, "lib/vectormath.txt")
print(vector) -- Doesn't work
```

Results in:
```lua
success == false
v == {
line=957
traceback=stack traceback:addons/starfall/lua/starfall/libs_sh/builtins.lua:957: in function 'pcall'SF:platform/main.txt:10: in main chunk
message=addons/starfall/lua/starfall/libs_sh/builtins.lua:957: Can't find file 'lib/vectormath.txt' (did you forget to --@include it?)
file=addons/starfall/lua/starfall/libs_sh/builtins.lua
}
```

Don't even ask why I need this, it's complicated...

**Comment by ANormalTwig** [comment]
Did you add `--@include lib/vectormath.txt` somewhere in your code?

**Comment by Manonox** [comment]
`--@includedir lib`

**Comment by Vurv78** [comment]
That's not a pcall issue. You are supposed to use ``requiredir`` to get the return values from ``--@includedir``, which I just learned and yeah that is pretty confusing. Maybe require should allow for that as well (or that's intended behavior that isn't working right now)?

**Comment by ANormalTwig** [comment]
Why even the need for directives? Can't you just read from the starfall directory and run it almost like loadstring does?

**Comment by Vurv78** [comment]
It needs to network it, but yeah I was thinking you could just have a preprocessor scan for require() calls with literal strings, but whatever

**Comment by Manonox** [comment]
> It needs to network it, but yeah I was thinking you could just have a preprocessor scan for require() calls with literal strings, but whatever

Kind of impossible to really do that, what if someone wants to dynamically require something

**Comment by Manonox** [comment]
Or for that matter, require EVERYTHING dynamically

**Comment by ANormalTwig** [comment]
I mean requiring dynamically doesn't really work with the current system anyway

**Comment by CornerPin** [comment]
It happens because when `require` tries to get the current script path it looks for the second function in the call stack, but when `require` is called by `pcall`, `short_src` of the second function is `[C]`.
https://github.com/thegrb93/StarfallEx/blob/b62e44e4d7f039dfd1d2359a53515254902a94d5/lua/starfall/libs_sh/builtins.lua#L711
Maybe it needs to check the whole stack and search for the first path that starts with `SF:`.

**Comment by Manonox** [comment]
> I mean requiring dynamically doesn't really work with the current system anyway
I am trying to make it possible that's the thing
At least requiring dynamically from a folder / a set of folders

**Comment by CornerPin** [comment]
See if it works now.
