### ISSUE TITLE
net.write/readTable does not work well for colors

### ISSUE THREAD

**Issue by ProfessorBoxtrot** [thegrb93/StarfallEx#1326]
When sending a color through net.write/readTable, it is not received as a color, but rather as a table with the string keys r,g,b, and a. As a result, no Color library methods can be called on the received color. If you use net.write/readColor instead, the color is properly received and the type is Color.

Example code:
```
if SERVER then
    local c = Color(255,0,0)
    local cClone = c:clone() --works
    
    timer.simple(3, function()
        net.start("sendColor")
        net.writeTable({
            Color = c
        })
        net.send()
    end)
end


if CLIENT then
    net.receive("sendColor", function()
        local c = net.readTable().Color
        print(type(c)) --table
        local cClone = c:clone() --error: attempt to call method 'clone' (a nil value)
    end)
end
```

**Comment by ProfessorBoxtrot** [comment]
what do you mean by function variables? I'm just sending a color inside of a table.

**Comment by ANormalTwig** [comment]
a Color is just a table with a metatable containing color functions and r, g, b, and a values.

**Comment by ProfessorBoxtrot** [comment]
so is a Vector, but you're able to send that through net.writeTable just fine.

**Comment by ANormalTwig** [comment]
hang on im stupid. Starfall turns tables into a string with certain types like vectors getting their own format

**Comment by ANormalTwig** [comment]
looks like its an issue with using TypeID() at https://github.com/thegrb93/StarfallEx/blob/5cdf9d0f7790cd9a11ec538487a9cc9b3b988625/lua/starfall/sflib.lua#L1099
