### ISSUE TITLE
Starfall holograms count towards the SENT limit

### ISSUE THREAD

**Issue by legokidlogan** [thegrb93/StarfallEx#1328]
While sf holos can be spawned past the SENT limit, they still add to it, preventing other things from spawning, such as ammo pickups.

**Comment by thegrb93** [comment]
It's because of https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/libs_sh/holograms.lua#L158

Could maybe change it to PlayerSpawnObject check.

**Comment by thegrb93** [comment]
I think someone in the past was complaining about holograms not calling PlayerSpawnedSENT though. If we want to keep PlayerSpawnedSENT, maybe need to decrease the sent counter afterwards as a workaround.

**Comment by thegrb93** [comment]
prop.createComponent and prop.createSent ones need to be addressed too.

**Comment by legokidlogan** [comment]
Not sure why someone would've wanted it to call `PlayerSpawnedSENT` considering the end result is roughly equivalent to just a pseudo-prop without physics, not an object with special scripting.

If someone wanted to listen to sf holos being created, they could wrap `holograms_library.create` or request for some new, Starfall-specific hook to be used instead.


WireMod (indirectly) uses `PlayerSpawnObject` on E2 holograms for model restriction checks, which seems reasonable to me.

**Comment by thegrb93** [comment]
https://github.com/thegrb93/StarfallEx/pull/1329

**Comment by adamnejm** [comment]
Now you receive this for each spawned holo lol
![image](https://user-images.githubusercontent.com/7283019/174034912-101e368b-7594-4a3d-a5d0-b70f9dcc6d0a.png)

**Comment by thegrb93** [comment]
See if latest update fixes it
