### ISSUE TITLE
Errors thrown in WebSocket functions don't halt the chip

### ISSUE THREAD

**Issue by ANormalTwig** [thegrb93/StarfallEx#1332]
![image](https://user-images.githubusercontent.com/78218557/173252627-a755be4f-5b86-4575-b263-1fc93f79ac07.png)
![image](https://user-images.githubusercontent.com/78218557/173252629-04299f34-82e9-4cd0-89f9-72b033e16e48.png)
![image](https://user-images.githubusercontent.com/78218557/173252636-436b8bfc-803f-4ed1-a12e-72cf71a7d27c.png)

**Comment by thegrb93** [comment]
The callbacks should be changed to use instance:runFunction if we want this.
