### ISSUE TITLE
Long player names break the Starfall List UI

### ISSUE THREAD

**Issue by CornerPin** [thegrb93/StarfallEx#1334]
When a player has a long name the rest of the content doesn't fit.
![image](https://user-images.githubusercontent.com/7669876/173571181-48f2e247-1761-41b3-9940-934015a5edea.png)
![image](https://user-images.githubusercontent.com/7669876/173571317-fc296234-fdea-405e-b8c5-347f0cc02178.png)

**Comment by thegrb93** [comment]
I think the solution is to make the size of the label to a set value.

**Comment by thegrb93** [comment]
It would be a good idea to remove 'Usaage' as well because its a typo and takes up a lot of space.
