### ISSUE TITLE
Parenting bugs and inconsistencies

### ISSUE THREAD

**Issue by adamnejm** [thegrb93/StarfallEx#1336]
Caused by https://github.com/thegrb93/StarfallEx/pull/1281, although some inconsistencies between serverside and clientside parenting were present before that.
```lua
--@client
local holo = holograms.create(owner():getPos(), Angle(), "models/holograms/cube.mdl")
holo:setParent(owner(), "chest") 
holo:setParent(owner(), 3)
--[[
Either one of these calls results in:
addons/starfall/lua/starfall/sflib.lua:494: attempt to call method 'Fire' (a nil value)
stack traceback:
    addons/starfall/lua/starfall/sflib.lua:494: in function 'setParentType'
    addons/starfall/lua/starfall/sflib.lua:525: in function 'setParent'
    addons/starfall/lua/starfall/sflib.lua:572: in function 'Parent'
    addons/starfall/lua/starfall/libs_sh/entities.lua:338: in function 'setParent'
    SF:main:3: in main chunk
]]
```

```lua
--@shared
local holo = holograms.create(owner():getPos(), Angle(), "models/holograms/cube.mdl")
holo:setParent(owner(), nil, 0)
holo:setParent(nil)
--[[
addons/starfall/lua/starfall/sflib.lua:505: bad argument #2 to 'FollowBone' (number expected, got no value)
stack traceback:
    [C]: in function 'FollowBone'
    addons/starfall/lua/starfall/sflib.lua:505: in function 'unParentType'
    addons/starfall/lua/starfall/sflib.lua:513: in function 'setParent'
    addons/starfall/lua/starfall/libs_sh/entities.lua:342: in function 'setParent'
    SF:main:6: in main chunk
]]
```

```lua
--@server
local holo = holograms.create(owner():getPos(), Angle(), "models/holograms/cube.mdl")
holo:setParent(owner(), "chest")
-- Hologram stays at feet, follows aim
```

```lua
--@server
local holo = holograms.create(owner():getPos(), Angle(), "models/holograms/cube.mdl")
holo:setPos(owner():getAttachment(owner():lookupAttachment("chest")))
holo:setParent(owner(), "chest")
-- Hologram is offset from feet to chest, but follows aim
```

```lua
--@shared
local holo = holograms.create(chip():getPos(), Angle(), "models/holograms/cube.mdl")
if SERVER then holo:setColor(Color(255,0,0)) end
holo:setParent(owner())
-- Inconsistency: serverside holo offsets on parent, clientside holo simply parents
```

```lua
--@shared
local holo = holograms.create(owner():getPos(), Angle(), "models/holograms/cube.mdl")
if SERVER then holo:setColor(Color(255,0,0)) end
timer.simple(1, function() -- Wait for Toolgun animation
    holo:setParent(owner(), nil, 6) -- ValveBiped.Bip01_Head1
end)
-- Clientside holo jumps to bone position, but its angles differ from select(2, owner():getBonePosition(6))
-- Serverside holo jumps to somewhere around head, angles not correct either
```

**Comment by thegrb93** [comment]
For the first one, it seems parenting to attachment is only possible in serverside.

**Comment by thegrb93** [comment]
The second one is normal because the hologram maintains its current position when you parent it.

**Comment by thegrb93** [comment]
I think the fourth one's issue might be related to this error
```
!! ERROR: bad input/output link:
!! starfall_hologram(starfall_hologram,SetParentAttachmentMaintainOffset) doesn't match type from <null>(<null>)
```

**Comment by adamnejm** [comment]
> The third one is normal because the hologram maintains its current position when you parent it. You need to set its position and angle to the check attachment first.

```lua
--@server
local holo = holograms.create(owner():getPos(), Angle(), "models/holograms/cube.mdl")
local att = owner():lookupAttachment("chest")
local pos, ang = owner():getAttachment(att)
holo:setPos(pos)
holo:setAngles(ang)
holo:setParent(owner(), att)
-- holo:setParent(owner(), "chest") -- same thing as above
```
You mean this? While the position and angles are now set correctly, it still follows aim instead of being parented to the chest.

**Comment by thegrb93** [comment]
Yeah I think that's also due to this error
```
!! ERROR: bad input/output link:
!! starfall_hologram(starfall_hologram,SetParentAttachmentMaintainOffset) doesn't match type from <null>(<null>)
```

**Comment by thegrb93** [comment]
The 5th/6th ones I think are just source engine quirks that can't be helped

**Comment by thegrb93** [comment]
I fixed the 1st and 2nd ones. Just need to figure out why `self.ent:Fire("SetParentAttachmentMaintainOffset", self.param, 0.01)` isn't working. Might just be holograms affected.

**Comment by adamnejm** [comment]
> The 5th/6th ones I think are just source engine quirks that can't be helped

Would it make sense to decrease the discrepancy manually? For example, offsetting the clientside hologram in the 5th example to match serverside's hologram behavior? If the offset is predictable of course

**Comment by thegrb93** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/5253

**Comment by adamnejm** [comment]
@thegrb93
The error is caused by the fact that you're providing a number parameter to the `SetParentAttachmentMaintainOffset` and [Valve Developer Wiki - Entity Hierarchy](https://developer.valvesoftware.com/wiki/Entity_Hierarchy_(parenting)) states:

### SetParentAttachment
>  The parameter is the name of the attachment point.

### SetParentAttachmentMaintainOffset
> This works exactly the same as the SetParentAttachment input [...]

___

After I changed the parameter to a `string`, it worked without throwing an error.
I think you can close the https://github.com/Facepunch/garrysmod-issues/issues/5253

**Comment by adamnejm** [comment]
Also, they recommend 0.02 delay between `SetParent` and `SetParentAttachmentMaintainOffset` calls. Starfall, even before the rework used `0.01` and it was fine, but it may be worth increasing that just in case.

**Comment by thegrb93** [comment]
Might be a good idea to try. Gonna sleep now tho

**Comment by thegrb93** [comment]
Didn't seem to help
