### ISSUE TITLE
Cannot manipulate server-sided holograms

### ISSUE THREAD

**Issue by NullLikesNothing** [thegrb93/StarfallEx#1337]
Starfall does not allow me to manipulate server side holograms in anyway (Client side is fine though)
![image](https://user-images.githubusercontent.com/82908498/174069443-94b5ade8-b492-411b-8b3a-6fa50e3c6b3a.png)
![image](https://user-images.githubusercontent.com/82908498/174069510-165b75ef-256d-4a46-b6b6-95e7540c1d35.png)

**Comment by adamnejm** [comment]
I'm thinking this could be because PlayerSpawnedSENT was hooked to Prop Protection in order to assign ownership.

**Comment by adamnejm** [comment]
Yep, https://github.com/Nebual/NadmodPP/blob/4dbf07b6f9ddaa579f0c857782849099c6857389/lua/autorun/server/nadmod_pp.lua#L310
