### ISSUE TITLE
Editor: CTRL+C doesnt work on linux

### ISSUE THREAD

**Issue by Damianu** [thegrb93/StarfallEx#134]
As stated in title, it just doesnt work.
Arch Linux 64 bit

**Comment by thegrb93** [comment]
Is the 'fix keybinds' setting enabled?

**Comment by thegrb93** [comment]
Okay I think maybe its because the HTML panel doesn't have lua running enabled. I'm going to change it to use a function rather than lua.

**Comment by thegrb93** [comment]
Okay it should be good now.
