### ISSUE TITLE
Make starfall code access permission list

### ISSUE THREAD

**Issue by Superlamaface** [thegrb93/StarfallEx#1347]
Expression 2 already has this feature implemented to it, and I think its a really good idea. I believe this should be looked into and would be a nice edition to Starfall as a whole. It will allow the chip owners to more easily control who can have their chips and who can't. 

- This would be separate for each chip and not a global permission.
- It will also have a global whitelist for people you want to have access to everything.

**Comment by thegrb93** [comment]
Could be an option added to the context menu (the one that lets you block users' starfalls).

**Comment by Superlamaface** [comment]
So a new tab like permission

**Comment by thegrb93** [comment]
Yeah, a button with the people icon, next to the settings icon, would work.

**Comment by Derpius** [comment]
> Expression 2 already has this feature implemented to it  

I assume you’re talking about my view requests PR?  

I thought about implementing it in starfall but never got around to it (and now I’m working on a game and prepping for a software engineer job so I haven’t touched gmod in like a month). However the majority of my code in wire is standalone, and could be ported across to starfall fairly easily

**Comment by Superlamaface** [comment]
I am talking about that exactly, I thought it was a great addition to e2 and was thinking that it would be a good thing for Starfall.

**Comment by thegrb93** [comment]
> > Expression 2 already has this feature implemented to it
> 
> I assume you’re talking about my view requests PR?
> 
> I thought about implementing it in starfall but never got around to it (and now I’m working on a game and prepping for a software engineer job so I haven’t touched gmod in like a month). However the majority of my code in wire is standalone, and could be ported across to starfall fairly easily

Does your code stop the duplicator tool? I'm not seeing any logic for that. Probably need to add that.

**Comment by Derpius** [comment]
@thegrb93 
> Does your code stop the duplicator tool? I'm not seeing any logic for that. Probably need to add that.

From my PR:
> Not preventing duplication of chips
> 
> After a suggestion from one of the people I tested with, the duplication process remains unchanged, as you can check if your chip was duped and act accordingly from within E2, and would prevent people from easily sharing complex creations with multiple chips.

Of course this behaviour could be adjusted but that was my reasoning

**Comment by thegrb93** [comment]
It's pretty easy to get around e2 dupe detection (just set max quota to 0 and delete the dupe protection) so it would make sense to have dupe protection.

**Comment by Derpius** [comment]
Would also need to implement some batch request for dupes with multiple chips (as well as handling a dupe that has chips from multiple players), and would mean detouring vanilla duplicator, adv dupe 2, and adv dupe 1 in such a way that a duplication can be cancelled, and then restarted by the view request code

**Comment by thegrb93** [comment]
No, just return false in ENT:CanTool if the player doesn't have permission

**Comment by thegrb93** [comment]
So I think for this, the client will have a file of allowed users.

When uploading a chip to the server, if this allowed list isn't empty, it'll look for currently joined players in the list and add them to the upload.

If a player joins the server and is in their list, the client will have to send a net message giving them permission to the existing chips.

ENT:CanTool will return false for chips that have a list of allowed players and the player tooling it isn't in the list

**Comment by thegrb93** [comment]
Actually ENT:CanTool might not be enough if a prop protection's CanTool returns true.

**Comment by thegrb93** [comment]
Looks like nadmod and fpp both don't so it should work fine.

**Comment by thegrb93** [comment]
Looks like prop protections don't return true, but admin mods most likely do.

**Comment by thegrb93** [comment]
Checks can be added here https://github.com/thegrb93/StarfallEx/blob/master/lua/entities/starfall_processor/shared.lua#L106
https://github.com/thegrb93/StarfallEx/blob/master/lua/entities/starfall_processor/init.lua#L85

Uploading and reading the allowed list info added here: max 64 steamids (512 bytes as a string)
https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/transfer.lua#L146
https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/transfer.lua#L116

Allowed users setting menu can be added to
https://github.com/thegrb93/StarfallEx/blob/f7c33ce0e0704c946ed048a88385d1b0d19f7b4e/lua/starfall/editor/sfframe.lua#L1094

```lua
function ENT:CanRead(ply)
    return ply==self.owner or table.Empty(self.canread) or self.canread[ply:SteamID64()]
end
```

**Comment by thegrb93** [comment]
Also this class can be extended to manage the list and file. https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/sflib.lua#L361

**Comment by thegrb93** [comment]
I'm mostly afraid adding this will make admins not like starfall since they won't have the ability to audit code and its too much work for a feature that prop protections already cover.
