### ISSUE TITLE
Change quota* functions to cpu*

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#1365]

**Comment by adamnejm** [comment]
Are you gonna keep backwards compatibility by aliasing the old functions?

**Comment by adamnejm** [comment]
Also, sorta related, how about changing `holograms` to `hologram`, it drives me nuts that it's plural while all other libraries are not.

**Comment by Vurv78** [comment]
``trace.trace`` and ``trace.traceHull`` 😅

**Comment by adamnejm** [comment]
> ``trace.trace`` and ``trace.traceHull`` 😅

`trace.ray` mb?
  
I like where this thread is going...

**Comment by Vurv78** [comment]
I think ``trace.line`` would fit better alongside ``trace.hull``

**Comment by Vurv78** [comment]
Also, ``sounds`` is plural as well (even going against glua's ``sound``) 🤔

**Comment by thegrb93** [comment]
I'm also going to move all the aliases to a single area.

**Comment by adamnejm** [comment]
`Material.setTextureRenderTarget`
`render.setRenderTargetTexture`

**Comment by adamnejm** [comment]
https://github.com/thegrb93/StarfallEx/blob/4d9701daee2f771f47b59f2b743cc1669f1ea08d/lua/starfall/libs_sh/entities.lua#L356-L357

**Comment by thegrb93** [comment]
yeah they can all be found by searching "=.+_methods" "=.+_library" in files
