### ISSUE TITLE
Make Client/Server CPU for other chips accessible

### ISSUE THREAD

**Issue by sr229** [thegrb93/StarfallEx#1368]
I do not know if this is already an issue, but Expression 2 has the ability to lookup other player's E2 name, E2 ops, and CPU time. This would probably be useful if this info is readily accessible in Starfall's side too, but there was no mention nor example of this of how to pull such data.

**Comment by Vurv78** [comment]
https://thegrb93.github.io/StarfallEx/#Types.Entity.getChipName

https://thegrb93.github.io/StarfallEx/#Types.Entity.getQuotaAverage

There is no ops getter though (ops are pretty useless anyway)

**Comment by thegrb93** [comment]
^
