### ISSUE TITLE
Cannot target sweps you have permission on

### ISSUE THREAD

**Issue by NullLikesNothing** [thegrb93/StarfallEx#1371]
You cannot directly strip a single weapon (or all) owned by yourself. You cannot drop a weapon owned by you.
![unknown](https://user-images.githubusercontent.com/82908498/182837962-12b146e8-3e16-45a3-9d4b-9e2b270cfebf.png)

**Comment by thegrb93** [comment]
I think this is the fault of the prop protection

**Comment by NullLikesNothing** [comment]
Falco's Prop Protection caused it.
![image](https://user-images.githubusercontent.com/82908498/183146681-694babf5-fec3-48d0-883f-8d83a208ea90.png)
Can't toolgun blacklisted entities
![image](https://user-images.githubusercontent.com/82908498/183146756-e06723be-0399-41be-850d-9774e05cdca2.png)

**Comment by thegrb93** [comment]
Is it fixed then?
