### ISSUE TITLE
Can't connect to some websockets

### ISSUE THREAD

**Issue by ANormalTwig** [thegrb93/StarfallEx#1374]
Example:
```lua
-- Doesn't connect
local ws = WebSocket("www.yourworldoftext.com/ws/", nil, true)
ws:connect()
```

Port should get inserted right after `.com` but I can't do that because its forced to be at the end
https://github.com/thegrb93/StarfallEx/blob/05c4aecd5347ecee8f86f9c7d11f9ac58551fbe6/lua/starfall/libs_cl/websocket.lua#L34

**Comment by thegrb93** [comment]
addr should be renamed to 'domain' and there should be a param added for the directory/extension

**Comment by thegrb93** [comment]
Or we should just allow the user to format it, and we just sanitize it.

**Comment by ANormalTwig** [comment]
Doesn't the `string.JavascriptSafe` pretty much prevent any way to do anything malicious already?

**Comment by thegrb93** [comment]
I don't think it protects completely against html injection, but it's only runnable on the owner of the chip anyway
