### ISSUE TITLE
Nextbot death callback argument names are misaligned

### ISSUE THREAD

**Issue by ReasonableScripts** [thegrb93/StarfallEx#1381]
In addDeathCallback the argument name assignments seem to be misaligned, so the argument for the nextbot entity that died actually represents the amount of damage sustained, and that also means that the argument for the damage type does not return anything other than nil, this also means that the argument for the nextbot that has died is inaccessible

**Comment by ReasonableScripts** [comment]
looking at the code myself it doesn't seem to have a problem but I'm not super familiar with Lua so I may have missed something

**Comment by adamnejm** [comment]
The Nextbot wasn't passed to the callbacks at all. Will be fixed after https://github.com/thegrb93/StarfallEx/pull/1382 gets merged.
