### ISSUE TITLE
Add more functions and hooks from GLua

### ISSUE THREAD

**Issue by Foresteam** [thegrb93/StarfallEx#1385]
## Clientside API
Set position, angles, material, remove for entities, etc.
There's a similar issue already, but mine is more global and I suggest not just to allow it for the owner, but for everyone, with existing HUD mechanisms, for example.
## Other
Player: SetAmmo, StripAmmo etc. Give, StripWeapon(s). GetRagdollEntity

It would also be nice if such hooks existed https://wiki.facepunch.com/gmod/GM:DoAnimationEvent

**Comment by thegrb93** [comment]
What clientside things would setPos/setAngle/remove be used for?

'Give' won't be possible because it bypasses admin only entities but you can use prop.createSent instead.

**Comment by Foresteam** [comment]
> What clientside things would setPos/setAngle/remove be used for?

Removing something that blocks my view or creates lags as a regular player, prop/holo blocks, for example. Namely, i was thinking of a more straightforward way to get my death ragdoll entity and animate it somehow since i'm not its owner, other than changing my pos/material right before the death to hide the original and spawning a brand new one.
* I wanted to play a sound with every swing of my crowbar, but there was no such events in SF. So KeyPress and timers became the solution
* I was using E2 previously, and found no giveWeapon function or similar which was confusing. I later came up with spawning a sent with its class, but it is a bit weird, imho
* I wanted to make my pistol a different weapon and remove its ammo to make two mouse buttons usable
> 'Give' won't be possible because it bypasses admin only entities but you can use prop.createSent instead.

Then it may be a good idea to create an alias, i guess.

I really like SF and the idea of using a self-depending language like Lua for writing chips, but it lacks API which makes a lot of struggle out of nowhere while the API is actually present in the game. I guess i could implement these on my own, if it would be accepted. So would it be?

**Comment by thegrb93** [comment]
> Removing something that blocks my view or creates lags as a regular player, prop/holo blocks, for example. Namely, i was thinking of a more straightforward way to get my death ragdoll entity and animate

Those functions won't work for that.

The weapon function, getDeathRagdoll, and Doanimation hook can probably be added though.
