### ISSUE TITLE
Odd lack of error message randomly appearing

### ISSUE THREAD

**Issue by KanaeXia** [thegrb93/StarfallEx#1386]
![image](https://user-images.githubusercontent.com/86935499/189199049-348a923f-2e85-414a-9840-16065cc6bb56.png)
![image](https://user-images.githubusercontent.com/86935499/189199069-eb7d86b0-d765-45c3-bd33-40a09e3d1e8e.png)

Somehow randomly, this two-line error will appear in console only, and error out the entire starfall chip.  To clarify, this hook is added clientside, and **Bed** is not removed before, during nor after this error occurs.

**Comment by thegrb93** [comment]
Does the error make the chip stop running for you or other players?

**Comment by KanaeXia** [comment]
Yes, the error completely stops the chip server side, client side, and for everyone.

**Comment by thegrb93** [comment]
Serverside? I thought you said the hook was clientside.

**Comment by KanaeXia** [comment]
Yeah.  But the error somehow stops the chip ENTIRELY.

**Comment by thegrb93** [comment]
@KanaeXia did pcall help you find the issue at all?

**Comment by thegrb93** [comment]
I think you've mentioned you play on metastruct, so I'm guessing their net library is modded and is the culprit.
