### ISSUE TITLE
[Feature Request] Client-Side printing for all players

### ISSUE THREAD

**Issue by SkylerMews** [thegrb93/StarfallEx#1393]
Allow StarFall chips to be able to print to a client's chat when said client accepts the required permission. 

This would allow users to provide information to clients without having to use a HUD or Screen.

It's a small feature, but I'd love to see it.

`setupPermissionRequest( { "print" }, "Allow chip to print messages into your chat.", true )`

or

`setupPermissionRequest( { "chat.print" }, "Allow chip to print messages into your chat.", true )`

**Comment by ANormalTwig** [comment]
if you're already asking for permissions why not just ask for `enablehud` and use `printHud()`?

**Comment by SkylerMews** [comment]
> 

Hmm, I guess that would make my feature a bit redundant? Although, it wouldn't require a HUD to be attached.

**Comment by thegrb93** [comment]
You can enableHud on players in vehicles that you own as well, assuming this is for a vehicle. Otherwise, yeah, the accept way to achieve this is requesting enableHud permission.
