### ISSUE TITLE
Constraint Entity

### ISSUE THREAD

**Issue by ProfessorBoxtrot** [thegrb93/StarfallEx#1394]
A type for constraint entities, returned by various constraint functions (constraint.weld, etc.)

Can have :break() called on it to break the constraint to allow for specific constraint deletion?

**Comment by thegrb93** [comment]
I think the main issue here is prop protections usually don't keep track of who owns constraints. Maybe we can make the constraint's remove function check the prop permission of all entities connected to it.

**Comment by thegrb93** [comment]
Should be easy to add
