### ISSUE TITLE
Severe lag spike on client / server using table.add with same table.

### ISSUE THREAD

**Issue by wrefgtzweve** [thegrb93/StarfallEx#1400]
Using the following code generates a large lagspike on both client and server.
```lua
local tbl = {1}
table.add(tbl,tbl)
```
![image](https://user-images.githubusercontent.com/69946827/199618799-292076c8-91fd-46e4-891f-2d8ecd9a91ff.png)

You can minge pretty hard with this and lag people out severely.

**Comment by thegrb93** [comment]
Can be done without table.Add too. You can decrease sf_timebuffersize or ban whoever's abusing it

**Comment by wrefgtzweve** [comment]
Shouldn't table.add check if the table is being added to itself? you should literally never do that anyways

**Comment by thegrb93** [comment]
Like I said though, you don't need table.add to do it.

**Comment by wrefgtzweve** [comment]
Adding a single line comparison doesn't hurt / prevents abuse with this specific one though, just because other methods exist doesn't mean this one shouldn't be fixed.

**Comment by ANormalTwig** [comment]
Should check any `while true do ... end` as well to make sure there's a break statement in it, might lag the game otherwise.
