### ISSUE TITLE
Strange client crash

### ISSUE THREAD

**Issue by wrefgtzweve** [thegrb93/StarfallEx#1403]
```lua
--@server
local entitys = find.inSphere (chip():getPos(),300)
for _,v in ipairs(entitys) do
    find.sortByClosest(v,chip():getPos())
end
```
Will crash the player that placed the chip

**Comment by ANormalTwig** [comment]
Doesn't seem to cause my game to crash, are you sure this is what caused your game crash?

**Comment by wrefgtzweve** [comment]
I condensed it a bit from the original,
```lua

local entitys = find.inSphere (chip():getPos(),300)
local distance = 50000 
local closestEntity
for _,v in ipairs(entitys) do
    find.sortByClosest(v,chip():getPos())
    print()
end
```
This is the initial code that crashed me, a friend of me keeps crashing whenever he runs it and i crashed when i ran it too

**Comment by ANormalTwig** [comment]
Doesn't cause my game to crash either.

**Comment by wrefgtzweve** [comment]
Make sure to put the `--@server` at the top of the second example, i seem to have forgotten that.
I just tried again (3rd time in a row) and crashed again:

First example code runs fine:
https://user-images.githubusercontent.com/69946827/200202431-ba7e3d5d-6667-4449-8303-bb8c751befe8.mp4

Second example crashes my game:
https://user-images.githubusercontent.com/69946827/200202393-ddeea5f0-c757-48c7-b277-7bbb21a565da.mp4

**Comment by wrefgtzweve** [comment]
I can't replicate it on another server, that server might run an older version though. It's really strange, ill look further.

**Comment by Vurv78** [comment]
Maybe they have some detour that's crashing you. Like how custom chatboxes detour chat.AddText

**Comment by wrefgtzweve** [comment]
Yup, it seems to be the custom chat. Only happens when it's ran with an empty print().
Funnily enough it cpu quotas on client but not on server

**Comment by wrefgtzweve** [comment]
For anyone wondering, <https://www.gmodstore.com/market/view/atlas-chat> is doing this.
