### ISSUE TITLE
Special cases in which client code does not start

### ISSUE THREAD

**Issue by Periapsises** [thegrb93/StarfallEx#1404]
In some instances, in my case with `error` and `throw`, the code gets executed only on the server side.

Here's the code I have tested with:
```lua
print( "Hello from Starfall " .. ( SERVER and "Server" or "Client" ) )
error( "Here's an error" ) -- Also tried with throw and got the same results
```
The code above runs only on server should `--@shared`, `--@server` be specified or not.
Only when using `--@client` will it run client side.

Commenting the error line fixes that problem, and it will then run both on server and client (When no realm is specified)

I've also experimented with `assert`, in which case the code gets executed on both sides if the check is successful, and only on server if it is not.
Running the code in a timer works fine.

I assume the client doesn't start as the chip overlay shows the client CPU as `None`

![image](https://user-images.githubusercontent.com/94928308/201530885-2404e01d-cd2e-4673-8f03-7015bbbf0745.png)

**Comment by thegrb93** [comment]
That's intended since an errored chip won't send the code to the client. Is there a reason this shouldn't happen?

**Comment by Periapsises** [comment]
If I understand right: If the server side code errors immediately, the client code isn't sent. Did I get that right?
Because I know if the server doesn't immediately error, you can still have the client work fine afterwards (Like still seeing the hud when the server errored without erroring the client)

What I thought would happen is that the client code was sent regardless of if the server code errors or not.

**Comment by thegrb93** [comment]
>If I understand right: If the server side code errors immediately, the client code isn't sent. Did I get that right?
Because I know if the server doesn't immediately error, you can still have the client work fine afterwards (Like still seeing the hud when the server errored without erroring the client)

Correct
