### ISSUE TITLE
Clientside lua error

### ISSUE THREAD

**Issue by wrefgtzweve** [thegrb93/StarfallEx#1405]
Not sure how to replicate this, i saw a player had this on the server so i thought i might as well report it.
My guess would be that the entity is no longer valid?
```
addons/starfallex/lua/starfall/libs_cl/light.lua:54: attempt to call method 'EntIndex' (a nil value)
  1. fn - addons/starfallex/lua/starfall/libs_cl/light.lua:54
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:109
```
https://github.com/thegrb93/StarfallEx/blob/26614040366e236dcd5a2450bb1ab64f572e0b1b/lua/starfall/libs_cl/light.lua#L54

**Comment by thegrb93** [comment]
I'm guessing a 3rd party addon called this hook with an invalid entity.
