### ISSUE TITLE
Parented clientside holos reset their position and angle offsets when the parent moves if it's also clientside

### ISSUE THREAD

**Issue by legokidlogan** [thegrb93/StarfallEx#1407]
On the client, if you create a starfall hologram, parent it to another client holo, and then move the parent, the child holo will move to the parent's origin, instead of maintaining its offset. It will also reset the angles.

- This also happens if, instead of using `:setPos()`/`:setAng()`, the parent holo is afterwards parented to some other entity.
- If client holos are parented to a server entity, `:setPos()`/`:setAng()`'ing the server ent will not cause the issue.
- If a client holo is parented to a server entity, then additional client holos are afterwards parented to the first holo, the issue doesn't occur at all.

Here's a simple script for testing:

```lua
--@client

local mdl = "models/hunter/blocks/cube025x025x025.mdl"
local mat = "models/debug/debugwhite"
local ang = Angle( 0, 0, 0 )
local childCount = 10


local hBase = hologram.create( chip():localToWorld( Vector( 0, 0, 50 ) ), ang, mdl )
hBase:setColor( Color( 255, 255, 0, 100 ) )
hBase:setMaterial( mat )
hBase:setSize( Vector( 5 ) )


--hBase:setParent( chip() )

for i = 1, childCount do
    local frac = ( i - 1 ) / ( childCount - 1 )
    local pos = hBase:localToWorld( Vector( 0, ( frac * 2 - 1 ) * 20, 10 ) )

    local holo = hologram.create( pos, ang, mdl )
    holo:setMaterial( mat )
    holo:setParent( hBase )
    holo:setSize( Vector( 20 / childCount ) )
end

timer.simple( 2, function()
    hBase:setPos( chip():localToWorld( Vector( 100, 0, 50 ) ) )
end )

--hBase:setParent( chip() )
```

**Comment by thegrb93** [comment]
May be a glua bug but I'll have to test it tonight and see

**Comment by ZH-Hristov** [comment]
We should probably have SetLocalPos() and SetLocalAngles() for parented holos in SF.

**Comment by thegrb93** [comment]
Would those resolve the issue? Might be worth adding.

**Comment by ZH-Hristov** [comment]
I have those in a custom lib and the local pos and angles don't seem to reset when moving.

I've only parented holos to the player with it, I don't know if the behaviour would be different with anything else.

**Comment by thegrb93** [comment]
@ZH-Hristov SetLocalPos and SetLocalAngles seems to just do just put the children at the parent's origin, same behavior as moving the parent. Must be a source bug.

I tried setting it here:
![image](https://github.com/thegrb93/StarfallEx/assets/6713261/a49f2d99-0b04-4802-b1ae-3d4b16885ad3)

**Comment by ZH-Hristov** [comment]
weird asf, could've sworn it worked
