### ISSUE TITLE
SF table outputted through wire does not work in E2

### ISSUE THREAD

**Issue by juke-cappatalist** [thegrb93/StarfallEx#1409]
If a table is outputted through the wire output to the E2, the E2 will not be able to address the table keys. Some functions do work though

**Comment by CheezusChrust** [comment]
Adding on to this, the "Array" type output simply doesn't work at all - when given any type of numerically indexed table it will complain that it contains invalid types.

**Comment by thegrb93** [comment]
I think the E2 update that made vectors glua vectors might be the reason
