### ISSUE TITLE
"PlayerNoClip" hook called everytime on client side

### ISSUE THREAD

**Issue by itisluiz** [thegrb93/StarfallEx#1411]
"PlayerNoClip" hook will get called everytime a noclipped player moves when running on client side. Appears to work as normal on server side.

```lua
--@name Noclip test
--@author
--@client

hook.add("PlayerNoClip", "onnoclip_test", function(ply, enabled)
    print(ply:getName(), enabled)
end)
```
Chat output
![image](https://user-images.githubusercontent.com/46863600/210282939-8d96d19f-31f7-41db-9023-22137fbda0fc.png)

**Comment by Vurv78** [comment]
It's a predicted hook, this is expected behavior

**Comment by thegrb93** [comment]
the isFirstTimePredicted function may help, otherwise, yeah its a source engine thing
