### ISSUE TITLE
Directives are being parsed even if they are in a string

### ISSUE THREAD

**Issue by Manonox** [thegrb93/StarfallEx#1418]
Made a dynamic require system library that can require things just like normal lua.

Tried to change the error message to mention how many paths it checked, and... yeah...
```lua
error("Can't find file '" .. rawpath .. "'. (" .. #paths .. " paths checked) (did you forget to --@include it?)")
```

Throws: `Bad include: it?") end`

P.S.:
I'll work around it with this for now
```lua
error("Can't find file '" .. rawpath .. "'. (" .. #paths .. " paths checked) (did you forget to --@".."include it?)")
```

**Comment by Manonox** [comment]
I think this can mess with your creation, if you do `"Blah, blah, ... @server ... blah, blah"` or `"Blah, blah, ... @client ... blah, blah"`
Which is... not ideal

**Comment by thegrb93** [comment]
The problem is, fixing it would slow down preproc parsing significantly since lua's regex lib is cursed.

**Comment by thegrb93** [comment]
I have a hacky idea that would maybe work

**Comment by Manonox** [comment]
> @thegrb93: I have a hacky idea that would maybe work

What's the idea?
Results, if any?

**Comment by thegrb93** [comment]
Nevermind, it's not worth it. Just do your string concat thing as a work-around. This is kind of a non-issue.
Especially since limiting it to per line would ruin stuff like
```lua
local myLib = require("myLib.txt") --@include myLib.txt
```
