### ISSUE TITLE
Custom props use RENDERGROUP_BOTH render group causing props to be rendered above other entities and effects.

### ISSUE THREAD

**Issue by UnrealEugene** [thegrb93/StarfallEx#1420]
I'm trying to create maps from custom props and ran into a problem, that some of created custom props are rendered above other close entities and effects (i.e. E2 holograms, explosion effects and even physgun beams). 

<img src="https://user-images.githubusercontent.com/55035123/214115852-710f8a34-5394-4381-b6fc-a5f3df524781.png" width="368">

As I understand, the problem lies in `RenderGroup` of `starfall_prop` which is set to `RENDERGROUP_BOTH`:
https://github.com/thegrb93/StarfallEx/blob/cb2bfe4daae2f9a2c19803161242f9c7cf5da6e4/lua/entities/starfall_prop/cl_init.lua#L2

 After changing it to `RENDERGROUP_OPAQUE` the problem seems to disappear.

Is there any reason to set render group of custom props to be `RENDERGROUP_BOTH`?

**Comment by thegrb93** [comment]
All the entities do apparently. It used to be required for the color-tool transparency to work, but maybe that's been fixed. You can try removing it and see if transparency works or not.

**Comment by adamnejm** [comment]
https://github.com/thegrb93/StarfallEx/blob/792eba8e939b7d605f121e1ac0e2a7006feb4130/lua/starfall/libs_sh/entities.lua#L394

**Comment by UnrealEugene** [comment]
> https://github.com/thegrb93/StarfallEx/blob/792eba8e939b7d605f121e1ac0e2a7006feb4130/lua/starfall/libs_sh/entities.lua#L394

Yeah, this should work, but after a bit of experimentation I found that holograms with custom mesh setted via `Entity:setMesh` also have this issue. It seems RenderMode is ignored as if it was set to normal when custom mesh is used.

**Comment by thegrb93** [comment]
Fixed by https://github.com/thegrb93/StarfallEx/pull/1422
