### ISSUE TITLE
screen rendering is clipping 

### ISSUE THREAD

**Issue by abirduphigh** [thegrb93/StarfallEx#1424]
I'm not sure if this is directly related to Starfall or perhaps it's my client setup, but this strange behavior started occurring seemingly out of the blue.

**_The issue:_**
When looking at a screen (while a processor renders objects on it), I see planar clipping that changes depending on what my relative angle and position is. It's hard to explain so I uploaded a short video clip of the experience: [https://imgur.com/a/VGDVu38](https://imgur.com/a/VGDVu38)

**_Did not solve the issue:_**
- Using a different screen model
- Adjusting video settings
- Changing game map
- Full game and system restart

For what it's worth, it doesn't happen with wire screens or egps with the same model.

Any ideas?

**Comment by thegrb93** [comment]
make sure you're clearing depth? hard to tell without code

**Comment by abirduphigh** [comment]
Yes my apologies, the code would have been very helpful. And because you mentioned it, I revisited my code and found the culprit! I was using `render.draw3DBox(Vector origin, Angle angle, Vector mins, Vector maxs)` and when the Z component of the Vector min is less than 0, it clips the object as I move closer to the screen. (Doesn't seem to effect the wireframe box). This is probably normal behavior but I was never aware of it until now.

```
--@client

Pos = Vector( 256, 256, 0 )
Ang = Angle()
Size = Vector( 512, 512, 800 )
Z = 0 -- If this is less than 0, the 3d box (excluding the wireframe box) will clip when I move close to the screen

hook.add( "render", "", function()

    render.setColor( Color( 255, 255, 255 ))
    render.draw3DBox( Pos, Ang, -Size * Vector( 0.5, 0.5, Z ), Size * Vector( 0.5, 0.5, 1 ))
    render.setColor( Color( 255, 0, 0 ))
    render.draw3DWireframeBox( Pos, Ang, -Size * Vector( 0.5, 0.5, Z ), Size * Vector( 0.5, 0.5, 1 ))
    
end )
```

**Comment by thegrb93** [comment]
Yeah, odd. Not sure why

**Comment by abirduphigh** [comment]
No worries. Thanks for helping me address it. Closing this issue.
