### ISSUE TITLE
Example Bumpmap Sphere (mesh_bumpmap.lua) throws an error.

### ISSUE THREAD

**Issue by UnrealEugene** [thegrb93/StarfallEx#1425]
https://github.com/thegrb93/StarfallEx/blob/2ef918e595f20986f0def5a072efefdfc52508b9/lua/starfall/examples/mesh_bumpmap.lua#L53

It seems that .obj file ([https://dl.dropboxusercontent.com/s/vdcb9ujr7qslg51/sphere.obj](https://dl.dropboxusercontent.com/s/vdcb9ujr7qslg51/sphere.obj)) doesn't exist anymore. It throws 404 on an attempt to download it.

**Comment by Damianu** [comment]
Maybe we should create a directory on gh-pages branch for hosting assets from examples?

**Comment by thegrb93** [comment]
Yeah, that's a good idea. Will implement soon

**Comment by thegrb93** [comment]
I had to make a new sphere model since I didn't have that other one anymore. Hopefully it works
