### ISSUE TITLE
hooks bypass detoured functions

### ISSUE THREAD

**Issue by Extra-Mental** [thegrb93/StarfallEx#1427]
detoured functions inside hook.add get un-detoured if you revert the function back and call the hook

Code:
```
local oldPrint = print

function print(...)
   oldPrint("[Detoured print] ", ...) 
end

hook.add("custom hook", "test", function() print("hook print") end)
hook.run("custom hook")

print = oldPrint

hook.run("custom hook")
```

Result:
```
[Detoured print] 	hook print
hook print
```

**Comment by Extra-Mental** [comment]
Actually looking more into this it may be normal functionality but im not positive, close this if so

**Comment by Vurv78** [comment]
You're using a global scope for the function inside of the hook, so when you switch said global it uses the switched one since that's the new value at the `print` global. It doesn't 'undetour' them

If you do `local function print(...)` instead it would likely work as you expect, although you could also just use `setfenv` to do custom stuff with print only in that hook.

**Comment by thegrb93** [comment]
@Extra-Mental what behavior is it you're looking for? The current result is correct lua behavior.

**Comment by thegrb93** [comment]
If you want it to stay detoured, you should use `local print = print` so that the hook uses your local instead of the global that gets reverted.

**Comment by Extra-Mental** [comment]
@thegrb93 

I was expecting the hook function to stay using the detoured print and print the same lines twice.

> If you want it to stay detoured, you should use `local print = print` so that the hook uses your local instead of the global that gets reverted.

Would this still work if i move the hook.add() to a separate file and replaced its line with require(saidfile)?

**Comment by thegrb93** [comment]
> local oldPrint = print
> 
> function print(...)
>    oldPrint("[Detoured print] ", ...) 
> end
> 
> hook.add("custom hook", "test", function() print("hook print") end)
> hook.run("custom hook")
> 
> print = oldPrint
> 
> hook.run("custom hook")

```lua
local oldPrint = print
function print(...)
   oldPrint("[Detoured print] ", ...) 
end

do
    local print = print
    hook.add("custom hook", "test", function() print("hook print") end)
    hook.run("custom hook")
end

print = oldPrint

hook.run("custom hook")
```

**Comment by thegrb93** [comment]
Closing since it's more of a lua question but feel free to ask more here if you're still stuck.

Part 1 and 2 of this can also provide a bit of info on the topic. https://github.com/thegrb93/StarfallEx/wiki/Lua-Starfall-Crash-Course
