### ISSUE TITLE
Compatibility issue with other mods

### ISSUE THREAD

**Issue by scottycool64** [thegrb93/StarfallEx#1432]
This mod, i believe changes the default syntax for functions to camel case, in my specific situation, im getting errors that the function SetOwner is a nil value. Error provided.
[JMod] lua/entities/ent_jack_gmod_eztoolbox.lua:25: attempt to call field 'SetOwner' (a nil value)
  1. SpawnFunction - lua/entities/ent_jack_gmod_eztoolbox.lua:25
   2. Spawn_SENT - gamemodes/sandbox/gamemode/commands.lua:761
    3. unknown - gamemodes/sandbox/gamemode/commands.lua:840
     4. unknown - lua/includes/modules/concommand.lua:54 #

**Comment by scottycool64** [comment]
Sorry, false closing

**Comment by ANormalTwig** [comment]
I don't see how this is an issue with StarfallEx.

**Comment by thegrb93** [comment]
Going to close since I'm not sure why you reopened
