### ISSUE TITLE
Add "Are you sure you want to overwrite this file?"

### ISSUE THREAD

**Issue by Damianu** [thegrb93/StarfallEx#1433]
We should add "Are you sure you want to overwrite this file?" popup when using "Save as"(Or saving for first time) when provided name already exists.

**Comment by thegrb93** [comment]
I think someone already added this

**Comment by thegrb93** [comment]
Maybe not. I think it can be added here https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/editor/sfframe.lua#L1642
