### ISSUE TITLE
BurstObject 'mesh_triangles' doesn't refill properly

### ISSUE THREAD

**Issue by adamnejm** [thegrb93/StarfallEx#1438]
[This value](https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/sflib.lua#L153) constantly decrements when using `Mesh.draw` and fails to refill in time for the next frame *(testing with 15533 tri mesh)*.  
Repro: [Renamon example](https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/examples/mesh_3d.lua) *(either HUD or screen modes)*

**Comment by thegrb93** [comment]
Your burst rate is set too low I guess?

**Comment by adamnejm** [comment]
That's the thing, you can set the `sf_mesh_triangles_burstmax` to whatever value, but it will eventually crash anyway, because the BurstObject refills slower than once per frame.

**Comment by ANormalTwig** [comment]
Should probably make it refill based on how many frames pass instead of time since you could have a really good PC that renders stuff very quickly making the burst drain regardless of performance.

**Comment by adamnejm** [comment]
Yeah, I had my `fps_max` set to 300. It's fine below `196` on my setup.

**Comment by thegrb93** [comment]
I see, so higher framerate consumes them faster. So the refill needs to scale inversely with frametime. That part of the BurstObject code can be moved to a 'refill' function. Then the triangle burstobjects can easily override the refill method with that.
