### ISSUE TITLE
Sound:setSoundLevel is non functional

### ISSUE THREAD

**Issue by Nwhis** [thegrb93/StarfallEx#1442]
Not sure if this is a starfall thing or a glua thing, but this function doesn't seem to actually change the sound level of a sound object, instead leaving it at the default of 75. Interestingly enough, getSoundLevel will return the correct number after attempting to set it, despite the audio not reflecting that.
Code to replicate:
`--@server`
`local snd = sound.create(chip(),"physics/plastic/plastic_box_scrape_smooth_loop2.wav")`
`snd:play()`
`snd:setSoundLevel(40)`
`print(snd:getSoundLevel())`

This will print 40 despite the audible sound level not actually changing (it should be very quiet)
Entity:emitSound's soundlevel input functions properly, however (you can use this to compare what it should sound like)

It's possible the original function is just straight up broken in glua, but I talked to someone in the gmod discord that said it works fine for them so I'm not really sure.

**Comment by thegrb93** [comment]
Try setting it before playing. I recall a source engine/glua bug where playing it first makes it not work. Not sure though.

**Comment by thegrb93** [comment]
I might be able to test it out. I think its worked for me before.

**Comment by Nwhis** [comment]
Well ain't that gooby. Docs state `Won't work unless the sound is playing.` so I had assumed as such. Guess that needs to be flipped around.

**Comment by Nwhis** [comment]
Confirmed this works as intended, just have to run it before playing the sound rather than after
