### ISSUE TITLE
mousemoved Hook doesn't work when cursor is enabled

### ISSUE THREAD

**Issue by Extra-Mental** [thegrb93/StarfallEx#1450]
The mousemoved hook only runs when you are aiming and doesnt get called when in any derma menu or input.enableCursor(true) is used

**Comment by thegrb93** [comment]
Maybe https://github.com/thegrb93/StarfallEx/pull/1449 could fix this too

**Comment by thegrb93** [comment]
Doesn't look like it. Just check if the x/y has changed since the previous frame in order to determine if the mouse has moved.
