### ISSUE TITLE
StringStream has no writeUInt8/writeUInt16/writeUInt32 methods

### ISSUE THREAD

**Issue by Manonox** [thegrb93/StarfallEx#1451]
It has readUInt8, readUInt16, readUInt32, but no reads..?
*(Maybe I am stupid or something?)*
![image](https://user-images.githubusercontent.com/23390269/227310865-b22a29bf-2e6e-4d34-86f0-b9c9331625d4.png)

**Comment by thegrb93** [comment]
The writeInt functions work for Uints.

**Comment by thegrb93** [comment]
The net functions use bits, not bytes. The stringstream isn't designed for manipulating bits, only bytes, so wouldn't be able to do that.

Could probably add alias functions for those.
