### ISSUE TITLE
Raise limits for mesh.generate

### ISSUE THREAD

**Issue by Manonox** [thegrb93/StarfallEx#1452]
`mesh.createFromTable` lags like hell and is much slower than doing it by hand with `mesh.generate`
https://github.com/thegrb93/StarfallEx/blob/e02b98793ec4447b9b63527318d1f22201f5c9bf/lua/starfall/libs_sh/mesh.lua#L1024
This line is strange to me, because we calculate the tri count a tiny bit later, why don't just check it there?
Or make it into a serverside ConVar, so we can remove this restriction if we really need it for something (in my case - some benchmarks for minecraft chunks)

**Comment by thegrb93** [comment]
There was a certain amount that is too high and crashes the game. https://github.com/thegrb93/StarfallEx/commit/73e99f021f3959f54e68930d196496f8f111334b

Dunno what the crash amount was though. If you can show it works fine with certain primitive types, maybe we can unrestrict it.

**Comment by Manonox** [comment]
Haven't tested anything, but as I understand it, gmod can't handle more than 65536 **vertices**, not primitives
```lua
lidar.points = lidar.points or {}
lidar.pointlimit = 4096

lidar.meshes = lidar.meshes or {}
lidar.meshlimit = 256
```
This config piece was taken from my lidar addon, it only allows 4096 points (quads). Which consist of 2 triangles with 3 vertices each, so the total maximum vertex count is 4096 * 2 * 3 = 24576
During creation, when I was testing different pointlimits, gmod crashed around 10900+ quads. Math checks out, kind of
Don't take my word for it though, I will do some more testing later (when I feel like it)
