### ISSUE TITLE
'require' doesn't support returning multiple values, while 'dofile' does

### ISSUE THREAD

**Issue by UnrealEugene** [thegrb93/StarfallEx#1453]
Example:
```
-- b.txt
return 1, 2, 3
```
```
-- a.txt
print(require("b.txt")) --@include b.txt
```
Running `a.txt` prints `1` in the chat. But if you change `require` to `dofile`:
```
-- a.txt
print(dofile("b.txt")) --@include b.txt
```
It prints `123` in the chat.

I believe this is not intended and `require` should support returning multiple values like `dofile` already does. 

The following line causes this behaviour:
https://github.com/thegrb93/StarfallEx/blob/3fe27da6649d00358c0df89d2a0cfc2fa45f49c3/lua/starfall/instance.lua#L687
Only the first returned value is saved while others are ignored.

Also the same issue applies to `dodir` and `requiredir` functions where tuples of return values are put in a table, causing loss of other return values. Though I don't know how to fix this issue for `dodir` and `requiredir` functions without breaking backwards compatibility.

**Comment by adamnejm** [comment]
That's standard Lua behavior tho.
```sh
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> print(dofile("/home/name/projects/lua/test/include.lua"))
1	2	3
> print(require("include"))
1
```
```sh
LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2022 Mike Pall. https://luajit.org/
JIT: ON SSE3 SSE4.1 BMI2 fold cse dce fwd dse narrow loop abc sink fuse
> print(dofile("/home/name/projects/lua/test/include.lua"))
1	2	3
> print(require("include"))
1
```

**Comment by adamnejm** [comment]
Not a big deal IMO. If you want multiple returns with `require`, just do:
```lua
-- include.lua
return { 1, 2, 3 }
```
and then
```lua
-- main.lua
local a, b, c = unpack(require("include"))
```

**Comment by thegrb93** [comment]
The reason is 'require' caches the result of its call so that requiring a file more than once will return then cached result on subsequent calls. This caching only caches a single value (which you can choose to give it a table of things if you want).
