### ISSUE TITLE
URL Whitelist Outdated

### ISSUE THREAD

**Issue by MonkaSC** [thegrb93/StarfallEx#1454]
The URL whitelist is outdated and is missing a bunch of good pomf-style file hosting services, like [catbox](https://catbox.moe), [uguu](https://uguu.se), [slob.fans](https://slob.fans), and [0x0](https://0x0.st) just to name a few. I know Teknik is on the whitelist but it's been shut down. [Hastebin](https://www.toptal.com/developers/hastebin) is under new ownership. Why e621 is whitelisted, I have no fucking clue. What legitimate purpose would this have in game? (showing furry dicks to minors is not a legitimate purpose.)
I understand the purpose behind the URL whitelist, but nobody uses half of the weird github/pastebin variations on there, and this system as a whole could be better implemented, like maybe doing HTTP requests server-side and serving it to the client. Please just at least update the whitelist, and, (jfc), please remove e621 from it.

**Comment by ANormalTwig** [comment]
Yes waiting for the server to request something that could be very large and sending that back in a net message would be very fast, good idea.

**Comment by MonkaSC** [comment]
Sorry if that's a dumb idea, I don't know much about gmod codings, but just at least consider changing the whitelist please.

**Comment by ANormalTwig** [comment]
If you want additions to the whitelist then provide a list of URLs you want added.

**Comment by Vurv78** [comment]
Pretty sure the logic is that you can just upload whatever porn/gore/awful thing on any other file host like discord so there's no point trying to "moderate" and not allow nsfw sites like e621.

**Comment by MonkaSC** [comment]
> Pretty sure the logic is that you can just upload whatever porn/gore/awful thing on any other file host like discord so there's no point trying to "moderate" and not allow nsfw sites like e621 to be whitelisted.

ok so you might as well whitelist every other degenerate porn site, right? its only purpose is porn, sure you can upload awful shit with other services but it's literally only for porn, it has no reason to be there.


> If you want additions to the whitelist then provide a list of URLs you want added.

the ones I provided in the post are the only ones me and my friends use, and I trust being in the whitelist. They've been running for a while and I don't see any signs of them going down any time soon.

**Comment by x4fx77x4f** [comment]
e621 isn't "literally only for porn". It's a furry art booru that allows adult content, similar to how some of the sites you've mentioned are file hosts that allow adult content.
Whether or not adult sites should be in the whitelist is something I'm undecided on, but remember that players can display whatever they like with a StarfallEx chip with *or without* HTTP.

**Comment by solum420** [comment]
> e621 isn't "literally only for porn". It's a furry art booru that allows adult content, similar to how some of the sites you've mentioned are file hosts that allow adult content.

ok and I could argue that there are minecraft let's plays uploaded to pornhub, so it should be whitelisted too, right? the stretch you are making here to validate e621 being whitelisted is both hilarious and sad.

**Comment by Xandertron** [comment]
sir you forgot to read the rest of the discussion

**Comment by ANormalTwig** [comment]
It doesn't really matter what URLs are whitelisted just as long as you can't grab someone's IP address in 1 easy step with an http request.

> ok and I could argue that there are minecraft let's plays uploaded to pornhub, so it should be whitelisted too, right?

PornHUB is entirely dedicated to porn evidenced by the description of the site and the type of ads ran on it. e621 advertises itself as a mature image board for furry artwork. Although the primary content on e621 is porn it's not it's dedicated purpose. Not trying to defend it staying, but your argument is baseless.

**Comment by safariragoli2** [comment]
Why is e621 whitelisted in the first place? Who is trying to see anything related to furry content? Seems to me that the owner is actually just a rеtard.

**Comment by ANormalTwig** [comment]
If you don't have any contribution to the issue don't comment, your insult isn't necessary.

**Comment by solum420** [comment]
> It doesn't really matter what URLs are whitelisted just as long as you can't grab someone's IP address in 1 easy step with an http request.
> 
> > ok and I could argue that there are minecraft let's plays uploaded to pornhub, so it should be whitelisted too, right?
> 
> PornHUB is entirely dedicated to porn evidenced by the description of the site and the type of ads ran on it. e621 advertises itself as a mature image board for furry artwork. Although the primary content on e621 is porn it's not it's dedicated purpose. Not trying to defend it staying, but your argument is baseless.

ok, pornhub is a video uploading site that allows adult content. sure adult content is it's primary purpose but not its dedicated purpose. do you realize how rediculous you sound defending this?

**Comment by thegrb93** [comment]
Any site that isn't malicious can be whitelisted. What's considered malicious is just ip-sniffing (as far as I know).

**Comment by solum420** [comment]
> Pornhubs dedicated purpose is in fact hosting porn videos...

if it was exclusively for uploading porn then all other content would be banned. but, since it's a video host which also allows adult content to be uploaded, (by your own logic) it should be whitelisted.

**Comment by ANormalTwig** [comment]
🧱

**Comment by solum420** [comment]
> 🧱

something about a pot calling the kettle black 🤷‍♂️

**Comment by solum420** [comment]
> ![Screenshot_20230405-160820_Firefox_1](https://user-images.githubusercontent.com/78218557/230197902-a637c223-41ff-455b-ba71-d9ffeebc7de5.png)
> 
> From PornHUB's TOS, it is not intended for any other purpose.

obviously it's not heavily enforced. I can find as much minecraft on pornhub as I can find sfw posts in e621

**Comment by ANormalTwig** [comment]
Hell naw I ain't arguing on GitHub ever again I'm just calling the opponent stupid next time this shit is like convincing a brick wall to turn to move out of the way.

**Comment by solum420** [comment]
> Hell naw I ain't arguing on GitHub ever again I'm just calling the opponent stupid next time this shit is like convincing a brick wall to move out of the way.

i was making the same point as you, which is ironic and very telling of the lengths you freaks will go to validate yourselves. nsfw shouldn't be supported for any addons or mods used in a game where the minimum age requirement is 13.

**Comment by thegrb93** [comment]
Either make a PR for whitelist changes you want or be quiet. Nobody's going to edit it for you.

**Comment by thegrb93** [comment]
And don't try to remove porn sites from it because those are not malicious and there are some uses for them.

**Comment by solum420** [comment]
> Im sorry you feel that way
> 

And i'm sorry you feel the need to defend posting nsfw furry porn in a video game (where the minimum age requirement is 13). That must be really embarrassing for you.

**Comment by thegrb93** [comment]
You can find even worse shit in imgur or dropbox. The point of the whitelist isn't to moderate content.

**Comment by ANormalTwig** [comment]
> > Im sorry you feel that way
> 
> And i'm sorry you feel the need to defend posting nsfw furry porn in a video game (where the minimum age requirement is 13). That must be really embarrassing for you.

I've said twice now that I don't support. Try reading the argument I made instead of attacking my character.

**Comment by MonkaSC** [comment]
I think solum has a gr8 point but we can agree to disagree, please just consider adding the said file hosts.

**Comment by x4fx77x4f** [comment]
I've had a reply typed up for hours but didn't want to send since I didn't want to bump, but since someone else did it first...
A comment in the whitelist file indicates whitelisted domains must "be trusted and have considerable userbase", and to not add "your own domains". All of the "pomf-style" sites mentioned in the OP seem rather obscure to me. I don't think we should be adding every random file host that exists, only reputable ones.
slob.fans in particular is set as the organization and homepage on safariragoli2's GitHub profile, who has participated in this thread. As such, that site in particular at least should *definitely not* be added to the whitelist.

**Comment by MonkaSC** [comment]
im not reading that

**Comment by MonkaSC** [comment]
slob.fans is a new file sharing site hosted by my friend, it's just us that use it so i understand. but all the other ones most definitely have a considerable user base.

**Comment by thegrb93** [comment]
>slob.fans in particular is set as the organization and homepage on safariragoli2's GitHub profile, who has participated in this thread. As such, that site in particular at least should definitely not be added to the whitelist

Good call
