### ISSUE TITLE
Can't print tables wrapped with struct wrapper

### ISSUE THREAD

**Issue by CheezusChrust** [thegrb93/StarfallEx#1462]
Test is with the following code.
```lua
--@server

chip():setFrozen(false)

timer.simple(1, function()
    printTable(chip():getPhysicsObject():getFrictionSnapshot())
end)
```

When ran in lua on an unfrozen prop sitting on the ground:
![image](https://github.com/thegrb93/StarfallEx/assets/21130637/402bcba4-cc0f-4415-b701-8da6e1cc808b)

When ran in SF on the same prop:
![image](https://github.com/thegrb93/StarfallEx/assets/21130637/5c29a4ce-5592-4341-8581-431cb030bdb9)

**Comment by ANormalTwig** [comment]
It uses a struct wrapper, pretty sure you have to index the table returned for the value to get wrapped.

**Comment by Vurv78** [comment]
This is asked so often that printTable should prob have an override for structwrappers

**Comment by ANormalTwig** [comment]
It's not new afaik other stuff like the result of the trace functions use it too.

**Comment by thegrb93** [comment]
> __tostring is already used for the struct name

We could make a __printtable then.

**Comment by thegrb93** [comment]
Jit would be unhappy with that
