### ISSUE TITLE
[Question] Incorrect Mesh UVs?

### ISSUE THREAD

**Issue by nokillnando** [thegrb93/StarfallEx#1466]
Im trying to use the in-game 3d mesh example (Renamon one) of which it loads perfectly fine, but as soon as I try to use a custom model the UVs get all wierd, while the mesh loads fine. It loads fine everywhere else though.
Is there something im missing?

![image](https://github.com/thegrb93/StarfallEx/assets/16519919/7b9dfbda-1d52-48b8-8e2b-e0bb873db14c)
how it should look
![image](https://github.com/thegrb93/StarfallEx/assets/16519919/33c7a35c-c48f-40d0-a997-b809416c91ce)
how it ends up looking

**Comment by adamnejm** [comment]
The model needs to be triangulated and the texture probably needs to be 1024x1024.

**Comment by thegrb93** [comment]
Unless you make your texture a vtf and load it using material.load.

**Comment by nokillnando** [comment]
The model was already triangulated, didnt think the texture required to be 1024, which it did fix. shouldnt it load correctly independent of texture size though, since it uses uv and all?

**Comment by adamnejm** [comment]
UVs are *[0..1]*. AFAIK GMod / Source 1 always interpolates texture UVs to *[0..1024]*.

**Comment by ANormalTwig** [comment]
I'm pretty sure its just because URL materials use rendertargets internally and SF forces them all to be 1024 x 1024

**Comment by adamnejm** [comment]
Oh yeah, that could be it! Never mind me then...

**Comment by nokillnando** [comment]
That could explain such behaviour then. looks like I will have to take care about that in the future then.
