### ISSUE TITLE
Realm check for include is incorrect

### ISSUE THREAD

**Issue by legokidlogan** [thegrb93/StarfallEx#1473]
When a shared chip tries to include a server-only or client-only chip, it considers it a bad include, which is incorrect and not how include behaved in the past.

Caused by https://github.com/thegrb93/StarfallEx/pull/1471

**Comment by thegrb93** [comment]
Need to also check `

**Comment by thegrb93** [comment]
Probably would also be good if the realm checks were done in editor.lua. So the errors are caught before uploading to the server.

**Comment by Superlamaface** [comment]
I agree the errors being in the editor would definitely help.
