### ISSUE TITLE
Convert UInt16 to UInt13 for latest gmod update

### ISSUE THREAD

**Issue by Vurv78** [thegrb93/StarfallEx#1479]
Making this in advance, feel like this change is gonna break something

https://github.com/Facepunch/garrysmod/commit/00286d4c97c53b809b720f6fa3a0dcc8ac9870e5

**Comment by thegrb93** [comment]
You'd only see breaks if you're mixing readUInt/writeUint with readEntity/writeEntity

**Comment by Vurv78** [comment]
Might've made this prematurely but I did remember seeing code depending on uint16 for the id.
Either way could use this as an issue to clean up that code to use uint13's instead
