### ISSUE TITLE
Make "ChatTextChanged" hook use its own permission

### ISSUE THREAD

**Issue by legokidlogan** [thegrb93/StarfallEx#1480]
Currently, the `ChatTextChanged` hook uses the broad `input` permission.
`input` by itself covers mostly-tame things such as `input.getCursorPos()`, while `ChatTextChanged` is much more nefarious in that it can be used to read `asay` and `psay` for servers that use ULX.

Instead, I'd recommend making `ChatTextChanged` use its own sub-permission, like there is with `input.bindings` and `input.emulate`

**Comment by thegrb93** [comment]
Added https://github.com/thegrb93/StarfallEx/commit/a29dacae2cf9a8c08075916c5da5e25491b8385f
However, isKeyDown can still be used like a keylogger. Probably need to disable it if the permission isn't satisfied and the chat window is open.

**Comment by thegrb93** [comment]
There doesn't seem to be a gmod function for checking if the chat window is open.

**Comment by legokidlogan** [comment]
There's [StartChat](https://wiki.facepunch.com/gmod/GM:StartChat) and [FinishChat](https://wiki.facepunch.com/gmod/GM:FinishChat) hooks.
