### ISSUE TITLE
Incorrect error conditions with invalid material tool settings

### ISSUE THREAD

**Issue by possiblynova** [thegrb93/StarfallEx#1481]
i have literally no clue why this bug happens, its a stupid interaction with the material tool, an invalid material_override, and setAngVel.

i havent tested it without FPP yet

# reproduction

if your `material_override` is invalid ([according to FPP](https://github.com/FPtje/Falcos-Prop-protection/blob/master/lua/fpp/server/core.lua#L385-L417), which many servers use), your chip's serverside tries to `setAngVel` on its own hologram, and you pull out your material tool

```lua
--@server

-- set an invalid material_override after placing and then select the material tool
-- regardless it's a strange bug
-- ex:
-- material_override invalid*

local holo = holograms.create(chip():getPos(), chip():getAngles(), 'models/hunter/plates/plate.mdl')

hook.add('think', '', function()
    holo:setAngVel(Angle(0, math.sin(timer.systime()) * 45, 0))
end)
```

# actual behavior

```
Hook 'think' errored with: SF:bug.txt:12: Permission hologram.setRenderProperty: You can't toolgun this entity
stack traceback:
	SF:bug.txt:12: in function <SF:bug.txt:11>
```

# expected behavior

not that?

**Comment by ANormalTwig** [comment]
This sounds like an error with FPP.

**Comment by possiblynova** [comment]
moving to fpp
