### ISSUE TITLE
Allow concmd() on other players via permission system

### ISSUE THREAD

**Issue by legokidlogan** [thegrb93/StarfallEx#1482]
Revert d2fef08, as the permission library is more than sufficient at handling concmd.

If it's too easy for people to give concmd perms without realizing, then perhaps the request popup could be adjusted to make some permissions (such as concmd) stand out like a sore thumb by changing their display colors.

**Comment by thegrb93** [comment]
If someone wants to do that improvement, the I think we can revert that.

**Comment by wrefgtzweve** [comment]
If this was ever implemented, please add a option to disable it for servers.
