### ISSUE TITLE
Add Entity:TakeDamageInfo() and the CTakeDamageInfo datatype

### ISSUE THREAD

**Issue by OctothorpeObelus** [thegrb93/StarfallEx#1483]
As of now, you can only apply generic damage to individuals, or blast damage. Adding the ability to damage with any of the supported types expands what we can do in SF.

[https://wiki.facepunch.com/gmod/Entity:TakeDamageInfo](https://wiki.facepunch.com/gmod/Entity:TakeDamageInfo)
[https://wiki.facepunch.com/gmod/CTakeDamageInfo](https://wiki.facepunch.com/gmod/CTakeDamageInfo)

**Comment by thegrb93** [comment]
Could probably just enhance the existing takeDamage with extra parameters. What parts of DamageInfo are you wanting exactly?

**Comment by thegrb93** [comment]
I think the only problem with this is there are some entities that will crash if you don't provide valid damageInfo for everything.

**Comment by OctothorpeObelus** [comment]
Are there ways to validate it internally to make sure this doesn't happen? As for what I'd want from DamageInfo is mainly some of the qol functions for detecting kinds of damage:

- GetDamageType
- SetDamageType
- IsDamageType
- IsExplosionDamage
- IsFallDamage
- IsBulletDamage
- SetReportedPosition (Not sure if this effects things such as knockback. If this has no effect, just leave them out)
- GetReportedPosition

**Comment by thegrb93** [comment]
So adding 'damage type' and 'position' to takeDamage should suffice then. Those other things could be added to the EntityTakeDamage hook.

**Comment by OctothorpeObelus** [comment]
Sounds good, thanks for hearing me out!

**Comment by thegrb93** [comment]
Looks like EntityTakeDamage already gives you everything you need. You can use the damage type to determine if it was blast or fall or bullet damage.

**Comment by thegrb93** [comment]
@OctothorpeObelus can you try this https://github.com/thegrb93/StarfallEx/pull/1485

**Comment by OctothorpeObelus** [comment]
I'll give it a shot as soon as I'm at my PC and I'll let you know

**Comment by OctothorpeObelus** [comment]
Seems to work well, I don't think anything is missing
