### ISSUE TITLE
#1502 Broke navmesh creation

### ISSUE THREAD

**Issue by ZH-Hristov** [thegrb93/StarfallEx#1505]
CNavArea doesn't have a CallOnRemove method, which means it doesn't work with the new ent list manager.

**Comment by thegrb93** [comment]
I think the best solution is to copy those functions from the Entity table to the NavMesh table since I think it should work correctly still for those entities.

**Comment by ZH-Hristov** [comment]
If you mean FindMetaTable("CNavArea").CallOnRemove = FindMetaTable("Entity").CallOnRemove, tried it and it doesn't work.

**Comment by ZH-Hristov** [comment]
It also seems to have broken nextbot spawning as well.

**Comment by ZH-Hristov** [comment]
Nextbot issue is an easy fix though. Line 95 has the old register command still in there and it needs to be removed.

**Comment by thegrb93** [comment]
Looks like cnavarea aren't actually entities so I'll just add a check.

**Comment by thegrb93** [comment]
Should be fixed
