### ISSUE TITLE
Add docs for type's fields

### ISSUE THREAD

**Issue by TheVayt** [thegrb93/StarfallEx#1512]
Currently there is no documentation in any form about fields of instances of Vector, Angle, and similar data classes.
For example, nowhere is it written that you can get or assign vector axis values via `vec.x`, `vec[1]`, or even `vec.xy`.

**Comment by TheVayt** [comment]
Adding parseable information about fields probably could benefit these projects:
https://github.com/yogwoggf/emmyfall, https://github.com/Zubbbz/starfall-vscode 
![image](https://github.com/thegrb93/StarfallEx/assets/31164554/b4970773-64c2-47f0-b257-7b593d8ec42b)

**Comment by Vurv78** [comment]
> nowhere is it written that you can get or assign vector axis values via vec.x, vec[1], or even vec.xy.

It's written on the __index function of the types

**Comment by TheVayt** [comment]
I see now. Still, a separate category for fields would be preferable and clearer for the unaware, than a metamethod description

**Comment by thegrb93** [comment]
Should be pretty easy to do. I can get the data added and parsed, but I probably won't be making updates to the docs to use that data anytime soon.

**Comment by thegrb93** [comment]
Maybe just adding the comments would make it work? They seem to be using a generator for that extension's code. https://raw.githubusercontent.com/yogwoggf/emmyfall/generator-output/emmyfall.lua

**Comment by thegrb93** [comment]
Maybe the author here knows what needs to be added? https://github.com/yogwoggf/emmyfall/

**Comment by thegrb93** [comment]
Maybe the author knows what needs to be added? @yogwoggf

**Comment by Vurv78** [comment]
Don't we already have ``---@field``?
https://github.com/thegrb93/StarfallEx/blob/3e864c364ca9cff5ddf370269159800c5b353278/lua/starfall/libs_sh/math.lua#L7

The SF Helper just doesn't seem to show them for libraries (and they are untyped)
Just need to add them to the classes.

**Comment by Vurv78** [comment]
> Maybe just adding the comments would make it work? They seem to be using a generator for that extension's code. https://raw.githubusercontent.com/yogwoggf/emmyfall/generator-output/emmyfall.lua

Yeah they just use the docgen's output json the same way the sfhelper does

**Comment by thegrb93** [comment]
I don't know if the parser accepts those on types, but should be easy to add if so. Their generator would also need to be updated probably. Not sure.
