### ISSUE TITLE
[Feature request] Add ability to link multiple Starfall Chips to a Starfall HUD and/or multiple Starfall HUDs to a seat

### ISSUE THREAD

**Issue by dobriyprop** [thegrb93/StarfallEx#1515]
Title is self-explanatory. While we can technically connect to more than one Starfall HUD manually or with enableHud() function, it will be much more straightforward and convenient to be able to just link more than one SF Chip to a single SF HUD and more than one SF HUD to a single seat instead of circumventing this limitation with enableHud or splicing together several chips in one.

P.S.: I searched through previous issues and haven't found any issue with similar request. I accept the chance that i might miss one, so i'm sorry if this is a duplicate request.

**Comment by thegrb93** [comment]
I believe you can already link more than one hud to a single seat.

Linking multiple chips to a single hud seems weird but possible; I think the current behavior is linking to another chip will replace the existing link. It would have to be changed so that linking to a chip toggles its link.

**Comment by dobriyprop** [comment]
> I believe you can already link more than one hud to a single seat.

Unfortunately, no. It's impossible. Newly linked HUD always overrides the HUD that was linked before it.
[2023-10-11_22-28.webm](https://github.com/thegrb93/StarfallEx/assets/18686703/445ac2ce-e959-41e3-9cbd-b4994fa4cc81)

**Comment by thegrb93** [comment]
@dobriyprop should be able to link multiple huds to a vehicle now.

**Comment by dobriyprop** [comment]
Yes, it works now! Thank you very much.
