### ISSUE TITLE
CL Permissions input.lua error

### ISSUE THREAD

**Issue by wrefgtzweve** [thegrb93/StarfallEx#1516]
Not sure how to replicate it but it happens pretty often on clients
It's been happening for at least 2 months now.
![image](https://github.com/thegrb93/StarfallEx/assets/69946827/e17de4a4-a9cd-4b9b-be33-e3c9dc0fe954)

```
[starfallex] addons/starfallex/lua/starfall/permissions/core.lua:86: attempt to call a nil value
  1. haspermission - addons/starfallex/lua/starfall/permissions/core.lua:86
   2. unknown - addons/starfallex/lua/starfall/libs_sh/input.lua:158
```

**Comment by thegrb93** [comment]
Did they get a lua error with loadPermissions? That's the only thing I think can cause that.

**Comment by wrefgtzweve** [comment]
Doesn't seem like it, for a bunch of players this is the only error they had during the play session.

**Comment by thegrb93** [comment]
Hopefully the refactor fixes it
