### ISSUE TITLE
Permissions Refractor breaks permission checks

### ISSUE THREAD

**Issue by Hazeofdream** [thegrb93/StarfallEx#1522]
![image](https://github.com/thegrb93/StarfallEx/assets/74027566/5f926271-a11c-49c1-ab69-aa8ca62204c7)
![image](https://github.com/thegrb93/StarfallEx/assets/74027566/7375dcbb-cedd-4766-bd6d-8564d14870c0)

Occurred after #1518

**Comment by thegrb93** [comment]
I think you're trying to check those on serverside? They don't exist on serverside. Works fine when I call the hasPermission on clientside.

**Comment by Hazeofdream** [comment]
> I think you're trying to check those on serverside? They don't exist on serverside. Works fine when I call the hasPermission on clientside.

this was under CLIENT

**Comment by Hazeofdream** [comment]
Correction it was serverside but permissions are SHARED

![image](https://github.com/thegrb93/StarfallEx/assets/74027566/ebceb9ad-f24f-4fa2-9eb6-35181660cdec)

**Comment by ANormalTwig** [comment]
yes, there are serverside permissions you can check for.

**Comment by Hazeofdream** [comment]
not to mention that not having a server side check for this would mean that you would need to add more networking over for server checks, which is unnecessary.

**Comment by thegrb93** [comment]
I don't know why it was letting you call that with non-existent permissions before, but that's incorrect behavior that the PR apparently fixed.

**Comment by thegrb93** [comment]
input, input.bindings, render.hud, etc. are all client-side only so you can't call hasPermission in shared with them.

**Comment by thegrb93** [comment]
If you want to give me some code that I can test with that you think should be working, I can look, but I don't see any issues right now.
