### ISSUE TITLE
require() only returns one value

### ISSUE THREAD

**Issue by legokidlogan** [thegrb93/StarfallEx#1528]
If you return multiple values in a file, and then `require()` it, you will only receive the first value, not all of them.

`require_test.txt`:
```lua
--@name Require Test

return 1, 2
```

Runner:
```lua
--@server
--@include require_test.txt

local ret1, ret2 = require( "require_test.txt" )

print( tostring( ret1 ) .. " " .. tostring( ret2 ) )
```

Expected `1 2`, got `1 nil`

**Comment by ANormalTwig** [comment]
Doesn't normal Lua also not return more than 1 value for `require()`?

**Comment by ANormalTwig** [comment]
Pretty sure it has to due to the way require caches the return value.

**Comment by legokidlogan** [comment]
The the [function's documentation](https://thegrb93.github.io/StarfallEx/#Libraries.builtins.require) should be updated accordingly, as it currently states that it returns multiple values.
