### ISSUE TITLE
[Feature Request] Add a Concommand to clientside terminate a user's Starfalls

### ISSUE THREAD

**Issue by snepderg** [thegrb93/StarfallEx#1531]
I went looking through the Source for sflib.lua and found some commands under the `_call` function to block and unblock SF users (_of which I did not know existed, mainly due to them being named with some kind of prefix between 'sf\_' and the command name_), but I noticed there isn't a concommand to just terminate their chips instead of blocking them.

Now, technically I could just invoke block and then unblock them, but that's not really practical at all. Also, I understand that it would be weird for a kill command to be steamid. I guess userid could work, but it might make more sense to keep it in-line with the block/unblock concommands.

**Comment by thegrb93** [comment]
Just need to move these blocks to a concommand.Add and replace with RunConsoleCommand

https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/editor/sfframe.lua#L2048-L2054
https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/editor/sfframe.lua#L2074-L2076

**Comment by thegrb93** [comment]
Steamid arg most likely, and autocomplete would be a good bonus.

**Comment by snepderg** [comment]
Noted, where would you recommend I create that concommand? I see that the _call for the block list defines block commands but it doesn't make much sense to me to define a kill command in there

**Comment by thegrb93** [comment]
Probably a concommand.Add in instance.lua or in the starfall_processor cl_init.lua

**Comment by snepderg** [comment]
Testing some code now, extrapolated those two to functions. Sorry if it's all lumped into one commit, still getting the hang of things.

**Comment by snepderg** [comment]
Annoyingly, VSCode insists on formatting some whitespace in other areas of the files. Trying to resolve an unrelated issue on my p2p server so I can test. I forked it here:

https://github.com/snepderg/StarfallEx/tree/feature/concmd-kill

**Comment by snepderg** [comment]
Okay, got it working. I figured out what the syntax error is. 

Unfortunately I cannot get argStr to work, so we're gonna have to go with wrapping the SteamID in quotes. I used `string.match()` before but decided string.StartsWith should suffice. (Although that may cause issues since it doesn't vet the SteamID). Anyway, it should support SteamID and SteamID64.

As for that bonus... I will get on adding autocomplete examples. Please let me know if there is anything else besides that, should be done tomorrow :)

**Comment by snepderg** [comment]
I should note, my intention is to allow `sf_user_terminate_client "<steamid>|<steamid64>"` in concmd.

**Comment by thegrb93** [comment]
All right cool, I'll check it out

**Comment by snepderg** [comment]
Tested in P2P, both commands are working as expected, with autocomplete included.

**Comment by thegrb93** [comment]
Can you open a pull request? I can review it there
