### ISSUE TITLE
drive.google.com is not whitelisted

### ISSUE THREAD

**Issue by EntityinArray** [thegrb93/StarfallEx#1534]
drive.google.com exists in the whitelist, but it doesn't seem to work.
https://github.com/thegrb93/StarfallEx/blob/aa125e80d93d6371f66f0ecc2bfcc6812be2170b/lua/starfall/permissions/providers_sh/url_whitelist.lua#L81

![image](https://github.com/thegrb93/StarfallEx/assets/18554021/4068233c-32e5-4487-b150-a1bb3838a44c)
```
SF:ps1.txt:5: Permission bass.loadURL: This url is not whitelisted. See https://github.com/thegrb93/StarfallEx/wiki/Whitelist for more information.
stack traceback:
	SF:ps1.txt:5: in main chunk
```

Happens on commit: aa125e80d93d6371f66f0ecc2bfcc6812be2170b

**Comment by x4fx77x4f** [comment]
`simple` (its definition is near the top of the file) works by escaping the parameter, prepending `^`, and appending `/.*`. That means the final pattern is `^drive%.google%.com/uc/.*`. Note the slash. Your URL lacks that slash, so it doesn't match. Unfortunately, adding a slash breaks the URL. The whitelist's code should be changed to something like
```lua
pattern("drive%.google%.com/uc%?id=[%w_%-]+")
```
Test URL: <https://drive.google.com/uc?id=1_U6K7wHZMoH9OOCHIk2BBtgXeoe_R5qW>
