### ISSUE TITLE
Rendertargets seem to not use texture filtering

### ISSUE THREAD

**Issue by marchc1** [thegrb93/StarfallEx#1543]
![image](https://github.com/thegrb93/StarfallEx/assets/106459595/3654bf6d-ceb2-4150-88af-757961d127ee)
The left is raw GLua, the right is Starfall. The same result is produced with regular drawing functions, but when drawing to a render target of 1024x1024 (same material settings, same rendertarget settings) and then drawing that render target, the GLua version seems to be texture filtered while the Starfall version is pixelated.

**Comment by thegrb93** [comment]
The glua one isn't actually anti-aliased, it just looks like it is because 'surface.DrawTexturedRect' scales UVs slightly to prevent edge wrapping.

**Comment by thegrb93** [comment]
![tex_test72](https://github.com/thegrb93/StarfallEx/assets/6713261/c95c8e45-b93e-4e51-a938-288924db9c54)
Here's the exported rendertarget texture
