### ISSUE TITLE
"inputPressed" and "inputReleased" issue on multiplayer

### ISSUE THREAD

**Issue by AzzyZun** [thegrb93/StarfallEx#1559]
When doing networking from client to server, the inputPressed / inputReleased hook on the clientside is getting triggered by any player on multiplayer. Is there any way to filter that, so that it's only limited owner's key presses?

**Comment by thegrb93** [comment]
You can specify --@owneronly so that your chip only runs for you in clientside, or you can add an `if player()==owner() then` check.
