### ISSUE TITLE
[Linux] Pasting stuff copied from outside of editor crashes/freezes game.

### ISSUE THREAD

**Issue by Damianu** [thegrb93/StarfallEx#159]

**Comment by Damianu** [comment]
It actually lags really badly.

**Comment by Damianu** [comment]
Note: Lags only after changing clipboard contents, after lag you can paste same stuff over and over, sometimes you need to press ctrl+v multiple times tho.

**Comment by Damianu** [comment]
Another important note: Doesnt happen on other DHTML stuff

**Comment by Damianu** [comment]
https://github.com/thegrb93/StarfallEx/blob/db9602d0a478e8a590fbe669d552f6103c102473/lua/starfall/editor.lua#L472
Can be fixed with removed line, however it MAY break something, cant findout what as I dont see RUNLUA: anywhere

**Comment by thegrb93** [comment]
So the problem is RUNLUA? Very strange. I don't see any issue with removing it though.
