### ISSUE TITLE
Stealing code is very easy

### ISSUE THREAD

**Issue by suunrider** [thegrb93/StarfallEx#16]
You can steal every starfall code with this client side lua `PrintTable(LocalPlayer():GetEyeTrace().Entity.files)`.
A way would be to delete the code after loading it directly, or obfuscating it.

**Comment by thegrb93** [comment]
I want the code stored on client-side so players with cantool permission can edit the starfall without having to re-transfer the data. Even if I deleted it, players could hook into the net function which transfers the code.

**Comment by thegrb93** [comment]
Even if I sent the code pre-compiled, there exist lua decompilers. I'm not sure if I want to spend the effort adding an obfuscator.

Let me know if anything needs to be done for remote code loading though because I think that's the best solution.

**Comment by thegrb93** [comment]
I just remembered, you could also use the file library to upload and run your code.

**Comment by suunrider** [comment]
Yes, I already tried that, but people still can steal the code by reading the net message

**Comment by thegrb93** [comment]
Maybe I can add string.dump

**Comment by thegrb93** [comment]
nvm it's already added.

**Comment by suunrider** [comment]
Garrys mod can't run lua binaries

**Comment by thegrb93** [comment]
I think loadString can
