### ISSUE TITLE
PatternSafe error while using some string functions

### ISSUE THREAD

**Issue by Damianu** [thegrb93/StarfallEx#162]
Hook 'net' errored with lua/includes/extensions/string.lua:257: attempt to index a string value with bad key ('PatternSafe' is not part of the string library)
lua/includes/extensions/string.lua:257: attempt to index a string value with bad key ('PatternSafe' is not part of the string library)
stack traceback:
	[C]: in function 'error'
	addons/starfallex/lua/starfall/sflib.lua:55: in function 'throw'
	addons/starfallex/lua/starfall/libs_sh/builtins.lua:396: in function '__index'
	lua/includes/extensions/string.lua:257: in function 'trimLeft'
	SF:d_os/d_os.txt:47: in function '__newindex'
	SF:d_os/programs/keyboard.txt:218: in function 'dofile'
	addons/starfallex/lua/starfall/libs_sh/builtins.lua:573: in function 'dodir'
	SF:d_os/core.txt:38: in function 'dofile'
	SF:d_os/d_os.txt:179: in function 'Launch'
	SF:d_os/d_os.txt:102: in function 'callback'
	SF:d_os/filetransfer.txt:70: in function 'gotData'
	SF:d_os/filetransfer.txt:121: in function <SF:d_os/filetransfer.txt:115>
	[C]: in function 'xpcall'
	addons/starfallex/lua/starfall/instance.lua:128: in function 'runWithOps'
	addons/starfallex/lua/starfall/instance.lua:211: in function 'runScriptHook'
	addons/starfallex/lua/starfall/libs_sh/net.lua:424: in function 'func'
	lua/includes/extensions/net.lua:32: in function <lua/includes/extensions/net.lua:17>

**Comment by thegrb93** [comment]
Seems to be an old version because the line numbers aren't matching up.

**Comment by thegrb93** [comment]
I see the error though.

**Comment by thegrb93** [comment]
I guess a workaround is to alias all the string functions with their glua function names. Any unsafe functions will require other workarounds however.
