### ISSUE TITLE
render.renderView() causes visual bugs if renderview is pointing at screen drawing itself

### ISSUE THREAD

**Issue by MrSmig** [thegrb93/StarfallEx#1623]
If a renderview is pointing at a screen drawing itself while a halo (or anything using the stencil library) is anywhere on screen, a visual bug appears (which takes on different appearances if its anything using a stencil or halo)

Reproduce via making a Renderview that faces a screen and draw it to said screen (like if you were trying to make the rendering recursively draw in itself), make sure you have the `physgun_halo` convar set to 1, then physgun a prop (or anything)

(This is with halos (via physgun_halo))
![image](https://github.com/thegrb93/StarfallEx/assets/148366458/4755294a-88ae-441b-a4ce-e4687020a4dd)

(This is what happens instead if its a stencil that is being used instead)
![image](https://github.com/thegrb93/StarfallEx/assets/148366458/10c80eeb-1643-44ac-ab4c-b8476f0f1dba)

Code to quickly reproduce this bug, place it down, link it to a screen, make sure you're looking at a screen and create any sort of halo (such as physgun halo)
```
--@client

local chip = chip()
local player = player()
local rtName = "examplert"
render.createRenderTarget(rtName)
local mat = material.create("gmodscreenspace")
mat:setTextureRenderTarget("$basetexture", rtName)
local viewdata = {
        origin = Vector(),
        angles = Angle(),
        x = 0,
        y = 0,
        w = 1024,
        h = 1024,
        drawviewmodel = false,
        drawviewer = false
    }
hook.add("renderscene","uhoh",function()
    if render.isInRenderView() then return end
    viewdata.origin = player:getEyePos()
    viewdata.angles = player:getEyeAngles()
    render.selectRenderTarget(rtName)
    render.enableClipping(false)
    render.renderView(viewdata)
    render.selectRenderTarget()
end)

hook.add("render","drawingtoscreen",function()
    if render.isInRenderView() then return end
    render.setMaterial(mat)
    render.drawTexturedRect(0,0,512,512)
end)
```
if anything needs elaboration just say.

**Comment by friztailo** [comment]
Have you tried enable drawmonitors in ViewData?

**Comment by thegrb93** [comment]
It seems like its causing gmod to think the screen resolution is 1024x1024 which affects a lot of stuff.
