### ISSUE TITLE
3D beams no longer have color

### ISSUE THREAD

**Issue by Advers** [thegrb93/StarfallEx#1625]
3D beams suddenly no longer can have their color (or alpha) set. Worked fine yesterday. Have to assume this is due to [9a9ba6c](https://github.com/thegrb93/StarfallEx/commit/9a9ba6ce8b9145d5dcd5e3981d6a2ba40f783454)

**Comment by Advers** [comment]
This also applies to render polys. Sprites are okay for whatever reason

**Comment by Advers** [comment]
Nevermind... have no idea why, but it's suddenly not reproducible.

**Comment by thegrb93** [comment]
It's possible that the rawset on the color is not working nicely with gmod. Might need to revert the rawset/rawgets
