### ISSUE TITLE
Clientside holo "Cannot remove while in rendering hook!" despite not being in a rendering hook?

### ISSUE THREAD

**Issue by ZH-Hristov** [thegrb93/StarfallEx#1630]
I can't for the life of me seem to replicate this in a standalone chip or trace it.

This is happening in a huge coroutine sequence with a lot of waits and it creates different coroutines that do add rendering hooks themselves, but are removed afterward.

The remove is definitely not in a rendering hook, it is just in the wrapped coroutine. (which is running on a think hook)

The error message wouldn't really be of any help imo, but here it is:
```
Hook 'think' errored with: SF:handy-spacemen.txt:579: Cannot remove while in rendering hook!
stack traceback:
	SF:handy-spacemen.txt:579: in function 'func'
	addons/starfallex-master/lua/starfall/libs_sh/coroutine.lua:55: in function <addons/starfallex-master/lua/starfall/libs_sh/coroutine.lua:52>
```

**Comment by ZH-Hristov** [comment]
This worked fine just the other day, only trying it today after updating my SF did it start doing this.

**Comment by thegrb93** [comment]
I think this bug might've been fixed?
