### ISSUE TITLE
2D Bass objects getting cut off/not being audible but still running if new simple fade is on.

### ISSUE THREAD

**Issue by ZH-Hristov** [thegrb93/StarfallEx#1634]
In one chip my MP3s play fine, but in the other I have to do bassObj:setFade(0, 0, false) for them to play properly, even though I am not really playing them any differently.

They are still running though, even if infinitely quiet, as visible if I do bassObj:getTime() / bassObj:getLength()

**Comment by legokidlogan** [comment]
What are your `min, max` values in the old `bassObj:setFade(min, max, true)` ?

Note that max behaves differently between simple and original fading:
  In original fading, *small* max -> more audible.
  In simple fading, *large* max -> more audible.

**Comment by thegrb93** [comment]
The title mentions 2D objects, which shouldn't be affected by fade at all I think.

**Comment by legokidlogan** [comment]
Oh, I didn't see that, sorry.
And yes, 2D sounds shouldn't be affected at all right now, I'll see if I can replicate it.

**Comment by legokidlogan** [comment]
Perhaps `not3D()` isn't behaving correctly?

**Comment by legokidlogan** [comment]
It looks like 2D sounds [require a HUD connection](<https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/libs_cl/bass.lua#L144>), which is not yet mentioned in the docs for `bass.loadFile()` and `bass.loadURL()`

**Comment by legokidlogan** [comment]
The internal sound's flags don't get changed to match the restriction either; it should be changed to either modify the string or throw an error notifying the player that they need HUD access for 2D sounds.

**Comment by ZH-Hristov** [comment]
> It looks like 2D sounds [require a HUD connection](https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/libs_cl/bass.lua#L144), which is not yet mentioned in the docs for `bass.loadFile()` and `bass.loadURL()`

I have a HUD connection in both chips I tested in, so it's not that.

**Comment by legokidlogan** [comment]
Did some debug prints, turns out `is3D()` is incorrect. It's a double-negative mistake, it ends up forcing the sound to be 3D if you have a HUD enabled.
