### ISSUE TITLE
Suggestion: restart() function

### ISSUE THREAD

**Issue by legokidlogan** [thegrb93/StarfallEx#1637]
Currently, there's no automatic way to restart a chip, it always has to be done manually via toolgun.

Having something like E2's `restart()` on serverside would be handy, even more so if you could optionally target a different chip owned by yourself.

**Comment by thegrb93** [comment]
Probably just be something like
```lua
local restarting = false
function builtin_library.restart()
    if not restarting then
        restarting = true
        timer.Simple(0,function()
            instance.entity:SetupFiles(instance.entity.sfdata)
        end)
    end
end
```
