### ISSUE TITLE
setComponentLocksControls() does not work on seat-linked HUDs

### ISSUE THREAD

**Issue by ProfessorBoxtrot** [thegrb93/StarfallEx#1638]
Using the following code with a starfall linked to a HUD and that HUD linked to a seat, controls will not be locked when entering the seat.
```lua
--@server

local stuff = chip():getLinkedComponents()


for i,v in pairs(stuff) do
    if v:getClass() == "starfall_hud" then
        v:setComponentLocksControls(true)
    end
end
```

Tested on latest version of main branch. Interacting with the HUD produces the expected result (locking your controls).

**Comment by thegrb93** [comment]
You need to run that code in a PlayerEnteredVehicle hook I think

**Comment by thegrb93** [comment]
Oh wait, I just reread what that function does, nevermind. Let me see
