### ISSUE TITLE
Add a remote uploader / updater for sf

### ISSUE THREAD

**Issue by Circuitbreak00** [thegrb93/StarfallEx#164]
Would be helpful to see a list of all spawned starfall chips to make sure no ones spawning anything spotty, would also be helpful for editing hidden chips in a base, for example.

**Comment by thegrb93** [comment]
Remote uploader and viewer is already possible to make using starfall itself. The uploader can be done with globaltables.player (but only your own chips). I guess this can be added sometime.

**Comment by thegrb93** [comment]
Moving to stuff to add
