### ISSUE TITLE
Can't get angle velocity on clientside

### ISSUE THREAD

**Issue by dobriyprop** [thegrb93/StarfallEx#1650]
### Issue
Documentation states that [getAngleVelocity()](http://thegrb93.github.io/StarfallEx/#Types.Entity.getAngleVelocity) function can be used on both server and client sides for Entity and PhysObj types. But when you try to get angle velocity of an entity on clientside - you receive an error "Physics object is invalid"

### Replication
1) Spawn a chip with following code
```lua
--@name
--@author
--@client

chip = chip()

print(chip:getAngleVelocity())
```
2) Receive an error
```
SF:main:7: Physics object is invalid
stack traceback:
	SF:main:7: in main chunk
```

### Possible solutions
- Fix getAngleVelocity() function to work on clientside
- Сorrect the function description in the documentation to specify that it can only be used on the server side

**Comment by thegrb93** [comment]
It looks like gmod doesn't have a binding for clientside angle velocity. You'll have to bug the develops for it.

**Comment by thegrb93** [comment]
The reason it does still exist clientside is there might be clientside entities that it will work on.

**Comment by legokidlogan** [comment]
That's because the client realm has code to understand and use physics objects (for `ents.CreateClientside()` and etc), but serverside ents don't send over their physics objects because they aren't needed for prediction and thus would be a waste of networking.

**Comment by dobriyprop** [comment]
Ok, now i understand why it is like it is. Thank you for explanation.

**Comment by thegrb93** [comment]
@dobriyprop you can estimate their angle velocity using their change in angle.

**Comment by dobriyprop** [comment]
I've tried but I've yet to figure out a reliable way of doing it.

**Comment by thegrb93** [comment]
```lua
local axis, ang = (E:getMatrix() * EprevMatrix:getInverseTR()):getAngleAxis()
local angVel = axis*math.deg(ang)
```
