### ISSUE TITLE
Severside clips on holograms do not appear for new players after they are created

### ISSUE THREAD

**Issue by Advers** [thegrb93/StarfallEx#1663]
Severside clips on holograms do not appear for new players after they are created.

![image](https://github.com/thegrb93/StarfallEx/assets/48806866/47a75e6e-d578-43cd-a1ef-2e97afef7bfe)
(What should appear. Left is a holo, right is a prop)

![image](https://github.com/thegrb93/StarfallEx/assets/48806866/93d8f3f8-4cb6-40b7-9476-667faaba2c90)
(What appears for people who initialize after the clips are created)

This is not desirable behavior. Working around this on the user's part, by always creating holo clips on the client manually, is possible, but makes :setClip() existing on the server kind of pointless

**Comment by thegrb93** [comment]
I think we just need `net.Start("starfall_hologram_clips") net.WriteEntity(self) net.SendtoServer()` in https://github.com/thegrb93/StarfallEx/blob/99bb20d9bf3701738cf1ab2fc018a7560d5c82ee/lua/entities/starfall_hologram/cl_init.lua#L21

**Comment by thegrb93** [comment]
Or replace the server netcode with SF.WaitForPlayerInit
