### ISSUE TITLE
"Failed to find supertype, Entity"

### ISSUE THREAD

**Issue by Aloncheeto** [thegrb93/StarfallEx#1664]
I am using the workshop mirror, when placing a starfall chip i get the error "lua/starfall/instance.lua:423: Failed to find supertype, Entity"

This first appeared on the server i played on, to test i entered single player and i got the same error. 

![image](https://github.com/thegrb93/StarfallEx/assets/72901838/69c282c5-7352-486b-baaa-7e64a298b920)

![image](https://github.com/thegrb93/StarfallEx/assets/72901838/3f1d2c7b-84ac-4c83-ae99-726010ef6300)

I await a response, thanks in advance

**Comment by thegrb93** [comment]
For some reason my revert commit wasn't deploying to workshop correctly. I just reran it and its fine now.
