### ISSUE TITLE
Projected Textures for Starfall

### ISSUE THREAD

**Issue by Advers** [thegrb93/StarfallEx#1669]
As it currently stands, the only way to use projected textures alongside Starfall is to spawn a gmod or wiremod lamp, but this is very limiting compared to what is possible with direct Lua control over projected textures. These would be a useful and good addition, though they will need new particular permissions and cvars to not be abused since they can significantly affect framerate and cause crashes. I think they could fit into light.lua, but creating a new library for them shouldn't be off the table. Feedback and opinions appreciated

**Comment by thegrb93** [comment]
light.lua would be the best place.

**Comment by Advers** [comment]
I've created a fork of my branch to work on this. I will add things as I find the time to do so
