### ISSUE TITLE
GWATER2 

### ISSUE THREAD

**Issue by terenbutor** [thegrb93/StarfallEx#1673]
how to make the water flow like from a tap? can you throw in the code for this?

**Comment by friztailo** [comment]
Use particle and gravity

**Comment by friztailo** [comment]
gwater2 used additional modules for render

**Comment by terenbutor** [comment]
how?

**Comment by friztailo** [comment]
https://thegrb93.github.io/StarfallEx/#Libraries.particle.create
https://thegrb93.github.io/StarfallEx/#Types.Particle.setGravity
https://thegrb93.github.io/StarfallEx/#Types.Particle.setCollide

Examples can also be found in the garry`s mod wiki. The syntax is almost identical to starfallex.
Learn to find information.

**Comment by friztailo** [comment]
https://thegrb93.github.io/StarfallEx/#Types.ParticleEmitter.add

**Comment by thegrb93** [comment]
He wants fluid simulation particles. You should look at the gwater source code maybe. Nobody here will be able to answer this question.
