### ISSUE TITLE
CPU Quota exceeded

### ISSUE THREAD

**Issue by terenbutor** [thegrb93/StarfallEx#1675]
what? How do I fix this?

**Comment by friztailo** [comment]
You have exceeded the maximum allowable load on chip.
There is an example on this topic: https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/examples/cpu_time.lua
Other examples: https://github.com/thegrb93/StarfallEx/tree/master/lua/starfall/examples
They are also available in the starfall editor.

**Comment by friztailo** [comment]
Only it is better to use `if not quotaCheck(0.95) then return end`

**Comment by adamnejm** [comment]
What about enabling GitHub Discussions for stuff like this?
