### ISSUE TITLE
hasPermission does not return correctly

### ISSUE THREAD

**Issue by Viper939999** [thegrb93/StarfallEx#1677]
https://youtu.be/N3IWglSAuUk
as you can see it has the perms to use it but says i dont

**Comment by legokidlogan** [comment]
Some permissions (such as `bass.loadURL`) require an additional argument to `hasPermission()`.
In this case, you would need to do `hasPermission( "bass.loadURL", url )`

**Comment by thegrb93** [comment]
Can look into making it throw an error if the arg isn't provided.
