### ISSUE TITLE
Custom material name as keyvalue

### ISSUE THREAD

**Issue by dstmnaki** [thegrb93/StarfallEx#1684]
As the title says have the name of a custom material be able to be defined using a keyvalue, if not defined the normal one should be used instead

Line 133 of "lua/starfall/libs_cl/material.lua"
***return CreateMaterial("sf_material_" .. shader .. "_" .. i, shader, {})***

Reason why i am requesting this is that when other players use custom materials that index will be off for materials that were used in dupes, this change would fix that

**Comment by thegrb93** [comment]
Materials can't be destructed so you'd be limited to a certain number of different names, and then once used, you wouldn't be able to use new names. This wouldn't work. What you want probably has a better solution, but I'm not sure what you're trying to do.

**Comment by dstmnaki** [comment]
replacement for url material tool, create materials using starfall, use them in dupes

**Comment by thegrb93** [comment]
create the material and set its url texture, then you can setMaterial in clientside with `ent:setMaterial("!"..material:getName())`

**Comment by dstmnaki** [comment]
that works until someone else has custom materials created, it adds a number to the end of the name

**Comment by dstmnaki** [comment]
also if the material can't be destroyed would it matter if you can set it's name anyways?

**Comment by thegrb93** [comment]
> that works until someone else has custom materials created, it adds a number to the end of the name

getName() accounts for that.

**Comment by thegrb93** [comment]
Materials are reused by other chips if one chip stops using them so they need their numbered naming scheme. You'd also have to worry about chips using the same material names and such. Not feasible.
