### ISSUE TITLE
Permission problem

### ISSUE THREAD

**Issue by suunrider** [thegrb93/StarfallEx#17]
You can set in multiplayer the props of everyone the material and the color, also of players. Things like `setNoDraw` also work, which are very abusive.

**Comment by thegrb93** [comment]
Done

**Comment by suunrider** [comment]
Did nothing, you can still set the color and the material of anyone's prop without permission.

**Comment by thegrb93** [comment]
I can't reproduce. For me, they give permission errors. Can you put your code?

**Comment by suunrider** [comment]
```
if SERVER then
    for k, v in pairs(find.all()) do
        if v and v:isValid() then
            v:setColor(Color( 255, 200, 200))
        end
    end
end
```
colors every entity. Server uses NADMOD Prop protection btw.

**Comment by thegrb93** [comment]
Try updating again

**Comment by suunrider** [comment]
Now it doesn't let me color each prop, but i cant do anything with my holograms too (setMaterial/setColor).

**Comment by thegrb93** [comment]
I'll add hologram setMaterial and setColor
