### ISSUE TITLE
SV Binding for the gameevent player_say

### ISSUE THREAD

**Issue by wrefgtzweve** [thegrb93/StarfallEx#1710]
https://wiki.facepunch.com/gmod/gameevent/player_say

![image](https://github.com/thegrb93/StarfallEx/assets/69946827/9720f09f-0fb4-4699-b816-523bafdfe6f6)
This hook will run after GM:PlayerSay 
A lot of addons mess with the PlayerSay hook which can be annoying with hook ordering, having a binding for this would be an easy way to see 100% the exact same thing as players see in their chat.

This would be useful for serverside, for clientside it's likely the same as the current `playerchat` hook.

**Comment by thegrb93** [comment]
I guess this could act as the serverside version of playerchat.
