### ISSUE TITLE
parse.markup making lua error if font is not valid

### ISSUE THREAD

**Issue by ax255** [thegrb93/StarfallEx#1718]
> [starfallex] 'font' isn't a valid font
>   1. Parse - lua/includes/modules/markup.lua:322
>    2. parseMarkup - addons/starfallex/lua/starfall/libs_cl/render.lua:1881
>     3. unknown - SF:sfasp/screen.txt:103
>      4. xpcall - [C]:-1
>       5. run - addons/starfallex/lua/starfall/instance.lua:560
>        6. runScriptHookForResult - addons/starfallex/lua/starfall/instance.lua:652
>         7. func - addons/starfallex/lua/starfall/sflib.lua:705
>          8. unknown - addons/srlions_hook_lib/lua/includes/modules/hook.lua:255

Snippet of the code i used

```lua
    local font = render.createFont("Roboto", 28, 400, true, false)

    hook.add("render", "rt1", function()
    
        local str = "<font=font>"

        local mk = render.parseMarkup(str, 1000)
        mk:draw(10, 10, 0, 0, nil, nil)

    end)
```

**Comment by adamnejm** [comment]
You're trying to use a font called `font`.
```lua
local str = string.format("<font=%s></font>", font)
```

**Comment by ax255** [comment]
i fixed it by doing local `str = "<font="..font..">"` to have the real font name made by sf, but sf should error the chip not doing lua error, i think calling invalid color <color=qdqdq> might lua error also

**Comment by thegrb93** [comment]
markup.Parse erroring is fine
