### ISSUE TITLE
Sf damage hook doesn't detect wiremod turret damage

### ISSUE THREAD

**Issue by Circuitbreak00** [thegrb93/StarfallEx#172]
The hook EntityTakeDamage doesn't trigger when you shoot at a prop with a wiremod turret, does the hook just not search for that damage type? Or just ignores it if the inflictor isn't a player or npc

**Comment by thegrb93** [comment]
I'll check and see

**Comment by thegrb93** [comment]
I think an addon is preventing the hook from being called. The hook works fine in my tests.
