### ISSUE TITLE
Starfall breaks PlayerButtonDown/PlayerButtonUp prediction in singleplayer

### ISSUE THREAD

**Issue by TankNut** [thegrb93/StarfallEx#1721]
Please change the section in [lua/starfall/libs_sh/input.lua](https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/libs_sh/input.lua) that relays PlayerButtonDown/Up hook calls from the server to the client if the game is in singleplayer, it actively breaks prediction and contradicts the [expected behavior](https://wiki.facepunch.com/gmod/GM:PlayerButtonDown) and can cause issues with other addons.

**Comment by thegrb93** [comment]
I can make it just called the sf hook

**Comment by TankNut** [comment]
That would work yeah
