### ISSUE TITLE
CL permissions check error

### ISSUE THREAD

**Issue by wrefgtzweve** [thegrb93/StarfallEx#1729]
```
[starfallex] addons/starfallex/lua/starfall/permissions/core.lua:120: attempt to call field 'check' (a nil value)
  1. haspermission - addons/starfallex/lua/starfall/permissions/core.lua:120
   2. unknown - addons/starfallex/lua/starfall/libs_sh/input.lua:157
```
Been getting this error since forever 

Happens semi frequently, figured I'd report it. I'm not sure how to replicate.
![image](https://github.com/thegrb93/StarfallEx/assets/69946827/210b946e-833e-4031-9d52-05d441de3e76)

**Comment by thegrb93** [comment]
I can make the default check function emit an error about what permission failed to initialize.
