### ISSUE TITLE
Player Quota Limit

### ISSUE THREAD

**Issue by edgarasf123** [thegrb93/StarfallEx#173]
Just an idea. Instead of calculating cpu quotas per chip, calculate the quata per player.

That way, people will be more encouraged just to use one chip and write more optimized code instead of just hogging up the resources of the server with seperate chip.

Maybe player quota would be something like 2*(chip quota) in addition to chip quota? Or replace chip quota with player quota completely?

**Comment by thegrb93** [comment]
I had this in mind too. Shouldn't be too difficult.

**Comment by Damianu** [comment]
Wouldnt that be much slower?

**Comment by thegrb93** [comment]
I don't think it would be slower.
