### ISSUE TITLE
Removing a custom prop does not free the max vertices limit

### ISSUE THREAD

**Issue by Exotic0015** [thegrb93/StarfallEx#1742]
While repeatedly removing and spawning a chip that spawns a custom prop the max vertices limit doesn't seem to be decremented resulting in the following error being thrown.

```
The custom prop vertices limit has been reached. (14400)
```

**Comment by thegrb93** [comment]
plyVertexCount doesn't have code to free when the custom prop is removed, yeah. Need to add that
