### ISSUE TITLE
SF Serverside error

### ISSUE THREAD

**Issue by wrefgtzweve** [thegrb93/StarfallEx#1744]
Not sure how to replicate it, started happening ~6 days ago. 
```
addons/starfallex/lua/starfall/transfer.lua:137: attempt to index field 'ErroredPlayers' (a nil value)
   1.  __index - [C]:-1
    2.  func - addons/starfallex/lua/starfall/transfer.lua:137
     3.  unknown - lua/includes/extensions/net.lua:38
```

It's probably a simple fix, seems like the the entity index got occupied by another ent during a net message? 
<https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/transfer.lua#L137>

**Comment by thegrb93** [comment]
Someone manually targeting that net.Receive with non-starfall entity?

**Comment by wrefgtzweve** [comment]
Seems to rarely happen, if someone specifically targeted it I'd expect it spamming
Could be used to spam though yeah
