### ISSUE TITLE
3D rendering is broken for screen components

### ISSUE THREAD

**Issue by legokidlogan** [thegrb93/StarfallEx#1747]
The 2D render context of `render` for screen components runs fine, but the 3D context doesn't appear to run at all. Here's an example of 2D rendering on a screen, 3D rendering on a screen, and 3D rendering in `PostDrawOpaqueRenderables` using a HUD.

```lua
--@name 2D Render
--@client

hook.add( "render", "test", function()
    render.drawRect( 100, 100, 50, 50 )
end )
```

```lua
--@name 3D Render
--@client

hook.add( "render", "test", function()
    local screen = render.getScreenEntity()

    render.draw3DSphere( screen:localToWorld( Vector( 0, 0, -20 ) ), 5, 20, 20 )
end )
```

```lua
--@name 3D Render HUD
--@client

hook.add( "PostDrawOpaqueRenderables", "test", function()
    render.draw3DSphere( chip():localToWorld( Vector( 0, 0, -20 ) ), 5, 20, 20 )
end )
```

https://github.com/thegrb93/StarfallEx/assets/26103433/b6abc35f-19c9-458c-a5e9-a78b8dc4aba8

This was tested on 64bit, both in p2p and a dedicated server.

Additionally, printing `timer.curtime()` in the `render` hook only yields one copy of each timestamp, where I would expect two copies each since the 2D and 3D contexts should be calling in the same frame. This indicates that the 3D context never runs at all anymore.

**Comment by legokidlogan** [comment]
Here's an old chip of mine that uses 3D rendering in a screen component, which now shows up blank. It's also using virtually no client cpus, implying again that the 3D context isn't running at all.
![image](https://github.com/thegrb93/StarfallEx/assets/26103433/81757d35-64a2-4eeb-a9f8-28852c31c4b2)

**Comment by thegrb93** [comment]
"render" doesn't have a separate 2d/3d context. Not really clear what the issue here is. You need to pushMatrix with the world arg set to true for the sphere to position correctly in your second example

**Comment by legokidlogan** [comment]
The `render` hook has been listed as a dual 2D/3D context for years, and has operated as such without needing an extra viewmatrix.
![image](https://github.com/thegrb93/StarfallEx/assets/26103433/c1852098-806b-4b16-9bf3-545530fb79a6)

**Comment by legokidlogan** [comment]
Pushing a matrix does indeed fix the problem, but it wasn't required in the past, so old chips will need to be updated.

**Comment by thegrb93** [comment]
No, render was never called multiple times, that doesn't make sense.

**Comment by thegrb93** [comment]
It used to be called by the HUD component which might explain the 2D context, but render now is only 3D. Now the HUD component calls 'drawhud' instead.

**Comment by legokidlogan** [comment]
The old chip in that screenshot didn't make use of a HUD. Just the `render` hook one a screen component, doing 3D rendering.

**Comment by thegrb93** [comment]
Still, render doesn't run two contexts. That would be horribly inefficient and would also cause code in render to run twice each frame
