### ISSUE TITLE
Serverside Hologram clips throw error when more than 4 clips are applied to one hologram

### ISSUE THREAD

**Issue by Advers** [thegrb93/StarfallEx#1748]
This is the error that appears in the console:
```
[starfallex-master] addons/starfallex-master/lua/starfall/libs_sh/bit.lua:156: attempt to perform arithmetic on local 'b1' (a nil value)
  1. readDouble - addons/starfallex-master/lua/starfall/libs_sh/bit.lua:156
   2. unknown - addons/starfallex-master/lua/entities/starfall_hologram/cl_init.lua:136
    3. ProtectedCall - [C]:-1
     4. callback - addons/starfallex-master/lua/starfall/sflib.lua:1148
      5. WaitForConditions - addons/starfallex-master/lua/starfall/sflib.lua:1121
       6. WaitForEntity - addons/starfallex-master/lua/starfall/sflib.lua:1145
        7. func - addons/starfallex-master/lua/entities/starfall_hologram/cl_init.lua:152
         8. unknown - lua/includes/extensions/net.lua:38
```
This occurs specifically when more than 5 clips are put onto a single hologram, at any time. Here is a chip I made to demonstrate the issue:
```
--@server

holo = hologram.create(chip():getPos(),Angle(),"models/props_c17/oildrum001.mdl")

for i=1,5 do
    holo:setClip(i,true,Vector(),Vector(1,0,0),holo)
end
```
If the loop only runs 4 times, there is no error. It throws the error at 5 or more.

![image](https://github.com/thegrb93/StarfallEx/assets/48806866/125e849b-86b5-456e-8c6f-75fe29f6871f)
4 clips, no error, clips appear

![image](https://github.com/thegrb93/StarfallEx/assets/48806866/6f2eddee-4d8f-44f5-bdca-d41df94c41bf)
5 clips, errors, clips do not appear

**Comment by thegrb93** [comment]
This loop is wrong now. Gotta fix it. https://github.com/thegrb93/StarfallEx/blob/master/lua/entities/starfall_hologram/cl_init.lua#L135

**Comment by thegrb93** [comment]
Probably change to `while clipdata:tell() < clipdata:size() do`
