### ISSUE TITLE
[Enhancement] A hook that runs when a wire input was wired to/unwired from something

### ISSUE THREAD

**Issue by dobriyprop** [thegrb93/StarfallEx#1750]
Is it possible to add a hook that will run only when an SF chip wire input was wired to or unwired from something? The `input` hook is not very efficient for detecting if an input of SF chip was wired to something because it runs every time if there's a change of value of an input. If value changes, for example, every server tick that will cause unnecessary cpu usage on server side.

**Comment by thegrb93** [comment]
I don't think wiremod itself has this functionality. You would likely just want to check if the inputs are connected by getting the input entity. You can use a timer or think hook to detect if that changes.

**Comment by thegrb93** [comment]
Or you can use the input hook and check if the input entity has changed, if it is then you know the wiring was changed.
