### ISSUE TITLE
selectRenderTarget not working properly on hud

### ISSUE THREAD

**Issue by CornerPin** [thegrb93/StarfallEx#177]
Calling **render.selectRenderTarget** with **nil** argument after using render targets breaks world rendering

![image](https://cloud.githubusercontent.com/assets/7669876/23822016/24f60d1c-0654-11e7-9786-4d360e49a1be.png)

Sample code:
```lua
if SERVER then
    local hud = chip():isWeldedTo()
    
    if hud and hud:getClass() == "starfall_hud" then
        hud:linkComponent( chip() )
    end
else
    render.createRenderTarget( "image" )
    
    hook.add( "postdrawopaquerenderables", "", function()
        render.selectRenderTarget( "image" )
        render.selectRenderTarget()
    end )
end
```

**Comment by CornerPin** [comment]
I've found that render.SetStencilEnable( true ) cause this in render.lua:616

**Comment by thegrb93** [comment]
Thanks. It's fixed.
