### ISSUE TITLE
Weird errors appearing "Table lengths not equal"

### ISSUE THREAD

**Issue by Xer0n** [thegrb93/StarfallEx#1776]
starfall/libs_sv/wire.lua:467: Table lengths not equal
stack traceback:
	starfall/libs_sv/wire.lua:467: in function 'adjustPorts'

---

starfall/libs_sv/wire.lua:467: Table lengths not equal

---

Seems to be anything that requires wire inputs

**Comment by adamnejm** [comment]
CC @marchc1 via https://github.com/thegrb93/StarfallEx/commit/1a22057df3adee626c5d43b746ba548b59738450

**Comment by Xer0n** [comment]
What's the quick easy solution for this?  Most of my Starfall scripts error now.

**Comment by adamnejm** [comment]
- switch to `adjustInputs`/`adjustOutputs`
- revert to before the aforementioned commit
- placeholder descriptions `wire.adjustPorts({MyInput={type="number", description="Description for this input."}})`

Either one of these should work until it's fixed.

**Comment by TheVayt** [comment]
@thegrb93 rewrote everything here https://github.com/thegrb93/StarfallEx/pull/1768/commits/ed0a1fe4f19ce60360b886ba2f15e5d53692c68b and broke it. Previous revision in PR https://github.com/thegrb93/StarfallEx/pull/1768 works fine
