### ISSUE TITLE
RT draw origin not at 0,0

### ISSUE THREAD

**Issue by ThatOneCheetah** [thegrb93/StarfallEx#179]
My MIDI player's visualiser code broke suddenly, and a after bit of figuring about I came to the conclusion that the drawing origin for RTs seems to be offset?

```lua
local strRT    = "very_fancy_rt_name"
local clrWhite = Color( 255, 255, 255 )

render.createRenderTarget( strRT )

hook.add( "render", "sfmxpRender", function()
    render.selectRenderTarget( strRT )
    render.setRenderTargetTexture( strRT )
    
    -- render.setColor( clrWhite ) -- visualiser stuff
    -- render.drawTexturedRect( 0, fHeight + 15, 1024, 1024 ) -- visualiser stuff
    
    render.setColor( clrWhite )
    --render.drawRect( 0, 0, 1024, 16 )   -- Will not draw anything
    --render.drawRect( 0, 16, 1024, 16 ) -- Draws a bar
    --render.drawRect( 0, 0, 1024, 32 )   -- Draws a bar half the size of what it should be
    
   -- snip --

    render.selectRenderTarget( nil )
    --render.setRenderTargetTexture( strRT ) -- Does not make a difference
    render.setColor( clrWhite )
    
    render.drawTexturedRect( 0, 0, 512, 512 )
    --render.drawRect( 0, 0, 16, 16 )
end )
```
  
This offset seems to be inconsistent, as it doesn't happen on some servers running StarfallEx *(recent change?)*.

**Comment by its-suun** [comment]
`render.createRenderTarget(strRT)` before `hook.add` is missing.

**Comment by ThatOneCheetah** [comment]
Pardon me, that *is* in the actual code, I forgot to C&P that over. Original post edited.

**Comment by its-suun** [comment]
You could also remove unecessary parts and reduce it to a minimum

**Comment by thegrb93** [comment]
I re-addedthe material scaling hack since all of the 2d drawing functions seem to rely on it. 3d drawing functions will need the custom material type (or scaled uvs).
