### ISSUE TITLE
instance.player sometimes becomes invalid

### ISSUE THREAD

**Issue by legokidlogan** [thegrb93/StarfallEx#1790]
`timer.simple()` inside of the `OnEntityCreated` hook in the client realm will sometimes error on other players with "Invalid starfall user"

```
Starfall 'lkl/utility_chips.txt' errored for player Weird_Weirdo
Hook 'onentitycreated' errored with: starfall/libs_sh/timer.lua:118: Invalid starfall user
stack traceback:
	starfall/libs_sh/timer.lua:118: in function 'simple'
	SF:lkl/utility_chips_dir/dup_enhanced_first_person.txt:440: in function <SF:lkl/utility_chips_dir/dup_enhanced_first_person.txt:436>
```

![image](https://github.com/user-attachments/assets/c6441659-029c-4524-a0e7-b725ec2c32c8)

**Comment by thegrb93** [comment]
The error you posted indicates that the chip owner was invalid and the script tried to use timer.simple which requires an owner for the timer limit to be checked. It doesn't have anything to do with the timer in the hook call itself.

**Comment by legokidlogan** [comment]
The chip errored on another player's client, not the owner. I've encountered this at least 30 or so different times now, none of which errored on the owner's client. In all cases, the owner's client instance was perfectly fine.

Furthermore, in all cases both the owner and the player who got the error had been fully spawned into the server for a long time, with the error occurring long after the chip was fully loaded by all clients. Whenever the error occurs, it only happens to one seemingly random player, never multiple at the same time.

**Comment by ax255** [comment]
Ive had this happen so many time too, sometime the owner player become invalid for some reason to some clients

**Comment by thegrb93** [comment]
> The chip errored on another player's client, not the owner. I've encountered this at least 30 or so different times now, none of which errored on the owner's client. In all cases, the owner's client instance was perfectly fine.
> 
> Furthermore, in all cases both the owner and the player who got the error had been fully spawned into the server for a long time, with the error occurring long after the chip was fully loaded by all clients. Whenever the error occurs, it only happens to one seemingly random player, never multiple at the same time.

I never said the error happened on the owner; just the error indicates that the owner entity went invalid. You'll have to add checks to your code to check that the owner is valid maybe. If the chip tries to use the owner to increment a limit counter and the owner is invalid, it'll error.

**Comment by legokidlogan** [comment]
<https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/libs_sh/timer.lua#L78>
timer.simple() doesn't use the chip owner for the limit, it uses the local player.

**Comment by legokidlogan** [comment]
Nevermind, sf stores the owner as `instance.player`
Totally not confusing at all.

**Comment by legokidlogan** [comment]
Either way, there shouldn't be anything that makes `instance.player` become invalid in that hook. This issue only started happening recently, sometime around when changes were made to handling full updates and OnRemoved.

**Comment by Advers** [comment]
I've been getting this error lately too, but it doesn't even come with a stack traceback for me. It's definitely something that started happening more recently. I can't figure out how to reproduce the issue on purpose, but I don't think it's something that can be reliably solved by isValid() checks on the user's part. It just happens.

**Comment by thegrb93** [comment]
I wonder if the IsValid() refactor is the cause.

**Comment by thegrb93** [comment]
I'll check if the subclass metas get their own IsValid functions or not.

**Comment by ax255** [comment]
Been getting those error where player.instance become invalid for about a month

**Comment by thegrb93** [comment]
Could see if https://github.com/thegrb93/StarfallEx/pull/1823 fixes it. Idk if the gmod devs have some weird jank where calling the method this way instead of directly would have different behavior.

**Comment by thegrb93** [comment]
If not, then I think a gmod update caused the change in behavior.

**Comment by thegrb93** [comment]
I'm not merging that btw till it's confirmed to help. Someone needs to check it out.

**Comment by thegrb93** [comment]
> I've been getting this error lately too, but it doesn't even come with a stack traceback for me. It's definitely something that started happening more recently. I can't figure out how to reproduce the issue on purpose, but I don't think it's something that can be reliably solved by isValid() checks on the user's part. It just happens.

I think the reason it's silent is because the chip owner is invalid when the error happens. I'll see if that can be fixed.

**Comment by thegrb93** [comment]
I think this can be closed now that the error networking is better. If you still find something is wrong feel free to open another.
