### ISSUE TITLE
Performing a full update causes all clientside instances to be destroyed

### ISSUE THREAD

**Issue by legokidlogan** [thegrb93/StarfallEx#1794]
Full updates (`record fix; stop`, etc) cause the local player's client instances of all chips to become destroyed. They remain destroyed after the update, requiring the chips to be restarted.

I know that recently there was a change made to fix ghost instances being left behind due to becoming disconnected from the chip and existing forever. Perhaps instead of destroying the instance unconditionally, starfall should try to reconnect it to the chip after the update, and if the chip no longer exists, then destroy the instance.

**Comment by thegrb93** [comment]
Can you add a print("Destroyed") here to confirm that this block is executing during the full update? https://github.com/thegrb93/StarfallEx/blob/master/lua/entities/starfall_processor/cl_init.lua#L22

**Comment by thegrb93** [comment]
I don't seem to be able to reproduce this. I'm guessing its specifically a dedicated server in which case the owners of the chips may become invalid and thus trigger errors similarly seen in https://github.com/thegrb93/StarfallEx/issues/1790
