### ISSUE TITLE
getFrictionSnapshot() function's tables do not have a .Other.

### ISSUE THREAD

**Issue by Mikey-Mikey** [thegrb93/StarfallEx#1797]
For some reason the PhysObj:getFrictionSnapshot() function does not return a .Other in the tables.
![image](https://github.com/user-attachments/assets/e1f635b0-cc24-4fa2-8b70-96cbe7f47691)

Here's the code for replicating this:
![image](https://github.com/user-attachments/assets/a908f5f0-41a1-4fbe-8fbe-7530cbaa2f41)

The Glua version of GetFrictionSnapshot() does return this. I even made an entity to show this:
![image](https://github.com/user-attachments/assets/c39e3fdd-bc85-4f9b-ad95-38b0bc0afb63)

**Comment by thegrb93** [comment]
Maybe the structwrapper is haven't trouble with the physobj type. Can take a look

**Comment by thegrb93** [comment]
Need to see if WrapObject is failing to work on physobj types
