### ISSUE TITLE
Serverside holograms do not show clips

### ISSUE THREAD

**Issue by Advers** [thegrb93/StarfallEx#1809]
Here is code to test the issue:
```
--@name Clip Test
--@author Adversarius
--@server

test = hologram.create(chip():getPos(), Angle(), "models/props_c17/oildrum001.mdl")

test:setClip(1, true, Vector(), Vector(1,0,0), test)
```

As can be seen, one clip is applied to the hologram. The clip does not appear properly.
![image](https://github.com/user-attachments/assets/da188636-d663-4a3d-9012-fa0c0f8fec8c)

Here is what the hologram should look like (simulated with a clientside hologram and clip).
![image](https://github.com/user-attachments/assets/3c444c9e-aac0-4944-a22d-775e67650d2a)

This appears to be an unintended bug after #1804. Clientside holograms are not affected.

**Comment by thegrb93** [comment]
Need to add `self.renderstack:makeDirty()` logic to https://github.com/thegrb93/StarfallEx/blob/master/lua/entities/starfall_hologram/cl_init.lua#L159
