### ISSUE TITLE
draw3DQuad() has a texture offset.

### ISSUE THREAD

**Issue by nerdkoopa** [thegrb93/StarfallEx#181]
draw3DQuad() has a texture offset on all edges. It was fixed for drawTexturedRectUV(), but it broke for quads.

**Comment by thegrb93** [comment]
yeah, will need to use an RT to scale the texture until a material type is made. Or maybe a texture option to specify whether the material is for 2D or 3D rendering.

**Comment by thegrb93** [comment]
I have another issue open for this so will close this one.
