### ISSUE TITLE
:setAnimation() Broken

### ISSUE THREAD

**Issue by NazeHexogon** [thegrb93/StarfallEx#1811]
Any attempt to use this function will result in the following error: note that I tested this with dupes I've created that had working animations up to this point. 

starfall/libs_sh/hologram.lua:479: attempt to index field 'renderstack' (a nil value)
stack traceback:
    starfall/libs_sh/hologram.lua:479: in function 'setAnimation'
    SF:main:15: in main chunk

**Comment by NazeBall** [comment]
same guy, I just ended up remembering my login for my main.
