### ISSUE TITLE
Importing audio URLs have stopped functioning. 

### ISSUE THREAD

**Issue by NazeBall** [thegrb93/StarfallEx#1815]
I tested this with my known working chips, and they also have the same issue. 

error: Callback errored with: SF:main:37: attempt to index local 'obj' (a nil value)
stack traceback:
	SF:main:37: in function <SF:main:36>

**Comment by NazeBall** [comment]
If you can't find/replicate the issue it might be the server I'm on. they love fucking with shit they shouldn't

**Comment by thegrb93** [comment]
What is your code?
