### ISSUE TITLE
hasPermission() not properly outputting

### ISSUE THREAD

**Issue by BPRJon** [thegrb93/StarfallEx#1819]
I'm trying to check if I have permission to draw on every player's hud with `render.hud` but it is outputting true no matter what.

```
for _,v in pairs(find.allPlayers()) do
     print(hasPermission("render.hud",v))
end
```

I also cannot check clientside permissions on SERVER

**Comment by thegrb93** [comment]
The hud check is separate from the permission. You'll have to check if a hud is enabled as well. Also yes, the permissions are not networked between server and client.
