### ISSUE TITLE
createCustom props are somehow listed as already having a collision listener and not having a collision listener

### ISSUE THREAD

**Issue by SubArrest** [thegrb93/StarfallEx#1822]
Was trying to add a collision listener to a createCustom prop and it threw the error that it already had one.
When trying to remove it before adding a collision listener it threw the error that it doesn't already have one.

```
--@server

local x, y, z = 48, 48, 108
local convexes = {
    {
        Vector(0, 0, 0), Vector(x, 0, 0), Vector(x, y, 0), Vector(0, y, 0),
        Vector(0, 0, z), Vector(x, 0, z), Vector(x, y, z), Vector(0, y, z),
    }
}

local Base = prop.createCustom(chip():localToWorld(Vector(-24,-24,0)),chip():localToWorldAngles(Angle(0)),convexes,true)
Base:setMass(50000)

Base:removeCollisionListener()
Base:addCollisionListener(function() print("bang") end)
```

**Comment by thegrb93** [comment]
Is another addon conflicting? I can't reproduce it saying it already has one.

**Comment by SubArrest** [comment]
Weird, I don't know if there is another addon conflicting but its definitely possible, always pops up with the same message of it saying its already got a collision listener on the server I'm on (and all other props apart from custom works fine)

**Comment by thegrb93** [comment]
Can you see if it works in singleplayer for you?

**Comment by SubArrest** [comment]
It's most likely the fault of the server I was on, I tried in singleplayer and a local server I setup and it worked fine with no issues
