### ISSUE TITLE
trace filters inverted behavior?

### ISSUE THREAD

**Issue by bluemetaknight** [thegrb93/StarfallEx#1826]
Just updated starfall today and noticed that the behavior on all my trace functions has been inverted.

Once where i used `local function filter(ent) return ent:getOwner() != owner() end`

I now have to use `local function filter(ent) return ent:getOwner() == owner() end`

I would like to know if this behavior is intentional or not before I go update all the instances of this in my scripts.

To clarify, the behavior I would like is to not hit entities owned by me.

**Comment by thegrb93** [comment]
The trace filter behavior hasn't been touched. Do you have a better code example?

**Comment by bluemetaknight** [comment]
This is the actual trace that is using the above filter.
```
            local tr = trace.line(Gun:getPos(),Gun:getPos()+(Gun:getForward()*RangerDist),filter)
            local AimPos = tr.HitPos:toScreen()
```
This code worked before I updated earlier today.

**Comment by thegrb93** [comment]
I tested with this and it seems to work fine.

```lua
--@server

local owner = owner()
hook.add("think","",function()
    local start = owner:getShootPos()
    local tr = trace.line(start, start+owner:getAimVector()*10000,
        function(e) return e~=owner end)
    print(tr.Entity)
end)
```

**Comment by bluemetaknight** [comment]
I did neglect to mention that my code is running client side. Just tested it with your above code and it seems like getOwner() doesnt function clientside anymore. It returns nothing, even when just checking the trace hit ent.

**Comment by ax255** [comment]
Seem like a CPPI issue, check what cppi addon you use. It's possible that the one you use doesn't specify ownership of props client side or you call :getOwner() before client know the owner.

**Comment by thegrb93** [comment]
It does sound like a prop protection issue. I don't the SF has changed anything regarding prop protection in a long time.

**Comment by thegrb93** [comment]
I'll give it a try using my prop protection sometime later.

**Comment by bluemetaknight** [comment]
Im using Nadmod Prop Protection, which itself hasant been updated in awhile.

**Comment by Advers** [comment]
I just had a problem similar to this, although it's more like "filters not working in specific cases." It seems filtering players has stopped working? Specifically, filtering for a single player entity does not work, but filtering for a table with a player or players in it does.

**Comment by thegrb93** [comment]
> I just had a problem similar to this, although it's more like "filters not working in specific cases." It seems filtering players has stopped working? Specifically, filtering for a player entity does not work, but filtering for a table with a player or players in it does.

This should fix the entity table issue https://github.com/thegrb93/StarfallEx/pull/1832

**Comment by thegrb93** [comment]
I just tested this and didn't have any problem
```lua
--@client

local owner = owner()
local chip = chip()
hook.add("think","",function()
    local start = owner:getShootPos()
    local tr = trace.line(start, start+owner:getAimVector()*10000, function()
        return owner~=chip:getOwner()
    end)
    print(tr.Entity)
end)
```

**Comment by bluemetaknight** [comment]
The whole point of my original code was to AVOID tracing objects owned by myself. The above code fails to do that because getOwner() no longer seems to work client side.

```
--@client

local owner = chip():getOwner()
print(owner)
```

This code should return owner, however it returns nil, at least on my machine.

**Comment by friztailo** [comment]
> The whole point of my original code was to AVOID tracing objects owned by myself. The above code fails to do that because getOwner() no longer seems to work client side.
> 
> 
> 
> ```
> 
> --@client
> 
> 
> 
> local owner = chip():getOwner()
> 
> print(owner)
> 
> ```
> 
> 
> 
> This code should return owner, however it returns nil, at least on my machine.

https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/libs_sh/entities.lua#L102

Maybe you have disabled the permission?

**Comment by thegrb93** [comment]
It works for me with and without nadmod pp.

> Maybe you have disabled the permission?
That wouldn't affect anything. I'm not even sure why that if check is there.

**Comment by thegrb93** [comment]
Try updating your version of nadmodpp, it works fine for me.
