### ISSUE TITLE
unable to alter weapons in hand

### ISSUE THREAD

**Issue by NazeBall** [thegrb93/StarfallEx#1835]
I don't know if it's a bug or intentional, but I can't alter the weapon I'm holding through Starfall by changing its color, material, setDraw, etc. 

the following is in a timer within the code itself.
Code I use to find the weapon: Tool = owner():getActiveWeapon():getClass()

**Comment by thegrb93** [comment]
I don't think the viewmodel (the entity of the weapon in your hands) gets updated if the weapon itself changes. You'd have to edit both, which not sure if possible for SF to do.

**Comment by ax255** [comment]
remove the `:getClass()` it return the string class of the weapon and not the weapon entity itself

```lua
local Tool = owner():getActiveWeapon()
Tool:setColor(Color(255, 0, 0))
```

**Comment by NazeBall** [comment]
ill try that, if that doesn't work ill have to take it up with the server I'm on

**Comment by NazeBall** [comment]
I'll have to take it up with the server I'm on as the world owns the tools and therefore can't be edited in Starfall. can't be dropped either so I can't get around it.
