### ISSUE TITLE
Typo in docs: "SPLASH" damage type

### ISSUE THREAD

**Issue by shroobloom** [thegrb93/StarfallEx#1840]
https://github.com/thegrb93/StarfallEx/blob/c18f4a26749632dd7f7aa3b23dac862a149b2a5b/lua/starfall/libs_sh/enum.lua#L1320

should be SLASH, as found in env.DAMAGE, not SPLASH.

**Comment by thegrb93** [comment]
Fixed with https://github.com/thegrb93/StarfallEx/commit/9305596a63490c4225e6d47487cbe2acd79e616d
