### ISSUE TITLE
PixelVis handles are created twice or more?

### ISSUE THREAD

**Issue by ZH-Hristov** [thegrb93/StarfallEx#1844]
Going by the default limit (50) this code will error saying the lmit was hit.

```
--@client
enableHud(player(), true)
local mat = material.load("sprites/light_glow02_add_noz")
local cp = chip():getPos()
local poses = {}

for i = 1, 26 do
        table.insert(poses, cp + Vector(50 * i, 0, 0))
end

hook.add("postdrawtranslucentrenderables", "", function()
    render.setMaterial(mat)
    
    for _, v in pairs(poses) do
        if render.pixelVisible(v, 30) <= 0 then continue end
        render.draw3DSprite(v, 30, 30)
    end
end)
```

Setting i to 25 will not produce an error.
Setting the limit to 51 and setting i to 26 will still error.
Setting the limit to 52 and setting i to 26 will work.

**Comment by Advers** [comment]
The limit for pixelVisible calls is per-frame. The render hook you're using (postdrawtranslucentrenderables) is called at least twice per frame and occasionally three or more if reflections are involved.

**Comment by Advers** [comment]
Consider using a different render hook if possible.

**Comment by thegrb93** [comment]
You can also put your loop in a pcall to catch whenever you're out of pixelvis handles.

**Comment by thegrb93** [comment]
Also postdrawtranslucentrenderables has two input args I think which allow you to determine which pass to draw.

**Comment by Advers** [comment]
> Also postdrawtranslucentrenderables has two input args I think which allow you to determine which pass to draw.

True, but the hook is still called at least twice even if you exit before drawing in the skybox. Can be tested by testing changes in curtime which only updates on think.

**Comment by ZH-Hristov** [comment]
Ah, right, I forgot about the sky pass.
