### ISSUE TITLE
Add Hologram:setSequence

### ISSUE THREAD

**Issue by shroobloom** [thegrb93/StarfallEx#1848]
Currently, there's no way to set the sequence of a hologram, only the animation. It would also be nice to be able to set an entity's sequence.

**Comment by ax255** [comment]
Internally on the :setAnimation() it does indeed set a sequence https://github.com/thegrb93/StarfallEx/blob/1b7d91a292d942716d8072101ccb3f21b9e1b2d5/lua/starfall/libs_sh/hologram.lua#L477

**Comment by shroobloom** [comment]
nevermind then, the problem with my code is unrelated to this, will have to do more digging :(
