### ISSUE TITLE
SFHelper won't open up in code editor as a tab

### ISSUE THREAD

**Issue by VoidNmbrZero** [thegrb93/StarfallEx#1871]
I recently switched to Linux and remembered that GMod exists, I didn't play for a while and when I click on SFHelper it opens "Do you wish to go to this URL?" dialog instead of opening as a tab. Sometimes it downloads the docs to sf_docs.txt (at least hints state so) but even after refreshing there is no sf_docs.txt anywhere. I can't tell is this Linux specific issue.

**Comment by VoidNmbrZero** [comment]
I've [noticed](https://github.com/thegrb93/StarfallEx/blob/2597744df5513323e97f252824241e55462dbfc7/lua/starfall/editor/sfframe.lua#L1869) it won't open docs in tab unless gmod branch is not "unknown"

**Comment by thegrb93** [comment]
It can't unless gmods chromium branch is being used
