### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by Ykropcheg** [thegrb93/StarfallEx#1874]
Add the ability to give yourself a weapon Player:giveWeapon(String swep) and using superuser to give not only to yourself;
Add the ability for superuser to write on behalf of another player in chat;
Add mousemoved and mouseWheeled to the server side and make it shareable as a result.

I apologize if this is the wrong section.

**Comment by VoidNmbrZero** [comment]
Why only :giveWeapon() to yourself though?

**Comment by Ykropcheg** [comment]
Self without the superuser directive, with superuser to all. It's just not really pleasant when you get your inventory clogged up with weapons you don't need :)

**Comment by Advers** [comment]
Why superuser? Feel like it could have a dedicated permission set for it.

>Add mousemoved and mouseWheeled to the server side and make it shareable as a result.
These hooks are clientside in GLua. Marking them "shared" in Starfall won't change the fact that they do not exist on the server.

**Comment by Ykropcheg** [comment]
Not necessarily a superuser, more perhaps as an example that without rights a person can't give a gun to another, but only to themselves. And with special rights he can give any user a weapon.

**Comment by legokidlogan** [comment]
If you need to give yourself weapons, just use `concmd( "gm_giveswep SWEP" )`.

Being able to force another player to write something to chat is a no-go imo, even for superuser. It easily leads to framing, slander, manipulation of someone else's sf/ulx/e2 chat commands, and so on. Never a good idea.

As Advers mentioned, the glua hooks used by `mousemoved` and `mousewheeled` are clientside, not shared. It's not quite that simple. However, it could be tracked serverside using the `SetupMove` hook instead. ...Except that you run into the same problem as #1514 where you would need a permission that clients can set individually (i.e. if they want to allow people to read these inputs or not) but have the value of said permission option get networked to the server, which the current infrastructure does not support.

**Comment by Ykropcheg** [comment]
I realize that you can issue weapons via concmd, but I am doing events and I would like to make a command event with different classes and therefore weapons and I need to issue a set of weapons to people

**Comment by legokidlogan** [comment]
Adding a `Player:giveWeapon()` function should be reasonable, it would just need to use the `entities.canTool` or its own brand new serverside permission (allowed on owner-only be default). Also have superuser bypass the permission requirement. Do note though that glua's `Player:Give()` function allows non-SWEP classes to be passed in, which may or may not have undesirable effects. Could maybe have it do a check to enforce SWEP-only classes.


> The superuser directive removes the ability to transfer points to other players

What points? How does the server handle giving out points normally? Why does superuser remove your ability to give points? Why does the transfer need to receiving player to use a chat command at all?

If you or one of your server developers are able to, it may be best to modify your point addon to make it easier to work with. You could even [extend the sf player metatable](https://github.com/CFC-Servers/cfc_sf_lib/blob/master/lua/starfall/libs_sv/ply.lua) or make a [new sf library](https://github.com/CFC-Servers/cfc_sf_lib/blob/master/lua/starfall/libs_sh/pvp.lua) custom to the server.

**Comment by thegrb93** [comment]
prop.createSent can be used to give players weapons. I don't think the other two things can be added though. I kinda agree that letting superuser do concmd or 'say' on players is probably too much power.

**Comment by thegrb93** [comment]
serverside mousemoved should be done by the user rather than SF
