### ISSUE TITLE
Suggestion: Add some way to reload/refresh the documentation from in-game without needing to rejoin.

### ISSUE THREAD

**Issue by MrSmig** [thegrb93/StarfallEx#1875]
There currently isn't a way to have newly added functions show up in SFHelper/Docs without rejoining the server entirely, while `sf_reloadlibrary` does allow for functionality to be updated, it doesn't seem to apply to Docs.

**Comment by thegrb93** [comment]
The work to do this doesn't really justify the benefit since reloading map doesn't take very long (so long as you don't have a million addons mounted).
