### ISSUE TITLE
Precaching of high complexity model always crashes chip on first placement

### ISSUE THREAD

**Issue by ZH-Hristov** [thegrb93/StarfallEx#1883]
Is there really nothing that can be done about this? Perhaps pausing the quota checking right before a model is about to be precached and then resuming it afterwards, if that is even possible.

The model doesn't even have to be that high polygon to crash the chip. Simple main character models like Grigori or Eli can crash the chip when being precached.

**Comment by ZH-Hristov** [comment]
At the very least, we could have the precacheModel function in SF that stops the quota check before it's ran perhaps?

**Comment by wrefgtzweve** [comment]
a precacheModel function would be incredibly abusive

**Comment by ZH-Hristov** [comment]
Could check if the model exists beforehand, run if doesn't.

**Comment by ZH-Hristov** [comment]
Alternatively, maybe the quota pause could be for specific functions like setModel or prop/holo creation, which could cause a precache to happen.

**Comment by thegrb93** [comment]
I don't think there's a solution for this. Any addon suffers from it. It's typically models with very large uncompressed textures that lag the most.

**Comment by ZH-Hristov** [comment]
> I don't think there's a solution for this. Any addon suffers from it. It's typically models with very large uncompressed textures that lag the most.

Is it the textures specifically? I can compress them but I've experienced it happening with a Grigori model with L4D animations ported from its workshop.

**Comment by thegrb93** [comment]
Probably a combination. Any ragdoll can be laggy since it has a combination of high res textures

**Comment by thegrb93** [comment]
Doesn't really help find a solution. Other than running the server on an ssd or ramdisk

**Comment by ZH-Hristov** [comment]
That's the thing though, I am running it off an SSD, and it can still happen.
Awful issue overall, not sure even Rubat could do anything about it. Seems like a deeply rooted engine thing.

**Comment by thegrb93** [comment]
Maybe a precache directive could be added with a limit on the number of models

**Comment by thegrb93** [comment]
--@precachemodel

**Comment by thegrb93** [comment]
Maybe a precache directive could be added
--@precachemodel
