### ISSUE TITLE
Bass Audio error 

### ISSUE THREAD

**Issue by NazeBall** [thegrb93/StarfallEx#1888]
I have had this issue for a few days now as well as on and off for a while, along with another person on the server I play having it for around a year where the audio of a Starfall that is with a URL just errors for you while everyone else can still hear it. I've checked, and the audio isn't blocked along with the link being proven to function. 

-- Code --

--@name Gnome Audio
--@author The808Error
--@client
--Link for Discord links
local URL="main"
local Link="https://drive.google.com/uc?export=download&id=1lsR20AEJmnobcZvtTrKcxGzS_8JUtzyi"

local _enter={
    main=Link
}

bass.loadURL(_enter[URL],"3d noblock",function(Sound)
    Sound:setPitch(1)
    Sound:setVolume(0.3)
    Sound:setLooping(true)
    Sound:setFade(600, 800)
    
    hook.add("think","",function()
        Sound:setPos(chip():getPos())
    end)
end)

-- Screenshot --

![image](https://github.com/user-attachments/assets/bdbe92d7-7c02-4fa6-81bf-bd4ea951e89b)

**Comment by NazeBall** [comment]
the other person it errored for first is the other person I mentioned.

**Comment by wrefgtzweve** [comment]
`bass.loadURL` can return a `nil` if the sound wasnt found / couldnt be played its like this in basegame too

**Comment by NazeBall** [comment]
know any reasons why Gmod wouldn't be able to play it? I was looking into this and apparently, it affects StreamRadio as well as E2 so it's not as much of a Starfall issue as I thought.

**Comment by NullLikesNothing** [comment]
> know any reasons why Gmod wouldn't be able to play it?

Check the second and/or third argument in the callback, it will give you more information

**Comment by thegrb93** [comment]
Maybe google drive isn't a very good host for streaming sound

**Comment by NazeBall** [comment]
The link itself isn't the issue, I've tried others in the past with all the same results. It could be a Starfall issue with it fucking with something but I doubt it, might just be a Gmod issue if anything. The stupid thing is I just fully factory reset this computer and the fact it's still having this issue is just odd.

**Comment by ax255** [comment]
google drive never worked for me even with the raw version you better off using another file hosting

**Comment by NazeBall** [comment]
I should, but this issue started before I even used google drive for audio

**Comment by thegrb93** [comment]
When bass loads a sound for a server full of people, the host hosting the sound has to open a streaming connection for every player that wants to play it, which some services will throttle. You could try adding a retry section to your code which will retry loading the sound if it fails, or try a different host.

**Comment by NazeBall** [comment]
Had it print to chat what the exact error was and it was something with Bass_Error_Timeout so it is probably what you mentioned or something similar.
