### ISSUE TITLE
ParticleEmitters do not consistently work after creation

### ISSUE THREAD

**Issue by Advers** [thegrb93/StarfallEx#1890]
Particle emitters will occasionally not show any particles created with them. They are still created (it's not an issue of reaching the SF emitter limit) and also does not appear to be related to the engine limit for particle emitters. SF says they are still "valid". This can happen to one emitter belonging to a single chip and not affect any others, or affect all of them -- basically appearing random.

**Comment by thegrb93** [comment]
I think gmod has an internal limit

**Comment by wrefgtzweve** [comment]
It does yeah, lua effects can hit this limit and just not work sometimes. I dont think there's a way to know if the limit is hit sadly.
