### ISSUE TITLE
#1889 instances not deinitializing when they're supposed to

### ISSUE THREAD

**Issue by yingKatsu** [thegrb93/StarfallEx#1892]
#1889 
most likely fullupdate related
![Untitled](https://github.com/user-attachments/assets/4d765754-a721-499e-bd08-918f13107ccc)

**Comment by thegrb93** [comment]
Is that in clientside or serverside or both?

**Comment by NullLikesNothing** [comment]
@thegrb93 It happens client-side as indicated by the screenshot.

Starfall '...' errored for player [redacted]
Player disconnected!

Server-side wouldn't have this happen unless the client actually left the game

**Comment by yingKatsu** [comment]
yup clientside. i see my code erroring for people in this way when they experience lag spikes (someone loading a megapac) and their game freezes a sec, which is why im pretty sure its fullupdates again

**Comment by thegrb93** [comment]
See if https://github.com/thegrb93/StarfallEx/pull/1893 fixes it

**Comment by Advers** [comment]
nevermind, it just seems to be PVS or fullupdate dependent

**Comment by thegrb93** [comment]
We need player entities to be always_transmit I think. The fact they go invalid and don't exist for other clients is just crazy.

**Comment by thegrb93** [comment]
I think its something to do with source engine's anti-cheating

**Comment by thegrb93** [comment]
Actually, I have another idea that'll work

**Comment by wrefgtzweve** [comment]
players can be invalid after a full update, They're resynced by default every 10s lots of servers up that though

it's not a anticheat thing but a garry hack to fix something 
https://wiki.facepunch.com/gmod/Networking_Usage#svplayerforcedupdateissue

**Comment by yingKatsu** [comment]
https://cdn.discordapp.com/attachments/921945120167833613/1304905421676478524/2024-11-09_14-24-29.mp4?ex=67311760&is=672fc5e0&hm=56a59544d94a55f28a1e14dd850018c855c8bac7c13fda521ebeebdba63af4ac&
latest version of gmod with only latest ver of starfall and dev library for sf

playerInstances table emptying itself for some reason.

my chips have been nonsensically "CPU Quota Reached!" erroring for a while now
noticed that their quota tooltips were freezing and not updating.
the reason why is because the quota is literally not being calculated bc the for loop that loops all instances is looping an empty table
the instances still run and delete as normal

code used:
```lua
local print = print
local printTable = printTable
dev.setGlobal()

print(SysTime())
for pl, insts in pairs(SF.playerInstances) do
    for instance in pairs(insts) do
        print(pl, instance.entity)
    end
end```

**Comment by thegrb93** [comment]
@yingKatsu can you open a new issue and tell how to make that happen?

**Comment by thegrb93** [comment]
Nevermind, it was actually easy to reproduce

**Comment by thegrb93** [comment]
@yingKatsu fixed now
