### ISSUE TITLE
Function Idea;  target:isInPvp() 

### ISSUE THREAD

**Issue by NazeBall** [thegrb93/StarfallEx#1894]
Check for when the target which would just be a player is in Pvp. It would be a bit tricky tho I would imagine as servers handle that a bit differently depending on the server. The only way I can see how is to somehow check if the player can take damage and go from there but I don't know a lot about how that works.

**Comment by wrefgtzweve** [comment]
Servers should probably implement that themselves, there's no way to check damage like that without actually applying damage

**Comment by adamnejm** [comment]
Many such addons usually set a networked variable on the player, try that.

For example, https://steamcommunity.com/sharedfiles/filedetails/?id=1308900979 uses [`Player:SetNWBool("_Kyle_Buildmode", true)`](https://github.com/kythre/Buildmode-ULX/blob/master/lua/ulx/modules/sh/sh_kyle_buildmode.lua#L342), so in Starfall you would get it with `Player:getNWVar("_Kyle_Buildmode")`

**Comment by thegrb93** [comment]
either GetVar or GetNWVar should have it. You can list the vars with GetTable or GetNWVars I think
