### ISSUE TITLE
SV Error instance.lua:685

### ISSUE THREAD

**Issue by wrefgtzweve** [thegrb93/StarfallEx#1896]
I've seen this error happen a few times now, i dont know how to replicate it as i see it in the logs from time to time, might be related to https://github.com/thegrb93/StarfallEx/issues/1895
```
addons/starfallex/lua/starfall/instance.lua:685: attempt to concatenate field 'message' (a nil value)
   1.  __concat - [C]:-1
    2.  runFunction - addons/starfallex/lua/starfall/instance.lua:685
     3.  unknown - starfall/libs_sh/timer.lua:90
```
Locals
```
func = Function [
  SF:Table_Data.txt:12
]
self = {
  ppdata = Table [2 items]
  UnwrapObject = Function [
  starfallex/lua/starfall/instance.lua:359
]
  Unsanitize = Function [
  starfallex/lua/starfall/instance.lua:405
]
  mainfile = "Table_Data.txt"
  stackn = Number [0]
}
tbl  = {
  1 = Bool [false]
  2 = "not enough memory"
}
```

**Comment by thegrb93** [comment]
`"not enough memory"` is a lua error due to the VM reaching its limit. Can't do anything about that since the `SF.MakeError` failed to create a table

**Comment by thegrb93** [comment]
The xpcall callback should return an SF Error but it returned a string instead because lua's memory was full.

**Comment by wrefgtzweve** [comment]
Would be nice if its accounted for, no other addons error due to high ram usage.

**Comment by thegrb93** [comment]
I would guess your error logger simply can't log them due to ram being full, whereas SFs error happens after catching a ram error. Dunno tho
