### ISSUE TITLE
send reliable stream overflow when including many files

### ISSUE THREAD

**Issue by suunrider** [thegrb93/StarfallEx#19]
I've included many files with
```
--@includedir ...
requiredir( ... )
```
and timed out and got `send reliable stream overflow` in console.

**Comment by thegrb93** [comment]
Will need to refactor the whole file transfer system to fix this. I have a file transfer library that handles transfers in a way that prevents overflows which is currently pr'd in the garrysmod repository but I doubt it will ever get added so I might include it with starfall.

**Comment by thegrb93** [comment]
I think my other branch with the experimental net library fixes this btw.

**Comment by thegrb93** [comment]
This is in the stuff to add 2 issue now. Should be fixed after I refactor networking.
