### ISSUE TITLE
Owner CPU time buffer not taken into account

### ISSUE THREAD

**Issue by ax255** [thegrb93/StarfallEx#1911]
This commit https://github.com/thegrb93/StarfallEx/commit/6bd4292127142445ee39c6e2116aee05fd573459 seem to have broken owner cpu time quota

Before: 
![image](https://github.com/user-attachments/assets/a745b57f-672f-46a1-9675-28302c3af847)
After:
![image](https://github.com/user-attachments/assets/d39ccacb-8d77-4848-acb2-d86d1f466005)

**Comment by NullLikesNothing** [comment]
The issue seems to be from `player` being something else, might've been copied from other code without checking.
The fix is to change `LocalPlayer() ~= player` to `LocalPlayer() ~= self.player`
