### ISSUE TITLE
render.getScreenEntity() returns nil for HUDs

### ISSUE THREAD

**Issue by Dave9031** [thegrb93/StarfallEx#1922]
Returns only **nil** for any of the "**drawhud**" hooks.
Works properly for **screens**.

```
--@client
hook.add("drawhud", "test", function()
    print(render.getScreenEntity())
end)
```

**Comment by NullLikesNothing** [comment]
i think the reason is because the HUD ent isn't what is actually drawing *to* your HUD, only a way of connecting to the SF chip, so i think this is to be expected. and what about cases like this? there's no HUD ent to return
```lua
--@client

-- No HUD ent even required
-- there's also a permission for this
-- server you can enableHud players in your seats
-- enableHud( ply, enabled )

if player() == owner() then enableHud( nil, true ) end
```

**Comment by Dave9031** [comment]
> i think the reason is because the HUD ent isn't what is actually drawing _to_ your HUD, only a way of connecting to the SF chip, so i think this is to be expected. and what about cases like this? there's no HUD ent to return
> 
> ```lua
> --@client
> 
> -- No HUD ent even required
> -- there's also a permission for this
> -- server you can enableHud players in your seats
> -- enableHud( ply, enabled )
> 
> if player() == owner() then enableHud( nil, true ) end
> ```

I see, thank you
I think in the **enableHud** case its fine if we get **nil** - as it would allow you to imply (as a SF user) :
--> **nil** = this "_drawhud_" hook ran because of **enableHud**.

But looking at the documentation, I think returning **nil** in other cases is a bug?

### render.getScreenEntity()
Returns the entity currently being rendered to

### Returns
- Entity
Entity of the **screen or hud** being rendered

**Comment by NullLikesNothing** [comment]
I don't think it has ever returned a HUD, that may have been a typo with the docs.
and how would it even get the HUD entity? it's internally using `HUDPaint` and has no reference to the entity in it's functions
You can also have multiple HUDs connected to one chip but all of them will toggle the status
```lua
--- Returns the entity currently being rendered to
-- @return Entity Entity of the screen or hud being rendered
function render_library.getScreenEntity()
	return ewrap(renderdata.renderEnt)
end
```
My guess is, whoever wrote the note for this assumed it would return a HUD too.
I also don't understand the point of getting the HUD entity in a `drawhud` hook? It's just a standard entity with one purpose, listen for `USE` and toggle the HUD status, screens I can understand as you are drawing to *them*, not *your* screen and is useful to separate screens/render different stuff on each one.

Though I guess you could use the SF `hudconnected( Entity ent, Player ply )` hook which will have `nil`/`NULL` (`nil` on calling realm, `NULL` on the other realm as it gets notified too)  for the ent if used via `enableHud`. (same applies for `huddisconnected`)

**Comment by adamnejm** [comment]
A remnant of when SF required HUD entities. Docs should be updated to remove the HUD part.
To check if the current chip's HUD is connected, track it with the hooks @NullLikesNothing mentioned above, or use [render.isHUDActive](https://thegrb93.github.io/StarfallEx/#Libraries.render.isHUDActive) on clientside / [Player.isHUDActive](https://thegrb93.github.io/StarfallEx/#Types.Player.isHUDActive) on server.

**Comment by Dave9031** [comment]
> I don't think it has ever returned a HUD, that may have been a typo with the docs. and how would it even get the HUD entity? it's internally using `HUDPaint` and has no reference to the entity in it's functions You can also have multiple HUDs connected to one chip but all of them will toggle the status
>
> I also don't understand the point of getting the HUD entity in a `drawhud` hook? It's just a standard entity with one purpose, listen for `USE` and toggle the HUD status, screens I can understand as you are drawing to _them_, not _your_ screen and is useful to separate screens/render different stuff on each one.

Thats a bummer...
My plan was to use them in the same way as screens. For example when you have 2 seats, it would be nice to be able to draw 2 separate things for each seat all from one SF chip 
(and like with screens, the plan was to use getRenderEntity to tell to **which** HUD we are drawing to right now)

> A remnant of when SF required HUD entities. Docs should be updated to remove the HUD part. To check if the current chip's HUD is connected, track it with the hooks @NullLikesNothing mentioned above, or use [render.isHUDActive](https://thegrb93.github.io/StarfallEx/#Libraries.render.isHUDActive) on clientside / [Player.isHUDActive](https://thegrb93.github.io/StarfallEx/#Types.Player.isHUDActive) on server.

So I assume this means my plan above is not realistically possible and I will need multiple SF chips for that right?

**Comment by NullLikesNothing** [comment]
> So I assume this means my plan above is not realistically possible and I will need multiple SF chips for that right?

No, you *can* do this but you will have to use `hudconnected` and save that in some variable, then in your rendering code just check which one it is

**Comment by adamnejm** [comment]
^ Yeah pretty much, just think in terms of "which player am I currently rendering for", instead of "which component am I rendering to".
If the player is sitting in ChairA, draw one thing, if the player is sitting in ChairB, draw a different thing and so on...

_pseudo-example_
```lua
local chair1 = prop.createSeat(...)
local chair2 = prop.createSeat(...)
local modes = {
  [chair1] = function() render.drawRect(...) end,
  [chair2] = function() render.drawCircle(...) end,
}

hook.add("DrawHUD", "", function()
  modes[player():getVehicle()]()
end)
```

**Comment by Dave9031** [comment]
> > So I assume this means my plan above is not realistically possible and I will need multiple SF chips for that right?
> 
> No, you _can_ do this but you will have to use `hudconnected` and save that in some variable, then in your rendering code just check which one it is

Oh, somehow that totally flew over my head ... my bad, I see now

> ^ Yeah pretty much, just think in terms of "which player am I currently rendering for", instead of "which component am I rendering to". If the player is sitting in ChairA, draw one thing, if the player is sitting in ChairB, draw a different thing and so on...
> 
> _pseudo-example_
> 
> ```lua
> local chair1 = prop.createSeat(...)
> local chair2 = prop.createSeat(...)
> local modes = {
>   [chair1] = function() render.drawRect(...) end,
>   [chair2] = function() render.drawCircle(...) end,
> }
> 
> hook.add("DrawHUD", "", function()
>   modes[player():getVehicle()]()
> end)
> ```

Thank you very much, i have been enlightened :)
I have nothing more to add
