### ISSUE TITLE
Issues following #1919

### ISSUE THREAD

**Issue by Advers** [thegrb93/StarfallEx#1928]
Will be posting any I find. Here's the first one:

```
Hook 'think' errored with: starfall/libs_sh/math.lua:361: attempt to call global 'aunwrap2' (a nil value)
stack traceback:
	starfall/libs_sh/math.lua:361: in function 'lerpAngle'
```

**Comment by Advers** [comment]
```
SF:outer_wilds_ship.txt:233: No two vertices can have a distance less than 0.20000000298023
stack traceback:
	SF:outer_wilds_ship.txt:233: in main chunk
```

Something related to custom props is broken, not exactly sure what but this was fine in the past and now it isn't

**Comment by legokidlogan** [comment]
```
addons/starfallex/lua/starfall/permissions/providers_sh/entity.lua:72: attempt to call method 'CPPIGetOwner' (a userdata value)
stack traceback:
	addons/starfallex/lua/starfall/permissions/providers_sh/entity.lua:72: in function 'check'
	addons/starfallex/lua/starfall/permissions/core.lua:117: in function 'checkpermission'
	addons/starfallex/lua/starfall/libs_sh/hologram.lua:424: in function 'setSize'
	SF:main:7: in main chunk
```
Any time a client other than the chip owner uses `:setSize()` on a clientside holo.

Same seems to happen for `:setScale()` and `:setPos()`, likely anything else that uses that permission check.
To note, the server has FPP, and this wasn't an issue before. No idea why it would think it's a userdata either.

**Comment by legokidlogan** [comment]
> Any time a client other than the chip owner uses `:setSize()` on a clientside holo.

Looks like `ent:getOwner()` works, but `holo:getOwner()` is broken in much the same way.

**Comment by legokidlogan** [comment]
I haven't found a way to reproduce it myself, but there's also a lua-level (i.e. appeared in the problem menu, not caught by sf pcall) client error from Starfall that's occurred on some players a handful of times.

```
[starfallex] addons/starfallex/lua/starfall/sflib.lua:1692: attempt to index a nil value
    1. IsHUDActive - addons/starfallex/lua/starfall/sflib.lua:1692
        2. customargfunc - addons/starfallex/lua/starfall/libs_cl/render.lua:190
            3. func - addons/starfallex/lua/starfall/sflib.lua:847
                4. unknown - addons/ulib/lua/includes/modules/hook.lua:260
```

**Comment by legokidlogan** [comment]
> I haven't found a way to reproduce it myself, but there's also a lua-level (i.e. appeared in the problem menu, not caught by sf pcall) client error from Starfall that's occurred on some players a handful of times.

Seems to happen inconsistently when removing a chip.

**Comment by thegrb93** [comment]
> I haven't found a way to reproduce it myself, but there's also a lua-level (i.e. appeared in the problem menu, not caught by sf pcall) client error from Starfall that's occurred on some players a handful of times.
> 
> ```
> [starfallex] addons/starfallex/lua/starfall/sflib.lua:1692: attempt to index a nil value
>     1. IsHUDActive - addons/starfallex/lua/starfall/sflib.lua:1692
>         2. customargfunc - addons/starfallex/lua/starfall/libs_cl/render.lua:190
>             3. func - addons/starfallex/lua/starfall/sflib.lua:847
>                 4. unknown - addons/ulib/lua/includes/modules/hook.lua:260
> ```

Huh, didn't think Ent_GetTable could return nil. Maybe it happens on entities not yet fully initialized

**Comment by thegrb93** [comment]
Wonder if I can use that

**Comment by legokidlogan** [comment]
They are fully initialized though, that's the thing. It seems to be running the hook while un-initializing.

**Comment by thegrb93** [comment]
@legokidlogan u think this might be wrong then? https://github.com/thegrb93/StarfallEx/pull/1929/files#diff-c1ad72f96c33fd2d55300cbd654163a7faf7febde883eaa5bb293fcf439bc2d6

**Comment by legokidlogan** [comment]
Yeah, the `SF.EntIsReady` change doesn't look right. The entity is already initialized on the client, it's a problem that has a chance to occur when the cip is removed.

Also, as noted in the gmod issue linked in the old code's comment, some entities may return non-nil from `GetTable` while still not having certain critical functions defined yet. So the old checks are still needed.

**Comment by thegrb93** [comment]
Okay, will revert that. I'd guess the issue you're seeing is the entity table might be nil when called from render hooks when the entity is removed due to a race condition.

**Comment by legokidlogan** [comment]
Ownership of clientside holos is still broken, it just results in a `nil` owner instead of instantly erroring. `:setPos()` and the like work when run on the chip owner's client, but not on any other client.

**Comment by thegrb93** [comment]
I'll look

**Comment by thegrb93** [comment]
It's cuz the CppiGetOwner was localized everywhere so its not using the cl hologram override. Hmmm

**Comment by Advers** [comment]
```
Hook 'postdrawopaquerenderables' errored with: addons/starfallex/lua/starfall/libs_cl/render.lua:2081: attempt to call upvalue 'cunwrap1' (a nil value)
stack traceback:
	addons/starfallex/lua/starfall/libs_cl/render.lua:2081: in function 'add3DBeam'
```

**Comment by legokidlogan** [comment]
On both server and client, NPCs now return false with `:isNPC()`

**Comment by legokidlogan** [comment]
Strangely enough, after #1919, props created with `prop.create()` no longer show up at all in the sf `EntityRemoved` hook.

**Comment by thegrb93** [comment]
Really weird since I didn't change much code for those. Is serverside or clientside? I can't reproduce in singleplayer so maybe the server is erroring for some reason

**Comment by thegrb93** [comment]
Or maybe its something prop protection related

**Comment by legokidlogan** [comment]
After some more testing, it's an issue with another addon, CFW, but only after #1919. It tracks connections between entities, and sf `:setParent()` changed in a way that throws an error in CFW, noted [in this CFW issue](https://github.com/ACF-Team/CFW/issues/13). The error then puts the entity in a bugged state that makes it not pass through `EntityRemoved` properly at all.

I also tested a sf-created entity parented via multi-parent and that did not trigger the error, only sf `:setParent()` does.

CFW needs to make their system more robust, but it probably wouldn't hurt to see what went wrong in sf `:setParent()` as well.

**Comment by thegrb93** [comment]
Ah, I would imagine its because they detoured SetParent and sflib's SetParent is before the detour.

**Comment by thegrb93** [comment]
I think https://github.com/thegrb93/StarfallEx/pull/1937 fixes?

**Comment by legokidlogan** [comment]
They do it on `Initialize + timer.Simple(0)`, so CFW will still detour it after sf grabs it.

It might be better do use `InitPostEntity` or do something like this, where it gets the value the first time it's called by sf:

```lua
local function Ent_SetParent(child, parent)
    Ent_SetParent = ENT_META.SetParent
    return Ent_SetParent(child, parent)
end
```
