### ISSUE TITLE
`render.drawTexturedRectUV` doesn't work as expected for URL created material

### ISSUE THREAD

**Issue by Cheatoid** [thegrb93/StarfallEx#1935]
As the title says. Just tried to draw a smaller portion of a bigger image with `render.createMaterial("URL to image.png", ...)` and `render.drawTexturedRectUV` in `render` hook (for screen), it is instead drawing the whole (big) image to the screen. Confirmed by using `material.createFromImage("local path to image.png", "")` and the same render code, which does render a smaller portion as expected.

**Comment by thegrb93** [comment]
Test code would be appreciated

**Comment by Cheatoid** [comment]
It is really just a simple code...
Material from filesystem, works as expected (draws the specified UV portion):
```lua
--@client
local mat = material.createFromImage("gui/tool.png", "")
--print(mat:getWidth(), mat:getHeight())
hook.add("render", "", function()
  render.setMaterial(mat)
  render.setColor(Color(255, 255, 255, 255))
  render.drawTexturedRectUV(0, 0, 128, 128, 0.25, 0.25, 0.75, 0.75)
end)
```
Material from URL, doesn't work (draws a whole image, not UV portion):
```lua
--@client
local url = "https://i.imgur.com/UZBKEvd.png"
local mat = render.createMaterial(url, function(mat, url, width, height, layout)
  --print("cb", mat, url, width, height)
end, function(mat, url)
  --print("done", mat, url)
  --print(mat:getWidth(), mat:getHeight())
  hook.add("render", "", function()
    render.setMaterial(mat)
    render.setColor(Color(255, 255, 255, 255))
    render.drawTexturedRectUV(0, 0, 128, 128, 0.25, 0.25, 0.75, 0.75)
  end)
end)
```

**Comment by thegrb93** [comment]
When you create from url, it formats the image in the top left of the texture with the size of the image, so your texture coordinates for the url one is wrong.

Assuming the url image size is 128x128:
local r=128/1024*0.25
render.drawTexturedRectUV(0, 0, 128, 128, r, r, 3*r, 3*r)

**Comment by Cheatoid** [comment]
No idea why make it like that nor do I care, that's too confusing. Since this is off standard, could you be nice and provide me with a new function which I could use? Previously I would have this:
```lua
local atlasSize = 512 -- big image is 512x512px
local subImageSize = 16 -- small image is 16x16px
local GetUVCoordinates = function(indexX, indexY)
    -- translate to bottom-up 1-based indexing
    local u1 = (indexX - 1) * subImageSize / atlasSize
    local v1 = 1 - (indexY * subImageSize / atlasSize)
    local u2 = indexX * subImageSize / atlasSize
    local v2 = 1 - ((indexY - 1) * subImageSize / atlasSize)
    return u1, v1, u2, v2
end
-- With this:
local u1, v1, u2, v2 = GetUVCoordinates(5, 1)
render.drawTexturedRectUV(0, 0, 256, 256, u1, v1, u2, v2)
-- I know it would draw the 5th subimage (starting from the bottom-most row left-to-right), scaled from 16x16 to 256x256.
```

**Comment by thegrb93** [comment]
change atlasSize and subImageSize to 512/1024 and 16/1024. Then change 'subImageSize / atlasSize' to just 'subImageSize', and change '1 - ' to 'atlasSize -'
