### ISSUE TITLE
Add option/function to enable damage system (`EntityTakeDamage`) for custom prop (`starfall_prop`)

### ISSUE THREAD

**Issue by Cheatoid** [thegrb93/StarfallEx#1938]
As the title says.
Why not? It would be fun to let us make some custom breakable props which can be destroyed using actual weapons (or anything that deals damage under the hood).

**Comment by legokidlogan** [comment]
Starfall already has `EntityTakeDamage`, you can store and update your own health values on the prop and `:remove()` it when it's out of health.

**Comment by legokidlogan** [comment]
However, it would be nice to also have `PostEntityTakeDamage` to listen for damage events after addons scale the damage, block some damage events, etc.

**Comment by Cheatoid** [comment]
> Starfall already has `EntityTakeDamage`, you can store and update your own health values on the prop and `:remove()` it when it's out of health.

Well, guess what. That's what I do currently; and it is pure crap code... because I have to handle tons of traces and maintain state and on top of all that ugly mess, each SWEP/weapon/vehicle requires me to MANUALLY support it in code (which is also next to impossible btw)...

What I am suggesting here is to take advantage of engine damage system that works for everything, so we could manage health and remove our custom props (`prop.createCustom`) and do whatever, the proper and easy way.

So, we could have:
```lua
--@server

local x, y, z = 16, 16, 16
local min, max = Vector(-x, -y, -z), Vector(x, y, z)
local convexes = {
    {
        Vector(min.x, min.y, min.z), Vector(max.x, min.y, min.z), Vector(max.x, max.y, min.z), Vector(min.x, max.y, min.z),
        Vector(min.x, min.y, max.z), Vector(max.x, min.y, max.z), Vector(max.x, max.y, max.z), Vector(min.x, max.y, max.z),
    }
}

local MaxHealth = 123 -- by specifying a number, it would enable damage system and assign max health
local cube = prop.createCustom(chip():localToWorld(chip():getUp() * z), Angle(), convexes, true, MaxHealth)
-- the following should print "health=123, maxHealth=123"
print("health=" .. cube:getHealth() .. ", maxHealth=" .. cube:getMaxHealth())
cube:setHealth(45) -- and of course this should work as well, if we want to set a new health

-- now grab any weapon and damage the custom prop to remove it:
hook.add("EntityTakeDamage", "cube.health", function(target, attacker, inflictor, amount, type, position, force)
    if target == cube then
        print("[EntityTakeDamage] cube damaged:", attacker, inflictor, amount, type, position, force)
        if target:getHealth() <= 0 then
            target:remove() --timer.simple(0, function() cube:remove() end)
            --return true
        end
    end
end)
```

Then anyone could use any weapon (or armed vehicle or whatever deals damage) to attack and break the custom prop.

**Comment by thegrb93** [comment]
EntityTakeDamage already works on custom props doesn't it?

**Comment by Cheatoid** [comment]
Well. It doesn't according to my testing.

**Comment by legokidlogan** [comment]
```lua
--@server

local convexes = {
    {
        Vector( -20, -20, -20 ),
        Vector( -20, -20, 20 ),
        Vector( -20, 20, -20 ),
        Vector( -20, 20, 20 ),
        Vector( 20, -20, -20 ),
        Vector( 20, -20, 20 ),
        Vector( 20, 20, -20 ),
        Vector( 20, 20, 20 ),
    },
}
local box = prop.createCustom( chip():getPos() + Vector( 0, 0, 50 ), Angle(), convexes, true )

hook.add( "EntityTakeDamage", "TEST", function( ent, _, _, amount )
    if ent ~= box then return end
    print( amount )
end )
```
this works perfectly fine for me.

**Comment by Cheatoid** [comment]
🤔 😕 🤔
There is issue on my end then I guess.
