### ISSUE TITLE
stuff breaking since commit be9f6ff?

### ISSUE THREAD

**Issue by kirillbrest123** [thegrb93/StarfallEx#1946]
Every time someone says something this is popping up:
`[ERROR] Error: PlayerSay hook returned a non-string!`
This is happening with default chatbox. With EasyChat, nothing gets sent at all.

I've manually ran every `PlayerSay` hook, but they all return nil. So i checked out `GM:PlayerSay`, and i saw that it gets detoured in `lua/starfall/sflib.lua`. I've checked it out, and it seems that there's been a [commit](https://github.com/thegrb93/StarfallEx/commit/be9f6ff41724b2ed5c01aa925d82a5fd33e77e07) there recently, and the time of the commit lines up with the time when the issue appeared.

Removing starfall fixes the issue, so I assume that its indeed caused by starfall.

UNCONFIRMED: you also can't spawn wire stuff? can't replicate

**Comment by wrefgtzweve** [comment]
starfall is currently breaking playersay to a point where nobody can say anything.

**Comment by Earu** [comment]
Just confirmed it, starfall replaces `GAMEMODE.PlayerSay`, if overridden back to:
```lua
function GAMEMODE:PlayerSay(ply, text, teamonly) return text end
```

It starts working again

**Comment by wrefgtzweve** [comment]
To fix it i've been doing `GAMEMODE.PlayerSay = GAMEMODE.BaseClass.PlayerSay`

**Comment by Earu** [comment]
> To fix it i've been doing `GAMEMODE.PlayerSay = GAMEMODE.BaseClass.PlayerSay`

Yeah this is essentially the same thing

**Comment by thegrb93** [comment]
someone had the great idea to remove darkrp docs, but now dealing with load ordering issues. lemme take a look

**Comment by thegrb93** [comment]
Since the ordering of Initialize hooks is random across servers, I didn't catch this one.
