### ISSUE TITLE
Nextbot:getGotoPos() not working

### ISSUE THREAD

**Issue by Advers** [thegrb93/StarfallEx#1949]
Might be affecting other functions, but getGotoPos seems to just return nil instead of an actual vector. Possibly a post-#1919 bug

**Comment by thegrb93** [comment]
It turns nil after the bot completes its task of going to it. Is that working?

**Comment by Advers** [comment]
Sorry, I've just looked more into it -- I had it backwards. getGotoPos() seems to work okay. It looks like it's actually setApproachPos() that's broken. It always says the vector being given to it is nil.
