### ISSUE TITLE
Vector Division and vdiv() not working

### ISSUE THREAD

**Issue by LazorDildar** [thegrb93/StarfallEx#197]
As far as I understand, the function vdiv should be called when, for example, Vector(1)/Vector(2) is evaluated.

I am getting errors, however.
```
local v1 = Vector(2);
local v2 = Vector(5);
print( v1 / v2 );
```
results in
```
main:6: Type mismatch (Expected number, got Vector) in function __div
addons/starfall/lua/starfall/sflib.lua:53: in function 'throw'
addons/starfall/lua/starfall/sflib.lua:121: in function 'CheckType'
addons/starfall/lua/starfall/libs_sh/vectors.lua:92: in function '__div'
```

and...
`print(  v1:vdiv( v2 ) );`
Results in nil.

Finally...
`print( Vector( v1.x/v2.x,  v1.y/v2.y,  v1.z/v2.z ) );`
Will function as intended.

**Thanks for your work on starfall btw!**

**Comment by thegrb93** [comment]
__div only works with scalars. vdiv self modifies.

**Comment by LazorDildar** [comment]
My mistake, misunderstood the term self modify. That works.

Is it possible that __div could detect a vector type as the operand and use vector division instead? Or a function that returns the result rather than self modifying? Unless there is a design philosophy that is why it functions as it does.

Either way, thanks for the prompt reply.

**Comment by thegrb93** [comment]
All right, you can divide them now with the / operator.
