### ISSUE TITLE
util.Decompress util.Compress

### ISSUE THREAD

**Issue by McDunkinY** [thegrb93/StarfallEx#20]
Hello,

Any chances of util.Decompress and util.Compress being added to Starfall? Along with that, what about net.WriteData and net.ReadData?

Thanks.

**Comment by thegrb93** [comment]
yeah i can add those.

**Comment by suunrider** [comment]
util.Decompress and util.Compress are already in the fastlz library

**Comment by thegrb93** [comment]
Cool. I'll just need to do net.writedata then.

**Comment by thegrb93** [comment]
I put it in the stuff to add issue. Put stuff you want to add there so I have a more compact list.
