### ISSUE TITLE
Permissions dont work without CPPI

### ISSUE THREAD

**Issue by Damianu** [thegrb93/StarfallEx#209]
![settings](http://s.damianu.me/CrimsonWhiskers)
No matter if I set owner only or can touch, I'll still get insufficient permission on render.setProperty, I dont have any CPPI installed.

**Comment by thegrb93** [comment]
Yeah, we need something to track the owner of things. Maybe something similar to e2. Related to https://github.com/thegrb93/StarfallEx/issues/183

**Comment by thegrb93** [comment]
Going to move to 'stuff to add'
