### ISSUE TITLE
Editor bugs

### ISSUE THREAD

**Issue by Damianu** [thegrb93/StarfallEx#213]
- [x] Opening model viewer and reloading editor causes errors
- [x] Doubleclicked words have offset
- [x] Tab adds 4 spaces, but when there are more than 1 lines selected it adds only 1
- [x] `--@client`, `--@server`, `--@includedir` not getting highlighted in wire editor
- [ ] Model viewer gets opened in a really small window
- [ ] Rightclicking a tab and doing `Save as` selects the wrong tab (one tab before)
- [x] Error when switching from wire to ace
- [x] Current font not shown in wire options

**Comment by its-suun** [comment]
`--@client`, `--@server`, `--@includedir` not getting highlighted in wire editor

**Comment by its-suun** [comment]
Model viewer gets opened in a really small window

**Comment by its-suun** [comment]
Rightclicking a tab and doing `Save as` selects the wrong tab (one tab before)

**Comment by its-suun** [comment]
```
[ERROR] addons/starfallex/lua/starfall/editor/editor.lua:653: attempt to index field 'searchBox' (a nil value)
  1. fn - addons/starfallex/lua/starfall/editor/editor.lua:653
   2. unknown - lua/ulib/shared/hook.lua:109
```
when switching from wire to ace

**Comment by its-suun** [comment]
You can't open the editor from console. `starfall_event editor_open` just enables the stars falling above your head.

**Comment by Damianu** [comment]
That's because this command is internal, it shouldnt be used to open editor.

**Comment by thegrb93** [comment]
I think sf_tabs.txt used to also save which tab was selected so when the editor loads, it opens that tab.

**Comment by Damianu** [comment]
http://wiki.garrysmod.com/page/cvars/AddChangeCallback that should be used on all convars needing reload/running code, gui should just change convars.

**Comment by Damianu** [comment]
@thegrb93 done

**Comment by thegrb93** [comment]
ctrl+w should close a tab and ctrl+q should close the editor.

**Comment by its-suun** [comment]
ctrl w should only close a tab if its saved
