### ISSUE TITLE
Permissions reset on rejoin

### ISSUE THREAD

**Issue by adosikas** [thegrb93/StarfallEx#214]
I can reproduce this every time, after disabling everything, rejoining resets all permissions to default.
This is especially a problem as several default permissions have severe security issues.

**Comment by Damianu** [comment]
Seems to also happen on servers.

**Comment by thegrb93** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/3124

**Comment by thegrb93** [comment]
The solution will be to reload the map after setting permissions, or add the commands to server.cfg.

**Comment by thegrb93** [comment]
Doh, I forgot it's not an achived convar

**Comment by thegrb93** [comment]
Ok fixed
