### ISSUE TITLE
Slow workflow

### ISSUE THREAD

**Issue by its-suun** [thegrb93/StarfallEx#217]
Not sure if other have the same problem but i experience this in multifile projects: I have a main file (`main.txt`) and additional files which get included from main. When I'm currently working on an additional file and i want to test the whole project, i first have to switch back to main, leave editor and leftclick the chip (happens quite frequently).
AFAIK in expression 2 `@autoupdate` exists which updates the chip as soon as you save the file. In Starfall there would still be the problem that you have to switch to the main file. To fix that maybe there could be a `--@place file.txt` preprocessor which defines the script which gets used when you update the chip. So additional files would have `--@place main.txt`.
If you are working on a general library which gets used by multiple projects, `--@place` isn't the best solution tho.

**Comment by Damianu** [comment]
There will be remote uploader with "Refresh current file" option.

**Comment by its-suun** [comment]
I need `Refresh current project` tho

**Comment by Damianu** [comment]
All you would have to do is select chip of yours and press Refresh current file, It'll refresh file which is already loaded in chip, and when it'll be refreshed includes also will reload.

**Comment by Damianu** [comment]
missclick

**Comment by its-suun** [comment]
Sounds good, maybe refresh it also by pressing R on the chip

**Comment by thegrb93** [comment]
What's the point of pressing R on the chip when left click does the same thing?

**Comment by thegrb93** [comment]
I guess R can see what files are in the chip and update them, but I don't like the preprocessor idea.

**Comment by thegrb93** [comment]
Moving to stuff to add
