### ISSUE TITLE
Chip errors on client when joining a server

### ISSUE THREAD

**Issue by its-suun** [thegrb93/StarfallEx#219]
When i place a chip with following code and rejoin it says `Client CPU: Errored` on the chip.
```lua
--@client

hook.add("think", "", function() end)
```

**Comment by thegrb93** [comment]
I think that's because it errors if the owner of the chip leaves.

**Comment by its-suun** [comment]
Is this fixed?

**Comment by thegrb93** [comment]
No, it's intended

**Comment by its-suun** [comment]
The code hasn't any owner() in it and it errors, how is that intended? I want to test my script if it works when a player joined and no way to test that easily when i cant rejoin

**Comment by Damianu** [comment]
That's because we cant check permissions anymore if you leave.
