### ISSUE TITLE
What happend to net.canSend()? / owner() returning invalid entity?

### ISSUE THREAD

**Issue by McDunkinY** [thegrb93/StarfallEx#22]
As the title suggests, net.canSend() appears to be gone but there is still a burst limit present in the code. Also, owner() seems to be returning an invalid entity, or no entity at all.

**Comment by thegrb93** [comment]
canSend() became getBytesLeft() and I'll check whats with owner()

**Comment by McDunkinY** [comment]
To be more specific. The issue might be directly related to your recent net update.
When calling net.send( owner() ) it throws an error saying "Invalid player"

**Comment by thegrb93** [comment]
what does print(owner()) before the net.send do?

**Comment by thegrb93** [comment]
Never mind. easy fix.
