### ISSUE TITLE
Holograms do not get cleaned up properly after spawning a new chip.

### ISSUE THREAD

**Issue by RileyGuy** [thegrb93/StarfallEx#224]
If you have holograms spawned before reloading a chip they count towards the limit after you reload the chip and the chip immediately spawns holograms, thus causing the limit exceeded error to throw sometimes.

**Comment by Damianu** [comment]
Do you have latest version? I remember there were fixes for that issue.

**Comment by RileyGuy** [comment]
I was on DDDev so yes.

**Comment by thegrb93** [comment]
It's because this function doesn't get ran until the frame after the hologram is deleted. https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/libs_sv/holograms.lua#L58

**Comment by thegrb93** [comment]
It was partially fixed before, but not entirely
