### ISSUE TITLE
Clientside modifications of hologram

### ISSUE THREAD

**Issue by Damianu** [thegrb93/StarfallEx#227]
Source engine allows client to overwrite settings on  his side for entity, so what I am proposing is making hologram type shared(ofc for methods that can be shared). So for example we can do something like hologram.fromEntity(net.readEntity()) and then call setPos, setMaterial,setColor etc on it(I know you can now do it serverside for speciffic players, but whole point of it is making it able to do it clientside too). That way we can just create holograms serverside but each player will see different moidel, color, position etc. Doesnt seem like an abusive thing, it'll be still a serverside hologram, just with possibility to desynchronize.

**Comment by thegrb93** [comment]
Alternatively, make those functions clientside if we can get a system for clientside prop permissions.

**Comment by thegrb93** [comment]
Related to https://github.com/thegrb93/StarfallEx/issues/183
