### ISSUE TITLE
Right-clicking a chip to open the editor always opens a new tab, even when its code is already in the editor

### ISSUE THREAD

**Issue by mitterdoo** [thegrb93/StarfallEx#23]
the title basically explains itself. it would be very nice if right-clicking a chip (with the processor tool of course) checks if its code is already open in the editor. after a bit of changing little bits of code and checking it on a screen/HUD, the tabs start piling up.

**Comment by thegrb93** [comment]
Yeah. I can change it so it behaves like e2.
