### ISSUE TITLE
timer.stop() gets broken after timer.start()

### ISSUE THREAD

**Issue by Damianu** [thegrb93/StarfallEx#234]
Code used to test:

```lua
timer.create("test",0.25,0,function()
    print("I'm working")
end)
timer.stop("test")

timer.simple(1,function() 
    print("Starting")
    timer.start("test")
    timer.simple(1,function()
        print("Stopping")
        timer.stop("test")
    end)
 end)
```
Expected behaviour:
Timer starts printing "I am working" after "Starting" and stops after "Stopping"
Current behaviour:
Timer starts printing "I am working" after "Starting" but doesnt sotp after "Stopping"

**Comment by Damianu** [comment]
Update: It gets broken after stop
https://github.com/thegrb93/StarfallEx/blob/f5e438f1d63583ece7e48a988238a35463a041bb/lua/starfall/libs_sh/timer.lua#L125
For some reason timer.stop() is alias of timer.start(), while it shouldnt.

**Comment by thegrb93** [comment]
Probably best to get rid of stop() in favor of pause() since now stop's behavior has changed and anyone using it will be trying to figure out why their stuff doesn't work.
