### ISSUE TITLE
Split CheckType into a glua version and starfall version to increase performance.

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#236]
http://wiki.garrysmod.com/page/Global/TypeID

**Comment by thegrb93** [comment]
Nvm this is for glua types. However I do want to split the checktype into a glua and starfall version to increase performance.

**Comment by Damianu** [comment]
http://wiki.garrysmod.com/page/Enums/TYPE it contains lua types too tho

**Comment by thegrb93** [comment]
Okay, will perf it against type() then and see.
