### ISSUE TITLE
Base64 encoded images

### ISSUE THREAD

**Issue by Damianu** [thegrb93/StarfallEx#238]
We can allow users to load ulr textures in much safer way(it doesnt require connecting to any external server). It wouldnt need much work, just additional permission and modification of our getTextureID and getURLMaterial.
More info about base64 encoded images:
http://www.hongkiat.com/blog/css-encoded-image/

TLDR: With this, you are able to encode image into base64 string and send it to clients so they dont need to  load it from url, thats also faster.

**Comment by thegrb93** [comment]
How is that faster?

**Comment by Damianu** [comment]
No need of connecting to ANY http server, user provides string which  html already has, all awesomium has to do is decode and display.

**Comment by thegrb93** [comment]
yeah but if you want other players to see it, you'll have to use the net library which is much slower.

**Comment by Damianu** [comment]
Unless you send it within file of script, while being faster is really weak argument, best one is no http server, so no ip sniffing etc.
