### ISSUE TITLE
Textures should be per-player instead of being per-instance

### ISSUE THREAD

**Issue by Damianu** [thegrb93/StarfallEx#239]
Limits are per-player, so textures should be too, that'd allow sharing single material between starfalls just by remoteRun with texture's table, currently it wont work as textures are stored in instance's table. 

Meshes too.

**Comment by thegrb93** [comment]
Working on this and the material type now.

**Comment by thegrb93** [comment]
Now I am

**Comment by thegrb93** [comment]
https://github.com/thegrb93/StarfallEx/pull/428
