### ISSUE TITLE
Render.clear()

### ISSUE THREAD

**Issue by Aeomi** [thegrb93/StarfallEx#25]
The render library is lacking Render.clear(); a method I find vital in to fully taking control of my objectives when it comes to Starfall. At least 30% of the time, I don't clear my renderTarget before each draw. I see no reason to take this control away from the user, and would appreciate its integration into StarfallEx.

Thank you

**Comment by thegrb93** [comment]
render.drawRect(0,0,1024,1024)

**Comment by thegrb93** [comment]
render.clear would require me to put some code in to make sure a render target is selected.

**Comment by thegrb93** [comment]
I might be able to adapt the render.clear code to only work when a render target is selected.

**Comment by thegrb93** [comment]
kk.

**Comment by thegrb93** [comment]
I just force pushed a hotfix for something i missed. Make sure you have the latest version as of now.
