### ISSUE TITLE
Color() weird constructor

### ISSUE THREAD

**Issue by Damianu** [thegrb93/StarfallEx#251]
I think it should be more vector like, so:
Color() - 255,255,255
Color(5) 5,5,5
Color(255,0)  -  255,0,0

So basically only empty defaults to 255 rest goes to 0.
Single argument should be treated as r g and b at once, so you can create nice gray shades.
It'd be also consistient to Vector() constructor.

**Comment by thegrb93** [comment]
No, I'm not doing more function overloads. Make a helper function if you need that functionality. I shouldn't have done what I did to vector in the first place either.
