### ISSUE TITLE
Hologram networking race conditions.

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#252]
Don't know if it was a freak bug that occurred, but one of my holograms was at 0.5 scale spontaneously. Will investigate.

**Comment by szymski** [comment]
Also, sometimes holograms can get materials from holograms of other people, especially when you quickly spawn multiple chips.

**Comment by thegrb93** [comment]
Looks like its due to the hologram netcode using the net library. If a hologram has setScale called on it, gets deleted, and a new hologram is created with the same entindex, then the setScale message arrives, it'll set the scale of the new hologram.

**Comment by thegrb93** [comment]
It should be using DTVars

**Comment by thegrb93** [comment]
Okay just gotta check the netcode and see whats wrong. I'm not sure if this will be fixable.

**Comment by thegrb93** [comment]
Probably need to do what E2 does and use a queue

**Comment by thegrb93** [comment]
Can someone give me code to reproduce this bug?

**Comment by thegrb93** [comment]
I need an example to reproduce this too pls
