### ISSUE TITLE
Hologram scale not sent to client on join/snapshot?

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#253]
Need to test to be sure but seems to be the case.

**Comment by Damianu** [comment]
Well you mentioned DTVars in other issue, this one wouldnt be the case then too

**Comment by thegrb93** [comment]
Yeah looks like the material/scale/everything gets reset and doesn't resend.

**Comment by thegrb93** [comment]
I'll fix this tomorrow

**Comment by Damianu** [comment]
https://github.com/thegrb93/StarfallEx/commit/b8c9d9a9470b13bee16a5019899ef22dc7dcdb40

**Comment by thegrb93** [comment]
No fast way to tell when a DTVar is updated on clientside.
