### ISSUE TITLE
StarfallEx Server compatibility?

### ISSUE THREAD

**Issue by Aeomi** [thegrb93/StarfallEx#26]
I recently put up a dedicated server to use StarfallEx on, and have tried over the past two days to get it working. I have reinstalled numerous times when all else seemed to fail, but for whatever reason, StarfallEx will not work. Currently running a clean install with Wiremod and StarfallEx both cloned from github: Wiremod works, but starfall does not, there are no starfall tools, nor any starfall concommands, which lead to my assumption that starfallEx simply isn't being mounted, but it is, so I'm at a loss.

I assume this branch is compatible with dedicated servers (I see no reason why it wouldn't be, that is.) So my question is if you have any idea what the issue might be?

Thank you

**Comment by suunrider** [comment]
I assume you called the folder `StarfallEx`, just rename it to `starfall`.

**Comment by Aeomi** [comment]
I did that the first time I uploaded the addon, after checking addon.txt. Still didn't work, thanks anyway though.

**Comment by thegrb93** [comment]
Yeah, folder name doesn't matter as far as I know. See any starfall errors in lua_errors_server.txt?
