### ISSUE TITLE
add bass.loadurl/bass.loadFile to usergroup permission

### ISSUE THREAD

**Issue by Garrysman232** [thegrb93/StarfallEx#264]
It would be nice

**Comment by thegrb93** [comment]
Usergroup permisssions are serverside only. bass functions are clientside. Clients control who can play sounds rather than admins.

**Comment by Garrysman232** [comment]
but same person can abuse bass functions

**Comment by thegrb93** [comment]
I think per-person and per-chip permissions will be the solution. It's currently not possible to make it admin only.
