### ISSUE TITLE
Can't update holograms' properties twice at once.

### ISSUE THREAD

**Issue by szymski** [thegrb93/StarfallEx#268]
Take a look at the following code:
```Lua
h = holograms.create(chip():getPos(), Angle(), "models/hunter/blocks/cube025x025x025.mdl", Vector(1))
-- Some calculations for the new scale
h:setScale(Vector(1, 2, 3))
```
The scale, as the title says, won't be changed to <1,2,3>, but will stay <1,1,1>. This behaviour was intended (if I get it correctly) to reduce network bandwidth, yet as you can see, it is sometimes annoying.
What I'd do, is just throw [this line of code](https://github.com/thegrb93/StarfallEx/blob/b8c9d9a9470b13bee16a5019899ef22dc7dcdb40/lua/entities/starfall_hologram/init.lua#L20) and similiar ones out, but let's hear what other people think.

**Comment by Damianu** [comment]
I think we just should move them to DTVars first as they got their own in-engine optimisations
https://github.com/thegrb93/StarfallEx/issues/252

**Comment by thegrb93** [comment]
https://github.com/thegrb93/StarfallEx/issues/252
