### ISSUE TITLE
Variables (specifically, tables) don't get cleared from memory when your chip errors

### ISSUE THREAD

**Issue by SandvichDISH** [thegrb93/StarfallEx#27]
So imagine you're me: You decided to make your raytracer camera take pictures in two (three, really, but the third isn't too relevant) stages. 

Stage 1: trace
Stage 2: render

So you store _all_ your trace data for all your pixels inside a big 'ol table. You only start rendering once the entire scene has been traced, so you need to keep all that information at hand. You like taking 512x512 pictures of course, because they're pretty. 

But you're sadly not a particularly amazing coder, so you run into some errors during the process of taking a picture. Mostly CPU Quota related, but errors of all kinds are relevant. Now, your trace stage was already 75% done, and now your starfall chip has crashed. Oh well, tweak code and try again. Errors again, whoops. Errors again! Oh well. 

Ah, but all this time, Garry's Mod's memory usage has been piling up, because those big tables full of trace data are all stuck in memory limbo, rather than being cleared out every time the chip errors. 

hl2.exe has stopped responding! All the memory available to our poor 32 bit source engine has been used up! Goodbye Garry's Mod!

I've tried solving it using try() to clear out all those tables every time an error occurs, but CPU Quota exceeded errors seem to bypass all that.

Sorry for writing such a silly story, but I thought this should make the problem I'm encountering clear. Thanks for reading!

**Comment by thegrb93** [comment]
Lua handles all memory related things on its own and the chip sets errored instances to nil in order to mark them for cleanup so I can't really think of why this would occur. Can I try your code and see if I can pinpoint the leak?

**Comment by SandvichDISH** [comment]
Sure, http://pastebin.com/6uEQ1Arq

It's all a bit messy because I'm still figuring stuff out, but you should get the idea.

**Comment by thegrb93** [comment]
I'll test it soon. Got exams this week.

**Comment by suunrider** [comment]
The problem is that the `Out of memory` error is catchable. So you can easily bypass the (existing?) memory limit.

**Comment by thegrb93** [comment]
Ok I'm looking at it now

**Comment by thegrb93** [comment]
I think the traces are creating too much garbage. I went ahead and optimized the trace library so that garbage and cpu usage is vastly reduced. I also fixed a bug with the trace filter that I saw. I also edited your script so that it works. Looks amazing btw. http://pastebin.com/KzPRZngn [!http://i.imgur.com/E513Qre.jpg]

**Comment by thegrb93** [comment]
I'm still trying to pinpoint the leak. I'll let you know when I do so.

**Comment by thegrb93** [comment]
Btw you should move the matrix pushing and popping outside your draw function to increase rendering performance.

**Comment by SandvichDISH** [comment]
Thanks! I'll check things out and see!

**Comment by SandvichDISH** [comment]
What I can say is that my problem still persists. I take a single 512x512 picture and it uses up a nice whole gigabyte of ram (not sure why that's happening either, but let's assume it's because of my code being inefficient). Then when I delete the starfall chip (errors don't seem to have anything to do with it after all) the memory usage persists, it doesn't clear. Then when I try to take a second pic without reloading my game I'll run out of memory about halfway through. I can't find any way to clear all that data from memory other than disconnecting and restarting the singleplayer session.

The latest version of my camera is a lot more advanced and further developed, so here's the code if you want to test it: http://pastebin.com/MX3C2VXX

To get it to not cpu quota I usually make sure my sf_timebuffer is around 0.05 or so.

**Comment by its-suun** [comment]
Well, instead of crashing your game it should better crash the chip

**Comment by its-suun** [comment]
```lua
local a = "a"
hook.add("think", "", function()
  try(function()
     a = a .. a
  end, function() end)
end)
```
crashes the client. If `out of memory` is uncatchable it won't happen

**Comment by thegrb93** [comment]
I'll do that.

**Comment by thegrb93** [comment]
I think it causes an Engine Error anyway. Can't really prevent out of memory or else e2 would've done that by now. I'm still investigating memory leaks atm though.

**Comment by thegrb93** [comment]
If only there was a way to track allocations per lua file.

**Comment by its-suun** [comment]
How is ea2 doing that? It checks for memory limit too, assuming with debug library

**Comment by thegrb93** [comment]
I think it just reads the global lua allocation size. What I could do is measure the lua allocation size each time there are no chips and a single new one is created, and kill all chips if the lua allocation goes over a convar memory limit.

**Comment by thegrb93** [comment]
It's randomly not cleaning up. I think it might be due to something wrong with the co-routine.

**Comment by thegrb93** [comment]
I might have to remove the coroutine library if it can leak memory without any fix. I'll test it soon.

**Comment by edgarasf123** [comment]
Shit, I would probably would quit using starfall if you remove coroutines. I'm using coroutines everywhere. 

Regardless, you must exit the coroutine for garbage collector to do its stuff. So maybe make a wrapper function when using coroutine.create(), which would return nil when chip is terminated.

Here an example that makes huge tables, and if you remove before cpu max quota, it doesn't leave any memory leaks.
```
--@client
if CLIENT then
    local perf_limit = 0.9
    local function checkYield()
        if math.max( quotaUsed(), quotaAverage()) > quotaMax() * perf_limit then
            return coroutine.yield()
        end
    end

    coroutine_process = coroutine.create(function()
        local t = {}
        while true do
            if checkYield() then return nil end
            t[#t+1]=t
        end
    end)
    hook.add("think", "main", function() 
        if coroutine.status(coroutine_process) ~= "dead" then
            coroutine.resume(coroutine_process)
        end
    end)
    hook.add("Removed","remove", function()
        coroutine.resume(coroutine_process,true)
    end)
end
```

**Comment by edgarasf123** [comment]
http://hastebin.com/neropugoha.lua
![image](https://cloud.githubusercontent.com/assets/2304691/14468154/5aa940ae-0093-11e6-93e4-c60d0e7d0ce3.png)

**Comment by thegrb93** [comment]
Thanks, I think I can fix this now.

**Comment by edgarasf123** [comment]
I just noticed thread paramater doesn't even work, It acts the same as you would do `debug.sethook( kill_thread, "", 1 )`

So yeah, run the sethook with the check if its inside coroutine.

**Comment by thegrb93** [comment]
I'm just worried the coroutine will be able to reach the starfall's internal sethook before the kill hook gets called, in which case the kill hook won't get called. I doubt that can happen but I don't know the behavior of sethook very well so idk...

**Comment by thegrb93** [comment]
Still not freeing memory for some reason. Here's my attempt and console output. https://github.com/thegrb93/StarfallEx/commit/2e7ccdb9edd685aefa8b32b42d43bb36232a99ba

```
```

**Comment by edgarasf123** [comment]
Well, shit . I'm guessing the only way to cleanup coroutines is to actually complete the coroutine :(. Maybe garbagecollector doesn't want to clean it up because of the createCoroutine() hack used? As far as I read, garbagecollector should cleanup unfinished coroutines when all references are gone.

**Comment by thegrb93** [comment]
That's what I thought too. I'll try this program without the use of coroutines and see if it leaks still.

**Comment by thegrb93** [comment]
No leaks. I'll research coroutines a bit and see if I can find why.

I honestly don't see the need for them. I always just use this xD. I'll continue trying to fix them though.
```
local function doTasks()
    while (quotaAverage()<quotaMax()/2 and prop.canSpawn()) do
        quotaTasks[1]()
        table.remove(quotaTasks,1)
        if #quotaTasks==0 then
            hook.remove("Think","doTasks")
            break
        end
    end
end
function addTask(func)
    table.insert(quotaTasks, func)
    hook.add("Think","doTasks",doTasks)
end
```

**Comment by thegrb93** [comment]
I'm going to try using pure lua coroutines instead of SF coroutines and see what happens.

**Comment by thegrb93** [comment]
No issue with lua coroutines so maybe you're right about that hack.

**Comment by thegrb93** [comment]
-- Can't use coroutine.create, because of a bug that prevents halting the program when it exceeds quota

Do you know what this comment is talking about?

**Comment by thegrb93** [comment]
I cleared the table of wrapped coroutines and that seemed to release all of the memory. I guess coroutines have weird behavior with weak tables. Need to investigate further.

**Comment by thegrb93** [comment]
This is indeed the case. http://lua-users.org/lists/lua-l/2006-11/msg00351.html

Now my question is, why are coroutines being wrapped? Those are safe to use without being wrapped right?

**Comment by thegrb93** [comment]
So all I need to do is remove all references to the coroutine when the chip exits.

**Comment by thegrb93** [comment]
Alright I think it's fixed.

**Comment by thegrb93** [comment]
https://github.com/thegrb93/StarfallEx/commit/b7dd3af2b69b7a9c5bda2f4f957c0a201772209f
