### ISSUE TITLE
Permission checks take lots more CPU time.

### ISSUE THREAD

**Issue by RileyGuy** [thegrb93/StarfallEx#272]
Permission checks take a lot more cpu time than the function normally would, especially on meta construct but I've noticed this in my SP world to an extent. E.g. moving 10 holos at the same time yields 75% cpu time on meta. Less in my SP but more than it really should.

**Comment by thegrb93** [comment]
I've seen some performance issues reported from meta before. They seem to have some really expensive custom functions which aren't in my control. The solution to this is our own prop permission system which there's already an issue open for.
