### ISSUE TITLE
Hook inputPressed and inputReleased doesn't work

### ISSUE THREAD

**Issue by ElHyperion** [thegrb93/StarfallEx#28]
Despite the input hook working fine for me, I can't seem to get any response from inputPressed or inputReleased.

Example code:
```lua
if SERVER then
    
    wire.adjustInputs({"Input"}, {"normal"})
    
    hook.add("inputPressed", "Trigger", function(name)
        print("Pressed")
    end)

end
```

**Comment by suunrider** [comment]
They are clientside only.

**Comment by ElHyperion** [comment]
Looks like I accidentally mistaked that for wire inputs, my bad.
