### ISSUE TITLE
Render hooks do not pop extra matrices after callback returns

### ISSUE THREAD

**Issue by davidsonbr** [thegrb93/StarfallEx#291]
```
--@client

hook.add( "render", "abuse", function()
    render.pushViewMatrix( {type="3D", x=0, y=0, w=1920, h=1080, origin=Vector(0,0,0), angles = Angle(0,0,0), aspect=1} )
end )
```
[Not rendering](http://gallery.polydev.us/img/hl2_2017-08-22_13-19-39.jpg)
[Rendering](http://gallery.polydev.us/img/hl2_2017-08-22_13-19-56.jpg)

**Comment by Damianu** [comment]
Are you sure you are using updated starfall? Tested your code and works perfectly fine for me.

**Comment by davidsonbr** [comment]
Odd, I checked and was on up to date with master. But re-checking out the repo resolved the problem.
