### ISSUE TITLE
You have permissions on weapons

### ISSUE THREAD

**Issue by its-suun** [thegrb93/StarfallEx#294]
You can remove or ignite `gmod_tool`, `weapon_crowbar`, and other weapons. Not sure if this is a mistake of PP (using nadmod).

**Comment by thegrb93** [comment]
I'm using nadmod too and this hasn't been an issue, I'll test it though

**Comment by thegrb93** [comment]
Yeah, works for me.

**Comment by adosikas** [comment]
Note that this happens when using NPP ([Nadmod Prop Protection](https://facepunch.com/showthread.php?t=1221183)), and not when using Nadmod with a different PP addon like FPP.

**Comment by thegrb93** [comment]
You're using an outdated nadmod then.
