### ISSUE TITLE
Update documentations

### ISSUE THREAD

**Issue by OrIOg** [thegrb93/StarfallEx#298]
With the new functions like prop.createComponent, the doc/SFHelper is outdated.  And the syntax highlighting is the same :sob:

**Comment by Damianu** [comment]
We have to automate this process somehow.

**Comment by Damianu** [comment]
I think we should consider using Travis with https://github.com/siffiejoe/lua-travis so it will automatically execute doc builder.

**Comment by thegrb93** [comment]
It would need to run before committing so editor/docs.lua gets updated too.
Imo it's not bad. Newly added things are considered unstable anyway.
