### ISSUE TITLE
SF editor not working for non UK/US Keyboard layouts

### ISSUE THREAD

**Issue by suunrider** [thegrb93/StarfallEx#3]
Already fixed in INPStarfall (https://github.com/INPStarfall/Starfall/issues/344)

**Comment by thegrb93** [comment]
I agree the new editor is worse. I don't know why AltGr would trigger the editor to close since the logic to trigger that is,
```
input.IsKeyDown( KEY_LCONTROL ) or input.IsKeyDown( KEY_RCONTROL )
```
I'll look and see if there's a different way that won't conflict with altgr.

**Comment by thegrb93** [comment]
Are you using right-ctrl+right-alt to use altgr or an actual altgr key? If you're using alt+ctrl, I can make it so it won't trigger if alt is pushed. Let me know.

**Comment by suunrider** [comment]
I use the altgr key

**Comment by thegrb93** [comment]
I don't have an altgr key unfortunately so I can't test it, but can you try the altgr_fix branch and see if it works?

**Comment by thegrb93** [comment]
I'll try to emulate altgr later and try it myself, but have to go for now.

**Comment by suunrider** [comment]
I tested altgr_fix branch and it doesn't work

**Comment by thegrb93** [comment]
Damn. Well I'm back and I'll emulate altgr and see what I can do.

**Comment by thegrb93** [comment]
Can't get altgr emulation working.
Could you run this in your console while in game and tell me what it prints when you push and release altgr?
```
lua_run_cl hook.Add("Think","PrintKeys",function() print(input.IsKeyDown( KEY_LCONTROL ), input.IsKeyDown( KEY_RCONTROL ), input.IsKeyDown( KEY_RALT ), input.IsKeyDown( KEY_LALT ), input.IsControlDown() ) end)
```

**Comment by suunrider** [comment]
sorry, forgot about this
with altgr:
```lua
true	false	false	true	true
```
without:
```lua
false	false	false	false	false
```

**Comment by suunrider** [comment]
Isn't it possible to just remove the ace editor and get the wire texteditor back? Downloading the editor when you want to start programming in starfall isn't really ideal.
Being independent from wiremod is the most useless aim of development since wiremod takes really care of backwards compatibility (starfall is also only on servers which have wiremod). The texteditor also got refactored, so it should be less pain to bring the editor back.

**Comment by thegrb93** [comment]
Yeah we could. I really like the text coloring and autocomplete this edit has to offer, but it is burdensome and has some glitches. I want to try fixing this and updating the javascript and see if it's worth keeping otherwise I'll revert it.

I think alt-gr is fixed now. Let me know and I'll merge it.

**Comment by suunrider** [comment]
I can now type `@`. But I still can't type `}`. (altgr + 0)

**Comment by thegrb93** [comment]
I can't find any part of the code where =,0,} are influenced by LALT or LCTRL so maybe its a bug with gmod html panels, but can you try doing } while in a block of text and see if anything happens at all and maybe I can find out whats causing it.

**Comment by thegrb93** [comment]
Are you able to type } in other awesominium windows? I googled around and find that some embedded browsers have this issue and it wouldn't surprise me if gmod also had this issue. If that's the case then we'll just have to move the editor away from awesominium.

**Comment by suunrider** [comment]
Where are other awesomium windows?

**Comment by thegrb93** [comment]
I guess run this in console
```
HTMLTest = vgui.Create( "HTML" )
HTMLTest:SetPos( 50, 50 )
HTMLTest:SetSize( ScrW() - 100, ScrH() - 100 )
HTMLTest:OpenURL( "www.google.com" )
```

**Comment by suunrider** [comment]
Can't type in it

**Comment by thegrb93** [comment]
Ah, also do HTMLTest:MakePopup()

**Comment by suunrider** [comment]
I can type } in it, also @

**Comment by thegrb93** [comment]
It might be a problem with the ace editor then. I'll try updating it.
