### ISSUE TITLE
Single entity to filter from trace not working

### ISSUE THREAD

**Issue by ElHyperion** [thegrb93/StarfallEx#30]
The description of the trace.trace() function says that the filter argument permits both a single entity and an array of entities to filter, but using a single entity does not seem to work.

**Comment by thegrb93** [comment]
I think I fixed it last night. Try updating and let me know.

**Comment by ElHyperion** [comment]
My bad, I've tested it on a server that did not use the newest version yet. Just tried it in singleplayer and I can now confirm it works
