### ISSUE TITLE
Stuff to Add 5

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#305]
Large additions
- [x] Material type
- [x] Particle Emitter Type
- [ ] Effect Type
- [ ] Relay client errors to chip owner.
- [ ] Gui that lists chips+their usage and allows uploading/downloading
- [x] Prop permission management. Also clientside render property modification.
- [ ] RAM Limiter
- [ ] Clientside holograms
- [ ] Light Library

Quick additions
- [x] wire array type i/o
- [ ] Add wire eyepod functionality to hud.
- [ ] Add wire keyboard functionality to hud.
- [x] mesh.createFromObj thread option
- [ ] models list for hud entity.
- [ ] sounds.generate. Probably use same management as RTs
- [x] Ability to change render matrix of holograms
- [x] Make starfall tool R update all scripts of the chip with those in the editor.
- [ ] Hologram model allow any

**Comment by Damianu** [comment]
Some way of ignoring serverside model check would be nice(wire_holograms_allowany but for starfall).

**Comment by thegrb93** [comment]
The problem I have with that is gmod's material system takes a shit for clients that don't have the model/material. Once that issue is resolved then I can do that.

**Comment by Damianu** [comment]
Yeah, also hologram should have info about instance which created this hologram(available from clientside)

**Comment by thegrb93** [comment]
a DTVar with the starfall entity id

**Comment by GalaxyOfWaffles** [comment]
Entity:NearestPoint

**Comment by Codingale** [comment]
Can we get ` Relay client errors to chip owner.` soon? On a server with 24 people coding those get annoying figuring out which is yours and looking at other logs in console.

**Comment by OrIOg** [comment]
- Ability to view/block owner of sounds.
- Ability to view/block owner's starfalls.
Isn't that done with permission system ?
The problem with holograms, if we use the permissions system,
is that if someone blind you, it's hard to remove with perms by chip, or you need to edit global perms or even by the console

**Comment by Damianu** [comment]
There is planned UI for generally listing and managing everything remotely. Basically:
>Player X
>>Chips Y
>>>Holograms of Y
>>> Sounds of Y

Something like that, saddly I didnt have time to make it a feature yet.

**Comment by KotoNinja** [comment]
net.writeTable/net.readTable hmmm

**Comment by KotoNinja** [comment]
aaand particle lib pls
