### ISSUE TITLE
Support for addons

### ISSUE THREAD

**Issue by Damianu** [thegrb93/StarfallEx#308]
We should add some hooks and maybe functions allowing to add stuff more easily from other addons. So you can request such things here.

# Current Todo:
- [ ] Hook after editor is initialized

**Comment by its-suun** [comment]
What about a way to register an addon and a way to get installed starfall addons in starfall?

**Comment by Damianu** [comment]
I personally think that extension system wouldn't be bad idea.

**Comment by thegrb93** [comment]
Starfall searches and runs files in starfall/libs_* . Any addon can already use that.

**Comment by thegrb93** [comment]
And they can add a postload starfall hook inside those files.

**Comment by Damianu** [comment]
That's right, totally missed that. I'll leave editor one on todo tho.
