### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by its-suun** [thegrb93/StarfallEx#31]
:warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning:
`:getEyeTrace().Entity` returns an unwrapped entity.
:warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning:

Credits:  Forsaken

**Comment by thegrb93** [comment]
I don't see how since it is using the SF.Sanitize function. Anyway, I'll switch it to my trace return improvement for performance reasons.

**Comment by thegrb93** [comment]
I'll test Sanitize and make sure its working properly.

**Comment by thegrb93** [comment]
Fixed Sanitize.

**Comment by thegrb93** [comment]
As soon as github feels like updating.

**Comment by thegrb93** [comment]
Github isn't updating so wait for it to display the commit from April 5 and it will be fixed.
