### ISSUE TITLE
Adding file type support to editor

### ISSUE THREAD

**Issue by Damianu** [thegrb93/StarfallEx#310]
So I thought about separating file types in editor and coloring them by extension, that'd require onetime script converting all scripts from .txt to .lua.
That'd allow having ability to add json coloring etc.
What do you think, yay or nay?

**Comment by Damianu** [comment]
I am not sure if glua allows writing to .lua tho. Gotta check that when I get back home.

**Comment by Damianu** [comment]
We can also workaroud that by doing something like myscript.lua.txt for non-whitelisted types.

**Comment by its-suun** [comment]
you cant write .lua, there is a whitelist of allowed file extensions

**Comment by its-suun** [comment]
also what else would you highlight besides json? I don't think its worth the effort

**Comment by Damianu** [comment]
Yeah, I've figured out how to make it much simpler to implement and dont mess with hacking.
