### ISSUE TITLE
Several Issues

### ISSUE THREAD

**Issue by edgarasf123** [thegrb93/StarfallEx#32]
**LUA:**

* When client StarFall errors, it displays glua error:
`cl_init.lua:71: attempt to index field 'instance' (a nil value)` 
```
SF:test/demo.txt:4: attempt to perform arithmetic on global 'derp' (a nil value)
SF:test/demo.txt:4: attempt to perform arithmetic on global 'derp' (a nil value)
stack traceback:
	SF:test/demo.txt:4: in function 'func'
	addons/starfallex/lua/starfall/instance.lua:38: in function <addons/starfallex/lua/starfall/instance.lua:37>
	[C]: in function 'xpcall'
	addons/starfallex/lua/starfall/instance.lua:71: in function 'runWithOps'
	addons/starfallex/lua/starfall/instance.lua:133: in function 'initialize'
	addons/starfallex/lua/entities/starfall_processor/cl_init.lua:68: in function 'CodeSent'
	addons/starfallex/lua/entities/starfall_processor/cl_init.lua:92: in function 'func'
	lua/includes/extensions/net.lua:32: in function <lua/includes/extensions/net.lua:17>

[ERROR] addons/starfallex/lua/entities/starfall_processor/cl_init.lua:71: attempt to index field 'instance' (a nil value)
  1. CodeSent - addons/starfallex/lua/entities/starfall_processor/cl_init.lua:71
   2. func - addons/starfallex/lua/entities/starfall_processor/cl_init.lua:92
    3. unknown - lua/includes/extensions/net.lua:32
```
* Hard to reproduce, but sometimes clientside starfall throws errors with weird symbols like `?*'/'.` or something similar. And when you do get it, its hard to fix it. Also when you right click on the errored chip, it opens additional file with those weird symbols as the name and inside the file itself(~8 characters long). I suspect it only appears when you're working with additional files. 
I know some people have experienced same errors too, I would appreciate if someone would add more details.
* The tooltip(which shows cpu quota) doesn't always appear. 

**File Browser**
* Missing reload/update button in file browser (in q-menu).
* Missing "delete folder" feature
* Renaming files inside folders, moves renamed files to root directory.

**Comment by thegrb93** [comment]
I'll take a look at all these once I get home. "The tooltip(which shows cpu quota) doesn't always appear." I think this is a gmod bug. Same thing happens with thrusters and other entities because the ENT:BeingLookedAtByLocalPlayer() is returning false. I think it only happens in singleplayer or listen server, but I'll report that.

**Comment by edgarasf123** [comment]
I couldn't see tooltips on dedicated servers too.

**Comment by thegrb93** [comment]
Devs say it's fixed in the dev branch.

**Comment by thegrb93** [comment]
Finished it all except " clientside starfall throws errors with weird symbols like ?*'/'. or something similar". Can I see the code that is sometimes causing this? I'm suspecting the starfall file transfer library of causing this since it's seemingly random, but idk since I've never seen it before.

**Comment by thegrb93** [comment]
Let me know if it happens again and I'll try to fix it.
