### ISSUE TITLE
Fix GetName to return a Empty string instead of error

### ISSUE THREAD

**Issue by Codingale** [thegrb93/StarfallEx#324]
In DarkRP the GetName function when called on a NULL player (due to LocalPlayer() returning NULL for  awhile) can cause a pop-up about the error for 120 seconds which is annoying.

I'm not sure if you'd want a special validation check for this, or if all of the functions should have something similar; though only DarkRP throws the error if I recall.. not sure.

https://github.com/FPtje/DarkRP/commit/77881a2191cfdea53465e5bcc1b856f7ed962bb7#commitcomment-25499347

**Comment by Damianu** [comment]
Can you at least provide said error? LocalPlayer() always returns null before entities get initialized, but that would cause error on all gamemodes. Starfall shouldnt call it that soon.
Unless you meant to create that issue for DarkRP, which would be kinda hilarious.

**Comment by Codingale** [comment]
Eh, it requires me to have people on the server with a Starfall down to log connections if I recall. Falco insisted he wasn't going to remove his simpleerr (see linked comment from above) 

Here's what check he does, I've asked everyone who writes a Starfall to actually add in checks for NULL and also hasPermission but they never do and new people keep joining. https://github.com/FPtje/DarkRP/blob/353dc3286092cdb2efade2cc0f2145db5a6c2e69/gamemode/modules/base/sh_entityvars.lua#L105

**Comment by thegrb93** [comment]
Looks like we just need to add `if not IsValid(ent) then SF.Throw("Invalid Player!", 2) end` to everything in player.lua

**Comment by Damianu** [comment]
I mean... we really shouldnt. As soon as entity is returned we have right to get name from it(and if its returned but not initialized its actually normal thing to do).  That's gmod standard. However I think we may just use some custom function to get name and replace it only for darkrp? (As it seems they did that bullshit only to fake names)

**Comment by Damianu** [comment]
As for your server I suggest adding simple lua script with this code:
```
local pmeta = FindMetaTable("Player")
function pmeta:Name()
    if not self:IsValid() then return "" end
    return GAMEMODE.Config.allowrpnames and self:getDarkRPVar("rpname")
        or self:SteamName()
end
```
Which shouldnt break anything as names will be right after initialization.

**Comment by Codingale** [comment]
The issue is it's called during initialization, when LocalPlayer() returns NULL

**Comment by Damianu** [comment]
It does not, LocalPlayer() can return nil or entity, in your case it occurs when it returns unitialized entity, which already has name etc but few functions wont work. Otherwise it wouldnt have Name() method at all and would break in all gamemodes.

**Comment by Codingale** [comment]
Whatever the cause, it's quite annoying and I'd rather not slap a hack on top of it to fix it for the mean time.

**Comment by Damianu** [comment]
Also instead of doing IsValid trickery we may actually make starfall wait till all entities are initialized before running clientside instead.

**Comment by Damianu** [comment]
I mean suppressing all clientside from starfall befor this hook got called: 
http://wiki.garrysmod.com/page/GM/InitPostEntity
That wouldn't even be that hard as its sure they got initialized after 1 tick (timer.Simple(0,...)) so we dont even have to queue them.

**Comment by thegrb93** [comment]
Clientside doesn't get ran anyway until the server receives the client's request and the client receives the code (many frames afterward). IsValid isn't trickery, it should be used anyway to prevent glua errors when calling those functions on disconnected players.

**Comment by Damianu** [comment]
Right, I assumed it would be that as he said there have to be players using SF to cause that error(which would mean SF core itself doesnt cause it). My bad.

**Comment by Codingale** [comment]
https://github.com/thegrb93/StarfallEx/commit/e0269d2e65aaec21d1cde939cc24ec0619d885f5#diff-34a8f88911ec8122772e3e358b57a6b7R212
Works for me
 :+1:
