### ISSUE TITLE
Make render properties of entity available from clientside

### ISSUE THREAD

**Issue by Damianu** [thegrb93/StarfallEx#327]
https://github.com/thegrb93/StarfallEx/blob/ac4944e0108a5676ebc73d1bd8767fbc01a5ccd0/lua/starfall/libs_sh/entities.lua#L112
Basically all that should be also available from clientside, we can already alter position of hologram, but changing it's color still requires doing it serverside.

**Comment by thegrb93** [comment]
Need clientside prop protection first

**Comment by thegrb93** [comment]
Just remembered this is already in stuff to add. I think I'll work on prop protection as soon as finals are over.
