### ISSUE TITLE
[PhysObj] Error : Tried to use a NULL physics object !

### ISSUE THREAD

**Issue by OrIOg** [thegrb93/StarfallEx#342]
I was trying to use the function "getMeshConvexes()" with a prop(models/props_c17/door01_left.mdl).
When I figured out that I couldn't get the physicsObject of any props. It's returning me something, but every time I try to use the function(from PhyscObj) it's returning me this error.
At this point I think the problem is from somewhere in the source code but don't know where :/

**Comment by thegrb93** [comment]
Can you put your code?

**Comment by OrIOg** [comment]
```
--@name
--@author
--@client

local door = find.byModel("models/props_c17/door01_left.mdl", function(ent) return ent:getOwner()==owner() end)[1]
print(door)
local phys = door:getPhysicsObject()
print(phys)
local msh = phys:getMeshConvexes()
printTable(msh)
```

**Comment by CornerPin** [comment]
This is because you are running it clientside. Physics objects can exist here, but always invalid.

**Comment by OrIOg** [comment]
So If I want to get the mesh I need to pass by the server ?
