### ISSUE TITLE
Permissions working but not showing in editor

### ISSUE THREAD

**Issue by OrIOg** [thegrb93/StarfallEx#343]
The permissions are working fine, but each time I reopen the menu and go in the tab permission they are all off. I know it's just a graphical issue but that's quite annoying.

**Comment by Damianu** [comment]
Do you have any errors?
Also does same apply for rightclick chip in context mode > starfallex > open global permissions ?

**Comment by OrIOg** [comment]
No error :/ And yes it's same with "open global permissions"

**Comment by Damianu** [comment]
Are you sure you are using latest starfall version? I cant reproduce that.

**Comment by Damianu** [comment]
Oh, it happens only for clientside permissions.

**Comment by Damianu** [comment]
@thegrb93 lua_run_cl PrintTable(SF.Permissions.providers["client"]) seems to miss "settings" where previously permissions were stored. Where are they now?

**Comment by Damianu** [comment]
It's fixed, however I am not sure if clientside providers lacking settings table was intended so I'll leave this open for now.

**Comment by thegrb93** [comment]
its in SF.Permissions.privileges.<privilage>[3].settings

**Comment by Damianu** [comment]
Already found that and made UI look for those instead, if this was planned we may close it then.

**Comment by thegrb93** [comment]
ok good. thx
