### ISSUE TITLE
We need Influence Cost for privileges

### ISSUE THREAD

**Issue by vintprox** [thegrb93/StarfallEx#346]
There is one usability problem that is noted in #345. It's associated with privileges that can lead to any sort of trolling, such as "concmd". An ordinary player simply ignores a lot of stuff when it's regular (as check-checkboxes-to-grant-permissions game). That's why we need a way to notify him about suspiciously **strong** privileges requested.
It must work like Innocence Counter™ (😀): as many features SF processor wants it being less allowed. Also about notifications: there should be specific balloons with text about certain permissions (most known facts) that pop up before applying overrides.

**Comment by thegrb93** [comment]
Not sure this feature is necessary, but doesn't seem like anyone wants to code regardless.
