### ISSUE TITLE
bass.loadURL with '3d' flag returns nil channel

### ISSUE THREAD

**Issue by ThatOneCheetah** [thegrb93/StarfallEx#35]
```
local sound = nil
bass.loadURL( "-snip-.ogg", "noblock noplay 3d", function( chan )
    sound = chan
    sound:play()
end )
```

causes

```
SF:Super Starfall.txt:44: attempt to index upvalue 'sound' (a nil value)
stack traceback:
	SF:Super Starfall.txt:44: in function 'func'
	addons/starfallex/lua/starfall/instance.lua:38: in function <addons/starfallex/lua/starfall/instance.lua:37>
	[C]: in function 'xpcall'
	addons/starfallex/lua/starfall/instance.lua:71: in function 'runWithOps'
	addons/starfallex/lua/starfall/instance.lua:251: in function 'runFunction'
	addons/starfallex/lua/starfall/libs_cl/bass.lua:89: in function <addons/starfallex/lua/starfall/libs_cl/bass.lua:87>
```

**EDIT:** Adding an `isValid( chan )` check [as described in the Garry's Mod Wiki](https://wiki.garrysmod.com/page/sound/PlayURL) prevents the error, but the channel is invalid/nil nonetheless.

**Comment by thegrb93** [comment]
This happens if bass encounters an error with the sound. Try printing the error code and string.
```
local sound = nil
bass.loadURL( "-snip-.ogg", "noblock noplay 3d", function( chan, code, errstring )
    print( code, errstring )
end )
```

**Comment by ThatOneCheetah** [comment]
> This happens if bass encounters an error with the sound. Try printing the error code and string.

I added the line: `print( code .. " error: " .. err )`;
which returned: `-1 error: BASS_ERROR_UNKNOWN`

**Comment by thegrb93** [comment]
Yeah.. bass is very crappy in its current version. Try converting the sound to an mp3.

**Comment by thegrb93** [comment]
Closing since its a gmod issue.
