### ISSUE TITLE
HTTP library isn't supporting headers

### ISSUE THREAD

**Issue by Damianu** [thegrb93/StarfallEx#351]
According to wiki, both http.get and http.fetch allow headers table to be passed for website.
http://wiki.garrysmod.com/page/http/Fetch
We should probbably allow starfall set those? At least I dont know any security risks it may cause.
Not really sure about usages except than faking user-agent or referer either.

**Comment by CornerPin** [comment]
Some web APIs may require additional headers. Discord, for example, requires _Authorization_ header, which contains bot token. Another usage may be cookies, as they're stored in headers.

**Comment by vintproykt** [comment]
Contrary, there is no real need for pretty secure requests from SF.

**Comment by thegrb93** [comment]
I don't know of any issues it would cause.
