### ISSUE TITLE
Enable changing of particle colors.

### ISSUE THREAD

**Issue by HelixCT** [thegrb93/StarfallEx#352]
Add http://wiki.garrysmod.com/page/CLuaParticle/SetColor to StarfallEX

**Comment by Fozie123** [comment]
Yeah fucking hell.

**Comment by Fozie123** [comment]
Add in Particle:SetColor() Plz Senpi <3

**Comment by Drusketh** [comment]
I, Drusketh, will attempt to fix this

**Comment by HelixCT** [comment]
Thank you

**Comment by thegrb93** [comment]
The current library creates ParticleEffects. Not CLuaParticles.

**Comment by HelixCT** [comment]
Would there be a way to change the color or ParticleEffects any other way?

**Comment by thegrb93** [comment]
I don't think so.

**Comment by Codingale** [comment]
Out of curiosity, is there a reason why other than we'd have to trust users to destroy the emitters when done?

**Comment by thegrb93** [comment]
You don't need to trust the user to destroy the emitter. It's just that no one has implemented a CLuaParticle library.

**Comment by Codingale** [comment]
[ParticleEmitter](http://wiki.garrysmod.com/page/Global/ParticleEmitter) the wiki page seems to claim you need to, at least I thought.

**Comment by thegrb93** [comment]
Yeah, but what I'm saying is starfall can take care of that internally.
