### ISSUE TITLE
Color Memory Leak(-ish)

### ISSUE THREAD

**Issue by edgarasf123** [thegrb93/StarfallEx#36]
I noticed if you use Color() frequently, the garbage collector doesn't always clean it up when all the references are gone. 
```
--@name mem_leak_test
--@author 
--@client 
if player() ~= owner() then return end
hook.add("think","mem_test",function()
    for i=1, 3000 do
        c = Color(0,0,0) -- {0,0,0}
    end
end)
```
Here a made a demo, showing memory usage when using Color versus normal tables.
https://dl.dropboxusercontent.com/u/8081284/ShareX/2016/04/2016-04-24_12-58-48.mp4

**Comment by thegrb93** [comment]
I'll look at it soon. Exams are closing in in the next few weeks.

**Comment by ThatOneCheetah** [comment]
I think using tables internally instead of colors could resolve this issue and perhaps speed up performance, I'm working on a possible implementation as you'd be busy with exams (do not base anything off of my fork as of yet, I am still reading in to how Starfall works with wrapping and such).

**Comment by ThatOneCheetah** [comment]
[This](https://github.com/ThatOneCheetah/StarfallEx/commit/52d1ee23565e37987685ffce5da5c44b23c37004) implementation uses tables internally and unwraps to Color structs, this seems to have fixed the memory leak *(? please confirm)* and improves performance regarding Color creation/operations.  
  
I have performed this test:
```
if SERVER then return end

local curtime   = timer.curtime

local take_tests = 16
local test       = 1

local stop_t = curtime() + 1
local amt    = 0

local total  = 0

print( "\\/\\/ NEW COLOR TYPE \\/\\/" )

hook.add( "tick", "test", function()
    while quotaUsed()*64 < quotaMax() and stop_t > curtime() do
        c   = Color( 255, 255, 255, 127 )
        amt = amt + 1
    end
    
    if stop_t < curtime() then
        if test < take_tests then
            test = test + 1
            total = total + amt
            amt = 0
            stop_t = curtime() + 1
        else
            hook.remove( "tick", "test" )
            print( "Managed to create ", total, " objects" )
            print( "With an average of ", math.round(total/take_tests,1), " per test, of which there were ", take_tests )
        end

    end
end )
```
  
of which the results were:

```
\/\/ OLD COLOR TYPE \/\/
Managed to create 	97707	 objects
With an average of 	6106.7	 per test, of which there were 	16

\/\/ NEW COLOR TYPE \/\/
Managed to create 	166699	 objects
With an average of 	10418.7	 per test, of which there were 	16
```
