### ISSUE TITLE
Particle metatable broke

### ISSUE THREAD

**Issue by GalaxyOfWaffles** [thegrb93/StarfallEx#360]
```lua
p=particle.attach(ent,"test_lighting",1,{})
p:destroy()
```
attempt to call method 'destroy' (a nil value)

**Comment by Urumasi** [comment]
Seems that the destroy method isn't available, it's commented out here
https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/libs_cl/particle.lua#L157

**Comment by thegrb93** [comment]
Yeah, it crashes the game I think
