### ISSUE TITLE
constraint.getTable permissions shouldn't be required

### ISSUE THREAD

**Issue by GalaxyOfWaffles** [thegrb93/StarfallEx#362]
https://github.com/thegrb93/StarfallEx/blob/6594eeea4d416c47e89f569459d10fd670b3834f/lua/starfall/libs_sv/constraint.lua#L377
It only returns things, it does not physically affect anything.

**Comment by thegrb93** [comment]
Some servers might not want you to have access to the constraint entities.

**Comment by GalaxyOfWaffles** [comment]
what why
E2 has it: `Array=entity:getConstraints()`

**Comment by RileyGuy** [comment]
@thegrb93 He does not mean the constraint entities, he means the *constrained* entities.

**Comment by RileyGuy** [comment]
@thegrb93 He does not mean the constraint entities, he means the constrained entities. Not to mention that starfall already has this functionality with constraint.getTable(ent).

**Comment by RileyGuy** [comment]
@thegrb93 He does not mean the constraint entities, he means the *constrained* entities. Not to mention that starfall already has this functionality with constraint.getTable(ent).

**Comment by thegrb93** [comment]
I think you're missing my point. The constraint entity is also returned by constraint.getTable. Idk what you'd be able to do with it so I guess it might be okay to allow it.
