### ISSUE TITLE
Found a hud component bug

### ISSUE THREAD

**Issue by Consoli0** [thegrb93/StarfallEx#363]
When you try to Terminate or Restart Clientside on a SF HUD component it errors in console and pushes a script error into the upper right corner of my screen.

[ERROR] addons/starfallex-master/lua/entities/starfall_hud/cl_init.lua:95: attempt to call method 'ChatPrint' (a nil value)
  1. Function - addons/starfallex-master/lua/entities/starfall_hud/cl_init.lua:95
   2. fn - lua/includes/extensions/entity.lua:134
    3. unknown - addons/ulib-v2_63/lua/ulib/shared/hook.lua:109

**Comment by thegrb93** [comment]
I've seen this error when you disconnect from singleplayer or host of listen server, but the way you're describing the bug and the stack trace doesn't make any sense. I can fix those cases I mentioned in a while.
