### ISSUE TITLE
Tilde key toggles developer console when trying to create '~'.

### ISSUE THREAD

**Issue by ThatOneCheetah** [thegrb93/StarfallEx#37]
As the title describes. (When holding either SHIFT button)
Also, if the the tilde key is a modifier (e.g. Dutch layout, French layout, etc.) it's impossible to create '~' without copy&paste.

**Comment by its-suun** [comment]
Can't be fixed by StarfallEx.
See https://github.com/Facepunch/garrysmod-issues/issues/1941

**Comment by thegrb93** [comment]
Yeah, it's better just to use != until this can be fixed.

**Comment by ThatOneCheetah** [comment]
I've figured out a little trick (not sure if Windows specific):
  
- Press **CTRL+LShift** (this should disable modifiers)
- Try to make **~** (*Shift+Tilde*), the console should still popup but a(n) **~** should appear
- Close console with **ESC**

Tested on `English United States`/`United States International` layouts.

**Comment by thegrb93** [comment]
Closing this in favor of the new editor issue.
