### ISSUE TITLE
Searching textbox - reloadTree

### ISSUE THREAD

**Issue by OrIOg** [thegrb93/StarfallEx#380]
[ERROR] addons/wire_starfall/lua/starfall/editor/sfderma.lua:420: attempt to call method 'reloadTree' (a nil value)   
1. OnChange - addons/wire_starfall/lua/starfall/editor/sfderma.lua:420   
2. unknown - lua/vgui/dtextentry.lua:206

When you clear your search box, this bug come out.
Looked at sfderma, and the function got a capitalized R -> 'ReloadTree' not 'reloadTree'

**Comment by Damianu** [comment]
You are probbably using an outdated version, try updating and let us know if it still occurs.

**Comment by OrIOg** [comment]
Solved, thanks you :+1:
