### ISSUE TITLE
Add "findMetaTable" function

### ISSUE THREAD

**Issue by CaptainPRICE** [thegrb93/StarfallEx#385]
- [ ] Implement an isolated [`FindMetaTable`](https://wiki.garrysmod.com/page/Global/FindMetaTable) function, but for types that are exposed by Starfall (a couple of them):
  - Angle (`_G.Angle`)
  - Vector (`_G.Vector`)
  - File (`file.Open`)
  - Entity (`_G.entity`)
  - PhysObj (`ents_methods.getPhysicsObject`)
  - Player [inherits from Entity]
  - Vehicle [inherits from Entity]
  - Weapon [inherits from Entity]

**Comment by Damianu** [comment]
There is a good reason you cant get metatable of builtin type in starfall, it'd be a serious security risk.
Something like extendClass(builtintype, method) would be better IMO as there is no other reason to want those metatables that wouldnt impose security risk.

**Comment by CaptainPRICE** [comment]
I do not want to expose metatables... I had said 'isolated' (read it more carefully).

**Comment by thegrb93** [comment]
I'm in support of having control over the methods table. This means each instance will need its own copy of types, checktypes, and wrappers (which is also good because I think conflicts can occur between instances currently). E.g. set ent1.MyVariable = 5 in an instance, read ent1.MyVariable in another instance.

**Comment by thegrb93** [comment]
Might be a heavy perf hit though since none of the wrappers will be localized anymore

**Comment by KubeRoot** [comment]
This would also theoretically require rewrapping anything that's passed between instances, particularly with `hook.runRemote`.

However, there is the issue of passing tables between instances - currently, one should be able to share a table with other instances and communicate by writing/accessing fields in that table. However, if each instance is meant to have isolated SF type metatables, the table would have to be replaced with an accessor that rewraps on the go.

**Comment by thegrb93** [comment]
I've found a way to do it without changing wrappers, however @KubeRoot is right. Won't be able to share tables between instances.

**Comment by thegrb93** [comment]
The only thing making this not work is the fact that I need the metatable of the type to __index the instance's methods table which is different for each instance. I would have to make __index a function and I don't know if the performance hit will be worth it.

**Comment by thegrb93** [comment]
The only benefit is being able to modify type's methods, but we're getting a lot more downsides so I don't think it'll be worth it unless and entirely new solution is found.

**Comment by Damianu** [comment]
you can stack __index, what this means that if instance has copy of methods in sometab, and that sometab has metatable with __index it'll be only used if index is already not present - as in you can add new methods but you cant remove/edit old ones
