### ISSUE TITLE
Introduce a client-side entity (CSEnt); hologram alternative/replacement

### ISSUE THREAD

**Issue by CaptainPRICE** [thegrb93/StarfallEx#386]
I think this should have been a thing from a long time ago, but nobody seems to really realize it.
I'd like to propose (sort of) a major alternative/replacement for holograms. This change would improve server-side performance (a couple of notes):
- CSEnt does not have a valid physics object (a hologram does not ever need one),
- CSEnt is functional on client-side only,
- Smaller entity list on the server-side.

This change would also make "any-model hologram" come true (see also #305).

As much as awesome improvement this would be for both client-side & server-side, there is one downside about it (which comes down to networking). In order to create/manipulate a CSEnt, server would only need to broadcast information to client (a player who opt-in to see certain CSEnts owned by another player; will have to introduce a "permission system" to allow clients to control of this). Implementation would have to be network-wise with respect to "permission system".

P.S. I have just noticed there actually is an existing issue (#48), however it had been closed off (with no links to follow/continue on).

**Comment by thegrb93** [comment]
Can be a default disabled CS permission.

**Comment by CaptainPRICE** [comment]
> Can be a default disabled CS permission

I'd prefer a default (function usage) permission to be "Owner only".

> Added to stuff to add.

Currently there are [no projects](https://github.com/thegrb93/StarfallEx/projects), [no milestones](https://github.com/thegrb93/StarfallEx/milestones), and I was unable to find an issue where you have listed this. No labels have been assigned to either #48 or this issue.
I must admit, it is very awkward how you use GitHub (once again, you have provided no links to follow/continue on). Shouldn't this issue be closed **after** CSEnt is implemented?

Anyways, this change would have to introduce a new "permission system" to allow clients to block certain player's CSEnts (and be network-wise, that is, a client should not receive net messages for any CSEnt owned by a blocked player).

**Comment by thegrb93** [comment]
Stuff to add is any new stuff to add. Not hard. We already have a clientside permission system
