### ISSUE TITLE
Manually marking co-routines for garbage collection (nillifying) results in the exact opposite.

### ISSUE THREAD

**Issue by ThatOneCheetah** [thegrb93/StarfallEx#39]
**~EDIT~**  
The actual issue seemed to be me attempting to manually dispose of a coroutine by doing `thread = nil` (I am new to coroutines and was not aware that this is not required), however, this seems to do the exact opposite.

I presume this prevents the behind-the-scenes checking of coroutines to mark the coroutine for garbage collection, as there is nothing to mark, because it is `nil`.
```
if SERVER then return end

local status = coroutine.status
function coroutine_yielded(c)return(status(c)~="running" and status(c)~="dead")end

local sound = {}

local co = coroutine.create( function()
        for i=1,4096 do
            bass.loadFile( "sound/synth/sine_440.wav", "3d noblock noplay", function( chan )
                if not chan then return end
                
                chan:play()
                chan:setVolume( 0 )
                sound[#sound+1] = chan
            end )
            
            if quotaUsed()*2 > quotaMax() then coroutine.yield() end
        end
        
        return true
end)

hook.add("think", "co-keepalive", function()
    if coroutine_yielded( co ) and quotaUsed()*2.10 < quotaMax() then
        local r = coroutine.resume( co )
        if r then co = nil end
    end
end)
```

**EDIT:** The above code seems to not accurately recreate the issue, I'm looking in to the reason.

**NOTE:** The above seems to only happen from time-to-time inside of coroutines; but recreating this result reliably proves to be difficult.

**EDIT:** Actual issue found, title changed, old content available *below*:

> I have discovered that loading many streams using `bass.loadFile` (as I do in my [midi parser](http://www.youtube.com/watch?v=RoDOI-cAZKE)) then deleting/refreshing the chip doesn't always call the `stop` method on the bass classes and dispose of them properly.  
  
> I don't have the exact code to replicate such thing but  
> ```
local sound = {}
for i=1,256 do
    bass.loadFile( "sounds/synth/sine_440.wav", "3d noblock noplay", function( chan )
        chan:play()
        chan:setVolume( 0 )
        sound[i] = chan
    end )
end
```
> should suffice to recreate the issue.  
> I'm not sure whether this is also the case with `bass.loadURL`, however, I do presume so.

**Comment by thegrb93** [comment]
How's your example not erroring? You're setting co to nil and then next tick passing it to the status function.

**Comment by ThatOneCheetah** [comment]
My example **is** errorimg but the coroutine and references created inside aren't being marked for gabage collection.

**Comment by thegrb93** [comment]
Okay just checking. Idk, I'll look at it soon.

**Comment by thegrb93** [comment]
I just tried this script and didn't see any leak. Is this related to the same lua anomaly we were discussing earlier?
