### ISSUE TITLE
[Bug] Starfall can not read its own outputs (a value is always nil)

### ISSUE THREAD

**Issue by CaptainPRICE** [thegrb93/StarfallEx#399]
I have come across a strange bug at Starfall (while playing on DaDam's server this morning; not sure if it is running the most recent version of StarfallEx - but I'd assume it does).

The following example Starfall script can be used to reproduce this issue:
```lua
--@server

wire.adjustOutputs({ "Out" }, { "string" })

timer.simple(1.0, function()
    wire.ports.Out = "What The Fuck!"
    timer.simple(1.0, function()
        print("wire.ports.Out:", wire.ports.Out)
    end)
end)
```

The problem is that, Starfall chip itself fails to **read** an output. An output is created and the value is being set (confirmed with Wire Debugger). But, whenever it tries to read an output back, it returns a nil value.
I have also tried using a `wire` library; using a `wire.self()["Out"]` returned a nil value as well.
As seen above, I have even added timers (I thought it was somehow delayed), but regardless of those attempts, it still does not work.

So, the question is, how come this not work?

**Comment by CornerPin** [comment]
`wire.ports` is read-only for inputs and write-only for outputs. You should use the wirelink of the chip or connect it to itself:
```lua
--@server

wire.adjustOutputs({ "Out" }, { "string" })
local wl = wire.getWirelink(chip())

timer.simple(1.0, function()
    wire.ports.Out = "What The Fuck!"
    timer.simple(1.0, function()
        print("wire.ports.Out:", wl.Out)
    end)
end)
```
or
```lua
--@server

wire.adjustOutputs({ "Out" }, { "string" })
wire.adjustInputs({ "In" }, { "string" })
wire.create(chip(), chip(), "In", "Out")

timer.simple(1.0, function()
    wire.ports.Out = "What The Fuck!"
    timer.simple(1.0, function()
        print("wire.ports.Out:", wire.ports.In)
    end)
end)
```

**Comment by CaptainPRICE** [comment]
@CornerPin Thanks for your explanation, and (workaround) example codes.

I thought about using such workaround:
```lua
local WIRELINK = wire.getWirelink(chip())
setmetatable(wire.ports, {
    __index = function(self, name)
        local value = rawget(self, name)
        if value == nil then
            return rawget(WIRELINK, name)
        end
        return value
    end;
})
```

But, that doesn't work because apparently, the `wire.ports` table has a "protection" metatable attached to it.

@thegrb93 Why was it made (reta**ed) like this?
It is not like there can be an input **and** output using the identical names (at the same time). Just, why such (reta**ed) design then?

Please fix.

**Comment by CaptainPRICE** [comment]
I'm closing this issue since I have finally achieved what I wanted to do. Read an output like so:
`wire.ports.Out`

/close
