### ISSUE TITLE
Wire-based editor errors out by pressing "Page Up/Down" key

### ISSUE THREAD

**Issue by CaptainPRICE** [thegrb93/StarfallEx#401]
The title says it all.
When using a Wire-based editor for Starfall, it errors out when you press the `PgUp`/`PgDown` keys (while there are some pages of the code).
(Also, any Wire Text Editor bugs seems to affect Starfall as well.)

**Comment by Mista-Tea** [comment]
Just to provide the actual error message (latest commit fefb7d181d7e28f7b28c5c90e28a97b3bbdc41ea)
```
[ERROR] addons/starfallex/lua/starfall/editor/tabhandlers/tab_wire.lua:1206: attempt to index a nil value
  1. unknown - addons/starfallex/lua/starfall/editor/tabhandlers/tab_wire.lua:1206
```

**Comment by Damianu** [comment]
``(Also, any Wire Text Editor bugs seems to affect Starfall as well.)``
That's pretty normal, however reporting them would be nice.
