### ISSUE TITLE
Starfall screen rendering problems

### ISSUE THREAD

**Issue by CornerPin** [thegrb93/StarfallEx#402]
In the latest version of StarfallEx, there are several problems with the screen rendering:
- Starfall screen can be seen through walls
- Sun and Starfall processor can be seen through the screen at some angles

https://puu.sh/A3CWk/a0abdb9ed2.mp4

**Comment by thegrb93** [comment]
Ah I think I can fix this easily

**Comment by thegrb93** [comment]
Should be fixed
