### ISSUE TITLE
PlayerSay potentially leaks hidden chat

### ISSUE THREAD

**Issue by Mista-Tea** [thegrb93/StarfallEx#404]
```lua
-- In StarFall:
hook.add( "PlayerSay", "Example", function( ply, text, isTeam )
    print( ply, text )
end )
```

Depending on hook ordering, this may allow the client to see chat that the server (in a later `PlayerSay` hook instance) did not intend them to see, e.g. **private messages, staff chat**, etc.

Although kinda hacky, a fairly easy way of dealing with this is overriding existing `PlayerSay` hooks and ensuring they don't leak things they shouldn't. They all generally get created immediately (e.g. E2) or after their core has finished loading (e.g. ExpAdv2), so overriding them in a predictable manner is easy.

However, StarFall dynamically adds/removes a `PlayerSay` hook depending on whether there are any registered instances, meaning the hook can't be overridden the same way the other ones can. Instead, overriding hook.Add and checking for PlayerSay is the only current way I can think of to know when it is created.

Does StarFall provide any method for addressing this? E.g., a hook call for when StarFall adds hook, something like that?

**Comment by thegrb93** [comment]
The way I dealt with it before was by overriding the gamemode function GM:PlayerSay and running the starfall hook in that. I probably removed it because it was affecting every hook and is an ugly hack. I'll add an option for that behavior and enable it for playersay.

**Comment by Mista-Tea** [comment]
Is there perhaps a better approach? In my particular case, I already use GAMEMODE:PlayerSay for my server since I want complete control over the hook.

**Comment by thegrb93** [comment]
Well shit, i just finished implementing the gamemode hook override again.

**Comment by Mista-Tea** [comment]
Would something like this work? https://github.com/IJWTB/StarfallEx/commit/c36e0896139087a9d4861f0380c369bf0a716583

Passing the hook function itself can be omitted if preferred, since we can still get things via `hook.GetTable()[hookname][identifier]`.

It opens up the possibility beyond just PlayerSay too, in the case something else conflicts.

**Comment by thegrb93** [comment]
I'm kind of reluctant to add things that never get used except by specific servers. And it only solves the problem for your server, not everyone's.

**Comment by Damianu** [comment]
Potentially just adding hook after everything is loaded would prevent it from leaking stuff because hooks stop getting executed after one of them returns false(to hide chat msg) and they should execute in order they were added in.

**Comment by thegrb93** [comment]
It's using the Initialize hook now for the override so if you get it before that, then you should maintain control over it.

**Comment by Mista-Tea** [comment]
I'll take a look when I get home, thanks.

On Apr 20, 2018 5:04 PM, thegrb93 <notifications@github.com> wrote:

It's using the Initialize hook now for the override so if you get it before that, then you should maintain control over it.
