### ISSUE TITLE
Add a "getTool()" function

### ISSUE THREAD

**Issue by sammythew** [thegrb93/StarfallEx#409]
Just a function that returns tool.Mode
could easily adapt the e2 function:

```
e2function string entity:tool()

if not IsValid(this) then return "" end
if not this:IsPlayer() then return "" end

if not IsValid(weapon) then return "" end
if weapon:GetClass() ~= "gmod_tool" then return "" end
  
return weapon.Mode
end
```
I don't know the sf function format though, so I can't

**Comment by thegrb93** [comment]
All right, added. I suggest checking out the function format, it's really easy; even easier than e2.

**Comment by thegrb93** [comment]
https://github.com/thegrb93/StarfallEx/commit/d53f7ba6f38a09d6b8d288cb5160f736ce07420b
