### ISSUE TITLE
Add Entity:GetTable()

### ISSUE THREAD

**Issue by sammythew** [thegrb93/StarfallEx#416]
Noticed this wasn't in starfall, or at least I couldn't find it.
As per Glua Logs:
> Returns the table that contains all values saved within the entity.

Also if Entity:GetChildren() (from glua) could be implemented as well, that'd be lovely,

If anyone has a bit of spare time to add these, please do! :)

**Comment by thegrb93** [comment]
GetTable contains all data attached to the entity used by every addon. I don't think that will be added. Can do getChildren though.

**Comment by TheFreezebug** [comment]
It doesn't really make sense to add this imo. Each starfall instance is going to have it's own copy of the entity. The information stored on an entity is not shared between instances, so you'll always know what keys / values are on your entity, because you create them

**Comment by thegrb93** [comment]
If you can be more specific what getTable() should do and what you need it for, i'll look into it.
