### ISSUE TITLE
hasPermission causes error for specific permissions

### ISSUE THREAD

**Issue by DaDamRival** [thegrb93/StarfallEx#418]
hasPermission will result in a error while checking permissions that have url whitelist enabled for them

`addons/starfallex/lua/starfall/permissions/providers_sh/url_whitelist.lua:12: bad argument #1 to 'match' (string expected, got nil)
addons/starfallex/lua/starfall/permissions/providers_sh/url_whitelist.lua:12: bad argument #1 to 'match' (string expected, got nil)

stack traceback:
	[C]: in function 'match'
	addons/starfallex/lua/starfall/permissions/providers_sh/url_whitelist.lua:12: in function 'v'
	addons/starfallex/lua/starfall/permissions/core.lua:101: in function <addons/starfallex/lua/starfall/permissions/core.lua:99>
	addons/starfallex/lua/starfall/permissions/core.lua:77: in function 'hasPermission'
	SF:main:3: in main chunk
	[C]: in function 'xpcall'
	addons/starfallex/lua/starfall/instance.lua:137: in function 'runWithOps'
	addons/starfallex/lua/starfall/instance.lua:216: in function 'initialize'
	addons/starfallex/lua/entities/starfall_processor/shared.lua:48: in function 'Compile'
	addons/starfallex/lua/entities/starfall_processor/shared.lua:78: in function 'SetupFiles'
	addons/starfallex/lua/entities/starfall_processor/cl_init.lua:63: in function 'callback'
	addons/starfallex/lua/starfall/transfer.lua:35: in function <addons/starfallex/lua/starfall/transfer.lua:30>
	[C]: in function 'xpcall'
	addons/starfallex/lua/starfall/netstream.lua:60: in function 'Remove'
	addons/starfallex/lua/starfall/netstream.lua:50: in function 'Read'
	addons/starfallex/lua/starfall/netstream.lua:204: in function 'func'
	lua/includes/extensions/net.lua:32: in function <lua/includes/extensions/net.lua:17>
`

**Comment by thegrb93** [comment]
Should be fixed. The reason it was erroring was because you didn't give it a url string.
