### ISSUE TITLE
getName bug

### ISSUE THREAD

**Issue by ghost** [thegrb93/StarfallEx#419]
I wanted to make a game with the player on the screen but I caught the error
![image](https://user-images.githubusercontent.com/24373388/39645391-36416ea6-4fe9-11e8-9ce5-4090c63bda43.png)
![image](https://user-images.githubusercontent.com/24373388/39645410-44b63408-4fe9-11e8-91cb-14e0ddca5e99.png)
![image](https://user-images.githubusercontent.com/24373388/39645419-4b12693e-4fe9-11e8-9702-a7ff6d6f9855.png)

**Comment by thegrb93** [comment]
Game["Player"] is for sure a player right?

**Comment by thegrb93** [comment]
Maybe that hook isn't working correctly

**Comment by thegrb93** [comment]
Yeah, that's the problem

**Comment by KotoNinja** [comment]
then the syntax is all right?

**Comment by thegrb93** [comment]
Yeah. Should be fixed now.

**Comment by KotoNinja** [comment]
Thx!
