### ISSUE TITLE
table.copy() changes players to null entities

### ISSUE THREAD

**Issue by sammythew** [thegrb93/StarfallEx#421]
Running this code:
```
tab = { owner() }
printTable(tab)
tabCpy = table.copy(tab)
printTable(tabCpy)
```

Returns this:
```
1	=	Player [1][Samuel]

1	=	(null entity)
```

Pretty sure this is not correct

N.B.
This is not exclusive to players, happens with all entities

**Comment by thegrb93** [comment]
All starfall types I think are affected. I'll fix it

**Comment by thegrb93** [comment]
Fixed
