### ISSUE TITLE
goto and labels not highlighted

### ISSUE THREAD

**Issue by bbblitz** [thegrb93/StarfallEx#437]
Neither goto's nor labels are highlighted in the editor.
http://lua-users.org/wiki/GotoStatement

**Comment by Damianu** [comment]
https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/editor/syntaxmodes/starfall.lua#L38
Add "goto" there
as for labels it should go there: https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/editor/syntaxmodes/starfall.lua#L389

```lua
elseif self:NextPattern("^::[^:]*::") then
    tokenname = "string"
```
should work
