### ISSUE TITLE
Some anchors don't work in starfall helper

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#440]

**Comment by Damianu** [comment]
Examples of those would be useful, I fixed some I knew about, but its pretty much because _library suffixes etc were stripped but not in all places.

**Comment by thegrb93** [comment]
It's when you search for a method and you click on one of the results.

**Comment by thegrb93** [comment]
I think I fixed it, but not sure how to get travis to rebuild the docs. I don't have all the necessary components installed right now.
