### ISSUE TITLE
Can't draw on rendertarget with 3D functions until rendertarget is cleared. 2D works though

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#443]

**Comment by Damianu** [comment]
https://github.com/thegrb93/StarfallEx/blob/ccf41bc333baf5ea5e807a10c587797018c5f0b9/lua/starfall/libs_cl/render.lua#L1183 That should be just changed to (true, enable) instead of enable, enable. 
I think it was a typo of mine.

**Comment by thegrb93** [comment]
The second argument just determines if depth should write or not (should just always be true); it doesn't have any effect on the depth testing iirc.

**Comment by thegrb93** [comment]
It just allows you to override whether the depth buffer is written to or not I think. It doesn't control the depth testing.

**Comment by thegrb93** [comment]
cam.IgnoreZ doesn't seem to work.

**Comment by thegrb93** [comment]
Should've put this here a while ago: if you render.clear(Color(), true), the rendertarget seems to work afterwards
