### ISSUE TITLE
:getOwner() returns [NULL Entity]

### ISSUE THREAD

**Issue by KotoNinja** [thegrb93/StarfallEx#445]
it's a prop player
![9b7065746df7ab4814685c9efdaf375f 1](https://user-images.githubusercontent.com/24373388/40884545-7d044a80-6726-11e8-9ac1-27ac56d7619c.png)
![05886b8ce00dc65bce2db11fb010fbce 1](https://user-images.githubusercontent.com/24373388/40884548-905eb3cc-6726-11e8-9050-ce68081d0ee9.png)

**Comment by CornerPin** [comment]
Player entities don't have owners if your server uses FPP.

**Comment by KotoNinja** [comment]
but there are alternatives?

**Comment by thegrb93** [comment]
use it on the prop entity, not the player entity

**Comment by KotoNinja** [comment]
but what am I doing?

**Comment by thegrb93** [comment]
entity(1) returns the player with entindex 1.

**Comment by KotoNinja** [comment]
ohhh ok thanks

**Comment by KotoNinja** [comment]
:P 
![39356c5840ea6ad3b68d6e4e6cab4dac 1](https://user-images.githubusercontent.com/24373388/40885605-9cc8297c-673a-11e8-9dd3-c0295c34840f.png)

**Comment by thegrb93** [comment]
Remember, it returns NULL if there's no entity. So use `test:getOwner():isValid()` not `test:getOwner()!=nil`
