### ISSUE TITLE
Owner's Client-Side State Features

### ISSUE THREAD

**Issue by edgarasf123** [thegrb93/StarfallEx#45]
**These features would be only be available on owner's clientside LUA state.**

A way to modify quota, such as function or processor.

And a way to access global lua table (_G) like defining _GMOD global variable in the sandbox environment. Essentially this would allow players to gain full control of LUA in their own state. Also it would be disabled if sv_allowcslua is set to 0.

Possible applications?
* **Midi keyboard:** Basically load [gmcl_midi module](https://facepunch.com/showthread.php?t=1421522), send data to serverside chip using SF net library. And then broadcast data to all players. Now you're able to play keyboard directly to the server.
* **Controller Support:** Be able control your vehicles using controllers such as steering wheel.
* **Adding console commands:** execute commands on the chip without needing to use chat.

And to prevent accidental messups by newbies, users may need to include ```--@safe 0``` preprocessor to enable above described features..

**Comment by its-suun** [comment]
Controllers are already supported with the `joystick` library

**Comment by thegrb93** [comment]
I like this idea, but most servers don't have sv_allowcslua 1. I think it would also be a bit confusing having the starfall libraries side by side with glua since all of starfall's objects are different from glua. I think it might be better to do your glua clientside script seperately and just send "SF_netmessage" netmessages to the server to control your chip.

**Comment by thegrb93** [comment]
Ex. 
```
net.Start("SF_netmessage")
net.WriteEntity(mychip)
net.WriteString("Controls")
...
net.SendToServer()
```

**Comment by thegrb93** [comment]
What do you think?

**Comment by edgarasf123** [comment]
That would work, but I'd like to keep my scripts compact, in one file. It would also allow me to share my code with my friends when everything is in one file.

**Comment by thegrb93** [comment]
It can be in one file. Just seperate each part using an if CurTime~=nil then --glua else --sf and detour SF.Editor.BuildIncludesTable to upload the file instead of whats in the editor.

**Comment by edgarasf123** [comment]
Hmm, I guess that could work.

**Comment by its-suun** [comment]
Can we have console commands in starfall without clientside glua?

**Comment by thegrb93** [comment]
I guess as long as it's on the owner's state.
