### ISSUE TITLE
render.destroyRenderTarget doesn't actually decrease the ResourceHandler's counter

### ISSUE THREAD

**Issue by sammythew** [thegrb93/StarfallEx#458]
Creating and destroying a render target 20 (default max RT's) times causes a max RT error.

```
for i=1, 23 do
    print(i)
    render.createRenderTarget("test")
    render.destroyRenderTarget("test")
end
```

This code prints 1 to 20 then gives:

> SF:main:7: Rendertarget limit reached

Don't really understand how the code works, this is just what I gathered from reading it.

**Comment by thegrb93** [comment]
That's weird I could've sworn it was working. I'll fix it today along with the other bug

**Comment by thegrb93** [comment]
I can't reproduce. I tried with 100 and it still worked

**Comment by sammythew** [comment]
Oh, my apologies, seems I'm not running on the most recent version, thought I was, disregard this issue :)

**Comment by thegrb93** [comment]
Np
