### ISSUE TITLE
Cause of "Color Memory-leak"

### ISSUE THREAD

**Issue by ThatOneCheetah** [thegrb93/StarfallEx#46]
[#407 on INPStarfall/Starfall](https://github.com/INPStarfall/Starfall/issues/407)  
Except it's on *line 269 in sflib.lua* on this fork.

**Comment by thegrb93** [comment]
The two weak tables don't reinforce each other because the weak keys for one are weak values for the other and vice versa.

**Comment by ThatOneCheetah** [comment]
Yes, but completely removing the cache and making the `sf2sensitive` table weak on both `k` and `v` seems to make all the memory-related issues *vanish*, there is an obvious link here.

**Comment by thegrb93** [comment]
If the vector is persisting in the weak table then that means there's still something referencing the vector (gmod's vector caching system maybe?).

**Comment by thegrb93** [comment]
Also keep in mind that weak tables don't clean themselves immediately, the garbage collector cleans them whenever it feels like.

**Comment by ThatOneCheetah** [comment]
It's Vectors, Angles, Colors, Tables, anything that acts as a non-literal index.
After forcing 100+ cycles of garbage collection, and it not cleaning properly, I doubt that this is expected behaviour.  
  
After checking the table, however (by printing it with `PrintTable`) it appeared to be empty, but no memory is freed until rejoining or restarting Garry's Mod.

**Comment by thegrb93** [comment]
What memory are you looking at? Windows task manager? collectgarbage("count")?

**Comment by ThatOneCheetah** [comment]
Task manager, at first I though that could be inaccurate, but as soon as it hits somewhere around 2GB (to me) GMod crashes because it ran out of memory.

**Comment by thegrb93** [comment]
collectgarbage("count") will show how much memory lua is using. I haven't seen any leaks, but gmod's internals such as the vector caching system might be a problem.

**Comment by ThatOneCheetah** [comment]
It seems to be Lua related:

```
] // Before SF test code
] lua_run_cl for i=1, 16 do collectgarbage() end
] lua_run_cl print( collectgarbage( "count" ) )
27767.518554688 ( ~27MB )
] // ---------------------------------------------------------------
] // After SF test code
] lua_run_cl print( collectgarbage( "count" ) )
352197.6484375 ( ~350MB )
] lua_run_cl for i=1, 16 do collectgarbage() end
] lua_run_cl print( collectgarbage( "count" ) )
240500.91894531 ( ~240MB )
] lua_run_cl for i=1, 16 do collectgarbage() end
] lua_run_cl print( collectgarbage( "count" ) )
240800.39648438 ( ~240MB )
```

It seems to be clearing up something, but shouldn't it technically drop back to 27-50MB (at most)?  
  
Using:
```lua
if SERVER then return end

hook.add( "think", "test", function()
    while quotaUsed()*2 < quotaMax() do
        test = Vector( 1, 1, 1 )    
    end
end )
```

**Comment by thegrb93** [comment]
Yes there's a leak there. And the sf lookup tables are empty?

**Comment by ThatOneCheetah** [comment]
Yup, I've added:

```lua
local function verbose()
	print( "/// SENSITIVE -> STARFALL \\\\\\" )
	PrintTable( sensitive2sf )
	print( "------------------------------")
	print( "/// STARFALL -> SENSITIVE \\\\\\" )
	PrintTable( sf2sensitive )
	print( "------------------------------")
end
```

To `SF.CreateWrapper`, set it to `SF.Vectors.Verbose` and called the function; which printed:
```
/// SENSITIVE -> STARFALL \\\
------------------------------
/// STARFALL -> SENSITIVE \\\
------------------------------
```

**Comment by ThatOneCheetah** [comment]
Perhaps [this](http://lua-users.org/wiki/GarbageCollectingWeakTables) has something to do with it.

**Comment by thegrb93** [comment]
Can we close this?

**Comment by ThatOneCheetah** [comment]
Yup.
