### ISSUE TITLE
massive render clientside memory leak

### ISSUE THREAD

**Issue by storm37000** [thegrb93/StarfallEx#466]
weird client side memory leak possibly caused by rendertargets (the old RT cam tool that was revived became VERY bad at some point, probably why Garry had to remove it. ) and only happens with render functions in starfall.  The leak is weird as it seems to be map persistent. Effecting even new players eventually preventing them from joining with crash as soon as they load in.

We are still trying to figure it out fully but results so far seem to point to PAC3 and this as being the main culprits.

**Comment by thegrb93** [comment]
This addon manages its render targets much better than pac3 and won't exceed the limit specified by sf_render_maxrendertargets

**Comment by thegrb93** [comment]
What do you mean ghost entities?

This has never been an issue with starfall. I've hosted my server without any issues for years using it.

**Comment by thegrb93** [comment]
I'll look at GDisasters real quick and make sure, but I think you are experiencing conflicts with another addon.

**Comment by storm37000** [comment]
the only change i made was removing this addon, people have stopped crashing to this specific way.

**Comment by thegrb93** [comment]
if you wish to figure out what addon is overriding the Remove function: `lua_run_cl PrintTable(debug.getinfo(FindMetaTable("Entity").Remove))`

That's the only thing I can suggest for figuring out the odd remove behavior.

**Comment by thegrb93** [comment]
Because, this addon doesn't tamper with remove functionality at all.
