### ISSUE TITLE
CalcView hook not passed arguments

### ISSUE THREAD

**Issue by kubinator4321** [thegrb93/StarfallEx#47]
[Related code](https://github.com/thegrb93/StarfallEx/blob/0a8d79d19f5de7c1c5f8dae4d5b6b7cd20280817/lua/entities/starfall_hud/cl_init.lua#L89)

The code should probably look like
`hook.Add("CalcView", hook_name, function(...) return ent:DoCalcView(...) end)`
In the current state DoCalcView doesn't receive any of the params and thus they aren't passed on to the hook.

**Comment by thegrb93** [comment]
Yea what the hell.

**Comment by thegrb93** [comment]
fixed
