### ISSUE TITLE
Light:setPos() throwing an assertion fail

### ISSUE THREAD

**Issue by Pollitto** [thegrb93/StarfallEx#471]
```lua
--@client

local light_test = light.create( chip():getPos(), 1024, 2, Color(120,50,50), true )
light_test:setPos( Vector(0,0,0) )
```
```
addons/starfallex/lua/starfall/sflib.lua:412: assertion failed!
stack traceback:
	[C]: in function 'assert'
	addons/starfallex/lua/starfall/sflib.lua:412: in function 'checkluatype'
	addons/starfallex/lua/starfall/libs_cl/light.lua:245: in function 'setPos'
	SF:main:6: in main chunk
```

**Comment by KubeRoot** [comment]
I think `setPos` should be using `checktype` instead of `checkluatype` at `checkluatype(pos, vec_meta)` at https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/libs_cl/light.lua#L245

If that's the case, the same problem exists with `setDirection` on line 197.

**Comment by Damianu** [comment]
> 
> 
> I think `setPos` should be using `checktype` instead of `checkluatype` at `checkluatype(pos, vec_meta)` at https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/libs_cl/light.lua#L245
> 
> If that's the case, the same problem exists with `setDirection` on line 197.

Exactly
