### ISSUE TITLE
Hologram UpdateClip  returns nil clientside

### ISSUE THREAD

**Issue by Ty-unge** [thegrb93/StarfallEx#475]
`[ERROR] addons/starfall/lua/entities/starfall_hologram/cl_init.lua:101: attempt to call method 'UpdateClip' (a nil value)`
  `1. func - addons/starfall/lua/entities/starfall_hologram/cl_init.lua:101`
   `2. unknown - lua/includes/extensions/net.lua:32`

**Comment by thegrb93** [comment]
That doesn't make sense. The checks should prevent that
```lua
local holoent = Entity(entid)
if holoent:IsValid() and holoent.UpdateClip then
	holoent:UpdateClip(clipid, enabled, origin, normal, islocal)
else
```

**Comment by thegrb93** [comment]
Are you sure you're running this version of starfall?

**Comment by thegrb93** [comment]
The line numbers don't match up so I think its safe to assume you're not using this version
