### ISSUE TITLE
ClientSide Holograms

### ISSUE THREAD

**Issue by edgarasf123** [thegrb93/StarfallEx#48]
http://wiki.garrysmod.com/page/Global/ClientsideModel
http://wiki.garrysmod.com/page/ents/CreateClientProp

Basically these allows you to create clientside holograms(entities). They're faster, and less resource intensive. 

I'm currently making a minecraft-like terrain generation. And I would like to introduce multiplayer feature. The problem is, creating terrain for multiple players would increase entity count drastically. If clientside holograms existed, I would give each player few invisible props, and leave the terrain rendering on clientside code(which would be local to each player).

Here's a current version of my game.
http://googledrive.com/host/0B11uwRQw_I-kVndMdC1tVnlIcm8/

**Comment by thegrb93** [comment]
Definitely. I'll look into that.

**Comment by thegrb93** [comment]
Moved to stuff to add.

**Comment by CaptainPRICE** [comment]
Bump!
