### ISSUE TITLE
Handling docs for starfall addons.

### ISSUE THREAD

**Issue by Damianu** [thegrb93/StarfallEx#497]
Instead of docgen generating lua table with SF.Docs = {...} It could do something like SF.RegisterDocs({...}) which would automerge that table. 
Reason for that would be making docgen universal, so you can run it on addon instead of starfall itself and get compatibile docs file to ship with addon.
\+ Writing simple tutorial how to run docgen locally without using travis so addon creators can handle it.

**Comment by Damianu** [comment]
Not if we assume that addon creators can just include generated file of their own. Something like myaddon_docs.lua

**Comment by Damianu** [comment]
Docgen can generate documentation from any addon without collisions as long as result table is merged instead of being set and file structure is valid.

**Comment by thegrb93** [comment]
I still want it generated at runtime because the html still needs it.

**Comment by thegrb93** [comment]
The html can't be merged

**Comment by Damianu** [comment]
I am not sure if you can get luadoc working inside gmod's lua env, otherwise it shouldnt be a problem

**Comment by thegrb93** [comment]
Would like to change all the doc from comment format to string in table too so the gen doesn't need to parse anything.

**Comment by Damianu** [comment]
Maybe something like:
```lua
//Top of the file:
local _DOC = SF.Docs.RegisterLibrary("Render"); //Realm gets resolved automatically when its executed

//Function
_DOC.RegisterFunction {
 Name = "SetColor",
 Description = "Sets drawing color",
 Arguments = { 
   {"color", "Color", "Color to Set"}
   //{name, type, desc}
 }
}
function render_library.SetColor(color)
end
```

**Comment by Damianu** [comment]
Only issue I see with this is that server would have to send those to clients on join, because AFAIK you cant save in addons folder so generating on startup and sending it with AddCSLuaFile wont work

**Comment by Damianu** [comment]
Or alternatively we can use lua syntax trick to do something like

```lua
SF_DOC [[
--- Sets the draw color
-- @param clr Color type
]]
function render_library.setColor(clr)
	checktype(clr, col_meta)
	currentcolor = clr
	surface.SetDrawColor(clr)
	surface.SetTextColor(clr)
end
```

**Comment by Damianu** [comment]
Another idea is to use debug library with registerExtension and just get execution path and read its file, then parse it like normal luadocgen would with regex for matching ``---``

**Comment by Damianu** [comment]
**Update**:
So we talked with @thegrb93, and so far it seems the best solution would be:
- Using solution provided by @szymski to generate docs table
- Once all addons are initialized generate JSON file from that table
- Write new HTML and JS files for documentation that'll populate page providing search and dynamic loading from JSON.

**Comment by thegrb93** [comment]
I thought u said the html would be static and it would just use javascript to display everything.

**Comment by Damianu** [comment]
Thats what I meant, writing HTML and JS files that are static and populate page from JSON

**Comment by thegrb93** [comment]
Looks like debug library can get the arguments and returns of the function I think.

**Comment by hobnob11** [comment]
as a developer of starfall addons, this sounds very useful, but how would the newly generated addon HTML be served to the client? currently the docs are hosted by you, with a cvar to allow people to host their own docs. I'm not sure how you would get the html to the clients, would you add some kind of support to send clients additional HTML files?

**Comment by Damianu** [comment]
HTML files will be shipped with addon like editor used to, it's json that's gonna be sent.

**Comment by hobnob11** [comment]
Is the ingame editor not just a html panel that loads the github docs page? Isn't that what the sf docs cvar is for? how would sending the user the JSON affect what the docs show?

**Comment by thegrb93** [comment]
The user would get the json and the html panel would add them dynamically to the docs page.

**Comment by thegrb93** [comment]
For outside of game, there will probably be a command added that can output the json to a file which can be copied to whatever is hosting the page.

**Comment by Damianu** [comment]
https://steamuserimages-a.akamaihd.net/ugc/781852401249628396/011FEBA55123E688A28D538FBE9D78F0A48CCC26/
I managed to write simple documentation parser that works from glua, can be done for enums etc too, supports current syntax and works for addons :) Only thing it cant do is C functions

**Comment by thegrb93** [comment]
We already have a parser that does that :V the challenge was making an efficient one that doesn't need to read all the lua files and parse the whole thing.

**Comment by Damianu** [comment]
We actually dont, current parser doesn't work for addons which is the main issue. This one is also more efficient as it doesnt read whole file, it stops iterating as soon as it encounters anything that isnt a comment or empty line above function.

**Comment by thegrb93** [comment]
The current parser does work for addons as long as it has their source. It's probably the least hacky method though, so I think it's in the right direction. As long as it doesn't cost a ton of loadup time.

**Comment by hobnob11** [comment]
Oh hi, yeah I generate my own SF docs using your docs parser, i set up a CI job to automatically pull the current repo, merge my addon with it, run the parser and upload the docs to my website. my servers then have the sf docs config value set to my website

it does have a number of issues, like for example if i dont update starfall but you guys do my docs will be out of sync from whats in my server.

**Comment by thegrb93** [comment]
My point wasn't that the current one doesn't have issues, I was just saying his approach wasn't what we had in mind before. It is the simplest solution though.

**Comment by hobnob11** [comment]
The issue I see with using lua "ingame" is how would you update the external website? most of my playerbase uses that on a second monitor.

**Comment by thegrb93** [comment]
It would be internal instead of external.

**Comment by hobnob11** [comment]
Yeah, we'd loose the external website, which is super useful, thats my main issue with this

**Comment by thegrb93** [comment]
That would be impossible I think. The best that could be done is the a json be saved to the users' data folder which they could run the webpage locally with.

**Comment by thegrb93** [comment]
What's wrong with the in-game SF helper? I use it all the time.

**Comment by Damianu** [comment]
It'd need networking json from server to client, then merging both and sending it to html through javascript. As for external, we can keep it as it is, it'd still have base addon documentation, but depending on server you'd be able to open server-specific documentation.

**Comment by hobnob11** [comment]
Nothings wrong with the ingame helper, but most of my players find it easier to have it open on a second monitor. And so long as I can still generate https://sf.h08.us, making the ingame docs automatic and based on the actual code sounds pretty useful. just please dont break my ability to generate external docs in the process thanks

**Comment by thegrb93** [comment]
I don't think this will touch the external docs at all.

**Comment by thegrb93** [comment]
@Damianu I've been meaning to ask, what do we need from the parser?

```lua
data = {
   name = "",
   description = "",
   type = "",
   realm = "",
   params = {},
   returns = {}
}
```
?

**Comment by adamnejm** [comment]
He's doing this in React so it would be nice to provide unique id

**Comment by thegrb93** [comment]
I guess each table's hash could be a uniqueid

**Comment by adamnejm** [comment]
Really depends on how he'll be rendering this, mapping a table with index as a key can cause some serious bullshit due to how react compares virtual dom with the displayed one. this would happen especially when sorting or filtering the table ie search field, so he would first have to go through the table and add unique indecies
but i dunno rly, i might be wrong, probably am, don't like react fuk js
