### ISSUE TITLE
Error doesn't get shown when render hook exceeds cpu quota

### ISSUE THREAD

**Issue by suunrider** [thegrb93/StarfallEx#5]
The code
```lua
hook.add( "render", "cpuquota", function()
  while true do end
end )
```
doesn't show any error.

**Comment by thegrb93** [comment]
I'll fix it. Have you tried the alt-gr testing I mentioned btw? I want to fix that, but don't know how without an alt-gr key to test with.

**Comment by thegrb93** [comment]
It's fixed now.
