### ISSUE TITLE
Hologram animations not working?

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#502]

**Comment by bjoern90** [comment]
it works fine for me but if i use the model like it does only exiest in clinetside it fuckes up like the neck is snapped and does t-pose https://i.imgur.com/rl4gqUU.png

**Comment by thegrb93** [comment]
Works fine in singleplayer

**Comment by thegrb93** [comment]
Works fine in local multiplayer

**Comment by bjoern90** [comment]
then what's the problem? i mean if you can view model clinetside with starfall (like models from addon) then why wont the animations work on mutilplayer server?

**Comment by thegrb93** [comment]
It's just not working on my dedicated server. Not sure why.

**Comment by thegrb93** [comment]
It's that neck snap t-pose bug though.

**Comment by bjoern90** [comment]
ah it happens on meta too...

**Comment by thegrb93** [comment]
I wonder if its the animation override I have installed for prone.

**Comment by bjoern90** [comment]
no i dont think it's the fault of that... also when doing the lizard dance starfall when using the loops on some models it tiwchs when it's like less a secound.. how to fix that?

**Comment by thegrb93** [comment]
What do you mean?

**Comment by thegrb93** [comment]
Happens with E2 too so it's not a starfall issue.

**Comment by bjoern90** [comment]
darn

**Comment by thegrb93** [comment]
Going to try removing the animation hack and see if that fixes it because its happening with all playermodels.

**Comment by bjoern90** [comment]
k

**Comment by thegrb93** [comment]
Yeah that fixed it

**Comment by thegrb93** [comment]
Overrided m_anim.mdl or f_anim.mdl causes it

**Comment by thegrb93** [comment]
Actually I think the problem is the server had it overrided but the client wasn't getting it or something.
