### ISSUE TITLE
Tab context menu - saving issue ?

### ISSUE THREAD

**Issue by OrIOg** [thegrb93/StarfallEx#505]
When you save("Save" or "Save As") with the context menu of a tab, it switch to the first tab of the editor.
And "Save" option switch and close the editor.

**Comment by thegrb93** [comment]
Guessing something here is going wrong. https://github.com/thegrb93/StarfallEx/blob/b592257df3f17515af5229ebbf65a7694e9361de/lua/starfall/editor/sfframe.lua#L563
