### ISSUE TITLE
Duplicate line shortcut not working

### ISSUE THREAD

**Issue by samuelWilliams99** [thegrb93/StarfallEx#513]
The duplicate line short (Ctrl + D) which previously worked, now only adds a blank line above the line intended to be duplicated, and places the cursor at the end of said line as if the text was duplicated.

Example:
![image](https://user-images.githubusercontent.com/33094920/51089126-0b931a80-1760-11e9-8969-097c80cd49b2.png)

Tried to supply a fix, but I can't find where these shortcuts are handled, sorry.

**Comment by thegrb93** [comment]
Ace or wire editor? I'm assuming wire. I can look

**Comment by thegrb93** [comment]
https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/editor/tabhandlers/tab_wire.lua#L2309

**Comment by samuelWilliams99** [comment]
Oh, sorry forgot to mention. Yes, I'm using the wire editor

**Comment by samuelWilliams99** [comment]
Ah thanks, I can try make a fix, though I'm unsure on using git in open projects like this, so I don't think I'd know how to submit it

**Comment by samuelWilliams99** [comment]
Oh, easy fix
Change line 2321 to `self.Caret = { self.Start[1], #self.Rows[self.Start[1]][1] + 1 }`

**Comment by thegrb93** [comment]
Hah, debugged real quick and figured it out too. Thanks though.

**Comment by thegrb93** [comment]
@samuelWilliams99 Click the 'fork' button to make a copy of this repository. Any changes you do to that copy, you can submit a pull request to add your changes.
