### ISSUE TITLE
No comment highlighting for // despite it still working for comments.

### ISSUE THREAD

**Issue by samuelWilliams99** [thegrb93/StarfallEx#514]
Seems to be the case for both wire and ace editor

**Comment by thegrb93** [comment]
For ace, it can be added here. https://github.com/thegrb93/StarfallEx/blob/master/html/starfalleditor2.html#L201

**Comment by thegrb93** [comment]
For wire, looks like here is where it should be added. https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/editor/syntaxmodes/starfall.lua#L555

**Comment by thegrb93** [comment]
I opened a PR with as much as I could get working. The block comments for ace/wire were being too tricky for me to spend anymore time on them. Maybe later I'll try again.
