### ISSUE TITLE
Change Vector:WithinAABox to allow for any order of vectors?

### ISSUE THREAD

**Issue by samuelWilliams99** [thegrb93/StarfallEx#515]
The starfall implemention requires all components of start vector to be less than end vector.
Also, once the vectors have been changed, would it not be better to directly call the gmod WithinAABox?
https://wiki.garrysmod.com/page/Vector/WithinAABox

**Comment by CornerPin** [comment]
Fixed. I compared a direct **WithinAABox** call with our own implementation and the direct call version runs 4 times slower.

**Comment by thegrb93** [comment]
It's problem the unwrapping making it slower, since it's such a fast method, 4 times slower makes sense.

**Comment by thegrb93** [comment]
Or they did an awful job lol
