### ISSUE TITLE
Starfall chip removed when entity it was placed on is removed, after unweld

### ISSUE THREAD

**Issue by samuelWilliams99** [thegrb93/StarfallEx#518]
Spawn a prop, place a starfall chip on it, then unweld them using weld tool, constraint.breakType or breakAll. When you remove that prop, the chip is still removed, despite no constraints between them.

**Comment by thegrb93** [comment]
It's a feature of the tool. Most garrysmod entities have this behavior.

I think the options to parent/nocollide/remove on unweld would be good though.

**Comment by thegrb93** [comment]
I'll make a gmod PR later tonight to fix this.

**Comment by thegrb93** [comment]
Can't be fixed afaik. It's just a gmod thing.
