### ISSUE TITLE
Optimize rendering

### ISSUE THREAD

**Issue by its-suun** [thegrb93/StarfallEx#52]
You can draw every 2. tick and it looks like you would draw normally.
Example:
```lua
--@client
-- The screen will stay red and not blink
local i = 0
hook.add("render", "", function()
    i = i + 1
    if i % 2 ~= 0 then return end
    render.setColor(Color(255, 0, 0))
    render.drawRect(0, 0, 512, 512)
end)
```
This could be implemented maybe for every render hook and achieve better performance.

**Comment by Damianu** [comment]
Yeah, drawing every 2 frames works fine, 3rth make blinking.

**Comment by edgarasf123** [comment]
Could be system/settings specific. Even though it works for you, it could flick for other people.

**Comment by thegrb93** [comment]
Is this with a hud or screen? I don't think this would work with a hud. If it's a screen then something must be causing the screen to draw twice per frame. Very strange.

**Comment by thegrb93** [comment]
Okay so hud behaves correctly. Going to ask around and see why ENT:Draw is being called twice.

**Comment by thegrb93** [comment]
It's because of RENDERGROUP_BOTH. I went ahead and made it RENDERGROUP_OPAQUE until I figure out another fix.

**Comment by thegrb93** [comment]
Nice find btw, I have no idea how you found it.

**Comment by thegrb93** [comment]
Okay this fixed.
