### ISSUE TITLE
Allow for included files to not be automatically opened/focused when opening main file

### ISSUE THREAD

**Issue by TheWizardLizard** [thegrb93/StarfallEx#522]
Currently, when you include a file at the top of a script and run it, the next time you (right click) open that script, it will also open the included file.

While that behavior is fine, focusing the editor on the included file and not the main script is not. A button to toggle this would probably work fine.

**Comment by thegrb93** [comment]
I think focusing the main file would be feasible

**Comment by TheWizardLizard** [comment]
Fixed w/ #564

**Comment by thegrb93** [comment]
Leave open till it's actually fixed
