### ISSUE TITLE
Entity permissions denied on own props and getOwner returning null on most entities with DBot Prop Protection

### ISSUE THREAD

**Issue by RileyGuy** [thegrb93/StarfallEx#525]
Starfall is not recognizing my own props as being owned by me unless entities are spawned from the entities menu specifically, this seems to happen with DBot Prop Protection, using latest github version as of writing this I believe.

**Comment by thegrb93** [comment]
They probably have something that's keeping this block from working, https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/permissions/providers_sh/entity.lua#L95-L111

**Comment by thegrb93** [comment]
I think DBot fixed it.

**Comment by thegrb93** [comment]
Maybe not.. I think it's his pp's fault though.

**Comment by thegrb93** [comment]
It is, he stores the original cleanup.Add and later after initialization overrides the cleanup.Add and uses the original instead of the current, so any other addon that overrided it not longer has it overrided. @roboderpy
