### ISSUE TITLE
Add functions for creating options in chip's context menu

### ISSUE THREAD

**Issue by CaptainPRICE** [thegrb93/StarfallEx#539]
Expression Advanced 2 is an example, it has such feature.
You can add (and remove) custom context menus by calling certain function from chip, and when user clicks on an option, it would run a callback function (clientside).
This would be a small but neat feature (for times when you're lazy to code screen/UI).

There' something to be aware of: All of the custom submenus/options should be added under a new "Custom Menus" root menu, rather than adding them directly into the main context menu (to prevent overflowing the main menu).
This is what I refer to as the "main menu":
![context main menu](https://user-images.githubusercontent.com/9789070/55585027-feb21180-5725-11e9-98ea-118ed9205606.png)

**Comment by thegrb93** [comment]
Not really interested in this. If someone really wants it then pull request it.
