### ISSUE TITLE
Entity:getAllConstrained() has no way to distinguish between constraints and wire connections

### ISSUE THREAD

**Issue by mitterdoo** [thegrb93/StarfallEx#540]
With the addition of wire connections to Entity:getAllConstrained(), my elevator Starfall chip was broken. It uses wired connections to props, for the Z-location of floors, and uses :getAllConstrained() to unfreeze the elevator car, which additionally *unfreezes* the floor references with the new update. Even with a filter (using "Weld"), it still adds on the wired connections.

I propose a 17-bit "flag" system for the filter, instead of just one string. This would include:
* Weld
* Rope
* Elastic
* Slider
* Axis
* AdvBallsocket
* NoCollide
* Motor
* Pulley
* Ballsocket
* Winch
* Hydraulic
* Muscle
* WireInput
* WireOutput
* Parent
* Child

Now, I would make a pull request myself, but I'm not sure which way to implement this with. Should they be defined as global variables like enums in GLua, adding a brand-new section to the documentation? Or, should the values just be defined in the function's documentation itself? This is a question that I would rather have @thegrb93 answer, instead of leaving me to decide something big like that for this big project.

**Comment by thegrb93** [comment]
Could have to take a filter callback like the find.* functions that passes the constraint. Returning true allows it to consider the constraint as valid, while false ignores it.
