### ISSUE TITLE
Networking entities from server -> client or client -> server returns worldspawn

### ISSUE THREAD

**Issue by CheezusChrust** [thegrb93/StarfallEx#546]
After noticing a few of my chips involving networked entities weren't working properly, I discovered that for whatever reason if you try to network an entity from the server to a client or vice versa it will always return worldspawn. To reproduce, try this code:
```lua
--@name Broken Entity Netting
--@shared

if SERVER then
    timer.simple(1,function()
        net.start("testToClient")
        net.writeEntity(chip())
        net.send()
    end)
    
    net.receive("testToServer",function()
        local ent = net.readEntity()
        print("Client -> Server")
        print(ent)
    end)
else
    net.receive("testToClient",function()
        local ent = net.readEntity()
        print("Server -> Client")
        print(ent)
    end)
    
    timer.simple(2,function()
        net.start("testToServer")
        net.writeEntity(chip())
        net.send()
    end)
end
```
This seems like a fairly new bug because these chips were working within the last few weeks I believe.

**Comment by thegrb93** [comment]
https://github.com/thegrb93/StarfallEx/commit/38e2129c1e55576f1bed429efb114e14029e3de7#diff-edd8d64126b7c07420e8c4660afb7f07R617 broke it I think
