### ISSUE TITLE
Add read/writeDouble to stringstream

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#549]

**Comment by thegrb93** [comment]
Just need double precision floats now

**Comment by RileyGuy** [comment]
If I'm not mistaken, doesn't lua automatically use doubles for everything? Or am I misunderstanding what this is about?

**Comment by thegrb93** [comment]
It creates a string of bytes equal to the raw double data in ram. Lots of file formats store their data this way and lua as no way of converting it aside from our own implementation or gmod's filestream.

**Comment by thegrb93** [comment]
@RileyGuy The implementation looks like this, https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/libs_sh/bit.lua#L60 except is 64 bits instead of 32

**Comment by thegrb93** [comment]
https://github.com/ToxicFrog/vstruct/blob/5ddf751b923f41be3dbb832d9a2df1c6055c26f3/io/f.lua

**Comment by thegrb93** [comment]
Need to fix endian-ness too.
