### ISSUE TITLE
Unexpected behavior on various vector methods

### ISSUE THREAD

**Issue by adamnejm** [thegrb93/StarfallEx#550]
Functions like _getLengthSqr_ or _getNormalized_ return NaN when given vector {0,0,0}. Expression 2 is dealing with this by checking output against a constant, I understand you might not find that solution pleasing, but the current state defies a purpose of many vector methods when you have to code a better version yourself.

**Comment by thegrb93** [comment]
getLengthSqrt definately shouldn't be giving nan, but getnromalized should

**Comment by thegrb93** [comment]
getLength and getLengthSqr return 0

**Comment by thegrb93** [comment]
The getNormalized nan should be handled by the user. if v.x~=v.x then end works.
