### ISSUE TITLE
Add Vehicle.killDriver() & Vehicle.stripWeapons()

### ISSUE THREAD

**Issue by CaptainPRICE** [thegrb93/StarfallEx#551]
These functions are already available via E2 / Pod Controller.
It would be nice to have those builtin to Starfall, to make it more independent (saving time and entity count as well).

**Comment by Damianu** [comment]
I'd say that if this gets implemented I'd highly suggest adding separate permission for stripWeapons so servers can disable it, as it's easy to troll new players with it.

**Comment by CaptainPRICE** [comment]
I agree partially, but though, I don't exactly really see the point in having permission in Starfall, when you could then just continue using Pod Controller for stripping weapons. So, in my opinion, there is no point in having such permission since Pod Controller itself doesn't have any restrictions/permissions control for this functionality.

**Comment by Damianu** [comment]
Starfall doesn't require wiremod, and permission can be just turned on by default. All actions that affect players directly should have permissions added.

**Comment by CornerPin** [comment]
`Vehicle.killDriver` is already in Starfall. It's not in the SF Ref because of a typo, I'll fix it.
