### ISSUE TITLE
Editor starts to mishighlight the pairs of parenthesis/brackets/keywords

### ISSUE THREAD

**Issue by CaptainPRICE** [thegrb93/StarfallEx#553]
Running on the most recent git version (as of date of this post, 7db54025a1a095ce39c58c04ef242ffdcff26dc8).

I couldn't find a reason as to why does it start to mishighlight the pairs of parenthesis/brackets/keywords.
I find it happen within the code of mine, I will try to come up with a smaller code snippet in order to have it reproducable easier.

**Comment by Damianu** [comment]
I believe that in some cases it highlights them correctly but doesnt update when you edit the code.
