### ISSUE TITLE
Script error while disconnecting from (listen) server

### ISSUE THREAD

**Issue by CaptainPRICE** [thegrb93/StarfallEx#554]
Running on the most recent git version (as of date of this post, 89a6622).

```
[ERROR] lua/starfall/libs_sv/prop.lua:34: attempt to perform arithmetic on a nil value
  1. Function - lua/starfall/libs_sv/prop.lua:34
   2. v - lua/includes/extensions/entity.lua:134
    3. unknown - lua/includes/modules/hook.lua:84
```

Steps to reproduce:
1. Start a new singleplayer game.
2. Spawn down the following Starfall chip/code:
    ```lua
    --@server
    prop.setPropClean(true)
    prop.createSent(chip():getPos(), Angle(), 'Seat_Airboat', true)
    ```
3. Disconnect from the server (enter `disconnect` in Console).

**Comment by thegrb93** [comment]
Fixed it in all the other places but must've forgot this one.
