### ISSUE TITLE
Add ability to specify which entity a local holoclip is local to

### ISSUE THREAD

**Issue by shadowscion** [thegrb93/StarfallEx#560]

**Comment by thegrb93** [comment]
I think I'd rather the user handle it with clientside holoclip. Server side should be deprecated

**Comment by thegrb93** [comment]
The only reason local mode exists is to make the clip smoother since controlling it server side is slow. Clientside won't have this issue

**Comment by shadowscion** [comment]
True

**Comment by Damianu** [comment]
On the other hand I'd still be in favor for adding this. It's easy to implement as we already have it serverside and it'd be useful for less advanced people.

**Comment by thegrb93** [comment]
Fine. I'm going to rework the hologram library first to be shared and add a function to cast entities to hologram.
