### ISSUE TITLE
Editor does not follow style system overrides

### ISSUE THREAD

**Issue by TheWizardLizard** [thegrb93/StarfallEx#561]
Expression 2:
![hl2 - 2019-05-01 - 14-49-10](https://user-images.githubusercontent.com/17933206/57035886-0ed3e880-6c21-11e9-98c4-b8e71ac68baa.png)

Starfall:
![hl2 - 2019-05-01 - 14-49-26](https://user-images.githubusercontent.com/17933206/57035895-14313300-6c21-11e9-909c-f25ed716e3c9.png)

This is probably a really easy thing to fix, judging from a commit to the adv dupe 2 repo:
https://github.com/wiremod/advdupe2/commit/9bd7c4dc56f077d9d10ba1a52ac167984ea2b1c8

Here is a clientside dark derma theme if you need something to test against:
http://f.devinity.org/IKQMAg

**Comment by thegrb93** [comment]
Most of the editor is controlled via Style, but Idk whats wrong with the DTree. Nothing is setting its color so it should use the skin background.

**Comment by thegrb93** [comment]
Maybe the base DTree is doing some initialization that ours isn't.

**Comment by thegrb93** [comment]
I tried a bunch of stuff and couldn't even get the background color of the StarfallFileTree to change to anything. Any idea @Damianu ?

**Comment by thegrb93** [comment]
Nvm found it.
