### ISSUE TITLE
Invalid main file on Settings/Wiki, long wait

### ISSUE THREAD

**Issue by adamnejm** [thegrb93/StarfallEx#567]
Is it possible to along with the error _Invalid main file_ stop user from waiting for it to finish uploading? (By that I mean to not upload the code at all, but that's probably already in place)

Specifically I'm talking about how you can just place a chip with Settings or Helper/Wiki opened and you have to wait about 30 seconds or so and you could make that even longer when just spamming the chip, got to around 2 minutes once. Frustrating

**Comment by thegrb93** [comment]
Huh, thought that was fixed. Will fix it

**Comment by thegrb93** [comment]
Ah, its a new bug

**Comment by thegrb93** [comment]
Fixed
