### ISSUE TITLE
builtin.printMessage - QOL changes

### ISSUE THREAD

**Issue by adamnejm** [thegrb93/StarfallEx#568]
Wiki shows it as shared function, but you can only run it on clientside. It is possible for this function to be called from both client and the server and I would be really happy if that was the case in Starfall.

Due to what I said above we're missing out on HUD_PRINTCENTER, as stated on GWiki:
```HUD_PRINTCENTER will not work when this is called clientside.```
I prefer to use PRINTCENTER, rather than spamming my console or chat.

If you decide to add this on the server side, it would be really nice if we could specify the player rather than just targeting owner of the chip, and also could target players that are in vehicles owned by us.

**Comment by Damianu** [comment]
Yeah it's inside ```if SERVER then``` but doesn't have --@client for some reason.

**Comment by thegrb93** [comment]
The problem is I don't know the effects of spamming it on a player in server-side and if it's malicious then metering would need to be added to it.

**Comment by thegrb93** [comment]
I think https://github.com/thegrb93/StarfallEx/issues/685 is a better solution
