### ISSUE TITLE
Hook inputPressed bug

### ISSUE THREAD

**Issue by Damianu** [thegrb93/StarfallEx#57]
It's called few times instead of only once.

`hook.add("inputPressed","test",function(key)
    if key == 15 then print ("bugs bugs bugs") end
end)`

It prints bugs bugs bugs few times..

**Comment by thegrb93** [comment]
In singleplayer and listen server it works as intended. I'll do some testing to see whats doing on with dedicated server.

**Comment by thegrb93** [comment]
Okay I think its fixed.
