### ISSUE TITLE
HUD Component pixelates your screen

### ISSUE THREAD

**Issue by adamnejm** [thegrb93/StarfallEx#573]
When you connect to a component that is linked to your Starfall chip (even with no code at all, not even directives), your graphics will drop antialiasing. Does not happen when HUD is not linked to a Starfall chip.
Before: https://adamnejm.com/media/2019/05/CK22079HS.jpg
After: https://adamnejm.com/media/2019/05/Uf6208hBy.jpg
Most noticeably on the texture from SProps, this will work outside of visclip areas, even for other players that connect to the HUD

**Comment by thegrb93** [comment]
That's texture filtering. I'll see what is wrong.

**Comment by adamnejm** [comment]
Another weird thing has been found, about the game-breaking glitch I've recently sent u (Sparky) with renderView.
When you place a chip with this code:
`hook.add("renderscene", "", function()
    render.renderView({})
end)`
and theres a Starfall screen present (don't have to link it, doesn't even has to be your screen) even more glitchy shit will happen:
Before: https://adamnejm.com/media/2019/05/uFQ210Ohi.jpg
After: https://adamnejm.com/media/2019/05/gRw211W5t.jpg

**Comment by thegrb93** [comment]
There must be an addon conflict, I dont see these issues.

**Comment by thegrb93** [comment]
Can you try without addons? If it isn't an issue without, then add them back 1-by-1 to find the culprit?

**Comment by adamnejm** [comment]
Ah, tested it on other servers and it was still happening, I guess it must've carried on from server to server. Will make sure to restart the game next time when working with render glitches
Closing

**Comment by thegrb93** [comment]
Did you confirm it to be an addon conflict?
