### ISSUE TITLE
Can't right click on folders in editor

### ISSUE THREAD

**Issue by hobnob11** [thegrb93/StarfallEx#585]
Just updated my dev server to f3cc26e24196792ef279d1726475c00f9c940d93, Wire version wiremod/wire@9a524dcfd369621363b3a7c45ce5020a373ff952, and I can no longer right click on folders inside the wire editor. 
![image](https://user-images.githubusercontent.com/2287055/59569636-0b36dc80-907c-11e9-8db3-4ac147340263.png)
Confirmed that on my production server, running c73f120ac6a1d6fa5b2704f6b3395605f2a41888, Wire version wiremod/wire@ea9f63ec7eb52ae8809a1e4e744c5eea546c6e1e I can right click on folders just fine. 
![image](https://user-images.githubusercontent.com/2287055/59569654-3d483e80-907c-11e9-987c-c1c04452dbf9.png)
(can't really take a picture of being unable to right click something..)
Using the Wire Editor, I updated all of my addons and I assume its either the wire update or the starfall update that caused this but with the latest versions of both it no longer works.

**Comment by thegrb93** [comment]
Yeah, looks like the sorting fixes and restructuring I did caused it. Should be an easy fix
