### ISSUE TITLE
Clientside sounds created with sounds.create aren't stopped/removed when chip is deleted

### ISSUE THREAD

**Issue by CheezusChrust** [thegrb93/StarfallEx#595]
To reproduce: Create and spawn a chip using a long/looping sound file that gets played clientside, then undo the chip. The sound will keep playing.

**Comment by thegrb93** [comment]
It's because the cleanup waits a frame to make sure the entity was actually deleted, but after that it's too late to stop the sound because you can't stop sounds playing on invalid entities. Guess I'll have to work-around that.

https://github.com/Facepunch/garrysmod-issues/issues/3260
