### ISSUE TITLE
Add render.drawSimpleText and markup

### ISSUE THREAD

**Issue by Damianu** [thegrb93/StarfallEx#60]
Same as render.drawText() just allowing to center text vertically, only minus of it is no \n support. It may also be bit faster(?).

Also yeah, I know we can center text with getTextSize(), it's just more comfy for simple labels without new lines.

If it wouldnt be a problem markup type would be also nice to have https://wiki.garrysmod.com/page/markup/Parse

**Comment by thegrb93** [comment]
Done
