### ISSUE TITLE
Replace all IsValid(ent) with ent and ent:IsValid()

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#603]
The global IsValid is much slower

**Comment by adamnejm** [comment]
You want both of those checks or either one is enough?

**Comment by thegrb93** [comment]
If ent can be nil then both, otherwise just ent:IsValid(). unwrap can return nil so the functions you added would need both.

**Comment by Damianu** [comment]
Notice that usually unwrap is used after checktype which won't allow nil

**Comment by thegrb93** [comment]
unwrap itself can return nil

**Comment by adamnejm** [comment]
Will fix again in a moment
Note to self: ditch Damianu's advices
