### ISSUE TITLE
render.setResolution(w,h)

### ISSUE THREAD

**Issue by Damianu** [thegrb93/StarfallEx#61]
I know it can be pretty hard to make, but I think it would give awesome abilities.
Especially changing aspect ratio(for different props) with that function would allow us to make screens look way better. Designing 1x1 is much harder(imo) than widescreens where you can make 2 colums not looking crowded etc, you can already achieve it using EGP emitter(without screen model tho).
So  yeah, I think it would be awesome thing to have in starfall.

**Comment by thegrb93** [comment]
It's very easy actually with the rendering code I did. I'll do it soon.

**Comment by thegrb93** [comment]
Problem. What if people want their aspect ratio to be perfect with the screen, but they don't know its dimensions? I'm not sure if I should allow modification of the aspect ratio.

**Comment by thegrb93** [comment]
I don't really see the point in this actually. Just use the pushMatrix function if you want to scale your rendering to different coordinate systems.
