### ISSUE TITLE
entites.applyDamage not restricted

### ISSUE THREAD

**Issue by adosikas** [thegrb93/StarfallEx#63]
I am not familiar with how the permission system works, but it looks like entites.applyDamage is not restricted in the same way as other permissions, allowing anyone to damage anyone else.

Defined here:
https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/libs_sv/entities.lua#L26

But not listed alongside the other functions here:
https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/permissions/providers_sv/CPPI.lua

(Also looks like entities.setColor is attached to cantool, but not used anywhere)

Maybe a solution to avoid this issue in the future would be to allow adding to cantool/canphysgun directly in the register function or having a special wrapper like P.registerPrivilegeCanTool as generic PP privileges can be useful for many things.

**Comment by thegrb93** [comment]
The whole permission system is a mess. I would definitely like to rewrite it sometime. Thanks for catching that.

**Comment by its-suun** [comment]
Credits go to [Forsaken](http://steamcommunity.com/id/Panda_master/) for finding the bug
