### ISSUE TITLE
Add an option for owner to connect to it's own HUD remotely

### ISSUE THREAD

**Issue by adamnejm** [thegrb93/StarfallEx#632]
Enhancement, QOL change.

Currently you change to allow concmd, which is not that big of a deal, I use it fairly a lot, but then setting position of the HUD component in front of your eyes, executing '+use'; '-use', setting its position back, it's a mess if you want auto-connecting HUD.

Either console command along the lines of 'sf_hud_connect [entindex]' or some command would be nice.

**Comment by thegrb93** [comment]
a function could be added. Like render.enableHUD or something

**Comment by Damianu** [comment]
I'd say render.enableHUD(ent), if ent is not provided then it just uses first one it finds connected to current chip

**Comment by thegrb93** [comment]
I think it could work with any ent at all. Then the HUD ent wouldn't even be needed.

**Comment by adamnejm** [comment]
Executing **Entity:Use()**, good idea. Some possibility of abuse tho.
