### ISSUE TITLE
Hologram:setAnimation() breaks the scale

### ISSUE THREAD

**Issue by adamnejm** [thegrb93/StarfallEx#637]
Not sure, but seems like this line
https://github.com/thegrb93/StarfallEx/blob/b56ab98f09d2ad12c0456fa5abd4d56b402655aa/lua/starfall/libs_sh/holograms.lua#L258
is overriding whole Think method of the hologram entity
https://github.com/thegrb93/StarfallEx/blob/b56ab98f09d2ad12c0456fa5abd4d56b402655aa/lua/entities/starfall_hologram/init.lua#L32
which contains scale update logic

**Comment by thegrb93** [comment]
Yea, I can fix that.

**Comment by adamnejm** [comment]
Also, not sure of the way you want to implement setParent on CL, but I suppose it would have to be on a constant update, thus this is a good time to make Holo:Think() run multiple functions, for scale, anim and in the future - parent.
