### ISSUE TITLE
add Function that can convert .obj to mesh vertices

### ISSUE THREAD

**Issue by tomekb530** [thegrb93/StarfallEx#647]
Could you add some server side function to conver .obj to vertices that we can use with prop.createCustom?

**Comment by thegrb93** [comment]
Yeah, I'll do that.

**Comment by thegrb93** [comment]
Added mesh.parseObj,

You're going to want to do
```lua
local triangles, data = mesh.parseObj(obj)
prop.createCustom(Vector(),Angle(),{data.positions})
```
