### ISSUE TITLE
False alarms from RAM usage cap

### ISSUE THREAD

**Issue by mitterdoo** [thegrb93/StarfallEx#648]
Currently, the detection for RAM usage just runs a GLua function that returns the current size of the garbage *of the entire GLua environment in-game*. This means other things can trigger the RAM limit on players, even if a chip is *only* being run serverside.

Although an *increase* in garbage in a chip can be detected by comparing garbage counts before and after chip execution, I don't think there is a way to detect a *decrease* in garbage used by the chip. A potential solution, would be to use the same sort of "rolling quota" that CPU usage utilizes, or use a Starfall Burst class instead. Instead of monitoring execution time, however, it may monitor the increase in garbage.

**Comment by thegrb93** [comment]
I think the cap should be larger yeah. Its main purpose is to keep chips from making other addons error via out of memory errors

**Comment by thegrb93** [comment]
Other checks might be added to prevent garbage collector thrashing, but that's a lot trickier.
