### ISSUE TITLE
Make obj parsing not require normals or texture coordinates

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#649]

**Comment by thegrb93** [comment]
People are going be scratching their head trying to figure out why their mesh isn't rendering correctly without this so nvm.

**Comment by adamnejm** [comment]
Please consider this again, I'd guess most programs (Blender for sure does it) will include those on export by default.

**Comment by thegrb93** [comment]
It doesn't include normals by default which left me confused for a while when I was first attempting custom meshes.

**Comment by thegrb93** [comment]
You can easily copy the code from the mesh library if you want your own .obj parser.

**Comment by adamnejm** [comment]
Well I guess thats fine, but just have to argue here that Blender does include normals by default ;) At least 2.8+ does, but I remember 2.79 doing it as well
https://media.adamnejm.com/2019/11/NbNNb.mp4
Anyway, keep it closed no hard feelings
