### ISSUE TITLE
Traces return an empty table even if you allow it via permissions

### ISSUE THREAD

**Issue by Etothepowerof26** [thegrb93/StarfallEx#651]
[I have allowed traces to be ran](https://i.imgur.com/ixmXIrl.png)

but with this piece of code:
```
--@name EyeTrace returns nothing
--@author
--@shared

if SERVER then
    printTable(owner():getEyeTrace())
else
    printTable(player():getEyeTrace())
end
```

the results are empty tables, but I should be expecting a trace result:
```
{}
{}
```

Here is some more testing with a helper function (and this also outputs 2 empty tables):
```
--@name Traces return nothing
--@author
--@shared

local function quickTrace(ply)
    return trace.trace(
        ply:getShootPos(),
        ply:getAimVector() * (4096 * 8),
        ply
    )
end

if SERVER then
    printTable(quickTrace(owner()))
else
    printTable(quickTrace(player()))
end
```

**Comment by thegrb93** [comment]
It's an empty table with an __index metamethod. try getEyeTrace().Entity and it will work. If the __pairs metamethod was implemented, then this could be fixed, but it's not unfortunately.

**Comment by Etothepowerof26** [comment]
Thanks for clarifying
