### ISSUE TITLE
If installed, expose some VRMod functions in SF

### ISSUE THREAD

**Issue by Neatro** [thegrb93/StarfallEx#654]
some ( client and serverside ) functions to get VR "data" like positions and such. There is no documentation on it, though reading through the addon's code, this shouldn't be a hard addition.

**Comment by thegrb93** [comment]
Link to said addon?

**Comment by thegrb93** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1678408548

This I assume?

**Comment by thegrb93** [comment]
Looks like it uses https://github.com/catsethecat/vrmod-module which someone would just need to write a starfall wrapper for.

**Comment by thegrb93** [comment]
Just look at the joystick and xinput libraries to get an idea of how to make it.

**Comment by Neatro** [comment]
Yes that addon indeed, i'll look into it soon on integrating it

**Comment by thegrb93** [comment]
I'm probably not going to be adding this. But anyone else is free to work on it.
