### ISSUE TITLE
Allow access to GLua Vector/Angle?

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#66]
Only problem is that all the vector function names will need to be aliased to match SF camel casing.
Might also be potentially a security problem which I'm unsure of. If anyone can confirm then I'll close this.

**Comment by its-suun** [comment]
Any existing code would also break if method names would start starting with an uppercase letter.

**Comment by thegrb93** [comment]
That's what the aliases would be for

**Comment by thegrb93** [comment]
To anyone who knows security issues that might arise from exposing the raw glua Color Vector Angle Matrix types, some advice would be appreciated.

**Comment by thegrb93** [comment]
If this is ever done, would need to to add __metatable metamethod to their metatables while running to prevent getting their metatable.

**Comment by thegrb93** [comment]
Okay, we're not going to give access to the glua vectors, but doing away with the wrapping on the number tables will work fine.

**Comment by thegrb93** [comment]
Nvm, doing this will create loads of garbage and make vector functions similar to e2
