### ISSUE TITLE
render.createPoly doesn't work

### ISSUE THREAD

**Issue by its-suun** [thegrb93/StarfallEx#67]
```lua
--@client
print(#render.createPoly{
    Vector(1, 1, 0.0),
    Vector(256, 256, 0.0)
})
```
prints `0`
If you try to draw that poly it shows nothing.

**Comment by thegrb93** [comment]
Looks like it should take tables instead of vectors, i.e. {x1, y1}, {x2, y2}

**Comment by thegrb93** [comment]
x, y are position and u, v are texture coordinates.

**Comment by thegrb93** [comment]
I'll update the help text

**Comment by thegrb93** [comment]
Nvm, fixed it
