### ISSUE TITLE
Type metatable setting each frame causing luaJIT issues

### ISSUE THREAD

**Issue by GaghrACF** [thegrb93/StarfallEx#674]
Running a starfall chip server-side causes all e2 chip CPU readings to increase.

**Comment by thegrb93** [comment]
Haha wtf

**Comment by thegrb93** [comment]
It happens even when I turn off starfall's cpu time measuring so it isn't that. Gotta be something else.

**Comment by thegrb93** [comment]
It happens without the hook.Add("Think", "SF_Think", ... so it's not that.

**Comment by thegrb93** [comment]
Found it. Looks like https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/libs_sh/builtins.lua#L583 is giving luaJIT an aneurysm.
