### ISSUE TITLE
Clientside CPPI Permissions don't always work correctly

### ISSUE THREAD

**Issue by DaDamRival** [thegrb93/StarfallEx#676]
Clientsided permissions (entities.setRenderProperty for example) that relay on CPPI don't always work correctly. This is can happen if the PP doesn't create a CPPI table on the clientside resulting in Starfall CPPI permissions to use CPPI methods on the serverside but it's own on the clientside resulting in the error 'The entity's owner hasn't been transmitted yet or doesn't exist
'. Something else that can also happen is that the CPPI table does exist on the clientside but the CPPIGetOwner and other methods hasn't been implemented or return CPPI_NOTIMPLEMENTED on the clientside resulting in the error 'You're not the owner of this prop' or similar errors for other permission modes. (Tested with NadmodPP)

**Comment by thegrb93** [comment]
NadmodPP doesn't have clientside CPPI so it should fall-back to starfall's own in that case. However, since the serverside does have CPPI, starfall doesn't bother sending the required stuff to the client for its own cppi.

**Comment by thegrb93** [comment]
Pretty annoying

**Comment by thegrb93** [comment]
https://github.com/Nebual/NadmodPP/pull/3
