### ISSUE TITLE
render.getTextureID() for gif?

### ISSUE THREAD

**Issue by Captain-Rusky** [thegrb93/StarfallEx#68]
When i do render.getTextureID for a gif file it only shows the first frame, is there anyway to show the full gif or show a certain frame?

**Comment by thegrb93** [comment]
Images from urls are opened with an html panel and once it finishes loading, it's texture is copied and the panel is closed. The solution for this is to keep the panel open and use the panel's texture instead of copying it. Frame control can probably be done with javascript.

**Comment by Captain-Rusky** [comment]
How would i aboe to keep the panel open? I am unsure on how I would be able to do it.

**Comment by thegrb93** [comment]
The starfall code that handles html textures needs to be changed so that the panel isn't removed.

**Comment by edgarasf123** [comment]
You could also probably convert gif to spritesheets

**Comment by thegrb93** [comment]
I probably won't do this since cpu usage of html panels can't be monitored. A sprite sheet + drawTexturedRectUV is a much better idea.
