### ISSUE TITLE
HL2 Weapon selection function

### ISSUE THREAD

**Issue by Neatro** [thegrb93/StarfallEx#692]
This could be used for custom HL2 huds
Will only work on players connected to a Starfall HUD element.
`CUserCmd:SelectWeapon( Weapon weapon )`
https://wiki.garrysmod.com/page/CUserCmd/SelectWeapon

This most likely needs a (server admin) permission so it can't be abused

Locking the inventory can be done using #691

**Comment by thegrb93** [comment]
#691 can't lock the inventory. I don't think it needs to be admin only, but I don't really know the usefulness of this being added except for making a custom inventory (which should be done in glua to begin with).

**Comment by thegrb93** [comment]
I think https://wiki.garrysmod.com/page/input/SelectWeapon would be a more correct binding

**Comment by thegrb93** [comment]
We can give it its own permission so having hud connected is unnecessary.
