### ISSUE TITLE
Make a render state class.

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#699]
Keeps track of render state and only calls render functions when needed so that we can exit render hooks without calling 100 render functions.

**Comment by thegrb93** [comment]
Would also be good to keep a stack of these to preserve them between render scopes.

**Comment by thegrb93** [comment]
Probably can also store the matrix and rendertarget states.

**Comment by Neatro** [comment]
This can definitly speed things up regarding rendering overall

**Comment by thegrb93** [comment]
Yeah, it could also prevent duplicate calls.

**Comment by thegrb93** [comment]
I think this would change too much with too little benefit.
