### ISSUE TITLE
constraint.ballsocketadv() rotateonly parameter has no effect -> cannot create traditional ballsocket

### ISSUE THREAD

**Issue by TurkeyKittin** [thegrb93/StarfallEx#705]
Parameters:
constraint.ballsocketadv( e1, e2, bone1, bone2, v1, v2, force_lim, torque_lim, minv, maxv, frictionv, rotateonly, nocollide )

From what I can tell, rotateonly should enable and disable free movement of the constrained entities. The only way I can get a restricted traditional ballsocketadv now is by using constraint.ballsocket() for the movement restriction, and constraint.ballsocketadv() for the angular limits simultaneously.

**Comment by adamnejm** [comment]
Are you using local position of the props in 5th and 6th argument?
When recreating the issue and supplying global entity position i got weird sort of ballsocket-slider effect, but when I did Vector(0,0,0) in both it worked exactly like the traditional Advanced Ballsocket.

**Comment by adamnejm** [comment]
And rotateonly is working fine for me

**Comment by adamnejm** [comment]
`// constrained movement
local e1 = prop.create(chip():getPos() + Vector(-30,0,45), Angle(), "models/hunter/blocks/cube05x05x05.mdl", 1); e1:setColor(Color(255,0,0))
local e2 = prop.create(chip():getPos() + Vector(30,0,45),  Angle(), "models/hunter/blocks/cube05x05x05.mdl", 1); e2:setColor(Color(255,0,0))
constraint.ballsocketadv(e1, e2, 0, 0, Vector(0), Vector(0), 0, 0, -Vector(180,180,180), Vector(180,180,180), Vector(0,0,0), false, false)

// free movement
local e3 = prop.create(chip():getPos() + Vector(-30,50,45), Angle(), "models/hunter/blocks/cube05x05x05.mdl", 1); e3:setColor(Color(0,255,0))
local e4 = prop.create(chip():getPos() + Vector(30,50,45),  Angle(), "models/hunter/blocks/cube05x05x05.mdl", 1); e4:setColor(Color(0,255,0))
constraint.ballsocketadv(e3, e4, 0, 0, Vector(0), Vector(0), 0, 0, Vector(0), Vector(0), Vector(0,0,0), true, false)
`

**Comment by thegrb93** [comment]
Can you do it with the tool itself? Starfall should have the same exact behavior.

**Comment by thegrb93** [comment]
Assuming it's not a bug
