### ISSUE TITLE
Hologram deinitlialization doesn't work when script crashes in a rendering hook

### ISSUE THREAD

**Issue by adamnejm** [thegrb93/StarfallEx#706]
Steps to reproduce:
```
holograms.create(chip():getPos(), Angle(), "models/holograms/cube.mdl")

render.setHUDActive(true)
hook.add("predrawopaquerenderables", "", function()
    throw(";o")
end)
```

This is not a problem with `render.setHUDActive()`.

Tested on following hooks:
**predrawopaquerenderables**
**postdrawhud**
**drawhud**
**render** (steps to reproduce vary - link screen to the chip)

LUA ERROR:
https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/libs_sh/holograms.lua#L72

>  **[ERROR] Entity:Remove cannot be called while rendering**
>   1. unknown - addons/starfallex/lua/starfall/libs_sh/holograms.lua:72
>    2. runLibraryHook - addons/starfallex/lua/starfall/sflib.lua:563
>     3. deinitialize - addons/starfallex/lua/starfall/instance.lua:348
>      4. Error - addons/starfallex/lua/entities/starfall_processor/shared.lua:134
>       5. runOnError - addons/starfallex/lua/entities/starfall_processor/shared.lua:48
>        6. Error - addons/starfallex/lua/starfall/instance.lua:426
>         7. runScriptHook - addons/starfallex/lua/starfall/instance.lua:284
>          8. v - addons/starfallex/lua/starfall/libs_sh/hook.lua:40
>           9. unknown - lua/includes/modules/hook.lua:84

**Comment by adamnejm** [comment]
The same error occurs when you're trying to do Hologram:remove(), but chip does not crash from it.

**Comment by thegrb93** [comment]
This a new gmod restriction?

**Comment by thegrb93** [comment]
Looks like server's script is conflicting with it.

**Comment by thegrb93** [comment]
Nvm, my reproduction script was bad.

**Comment by thegrb93** [comment]
I guess an easy solution is put the hologram cleanup in a timer.

**Comment by thegrb93** [comment]
well, we can pcall the cleanup and put any fails in a timer.

**Comment by adamnejm** [comment]
If that escapes the rendering scope then sure
