### ISSUE TITLE
Referencing undefined variable "on" in cl_lights.lua

### ISSUE THREAD

**Issue by FPtje** [thegrb93/StarfallEx#707]
To not bother other people in [this issue](https://github.com/Facepunch/garrysmod-requests/issues/1441), let's continue here.

You mentioned the following warning being a false positive:
```
.\lua\starfall\libs_cl\light.lua: [Warning] line 215, column 35 - line 215, column 37: Variable 'on' shadows existing binding, defined at line 127, column 8
```

It isn't really, though the actual source of the error is in the second location (line 127). Here's what happens:

Line 127 is part of the following function:
```lua
function light_library.create(pos, size, brightness, color)
	if table.Count(SF.instance.data.light.lights) >= 256 then SF.Throw("Too many lights have already been allocated (max 256)", 2) end
	if maxSize:GetFloat() == 0 then SF.Throw("sf_light_maxsize is set to 0", 2) end
	checkpermission(SF.instance, nil, "light.create")
	checktype(pos, vec_meta)
	checkluatype(size, TYPE_NUMBER)
	checkluatype(brightness, TYPE_NUMBER)
	checktype(color, col_meta)
	local slot = getFreeSlot()
	if not slot then SF.Throw("Failed to allocate slot for the light", 2) end

	local col = cunwrap(color)
	local light = {
		data = {pos = vunwrap(pos), size = math.Clamp(size, 0, maxSize:GetFloat()), brightness = brightness, r=col.r, g=col.g, b=col.b, decay = 1000},
		slot = slot,
		dietime = 1,
		on = on -- <-- LINE 127!
	}

	SF.instance.data.light.lights[light] = true
	gSFLights[slot] = light

	return wrap(light)
end
```

The `on` variable here (probably) isn't defined. That's a bug. Glualint doesn't know `on` isn't defined, since for all it knows, `on` might be defined somewhere as a global. That's what it then assumes: you use it, and it's not defined locally, so it must be defined globally. Then when it reaches line 215, it finds the name `on` being re-used:

```lua
function light_methods:setNoWorld(on)
```

`on` Was assumed to be global, so then this parameter with the same name must be shadowing that global.

Granted, the warning isn't very clear, and the actual programmer error lies in a different place than reported. That should be fixed in glualint. Still, the warning points to a very real bug in your code. I suppose you should have some logic that sets `on` to a real value, or just default it to `false` or something.

**Comment by thegrb93** [comment]
Dead code, yeah, but not a bug. Might as well remove it
