### ISSUE TITLE
Cant spawn components

### ISSUE THREAD

**Issue by norrbotten** [thegrb93/StarfallEx#708]
[ERROR] addons/starfallex/lua/weapons/gmod_tool/stools/starfall_component.lua:109: attempt to call global 'MakeComponent' (a nil value)
  1. LeftClick - addons/starfallex/lua/weapons/gmod_tool/stools/starfall_component.lua:109
   2. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:240

**Comment by adamnejm** [comment]
Made a Pull Request fixing it. Keep in mind that components created using `prop.createComponent` were not affected by this and can still be created without any issues while you wait for the merge.
