### ISSUE TITLE
Web texture bug

### ISSUE THREAD

**Issue by Damianu** [thegrb93/StarfallEx#71]
I think that web textures arent getting disposed propperly, when I refresh my code loading 2 textures after some time they can stop loading until reconnect.

**Comment by thegrb93** [comment]
I've noticed it too. I've tried debugging but its really hard to debug weak tables. I'll see if anyone knows any weak table debugging techniques.

**Comment by thegrb93** [comment]
It could also just be that the garbage collector hasn't gotten to cleaning them yet, which is unpredictable.

I think the best solution may be to ditch weak tables all together and introduce a "render.freeTexture" function.

**Comment by Damianu** [comment]
Well I didnt really get into code of handling those, but maybe console command like "sf_freeTextures" would be possible?
