### ISSUE TITLE
Add Entity:GetModelBounds()

### ISSUE THREAD

**Issue by adamnejm** [thegrb93/StarfallEx#719]
[Entity:GetModelBounds()](https://wiki.garrysmod.com/page/Entity/GetModelBounds)

**Comment by adamnejm** [comment]
[Entity:GetModelRadius()](https://wiki.garrysmod.com/page/Entity/GetModelRadius) Could be useful as well

**Comment by thegrb93** [comment]
How does it differ from OBBMins and OBBMaxs

**Comment by adamnejm** [comment]
I was convinced OBB gives you collision bounds.
Ignore.
