### ISSUE TITLE
FastLZ broken?

### ISSUE THREAD

**Issue by Damianu** [thegrb93/StarfallEx#73]
Code: 

print(fastlz.compress("TEST"))
print(fastlz.compress("TEST2"))    
print(fastlz.compress("TEST3"))

always returns "]"

**Comment by thegrb93** [comment]
The result contains null characters which will stop the print function from printing it all.
Try 'print(#fastlz.compress("TEST"))'

**Comment by Damianu** [comment]
Yeah, that's what happens when you code at night, sorry ;x.
