### ISSUE TITLE
Getting an Error in Server Console Every Tick

### ISSUE THREAD

**Issue by bellum128** [thegrb93/StarfallEx#730]
Something appears to trigger this error on our server, and I'm not sure what.
It seems to happen psuedo-randomly, and I don't even think it is caused by players spawning a Starfall dupe with Advanced Dupe 1 as the error implies.

The error appears every tick or so, spamming the console.

We also auto-update all legacy addons daily from GitHub if possible, so it should be at the latest version.

Please advise on if there is a glaring mistake on my end that I need to do (as I couldn't seem to find any installation documentation).

```
[Advanced Duplicator] addons/starfallex/lua/entities/starfall_processor/init.lua:141: attempt to call method 'IsValid' (a nil value)
  1. v - addons/starfallex/lua/entities/starfall_processor/init.lua:141
   2. Run - lua/includes/modules/hook.lua:84
    3. FinishPasting - lua/autorun/server/advdupe.lua:2412
     4. v - lua/autorun/server/advdupe.lua:1730
      5. unknown - lua/includes/modules/hook.lua:84
```

**Comment by thegrb93** [comment]
Duplicator is putting a non-entity in CreatedEntities table. I recommend removing AdvDupe1 in favor of AdvDupe2. AdvDupe2 is less buggy and can still load Advdupe1 files.

**Comment by bellum128** [comment]
Yeah we definitely heavily push Advanced Dupe 1 on our server, and the only reason I could think to keep it is for the public folder that some newer players might enjoy.
Is there any way you could throw in a valid entity check at the line that created the error on the Starfall end? It would be nice if the two addons could co-exist, especially since Adv Dupe 1 is such a historic addon.

**Comment by bellum128** [comment]
(Fixed some important typos)
