### ISSUE TITLE
Inconsistent layout with materials

### ISSUE THREAD

**Issue by DaDamRival** [thegrb93/StarfallEx#734]
The layout function is very buggy and inconsistent, in the scenario below the mat1 and mat3 will set the layout fine but the mat3 won't when you first run the code on a fresh server. Running the code again will make some materials set the layout fine and other won't. But if you comment out mat1 and mat3, mat2 will set the layout fine first time on a fresh server but after that it will never set it.

```lua
--@client

local base64 = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA9UlEQVQ4y42Suw0CMRBET6ILInToTnwlImISCBApCVUQ0AcFUAJFUBE1LBpLzxruw2Fp5fV6Z7w73qKwdZuOYnKog/Pyuoj6UqWz4viDCxIRbE9laFfsVc2TvTer+AkWAP94n2WwgI9y3E1CImCVy1m72ov9LgEhar0OSZOQSkQia4FVEiBePj/XGSzfyVtgL0vJvIhoXo3HE4FAMkh4GWL1rXsnRYvUiieqPyWJBFJXX3HOWQs5BClTiSQAFjGt8JVfE+hzQDKqM4WI2juR/vco79+IPzjGqA2hgxm0ztVMpGevjPb+IvEKXIdesC4xB/ogYWA+zZlLZzGJgi4AAAAASUVORK5CYII="

local function cb(_, _, _, _, layout)
    layout(0, 0, 1024, 1024)
end

local mat1 = render.createMaterial("https://u.teknik.io/LmVxF.png", cb)
local mat2 = render.createMaterial(base64, cb)
local mat3 = render.createMaterial("https://u.teknik.io/LmVxF.png", cb)

hook.add("render", "", function()
    render.setMaterial(mat1)
    render.drawTexturedRect(0, 0, 256, 256)
    
    render.setMaterial(mat2)
    render.drawTexturedRect(256, 0, 256, 256)
    
    render.setMaterial(mat3)
    render.drawTexturedRect(0, 256, 256, 256)
end)

```

**Comment by thegrb93** [comment]
What gmod branch? And yea, I saw a texture load wrong recently too on chromium. Still needs work.

**Comment by DaDamRival** [comment]
x86-64 - Chromium + 64-bit binaries
Linux

**Comment by thegrb93** [comment]
The only thing I've found so far that helps is changing the `renderImage();` after doing layout to `setTimeout(renderImage, 500);`. I'm hoping for a better solution. maybe something like img.onlayout or something like that.

**Comment by thegrb93** [comment]
I might try more requestAnimationFrame too.

Might also try window.onpaint

**Comment by thegrb93** [comment]
Found this snippet too, might be worth trying.

```javascript
// after preloading the image

requestAnimationFrame(function() {
   /*
   ... code to add the image to the dom
   */

   requestAnimationFrame(function() {
      document.body.offsetWidth // force repaint

      requestAnimationFrame(function() {
         // image is painted
      })
   })
})
```

**Comment by thegrb93** [comment]
That snippet seems to work

**Comment by thegrb93** [comment]
Hm your example still fails tho. Seems they are empty sometimes

**Comment by thegrb93** [comment]
Ok got it
