### ISSUE TITLE
Add HTML & CSS (Material from DHTML Panel)

### ISSUE THREAD

**Issue by adamnejm** [thegrb93/StarfallEx#736]

**Comment by adamnejm** [comment]
Disallowing JS or sandboxing it with use of CSS classes like
<div class="myClass  onclick"></div>
OR
<div class="myClass" onclick="starfall.onclick(args)"></div>
and internally making use of DHTML.AddFunction
And allowing only minimal SF -> JS interactions like adding/removing classes or elements

Even when HTML would be stripped down to minimum, divs text etc and maybe some crazier stuff with appropriate perms like img tags.

https://wiki.garrysmod.com/page/Category:DHTML

**Comment by thegrb93** [comment]
If we can limit the number of nodes created and which nodes are created and enforce url whitelists then maybe it could work.
