### ISSUE TITLE
Convar or detection for game branch

### ISSUE THREAD

**Issue by Neatro** [thegrb93/StarfallEx#737]
Since chromium and awesomium work different regarding url textures and FFT, maybe we can have best of both worlds if the user can choose (or it's automatically detected) which branch, and in which code to use to load the images in Starfall

**Comment by thegrb93** [comment]
Anyone know if there's a glua function for this?

**Comment by Neatro** [comment]
https://wiki.garrysmod.com/page/Global_Variables
globsl var BRANCH it seems, should show which branch you are on

**Comment by thegrb93** [comment]
What's the awesomium branch string? I don't feel like switching atm.

**Comment by Neatro** [comment]
Ill look in a bit, gimme few hours

**Comment by thegrb93** [comment]
Not sure about exposing it to the starfall libraries but I can fix the branch dependencies.

**Comment by Neatro** [comment]
Ran on "NONE" branch: `print( BRANCH )` -> `unknown`
Ran on "x86-64 - Chromium + 64-bit binaries" branch on 32 bit: `print( BRANCH )` -> `x86-64`
Ran on "x86-64 - Chromium + 64-bit binaries" branch on 64 bit : `print( BRANCH )` -> `x86-64``
Ran on "chromium - discontinued" branch on 64 bit : `print( BRANCH )` -> `chromium`

**Comment by thegrb93** [comment]
Actually I don't think I want to do this because I'll have to remember to remove them when the game updates.
