### ISSUE TITLE
When opening a chip, don't open includes if they exist already and match existing ones.

### ISSUE THREAD

**Issue by adamnejm** [thegrb93/StarfallEx#738]
1. Let owner of the code comment outthe include directive and don't download them to player that opened the chip
2. If uncommented make a popup informing about importing included files, let accept or decline

**Comment by thegrb93** [comment]
I think the only thing I'd be willing to add is a directive that makes opening a chip not possible.

**Comment by thegrb93** [comment]
Actually, it wouldn't be a directive. I think it would be a toolgun option.

**Comment by adamnejm** [comment]
Well that doesn't solve anything really

**Comment by thegrb93** [comment]
Explain your request better because I'm misunderstanding then.

**Comment by adamnejm** [comment]
I honestly think even something really simple like Derma popup for each included file to open in editor (like we have for closing unsaved files) would be nice

**Comment by adamnejm** [comment]
Let's say you have a library, other person has it too, but in different directory, there's really no need for him to fetch the included files in this case (which might be quite a few if lib is not contained in a single file). Not asking you too look for the files in his folder tree, rather just an option to disable opening included files in a chip you open - only the main one.

**Comment by thegrb93** [comment]
Well a gui would be a lot slower than just ctrl+w the tabs that opened.

**Comment by thegrb93** [comment]
Is that sufficient and can this be closed?

**Comment by adamnejm** [comment]
Well I still use "Close all but this" and get 10 or 20 popups, commenting would be nice or a single popout if to import all or not. But whatever, close if you want

**Comment by thegrb93** [comment]
We could maybe only open the tabs if the files aren't already saved in your disk.
