### ISSUE TITLE
Custom Prop fails to sync to new players

### ISSUE THREAD

**Issue by DaDamRival** [thegrb93/StarfallEx#744]
Custom props fail to sync to new players. This most likely happens because the net library is highly unreliable in the PlayerInitialSpawn, the [gmod wiki](https://wiki.garrysmod.com/page/GM/PlayerInitialSpawn) recommends using a timer with a delay of at least 5 seconds as a quick and dirty workaround

**Comment by thegrb93** [comment]
someone recommended SetupMove hook might work too, so I'll test that out.

**Comment by thegrb93** [comment]
Not sure if its fully fixed or not. Can reopen if more issues happen
