### ISSUE TITLE
Allow hiding holograms for certain players from serverside

### ISSUE THREAD

**Issue by adamnejm** [thegrb93/StarfallEx#745]
Since clientside code doesn't run for each player on the server (based on their position relative to the executing chip), hiding SV holograms would be a nice feature.
Right now I would have to teleport my chip to each and every player on the server, wait for him to load the code and then set the color.

**Comment by thegrb93** [comment]
The client code is supposed to do this so I'm not adding this feature. A better solution is to find a way to get the starfall entity to transmit to all players regardless of their pvs.
