### ISSUE TITLE
Find some way to get the starfall processor to transmit/initialize regardless of PVS

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#746]

**Comment by adamnejm** [comment]
To be honest, not all scripts require to be run by all players.
A new directive that tells it to transmit regardless of PVS would be nice. Separate timebuffer could also be used (maybe 15-25% of the default 0.006) when script is running from a chip that's in a separate PVS.
With all that new hooks could also help determine who ran / unloaded the script from a different PVS.

**Comment by thegrb93** [comment]
I'd rather it be consistent, but the first step is figuring out how to even make this possible.

**Comment by thegrb93** [comment]
Another option would be to make the instance independent of the chip entitiy.

**Comment by adamnejm** [comment]
Ah yes, that's a good idea indeed.
But wouldn't using engine flag `EFL_FORCE_CHECK_TRANSMIT` on initial load and when player changes PVS work?

https://wiki.garrysmod.com/page/ENTITY/UpdateTransmitState

Or maybe just always returning `TRANSMIT_ALWAYS` in the update state hook would work?

**Comment by thegrb93** [comment]
Yeah, I think that would work.
