### ISSUE TITLE
Starfall Screen interferes with other render elements

### ISSUE THREAD

**Issue by adamnejm** [thegrb93/StarfallEx#747]
Starfall Screen when in view and under certain angles / positions will cut 3/4 off other render elements, leaving always(?) bottom right portion.
This includes, but is not limited to:
- EGP v3 / Wire Screens
- Some "Hover Names" addons
- Weight STool tooltip

Problem is not isolated, I'm pretty sure everyone experiences it.
I've checked Weight STool code and it uses cam.Start3D2D so it might not be problem with RTs

Screenshots:
https://media.adamnejm.com/2019/12/9w6rh.jpg
https://media.adamnejm.com/2019/12/mi6pC.jpg

**Comment by thegrb93** [comment]
The call to surface.DisableClipping( false ) is what's causing it.
