### ISSUE TITLE
Performance issues on other players using screens and render

### ISSUE THREAD

**Issue by F0x06** [thegrb93/StarfallEx#750]
Hi, first of all this project is amazing !

I have a wired performance issue and can't find the solution, let me explain:

If i create anything that renders lines on a screen inside the `render` hook, my friend have higher Client CPU usage about 4-6 times more, Even with a single line drawn on the screen.

I noticed that when creating an oscilloscope, worked perfectly on my side, but the chip exceed quota on all other players with about 4-6 times higher usage, i don't understand :/

If my friend spawns the chip the issue is reversed an i higher usage on my side.

Any ideas ? Thanks

**Comment by adamnejm** [comment]
GitHub is more about issues related to the 'source' code of Starfall.
For further questions like this, please visit official Discord and post them in **#help** channel.

Quota limit (or time buffer) is set individually by the player on his client.
Default quota for owner of the chip is 0.015 `sf_timebuffer_cl_owner`
Default quota for chips spawned by other players is 0.006 `sf_timebuffer_cl`

If I'm not mistaken, the actual usage will differ depending on the player's PC, but I'll always be around the same value, no matter if spawned by you or somebody else and no matter the console commands I've mentioned  earlier.

The thing that's crashing chips is usage hitting the timebuffer limit.
Personally I like to keep it at 0.1, for both, myself and other players.

You can ask your friends to increase it, but it's always wise when working with something that'll require "a lot" of CPU to put an limit yourself - search for `quota` in the documentation for related functions.

Make sure you're also using RenderTargets when drawing a lot of things each frame that are static and/or can be drawed less frequent.

**Comment by F0x06** [comment]
Thanks for the reply, we already tried to put `0.015` on both sides, we have equivalent high-end gaming pc's and his execution time is 4x slower than mine, sure i can optimize with RenderTargets but i don't understand how we can get 4x difference, like i said `if my friend spawns the chip, the problem reverses and i'm 4x slower`

Maybe the ping is a factor ? My friend have 35 avg and me 17

**Comment by thegrb93** [comment]
What server are you running it on? some servers have heavier permission overhead.

**Comment by thegrb93** [comment]
I think the issue is permission overhead. That would explain why it runs faster for the owner, since less permission checking is being done.

**Comment by thegrb93** [comment]
If you're able to use FProfiler, you can do sf_timebuffer_softlock_cl 0, respawn the chip, and run the profiler to see what's consuming the cputime.

**Comment by F0x06** [comment]
> I think the issue is permission overhead. That would explain why it runs faster for the owner, since less permission checking is being done.

Little update, my friend realized that his game was on the deprecated chromium branch... After switching back to default and ensuring we have `0.015` for `sf_timebuffer_cl_owner ` and `sf_timebuffer_cl` on both sides, his machine is `5%` slower according to the `Client CPU` on the chip which is a lot better.


Its my own server, i'll try to profile with FProfiler / Gcompute to see and also disable all addons except WireMod and SFX.

**Comment by F0x06** [comment]
5% is ok so i'm closing this issue, thanks for the help :)

**Comment by thegrb93** [comment]
np

**Comment by F0x06** [comment]
BTW, when i try to join the discord server specified in the README i got an "Invalid invite" error, can i have the link please ? Thanks :)

**Comment by adamnejm** [comment]
https://discord.gg/44Ec5uX
