### ISSUE TITLE
Add debug.getlocal

### ISSUE THREAD

**Issue by DaDamRival** [thegrb93/StarfallEx#753]
For example, to get the arguments of a function which could be used in automatic docs generation.
![9p9TCLQ](https://user-images.githubusercontent.com/20374966/71418859-0f683600-266d-11ea-8363-ddfc3ff421ba.png)

**Comment by thegrb93** [comment]
It would have to only return the name probably.

**Comment by DaDamRival** [comment]
While in my use case that would be enough, i do think that being able to get local variables and their values is also valuable. Although i have no clue how that could be made save.
