### ISSUE TITLE
ents_methods:getClass() does not return worldspawn as class, instead errors

### ISSUE THREAD

**Issue by Neatro** [thegrb93/StarfallEx#769]
`entity(0):GetClass()` should return the class of the world, being "worldspawn", but instead throws `Entity is not valid.` as an error.

**Comment by Damianu** [comment]
It's due how starfall works, it won't allow you to call any metamethod on entity that is not valid, seems like gmod returns false on entity(0):IsValid().

https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/libs_sh/entities.lua#L65

**Comment by thegrb93** [comment]
For methods like that we can use another GetEnt that doesnt check isvalid
