### ISSUE TITLE
Add shared player_methods:setEyeAngles( Angle )

### ISSUE THREAD

**Issue by Neatro** [thegrb93/StarfallEx#770]
Server Side permissions: 
    Friends (pp buddies) and owner only.
    Admin-only enable/disable switch

Client Side permissions: 
    HUD element enabled only
    Admin-only enable/disable switch

http://wiki.garrysmod.com/page/Player/SetEyeAngles

**Comment by adamnejm** [comment]
I think perms in starfall need to be improved to include things like admin switches and buddies especially for player methods

**Comment by Neatro** [comment]
Server permissions are a thing though, can only be set by admins, though that only affects server-side actions
![Screenshot](https://user-images.githubusercontent.com/26172882/72168158-e49c1280-33cc-11ea-84c1-e0cee5faa821.PNG)
Admin switches are there, but we could indeed add "Owner only", "Buddies/Friends only" buttons, you should add a seperate issue for that

**Comment by adamnejm** [comment]
Can I allow all players to be able to setVelocity on other players, but not their props?

**Comment by Damianu** [comment]
That's handled by your prop protection. Permissions in starfall aren't target based.

**Comment by thegrb93** [comment]
I think if servers did enable this unwittingly then starfall would get a bad reputation for allowing aimbots.

**Comment by Neatro** [comment]
make it off by default and give a warning to admins when they switch it on that it can be used for aimbots etc. 
you can already setpos players on servers that have switched it on, noone complained so far.

**Comment by thegrb93** [comment]
Only if the server gives physgun permission to the player on themself.

**Comment by Neatro** [comment]
yeah... but still, a warning could be added when switching that feature on, and make it off by default, so setEyeAngles can't be used before switching it on first

**Comment by thegrb93** [comment]
```lua
--- Sets a player's eye angles
-- @param ang New angles
function player_methods:setEyeAngles(ang)
	local ent = getent(self)
	local ang = aunwrap(ang)

	checkpermission(instance, ent, "entities.setAngles")

	ent:SetEyeAngles(ang)
end
```

**Comment by adamnejm** [comment]
The point here is that we need a way to handle client's permissions from the server. Either make that one an exception and just network the state to clients on join/change or make a bit better system for registering *'shared'* permissions which might come useful in the future or for 3rd party extensions

**Comment by thegrb93** [comment]
I think making this serverside only would be fine.

**Comment by adamnejm** [comment]
Serverside is quite laggy, even on my local host the stutter is noticeable.
You can already do stuff like `input.lockControls` on clientside so I think this would be a natural place for this function as well.

I think with two protection mechanisms, one being global serverside permission setting (most certainly disabled by default) and the other being conditioned by player connecting to your HUD will make it safe.
Just need to restore or reset player's angles when they disconnect.

Additionally, this is quite interesting:
```lua
local ply = Player(2)
hook.Add("Tick", "rotateyourowl", function()
	local ang = ply:EyeAngles()
	ang.r = math.sin(CurTime()*5)*10
	
	ply:SetEyeAngles(ang)
end)
--hook.Remove("Tick", "rotateyourowl")
```
Running it on server will lock your view while on client it will only control the `roll` axis.

**Comment by thegrb93** [comment]
The problem I have with clientside setEyeAngles is that works near perfectly for aimbot and I don't have any ideas how to limit that.
