### ISSUE TITLE
Collision listener doesnt work on starfall_prop

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#771]

**Comment by DaDamRival** [comment]
I guess a workaround could be to use [ENTITY:Touch](https://wiki.garrysmod.com/page/ENTITY/Touch) and [ENTITY:GetTraceTouch](https://wiki.garrysmod.com/page/Entity/GetTouchTrace)

**Comment by DaDamRival** [comment]
Actually, [ENTITY:PhysicsCollide](https://wiki.garrysmod.com/page/ENTITY/PhysicsCollide) could be used since its used for lua entities rather than needing to use AddCallback like non lua entities need.

**Comment by thegrb93** [comment]
Ye
