### ISSUE TITLE
Wire I/O functions broken (attempt to index global 'wire' (a nil value))

### ISSUE THREAD

**Issue by CheezusChrust** [thegrb93/StarfallEx#778]
On the latest version of Starfall, it seems wire I/O functions don't work at all.

Error:
```
SF:main:5: attempt to index global 'wire' (a nil value)
stack traceback:
	SF:main:5: in main chunk
```

Can be reproduced by attempting to use inputs/outputs:
```lua
--@name broken
--@author
--@server

wire.adjustInputs({"Stuff"},{"number"})

wire.ports.Stuff = 69
```

**Comment by thegrb93** [comment]
What's the error when you start the game?

**Comment by thegrb93** [comment]
It's probably https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/libs_sv/wire.lua#L5

Starfall is being loaded before wire. Will need to use initialize hook.

**Comment by thegrb93** [comment]
Should also make sure https://github.com/thegrb93/StarfallEx/blob/92bfd35e7b61fc8aaaa9f29ab35d580dcbfc08ff/lua/entities/starfall_processor/cl_init.lua#L51 is working

**Comment by thegrb93** [comment]
https://github.com/thegrb93/StarfallEx/issues/528 will also fix it. Will start working on it tonight.

**Comment by thegrb93** [comment]
Went ahead and reverted it till the fix is ready
