### ISSUE TITLE
Matrix not working on render target

### ISSUE THREAD

**Issue by Damianu** [thegrb93/StarfallEx#78]
Dunno if its actual bug or GMod behaviour, but when you push matrix after/before setting render target stuff inside wont render at all.

**Comment by thegrb93** [comment]
I think I encountered this before and this was the motivation to make rendering fully 3D instead of using rendertargets. I think the solution is to add an option to select the rendertarget with a 3D context instead of a 2D one.

**Comment by Damianu** [comment]
Sure, if it'd fix the issue that'd be great.

**Comment by thegrb93** [comment]
Just need to create a 3D context to use matrices on RTs now.

**Comment by Damianu** [comment]
You gotta push matrix with world arg as true, as it shouldnt be multiplified with screen's transform.

**Comment by thegrb93** [comment]
Ahh
