### ISSUE TITLE
Mesh not being destroyed properly in some cases

### ISSUE THREAD

**Issue by Neatro** [thegrb93/StarfallEx#781]
Meshes will hog up vram if not destroyed properly.
This happens when: 
- using prop.createCustom() where a custom prop was initialized with an invalid physics object.
- The chip crashing (or during catching an error with pcall/xpcall) with some meshes made.
- (possibly) the chip being removed with still having meshes active.

All imeshes has to be destroyed through its :Destroy() method when no longer used. Setting it's value to nil wont free the vram it's taking up.

**Comment by thegrb93** [comment]
User created mesh types are cleaned up when the chip is removed or errored no matter what. See mesh.lua:230

I think the custom prop is the only issue. Any idea why the initialized physics object would be invalid?

**Comment by thegrb93** [comment]
Should be fixed now, but if you have other info/idea let me know.
