### ISSUE TITLE
entity:getColor() returns table

### ISSUE THREAD

**Issue by suunrider** [thegrb93/StarfallEx#8]
```lua
if SERVER then
    print( type( entities.self():getColor() ) )
end
```
prints `table` and not `Color`.

**Comment by thegrb93** [comment]
Yeah weird. The getcolor function returns a color object with no __tostring metamethod.
```
] lua_run print(Entity(1):GetColor())
> print(Entity(1):GetColor())...
table: 0x3a115598
] lua_run print(Color(255,255,255))
> print(Color(255,255,255))...
255 255 255 255
```

The solution is to make our own tostring method. I can do that real quick.

**Comment by thegrb93** [comment]
Should be fixed

**Comment by suunrider** [comment]
The problem is that it returns a table, but i want Color. So i could just make
```
ent1:setColor(ent2:getColor())
```

**Comment by thegrb93** [comment]
Let me try that

**Comment by thegrb93** [comment]
Yeah that works now.
