### ISSUE TITLE
Make wire.adjustInputs and wire.adjustOutputs able to accept one table

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#804]
keys will be the name and values the type.
{X = {type = "number"}}

**Comment by CornerPin** [comment]
Why not `{X = "number"}`?

**Comment by thegrb93** [comment]
This way you can define a structure with more information such as a trigger callback and just pass it all into the adjustInputs.

```lua
local myInputs = {
   X = {
      type = "number",
      onchange = print,
      somedata = {}
   }
}
```

**Comment by thegrb93** [comment]
Would be cooler if you could pass in the callback and have it be called internally automatically.

**Comment by thegrb93** [comment]
```lua
local myInputs = {
   X = {
      type = "number",
      trigger = print,
   }
}
wire.adjustInputsCallbacks(myInputs)
```

**Comment by thegrb93** [comment]
This and my previous comment should work well
```lua
wire.adjustInputs({X = "number"})
```

**Comment by CornerPin** [comment]
I think that will look kinda messy if you have a lot of inputs/outputs, how about:
```lua
wire.adjustInputs({Direction = "Vector", Distance = "number"})

wire.adjustInputCallback("Direction", function(vec)
	-- Process vec
end)

wire.adjustInputCallback("Distance", function(dist)
	-- Process dist
end)
```

**Comment by thegrb93** [comment]
You can build the table one by one if you want to. The goal here is to reduce amount of code required.

**Comment by thegrb93** [comment]
Individual calls to set each callback is not very compact.

**Comment by Neatro** [comment]
We could make it trigger custom hooks, like the custom hook in hook.run(), the value is then passed through kind if as if it was: `WIRE:Inputname(value)`
