### ISSUE TITLE
Starfall superuser mode

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#814]

**Comment by thegrb93** [comment]
Only problem here is prop protection won't like it.

**Comment by adamnejm** [comment]
Afaik NPP checks if entity is marked persistent, in that case it doesn't clean it
https://wiki.facepunch.com/gmod/Entity:SetPersistent

**Comment by thegrb93** [comment]
I mean the prop protection checks; the player entity is invalid.

**Comment by thegrb93** [comment]
Would be easier if there was an option to spawn a chip as superuser. Then no players restrictions would be used.
