### ISSUE TITLE
Add bone arguement to entities.setParent

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#815]
https://wiki.facepunch.com/gmod/Entity:FollowBone

**Comment by thegrb93** [comment]
This tends to cause prediction issues. Not sure its a good idea.

**Comment by adamnejm** [comment]
Can we revisit this? `EF.FOLLOWBONE` on client works flawlessly by itself, but not on the server.
Tested some other stuff, but for now only `FollowBone` seems to work.

What kind of prediction issues is this function causing?  
  
  
```lua
--@shared

local base = holograms.create(chip():getPos(), chip():getAngles(), "models/pac/jiggle/base_jiggle_5.mdl")
base:setParent(chip())

local child = holograms.create(chip():getPos() + Vector(20, 0, 0), chip():getAngles(), "models/pac/jiggle/base_jiggle_5.mdl")
child:setColor(CLIENT and Color(255, 150, 50) or Color(50,100,255))


local bone = CLIENT and 8 or base:getBoneName(8)
child:setParent(base, bone)
child:addEffects(EF.FOLLOWBONE --[[+ EF.PARENT_ANIMATES]] )
```

![image](https://user-images.githubusercontent.com/7283019/155222785-33c00284-cabc-49ff-b592-71e325e1e146.png)

**Comment by thegrb93** [comment]
If it works on client flawlessly, maybe it can be added. I remember it causing pac outfits to lag behind and such when used in server-side.

**Comment by adamnejm** [comment]
Should only be allowed on holograms, crashes occur in some circumstances when parenting props. Besides that, works flawlessly on server, while on client it's unparenting when the entity is re-sent *(just like `setParent`)*.  
  
When it comes to PAC and prediction, I couldn't break anything. PAC is erroring when I join local server using the same Steam account so can't yet test the *'lagging issue'* reliably. Will try some more stuff when I find time.
