### ISSUE TITLE
material.destroy doesn't properly destroy the rendertarget it's using

### ISSUE THREAD

**Issue by DaDamRival** [thegrb93/StarfallEx#818]
Using material.destroy doesn't seem to destroy the rendertarget it is using properly and trying to create a new material will result in the following error:
```
addons/wire_starfall/lua/starfall/libs_cl/material.lua:749: A rendertarget with this name already exists!
stack traceback:
	addons/wire_starfall/lua/starfall/libs_cl/material.lua:749: in function 'setTextureURL'
	SF:main:11: in function 'new'
	SF:main:15: in main chunk
```

The code used to test this:
```lua
--@client

local mat
local function new()
	if mat then
		mat:destroy()
		print("destroyed")
	end
	
	mat = material.create("UnlitGeneric")
	mat:setTextureURL("$basetexture", "https://u.teknik.io/3DVA3.png")
end

new()
new()
```

Replacing `mat:destroy()` with`render.destroyRenderTarget(mat:getName() .. "$basetexture")` will work.

**Comment by thegrb93** [comment]
This is known. URL textures use a rendertarget under the hood.

**Comment by thegrb93** [comment]
render.createRenderTarget("myrt")
mat:setRenderTargetTexture("$basetexture", "myrt")
mat:setTextureURL("$basetexture","http://watever")

This is what you should do if you want to manage the rt

**Comment by DaDamRival** [comment]
The same happens with `render.createMaterial` since it uses `material.create` internally, and i feel if `material.destroy` doesn't actually destroy everything the material created this can cause a lot of confusion. It took me a while digging through to sourcecode to even find out why destroying the material was breaking the creation of a new one. Besides, this also breaks backwards compatibility since this didn't use to be the case.

**Comment by thegrb93** [comment]
I think this change is better, but chips that reuse rendertargets and use material.destroy will break. They'll need to setRendertargetTexture("watever","") to prevent their RT from being destroyed.

**Comment by thegrb93** [comment]
Imo the best solution actually is to just make sure the documentation clearly shows that a rendertarget is created.

**Comment by thegrb93** [comment]
>Besides, this also breaks backwards compatibility since this didn't use to be the case.

Yeah, getTextureID used to leak vram
