### ISSUE TITLE
Scissors rect support

### ISSUE THREAD

**Issue by Damianu** [thegrb93/StarfallEx#82]
https://wiki.garrysmod.com/page/render/SetScissorRect

**Comment by Damianu** [comment]
https://github.com/thegrb93/StarfallEx/pull/83 it was quite easy to implement. After some testing it works, but only with render targets.

**Comment by thegrb93** [comment]
It probably requires a 2D context

**Comment by Damianu** [comment]
Yeah it does, forgot about hud. Shall I just check if its render target/hud or there is way of determining context?(Like when starting 2d cam)

**Comment by thegrb93** [comment]
I don't think a check is necessary, but you can do this if you want.
```
local i = #view_matrix_stack
if i==0 or view_matrix_stack[i]~="2D" then SF.throw("blah",2) end
```

**Comment by Damianu** [comment]
If you try to do that in 2D enviroment it starts glitching and may produce console warnings.
I'll update my code soon.

**Comment by Damianu** [comment]
Done(explained in PR)
