### ISSUE TITLE
URL Textures not working on Beta gmod

### ISSUE THREAD

**Issue by adamnejm** [thegrb93/StarfallEx#823]
Worked before, updated with latest non-beta fix. No longer works

**Comment by thegrb93** [comment]
What does lua_run_cl print(BRANCH) show?

**Comment by adamnejm** [comment]
`print(BRANCH)` -> `x86-64`

**Comment by adamnejm** [comment]
Broke for everyone on my server after I updated Starfall with commits from 29.02.2020
Both Linux and Windows are affected
