### ISSUE TITLE
Make Starfall chips respond to E2's :getName()

### ISSUE THREAD

**Issue by CSGKCJDBCPQ2K8** [thegrb93/StarfallEx#84]
I think this would be nice to have.

**Comment by thegrb93** [comment]
Are you saying getName should return the name of a starfall chip?

**Comment by edgarasf123** [comment]
Starfall chip names are clientside only, and E2 is serverside. Thefore it's not possible.

**Comment by thegrb93** [comment]
They are server side too, just not stored, but that's easily changed.

**Comment by edgarasf123** [comment]
Also, the getName() checks if the entity is an e2 chip.
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/selfaware.lua#L111

**Comment by thegrb93** [comment]
There u go. Should work once this is pulled. https://github.com/wiremod/wire/pull/1293
