### ISSUE TITLE
Newly connected players do not get chip source code.

### ISSUE THREAD

**Issue by ShadowzOfTheDark** [thegrb93/StarfallEx#844]
Whenever a new player connects to the server, the code isn't sent to the client so any client side scripts don't run. Attempting to restart the chip using the context menu results in following error:

[ERROR] addons/starfallex/lua/entities/starfall_processor/shared.lua:27: attempt to index field 'files' (a nil value)
  1. Compile - addons/starfallex/lua/entities/starfall_processor/shared.lua:27
   2. DoClick - addons/starfallex/lua/entities/starfall_processor/shared.lua:160
    3. OnMouseReleased - lua/vgui/dlabel.lua:237
     4. unknown - lua/vgui/dmenuoption.lua:77

**Comment by thegrb93** [comment]
I don't think this is reproducible. Its been working forever.

**Comment by adamnejm** [comment]
Ummm, it has been wonky since I can remember. Not in this exact way, but most of the scripts are dead in client untill I restart clientside, and I can do that fine without any errors

**Comment by adamnejm** [comment]
Very rarely there's a screen working once I reconnect

**Comment by thegrb93** [comment]
That can be attributed to the script erroring while you are spawning. Lots of bad stuff can happen that user's scripts don't account for (invalid entities, etc). This seems to be the data not even being sent.

**Comment by adamnejm** [comment]
Hmm, starting all clientside scripts once the player moves for the first time? Then you basically wouldn't have to account for the invalid entity stuff

**Comment by thegrb93** [comment]
Sounds like a good idea.

**Comment by ShadowzOfTheDark** [comment]
This happens for every player that connects to the server. Keep in mind, these players when they join are in an area portal which might have something to do with it.

**Comment by thegrb93** [comment]
Well the starfall chip is set to always transmit.

**Comment by thegrb93** [comment]
Perhaps an addon is preventing this from working: https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/sflib.lua#L656

**Comment by thegrb93** [comment]
Nvm had some kind of memory lapse thinking that code was sent using that. We can try changing it so code is sent with that.

**Comment by thegrb93** [comment]
The problem is most likely another addon erroring in the NetworkEntityCreated hook
