### ISSUE TITLE
Don't initialize client-side until joined player is fully initialized

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#845]

**Comment by adamnejm** [comment]
Player would probably be fully initialized when he's able to move.
```lua
hook.Add( "CreateMove", "", function(m)
    if m:GetButtons() == 0 then return end
    hook.Remove("CreateMove", "")
    -- request here?
end)
```

**Comment by thegrb93** [comment]
There's a starfall helper func for it.

**Comment by thegrb93** [comment]
That helper func was designed for serverside though. Not sure if it'll work clientside.

**Comment by thegrb93** [comment]
Just realized the server doesn't send starfall code until the player is fully initialized so this is redundent

**Comment by thegrb93** [comment]
Nvm I'm wrong, it uses the clientside Initialize hook. Should use serverside SF.WaitForPlayerInit
