### ISSUE TITLE
Hologram.setModel Clientside invalid model.

### ISSUE THREAD

**Issue by DaDamRival** [thegrb93/StarfallEx#846]
Setting the model of a clientside holo will result in a invalid model error due to the fact that [util.IsValidModel](https://wiki.facepunch.com/gmod/util.IsValidModel) will return false if the model hasn't been precached by the server

**Comment by thegrb93** [comment]
Can't really do anything about that. I would imagine actually setting the model would result in an error too.

**Comment by DaDamRival** [comment]
Can't the check just be removed? Since when creating holograms it isn't even checked i don't see how this would be a issue.

**Comment by thegrb93** [comment]
I guess, does it make them an error or does it work as expected?

**Comment by DaDamRival** [comment]
With the check removed and setting the model of a holo that wasn't precached works as expected.
