### ISSUE TITLE
RenderTarget is affected by HDR when rendered to itself.

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#86]
I never noticed since I leave HDR off, but maybe needs http://wiki.garrysmod.com/page/Enums/CREATERENDERTARGETFLAGS to fix. dunno

**Comment by thegrb93** [comment]
Also doesn't seem to affect gm_flatgrass

**Comment by edgarasf123** [comment]
it does affect in gm_flatgrass
Without HDR
![](http://i.imgur.com/gK4ygFk.jpg)

With HDR
![](http://i.imgur.com/h4Bx4D0.jpg)

**Comment by thegrb93** [comment]
I'll look at it in the morning. Just finished the semester so should have some time.

**Comment by edgarasf123** [comment]
![](http://i.imgur.com/hOWwGrZ.gif)
![](http://i.imgur.com/h76XWyI.gif)

[hdr_test.lua](https://gist.github.com/edgarasf123/a654fd122fab0fdbf97660f24aea3e29)

**Comment by thegrb93** [comment]
I think it's because the background is pure black which makes HDR overcompensate. Look at the sky in the background, it turns white too.

**Comment by thegrb93** [comment]
The same thing happens with over wire screens.

**Comment by thegrb93** [comment]
I got to figure out why wire screens don't get affected this way though.

**Comment by thegrb93** [comment]
By the way, Matrix() returns an identity matrix.

**Comment by thegrb93** [comment]
I think the only difference between starfall and wiremod is they use cam.Start3D2D

**Comment by edgarasf123** [comment]
The render target stores the image __after__ HDR processing. And because I reuse old render target image, it turns old pixels brighter and brighter in each frame. Wire screens don't reuse old render target images, so its not visible.

That's my guess.

**Comment by thegrb93** [comment]
So I need to modify RT textures to not do any HDR. I'll try

**Comment by thegrb93** [comment]
Not sure how. Tried this.
```
GetRenderTargetEx( rtname, 1024, 1024, 
			RT_SIZE_OFFSCREEN, 
			MATERIAL_RT_DEPTH_SEPARATE,  
			2048, 
			0, 
			IMAGE_FORMAT_DEFAULT 
		)
```
I'll see if anyone replies to https://facepunch.com/showthread.php?t=1508566&p=51570474&viewfull=1#post51570474 otherwise I'll make a request in the garrysmod requests.

**Comment by thegrb93** [comment]
Okay, I've found out that this only happens when you render the rendertarget to itself.

**Comment by Damianu** [comment]
Actually it does not. For me it was enough to draw web image to renderarget and hold it in memory, then it goes darker but not full dark. When you render rendertarget to itself its more glitchy than HDR.

**Comment by thegrb93** [comment]
If I remember, wire screens are affected similarly.

**Comment by thegrb93** [comment]
Going to leave it open for future reference.

**Comment by thegrb93** [comment]
If anyone wants to know the solution. Use a double buffer (i.e. two rendertargets).

**Comment by thegrb93** [comment]
There might be a flag that can be applied to the rendertarget material to prevent this. I'm not yet willing to spend the time experimenting to test this theory yet, but it might be fixable.
