### ISSUE TITLE
Attempt to call field 'AddHook' (a nil value) while the server initializes

### ISSUE THREAD

**Issue by Zentropy99** [thegrb93/StarfallEx#872]
![image](https://user-images.githubusercontent.com/5921822/80397174-09ea5900-88b6-11ea-9199-bb1e6733e8ea.png)

**Comment by adamnejm** [comment]
acffunctions.lua is not a part of Starfall.
Afaik it's caused by ACF itself because developers don't wanna accept pull request fixing it.
You can use this fork and branch of ACF:
https://github.com/DaDamRival/ACF/tree/starfall_fix

**Comment by Zentropy99** [comment]
Thanks.

**Comment by thegrb93** [comment]
@Zentropy99 you can also use ACF-3 which has fixed starfall lib.
