### ISSUE TITLE
--@name no longer supports multi-word names

### ISSUE THREAD

**Issue by ElHyperion** [thegrb93/StarfallEx#88]
When naming a script with multiple words separated by whitespace, the processor appears to pick up only the first word, as can be seen on the tab name and the bubble on the Starfall chip the player is aiming at. Multiple words were working fine before, so I thought I'd report this as an issue.

### Example
`--@name Ultra Awesome Program`
displays only as **Ultra**

**Comment by thegrb93** [comment]
Well I know the change that caused it. I'll debug and fix tomorrow when I get home.

**Comment by ElHyperion** [comment]
Also, includes with spaces in the path name won't work for me either.

**Comment by thegrb93** [comment]
Okay, that's fixed. I have no idea why the rest of that comment detection code is there. Might remove it sometime.
