### ISSUE TITLE
Provide custom __tostring on hologram wrapper

### ISSUE THREAD

**Issue by Zentropy99** [thegrb93/StarfallEx#886]
Hologram gets created though.

**Comment by adamnejm** [comment]
Not a bug. Clientside entities have index of -1

**Comment by Zentropy99** [comment]
oh ok.
so you cant keep them in variables?

**Comment by adamnejm** [comment]
Yes, just like with serverside holograms.
Also for converting sv to cl (or vice versa?) use `Entity:toHologram()`

**Comment by Zentropy99** [comment]
on server side it works, returns: Entity [123][starfall_hologram]

**Comment by adamnejm** [comment]
```lua
--@shared
local holos = {}
for i = 1, 5 do
    holos[i] = holograms.create(chip():getPos() + Vector((i-1)*15, SERVER and 15 or 0, 0), Angle(), "models/holograms/cube.mdl", Vector(0.65))
end
local first = holos[1]
middle:setColor(Color(255,0,0))
holos[5]:setColor(Color(0,255,0)) -- last
```

**Comment by Damianu** [comment]
It's not a bug, starfall doesnt provide custom tostring metamethod, so you basically see entity's one. Serverside holograms use custom entity with starfall_hologram class, clientside ones use C_BaseFlex, you can interact with it as with any other hologram.

**Comment by adamnejm** [comment]
This is how you work with holograms, basic usage is the same on server and client

**Comment by Zentropy99** [comment]
Ok, thanks.

**Comment by thegrb93** [comment]
I think a custom tostring would lead to further confusion down the line. I don't think there's any problem here.
