### ISSUE TITLE
http whitelist

### ISSUE THREAD

**Issue by Earu** [thegrb93/StarfallEx#892]
I don't understand the point of this, you're assuming the only HTTP traffic there is with starfall is related to providing images (?). I was using it to make requests to some web APIs; is that not valid usage (?).

**Comment by Damianu** [comment]
Do that on your own client(you can disable whitelist) and network it to other players.
Feature to add stuff to whitelist on your own client is requested (There isn't anyone working on it right now tho afaik)

Sending requests from other clients to some APIS is not a valid usage as it allows abuse.

**Comment by Earu** [comment]
Thing is, my HTTP request is done server-side and then yes, I network it to clients. I understand why you would want that disabled client-side, but server-side?

**Comment by adamnejm** [comment]
Well then you could abuse the server.
Perform the request on your client, send it to server and broadcast to other clients

**Comment by Damianu** [comment]
Default settings are meant to be safe for any server with starfall installed. 
It's up to server's admins to decide if they trust their players enough to allow them to make HTTP/HTTPS requests to other services. 
If that's the case - server admin can disable whitelist, if not - @adamnejm provided you with slower but safe solution.

**Comment by adamnejm** [comment]
I have disabled the http on my server entirely, never heard anybody complain

**Comment by Earu** [comment]
Okay, I guess, could you whitelist the github.com domain then?

**Comment by adamnejm** [comment]
I guess so, up to D since he's in charge of whitelist.
Pull request it here:
https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/permissions/providers_sh/url_whitelist.lua

**Comment by adamnejm** [comment]
But raw and gist are already registered
```lua
simple [[raw.githubusercontent.com]]
simple [[gist.githubusercontent.com]]
```

**Comment by Earu** [comment]
Yeah, I'm using the API endpoint though (api.github.com)

**Comment by Damianu** [comment]
I have mixed feelings about that so I'll leave final decision to @thegrb93.
Basically I can see appeal of using github API, but I'd rather have someone whitelist it himself. 
But then... it's an API, so it's rate limited and other services running on same IP may be prevented from accessing it.

**Comment by thegrb93** [comment]
You may also get someone ip-banned from the api if it detects abuse.

**Comment by thegrb93** [comment]
Sending the data from your own client->server->other clients is pretty easy with net.writeStream net.readStream or net.writeString net.readString so that's the best solution.
