### ISSUE TITLE
Outdent Editor Feature

### ISSUE THREAD

**Issue by edgarasf123** [thegrb93/StarfallEx#90]
Basically a reverse of tab indentation, which usually editors have it bound to Shift+Tab. But since the key shortcut is already bound to steam overlay, you could use CTRL+Tab as E2 editor has.
![](http://i.imgur.com/jc87K9U.gif)

**Comment by thegrb93** [comment]
I changed my steam overlay keybind for that long ago, and because it gets in the way of sprinting while looking at the scoreboard. That's probably the best solution.
