### ISSUE TITLE
Clientside holograms invalid model if not precached by server.

### ISSUE THREAD

**Issue by DaDamRival** [thegrb93/StarfallEx#906]
Both holograms.create and holograms.setModel are affected.

#846
141f4c14acdc2078e880778e24100579f19c27a6

**Comment by thegrb93** [comment]
Ah that's lame, I thought isvalidmodel just checked the model path.

**Comment by thegrb93** [comment]
Well we need some kind of check to make sure it exists and isn't an animation model

**Comment by thegrb93** [comment]
I guess is fixed again
