### ISSUE TITLE
A way to disable certain HUD elements.

### ISSUE THREAD

**Issue by Superlamaface** [thegrb93/StarfallEx#916]
This would be where we can request permission from the client to disable certain HUD elements. These HUD elements could be the Health/Shield Display, Cursor, HotBar, Gun Ammo, Chat, and Toolgun Tooltips. This would allow us to recreate certain parts of the hud we dont like and keep what we like without having to turn of Draw Hud in Drawing and lose all the functions that we still want/need to be able to play Gmod still with just a different feel/look we want.

**Comment by thegrb93** [comment]
Return false in this hook http://thegrb93.github.io/StarfallEx/#Hooks.hudshoulddraw to hide hud element. I updated the docs to say that.
