### ISSUE TITLE
KEY global table nil serverside

### ISSUE THREAD

**Issue by hobnob11** [thegrb93/StarfallEx#921]
```lua
--@shared

if SERVER then print("SERVER: ", KEY) else print("CLIENT: ", KEY) end

```

has this output:
```
SERVER: 	nil
CLIENT: 	table: 0x023fbbc0b478
```

Documentation says that this table should be shared, so I'm not sure whats going on here.

**Comment by thegrb93** [comment]
@hobnob11 are there any functions you're trying to use them on in serverside?

**Comment by thegrb93** [comment]
I think we should make all enums shared since they can be networked.
