### ISSUE TITLE
Hud connected hook not called when entering a vehicle that has linked hud

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#925]

**Comment by adamnejm** [comment]
Could be nice if there's a way to differentiate players entering a vehicle with players manually connecting to the HUD ent. Preferably add a second parameter.
Also fix docs to include the first, already existing, parameter

**Comment by thegrb93** [comment]
I glanced through the code and didn't see any issue. I'll have to try reproducing it in-game sometime.

**Comment by thegrb93** [comment]
Can't reproduce
