### ISSUE TITLE
Add the mesh library

### ISSUE THREAD

**Issue by Neatro** [thegrb93/StarfallEx#930]
not to be confused with imesh
https://wiki.facepunch.com/gmod/mesh

ability to draw dynamic imesh

**Comment by thegrb93** [comment]
Something like
`mesh.generate(Mesh m = nil,  number primitiveType, number primiteCount, function callback)`

Basically it would manage the mesh.begin/end and ensure no crashes. The other mesh functions would only be allowed to be called inside of 'callback'.

**Comment by thegrb93** [comment]
Also make sure mesh.generate can't be called again until it returns.

**Comment by thegrb93** [comment]
Might also need to find a way to prevent destroying an IMesh while in generate otherwise it may crash. Or just don't have IMesh capability.
