### ISSUE TITLE
Problem when DLib is installed.

### ISSUE THREAD

**Issue by Jason-m858** [thegrb93/StarfallEx#935]
Hello,
We have a problem with StarfallEx when DLib is installed. The latest [Dlib](https://gitlab.com/DBotThePony/DLib/-/jobs) and StarfallEx versions at the time of writing were used. But the Workshop / MasterBranch Version of Dlib had the same Error
We get the following Error:
`stack traceback:
	addons/dlib/lua/dlib/modules/color.lua:66: in function 'Color'
	addons/starfallex/lua/starfall/libs_cl/render.lua:827: in function 'createRenderTarget'
	SF:main:12: in main chunk`

We used the render_view.lua example to get the Error but most other StarFall Scripts terminate with the Same Error. But Some Scripts like the Hello World Script are Working.

**Comment by Damianu** [comment]
https://gitlab.com/DBotThePony/DLib/-/blob/develop/lua_src/dlib/modules/color.lua#L66
https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/libs_cl/render.lua#L827

**Comment by thegrb93** [comment]
@DBotThePony

**Comment by thegrb93** [comment]
The problem is starfall disables basic type metamethods during execution, so dlib's number __index won't work.

**Comment by thegrb93** [comment]
@DBotThePony another option: if you're sure the metamethods won't lead to sandbox break, you can set the number metatable after https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/sflib.lua#L10 is ran. But only if you can trust users with the DLib number metatable.

**Comment by thegrb93** [comment]
Fyi, if that metatable gives full access to 'math' library then it's not safe. The math library has some sandbox breakable functions in it.

**Comment by Jason-m858** [comment]
Since @DBotThePony has added some changes, I just tested it again with the latest developer build of DLib and the bug seems to be gone now. I will try some more chips and if there are no more errors then I will mark the issue as solved.

**Comment by Jason-m858** [comment]
I haven't seen any more errors that can be traced back to DLib and therefore close this issue
