### ISSUE TITLE
Whitelist URLs not Working on multiple Domains.

### ISSUE THREAD

**Issue by Jason-m858** [thegrb93/StarfallEx#937]
The whitelist for dropbox URLs does not seem to work. When we use a dropbox link in StarfallEx we get the following error message: [Picture](https://push.jason-m.net/mBtSFUMNxk.jpg)

But according to the Wiki entry and the File that is [linked](https://github.com/thegrb93/StarfallEx/blob/d72b57dac50498488eb5ffbbbc047cfa1070e9ef/lua/starfall/permissions/providers_sh/url_whitelist.lua) Dropbox Should work. I shared a Mp3 over Dropbox and testet with this Links:
`https://www.dropbox.com/s/2c3uu95bvyw7pdx/Ace%20of%20Base%20-%20All%20That%20She%20Wants.mp3?dl=0
https://www.dropbox.com/s/2c3uu95bvyw7pdx/Ace%20of%20Base%20-%20All%20That%20She%20Wants.mp3?dl=1
https://www.dropbox.com/s/2c3uu95bvyw7pdx/Ace%20of%20Base%20-%20All%20That%20She%20Wants.mp3?raw=1
https://uc97f50c60233237f5f2a9f8773f.dl.dropboxusercontent.com/cd/0/inline/A7zYO6AWM-dbmmUp7YXp3nQozsTcHl-7-h5DnQyBSKCuLuzmrg6FuxYm8plnrVkR0BoZ5gGfkwloj4yLIf1EUgxtmz2_kiikq7YLPzSJt8DOAYeX6AhT6n_YtOs8pBNODw4/file#`

All had the Whitelist Error.

And then there is a missing Whitelist for Steam. All Pictures and Gifs and Videos that are sent over the Chat Function from Steam get another URL then the Whitelistet ones. (steamuserimages-a.akamaihd.net) [ExamplePicture](https://steamuserimages-a.akamaihd.net/ugc/1475443067859980096/685F2468519E31C5C214959EC3AA0B0757B01E1B/)

Another Missing URL for Reddit: preview.redd.it [Example](https://preview.redd.it/injjlk3t6lb51.jpg?width=640&height=800&crop=smart&auto=webp&s=19261cc37b68ae0216bb855f8d4a77ef92b76937)

**Comment by ButtSauce** [comment]
![sREh28ksP2](https://user-images.githubusercontent.com/35794905/87855287-973fc580-c95a-11ea-8e17-8111e2bdf474.png)

assuming it's because www.dropbox.com isn't whitelisted correctly

**Comment by Jason-m858** [comment]
You forgot steamuserimages-a.akamaihd.net in Your Commit. This URL is used for Content that Users can send in the Steam Chat

**Comment by ButtSauce** [comment]
fixed https://github.com/thegrb93/StarfallEx/pull/938/commits/6675c8b7548258010e4777743655420b042a57fe
