### ISSUE TITLE
Add wire.addInput & wire.addOutput

### ISSUE THREAD

**Issue by adamnejm** [thegrb93/StarfallEx#959]
Right now we only have overrides which don't work well for user-created libraries.

Of course it is possible to copy the current links with `wire.getI/O`, add custom ones to that and then use the `wire.adjustI/O` to set them all back again without unlinking stuff, but I think the new functions would simplify the process.

**Comment by thegrb93** [comment]
Just store your ports in a table, add/remove it from your table, and wire.adjustPorts(yourtable)
