### ISSUE TITLE
Add entity.Use

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#963]

**Comment by thegrb93** [comment]
Entity:Use( Entity activator, Entity caller = NULL, number useType = USE_ON, number value = 0 )


USE_OFF | 0 |  
USE_ON | 1 |  
USE_SET | 2 |  
USE_TOGGLE | 3

**Comment by thegrb93** [comment]
```lua
--- Simulate a Use action on the entity
-- @param user The one who used the entity
-- @param caller The entity triggering this action (Default: NULL)
-- @param usetype The USE_ enum use type. (Default: USE_ON)
-- @param value The use value (Default: 0)
function ents_methods:use(user, caller, usetype, value)
    local ent = getent(self)
    checkpermission(instance, ent, "entities.canTool")
    user = getent(user)
    if caller~=nil then caller = getent(caller) end
    if usetype~=nil then checkluatype(usetype, TYPE_NUMBER) end
    if value~=nil then checkluatype(value, TYPE_NUMBER) end
    ent:Use(user, caller, usetype, value)
end
```

server only

**Comment by adamnejm** [comment]
I don't think people should be able to specify `user` directly, at least not unless they're admins or something.
Right now this will allow you to force other people into activating your HUD Component, sit in vehicles and whatnot :D
I'm pretty sure `activator` on the other hand can be left as it is, but that again depends on how `ENT:Use` is handled in custom ents

**Comment by thegrb93** [comment]
Yeah, should probably force user to either not be a player or force it as instance.player.
