### ISSUE TITLE
Some libs trying to use other libs before postload

### ISSUE THREAD

**Issue by thegrb93** [thegrb93/StarfallEx#964]

**Comment by thegrb93** [comment]
Don't see any issues

**Comment by KubeRoot** [comment]
Was this perhaps about https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/libs_sh/surfaceinfo.lua#L32 which was discussed on discord?

**Comment by Vurv78** [comment]
Like I said in the discord, at least for surfaceinfo.lua, we can replace line 35 with instance.Types.LockedMaterial.Wrap(sunwrap(self):GetMaterial())

**Comment by thegrb93** [comment]
No, it should be working as is. Something else is wrong if not.

**Comment by thegrb93** [comment]
Make sure you're up to date. This had an error in an older version.
