### ISSUE TITLE
Clientside printing can only print numbers from -9 to 99, no other types work

### ISSUE THREAD

**Issue by CheezusChrust** [thegrb93/StarfallEx#975]
Printing on clientside Starfall chips now only prints if you're printing a number from -9 to 99, or a 1-2 character string. Anything else prints a blank line. This is on the latest version.

Test code:
```
--@client

print(-10)
print(-9)
print(99)
print("ab")
print(100)
print("123")
print({1,2,3})
print(1, 2, 3)
print(true)
```

Output I get:
```
[blank line]
-9
99
ab
[5 blank lines]
```

**Comment by adamnejm** [comment]
Oh, didn't see you opened an issue as I also stumbled upon this myself.
Should be fixed after https://github.com/thegrb93/StarfallEx/pull/976 gets merged.
