### ISSUE TITLE
All pcb*.mdl screens have incorrect offsets since the latest October update

### ISSUE THREAD

**Issue by StyledStick** [thegrb93/StarfallEx#998]
Since the last Gmod update, all screens using the PCB models (models/cheeze/pcb/pcb*.mdl) are incorrectly being displayed sideways. I've tested this on multiple servers and with multiple versions of Starfall and even the very old ones have this issue now.

![instance1](https://user-images.githubusercontent.com/14253048/99194714-fa523500-275f-11eb-8c8b-ed69701dd057.png)

It might be related to the fact that in the file **lua/entities/starfall_screen/cl_init.lua**, PCB model names have double foward slashes after "models".
`ENT.Monitor_Offsets = { ["models//cheeze/pcb/pcb4.mdl"] = { ...`

Removing one of the slashes seems to fix the issue.

![fixed1](https://user-images.githubusercontent.com/14253048/99194720-06d68d80-2760-11eb-80eb-a576193eca84.png)

**Comment by thegrb93** [comment]
Very strange. I'll try to reproduce the issue before I change anything.

**Comment by StyledStick** [comment]
I was looking through the October 2020 update [changelogs](https://gmod.facepunch.com/blog/october-2020-update) and found something interesting:

![ch](https://user-images.githubusercontent.com/14253048/99483978-288d6b80-293e-11eb-9f47-a8d172da5f73.png)

My guess is that GetModel used to return double slashes before they fixed it. Anyways, thanks for replying, it's a new experience to collaborate on GitHub for the first time.

**Comment by thegrb93** [comment]
Seems to be working fine for me

![20201118012751_1](https://user-images.githubusercontent.com/6713261/99493520-58883f00-293d-11eb-82a5-7e0169ec488d.jpg)

**Comment by StyledStick** [comment]
Have you tried to render anything to those screens? Let me clarify this a bit more:

The values of Monitor_Offsets are not found for those specific models since the return of GetModel changed on the last update, and then those offsets are being calculated manually instead (check [here](https://github.com/thegrb93/StarfallEx/blob/95115d514c1fed397eeeb4d801e734cc9da2289e/lua/entities/starfall_screen/cl_init.lua#L21)).

The positions and scale are right, but the rotation of the render target onto those screens aren't. Here is the sample code I used on the screenshot below:
```
local bigFont = render.createFont("Tahoma", 64, 800, 1)
hook.add("render", "render_test", function()
    render.setFont(bigFont)
    render.drawText(8, 8, "Hello world!", 0)
end)
```
![scr2](https://user-images.githubusercontent.com/14253048/99552811-3245bc00-299c-11eb-809a-0bea7871a937.png)

Also, you may have noticed that the screen on the left looks right. That one already has the correct model path in Monitor_Offsets (without the double forward slashes, check [here](https://github.com/thegrb93/StarfallEx/blob/95115d514c1fed397eeeb4d801e734cc9da2289e/lua/entities/starfall_screen/cl_init.lua#L212)).

**Comment by thegrb93** [comment]
Ohh ok. The ghost in your screenshot had confused me. I'll take your word for it and remove the double slashes for now since I'm stuck away from my PC until later.

**Comment by thegrb93** [comment]
I think what's happening is its auto-generating the screen dimensions since the model path isn't matching what's in the table.
